DROP TABLE PCLUB.ADMPT_LOY_CLIENTE;
DROP TABLE PCLUB.ADMPT_LOY_SALDOS;
DROP TABLE PCLUB.ADMPT_LOY_MOVTOS;
DROP TABLE PCLUB.ADMPT_LOY_CANJE;
DROP TABLE PCLUB.ADMPT_LOY_CANJEDET;
DROP TABLE PCLUB.ADMPT_LOY_DETMOVSAL;

-- DWH
DROP TABLE PCLUB.ADMPT_DETCAT_CONCEPTO;
DROP TABLE PCLUB.ADMPT_CAT_CONCEPTO;
ALTER TABLE ADMPT_KARDEX DROP COLUMN ADMPV_IDTRANSLOY;

DROP TABLE PCLUB.ADMPT_SALDO_CLI_DES;

DROP TABLE PCLUB.ADMPT_CIB_TMP_DUPLICADO;

DROP PACKAGE PCLUB.PKG_CC_IMPLOYALTY;

DROP FUNCTION PCLUB.FN_VALIDAR_RUC;

BEGIN
	DELETE FROM PCLUB.admpt_concepto 
	WHERE ADMPV_COD_CPTO IN ('17','18','22','38','19','47','48','20');
	COMMIT;
END;

DROP INDEX PCLUB.IDX_CANJE_LOYALTY;

DROP INDEX PCLUB.IDX_KARDEX_LOYALTY ;

DROP INDEX PCLUB.IDX_CLI_CICFACT;