CREATE OR REPLACE FUNCTION PCLUB.FN_VALIDAR_RUC(V_RUC VARCHAR2) RETURN INTEGER
IS
BEGIN
DECLARE
TYPE VA_DIGITOS_RUC IS VARRAY(10) OF NUMBER;
V_DIGITOS_RUC VA_DIGITOS_RUC;
V_LONGITUD NUMBER;
V_NUM NUMBER;
V_CARACTER_ERR NUMBER;
V_DIGITO NUMBER; 
V_SUMA NUMBER DEFAULT 0;
V_CHEQUEO NUMBER;
V_MODULO11 NUMBER;
V_VERIFICAR NUMBER;
V_DIGITO_FINAL NUMBER;

BEGIN
V_LONGITUD:=NVL(LENGTH(V_RUC),0);
V_DIGITOS_RUC:=VA_DIGITOS_RUC(5,4,3,2,7,6,5,4,3,2);

IF V_LONGITUD=11 THEN
  FOR N IN 1..V_LONGITUD LOOP
   
   IF N<V_LONGITUD THEN
      V_DIGITO:=TO_NUMBER(SUBSTR(V_RUC,N,1));
      V_SUMA:=V_SUMA+V_DIGITO*V_DIGITOS_RUC(N);
   ELSE
      V_CHEQUEO:=TO_NUMBER(SUBSTR(V_RUC,N,1));
   END IF;
   
  END LOOP;
  
  V_MODULO11:=MOD(V_SUMA,11);
  V_DIGITO_FINAL:=11-V_MODULO11;
   
  IF V_DIGITO_FINAL =10 THEN
      V_VERIFICAR:=0;
  ELSIF V_DIGITO_FINAL = 11 THEN
      V_VERIFICAR:=1;
  ELSE
      V_VERIFICAR:=V_DIGITO_FINAL;
  END IF;
   
  IF V_CHEQUEO=V_VERIFICAR THEN
     RETURN 1;
  ELSE
     RETURN 0;
  END IF;
ELSE
  RETURN 0;  
END IF;
END;
EXCEPTION
       WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20000, 'ERROR EN LA FUNCION FN_VALIDAR_RUC');
            RETURN 0;
END FN_VALIDAR_RUC;
/