INSERT INTO PCLUB.ADMPT_PARAMSIST (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
VALUES ((SELECT MAX(TO_NUMBER(ADMPC_COD_PARAM)) + 1 FROM PCLUB.ADMPT_PARAMSIST), 'LATAM RECORD TYPE SYSFT_LATAM_LOTE_CANJE_KM_CC', '1');

INSERT INTO PCLUB.ADMPT_PARAMSIST (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
VALUES ((SELECT MAX(TO_NUMBER(ADMPC_COD_PARAM)) + 1 FROM PCLUB.ADMPT_PARAMSIST), 'LATAM COMPANY ID SYSFT_LATAM_LOTE_CANJE_KM_CC', 'CLARO');

INSERT INTO PCLUB.ADMPT_PARAMSIST (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
VALUES ((SELECT MAX(TO_NUMBER(ADMPC_COD_PARAM)) + 1 FROM PCLUB.ADMPT_PARAMSIST), 'LATAM REC TYPE SYSFT_LATAM_CANJE_KM_CC', 'C');

INSERT INTO PCLUB.ADMPT_PARAMSIST (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
VALUES ((SELECT MAX(TO_NUMBER(ADMPC_COD_PARAM)) + 1 FROM PCLUB.ADMPT_PARAMSIST), 'LATAM PROGRAM ID SYSFT_LATAM_CANJE_KM_CC', 'CLARO');

INSERT INTO PCLUB.ADMPT_PARAMSIST (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
VALUES ((SELECT MAX(TO_NUMBER(ADMPC_COD_PARAM)) + 1 FROM PCLUB.ADMPT_PARAMSIST), 'LATAM PUNTOS MINIMO PARA CANJE', '1');

INSERT INTO PCLUB.ADMPT_PARAMSIST (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
VALUES ((SELECT MAX(TO_NUMBER(ADMPC_COD_PARAM)) + 1 FROM PCLUB.ADMPT_PARAMSIST), 'LATAM EQUIVALENCIA CLARO PUNTOS', '1');

INSERT INTO PCLUB.ADMPT_PARAMSIST (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
VALUES ((SELECT MAX(TO_NUMBER(ADMPC_COD_PARAM)) + 1 FROM PCLUB.ADMPT_PARAMSIST), 'LATAM EQUIVALENCIA KM LATAM', '1');
--CODIGO DE LA TABLA admpt_premio (CAMPO admpv_id_procla) PARA CANJE DE CC A KM
INSERT INTO PCLUB.ADMPT_PARAMSIST (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
VALUES ((SELECT MAX(TO_NUMBER(ADMPC_COD_PARAM)) + 1 FROM PCLUB.ADMPT_PARAMSIST), 'LATAM TBL PREMIO ID TRANS CC A KM', '1');

INSERT INTO PCLUB.ADMPT_PARAMSIST (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
VALUES ((SELECT MAX(TO_NUMBER(ADMPC_COD_PARAM)) + 1 FROM PCLUB.ADMPT_PARAMSIST), 'LATAM PREFIJO SYSFT_LATAM_LOTE_CANJE_KM_CC', 'CLAROPE');

INSERT INTO PCLUB.ADMPT_PARAMSIST (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
VALUES ((SELECT MAX(TO_NUMBER(ADMPC_COD_PARAM)) + 1 FROM PCLUB.ADMPT_PARAMSIST), 'LATAM TIPO ARCHIVO SYSFT_LATAM_LOTE_CANJE_KM_CC', 'C');

insert into PCLUB.admpt_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO, ADMPC_TPO_OPER, ADMPC_PROC)
values ('129', 'TRANSFERENCIA LATAM A CLARO', 'A', '', 18, 'C', 'LATAM', 'E ', '1');

insert into PCLUB.SYSFT_LATAM_EQUIV_TIP_DOC (SYLEN_IDENTIFICADOR, SYLEV_ID_TIPO_DOC_CC, SYLEV_TIPO_DOC_LATAM, SYLEV_DESC_DOC_LATAM, SYLEC_EST, SYLED_FEC_REG, SYLEV_USU_REG)
values (1, '2', 'DNIPE', 'DNI', 'A', sysdate, 'CARGA');

COMMIT;

