INSERT INTO PCLUB.ADMPT_TIPO_PREMIO (ADMPV_COD_TPOPR, ADMPV_DESC, ADMPC_ESTADO, ADMPN_ORDEN, ADMPN_GRUPO)
VALUES ('34', 'Paquete Roaming', 'A', 10, null);


INSERT INTO PCLUB.ADMPT_TIPO_PREMCLIE (ADMPV_COD_TPOPR, ADMPV_COD_TPOCL)
VALUES ('34', '2');


INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQRRC5MB', '34', 'RRC 5 MB', 530, 0, 'A', 944, 0, 'T', 'JUN-14', 'RRC5MB', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQRRC10MB', '34', 'RRC 10 MB', 950, 0, 'A', 945, 0, 'T', 'JUN-14', 'RRC10MB', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQRRC15MB', '34', 'RRC 15 MB', 1270, 0, 'A', 946, 0, 'T', 'JUN-14', 'RRC15MB', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQRRC30MB', '34', 'RRC 30 MB', 2010, 0, 'A', 947, 0, 'T', 'JUN-14', 'RRC30MB', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQRRC50MB', '34', 'RRC 50 MB', 2640, 0, 'A', 948, 0, 'T', 'JUN-14', 'RRC50MB', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQRRC100MB', '34', 'RRC 100 MB', 5065, 0, 'A', 949, 0, 'T', 'JUN-14', 'RRC100MB', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQRRC250MB', '34', 'RRC 250 MB', 12135, 0, 'A', 950, 0, 'T', 'JUN-14', 'RRC250MB', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQMUN5MB', '34', 'Mundo 5  MB', 2955, 0, 'A', 951, 0, 'T', 'JUN-14', 'RM5MB', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQMUN10MB', '34', 'Mundo 10 MB', 5700, 0, 'A', 952, 0, 'T', 'JUN-14', 'RM10MB', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQMUN15MB', '34', 'Mundo 15 MB', 8230, 0, 'A', 953, 0, 'T', 'JUN-14', 'RM15MB', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQMUN30MB', '34', 'Mundo 30 MB', 15825, 0, 'A', 954, 0, 'T', 'JUN-14', 'RM30MB', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQMUN50MB', '34', 'Mundo 50 MB', 25320, 0, 'A', 955, 0, 'T', 'JUN-14', 'RM50MB', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQRRC5MIN', '34', 'RRC 5Min', 635, 0, 'A', 956, 0, 'T', 'JUN-14', 'RRC5MIN', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQRRC15MIN', '34', 'RRC 15Min', 1690, 0, 'A', 957, 0, 'T', 'JUN-14', 'RRC15MIN', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQRRC25MIN', '34', 'RRC 25Min', 2535, 0, 'A', 958, 0, 'T', 'JUN-14', 'RRC25MIN', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQRRC55MIN', '34', 'RRC 55Min', 5065, 0, 'A', 959, 0, 'T', 'JUN-14', 'RRC55MIN', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQRRC95MIN', '34', 'RRC 95Min', 7810, 0, 'A', 960, 0, 'T', 'JUN-14', 'RRC95MIN', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQMUN5MIN', '34', 'Mundo 5 Min', 1055, 0, 'A', 961, 0, 'T', 'JUN-14', 'RM5MIN', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQMUN15MIN', '34', 'Mundo 15 Min', 3060, 0, 'A', 962, 0, 'T', 'JUN-14', 'RM15MIN', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQMUN25MIN', '34', 'Mundo 25 Min', 4855, 0, 'A', 963, 0, 'T', 'JUN-14', 'RM25MIN', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQMUN55MIN', '34', 'Mundo 55 Min', 9710, 0, 'A', 964, 0, 'T', 'JUN-14', 'RM55MIN', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQMUN95MIN', '34', 'Mundo 95 Min', 15190, 0, 'A', 965, 0, 'T', 'JUN-14', 'RM95MIN', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQFACE15MB', '34', 'RRC Facebook 15 MB', 1035, 0, 'A', 966, 0, 'T', 'JUN-14', 'FB15MB', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQFACE30MB', '34', 'RRC Facebook 30 MB', 1460, 0, 'A', 967, 0, 'T', 'JUN-14', 'FB30MB', null, '', '');

INSERT INTO PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
                  		VALUES ('U_PAQFACE50MB', '34', 'RRC Facebook 50 MB', 2090, 0, 'A', 968, 0, 'T', 'JUN-14', 'FB50MB', null, '', '');

COMMIT;
