INSERT INTO PCLUB.ADMPT_PARAMSIST (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
VALUES ((SELECT MAX(TO_NUMBER(ADMPC_COD_PARAM)) + 1 FROM PCLUB.ADMPT_PARAMSIST), 'LATAM CONCEPTO TRANSF CLARO A LATAM', 'TRANSFERENCIA CLARO A LATAM');

INSERT INTO PCLUB.ADMPT_PARAMSIST (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
VALUES ((SELECT MAX(TO_NUMBER(ADMPC_COD_PARAM)) + 1 FROM PCLUB.ADMPT_PARAMSIST), 'LATAM CONCEPTO TRANSF LATAM A CLARO', 'TRANSFERENCIA LATAM A CLARO');

UPDATE PCLUB.ADMPT_PARAMSIST SET ADMPV_VALOR = 'MILLASLATAM'
WHERE ADMPV_DESC = 'LATAM TBL PREMIO ID TRANS CC A KM';

COMMIT;

