insert into PCLUB.Admpt_Tipo_Aplic(ADMPV_COD_TIPAPL, ADMPV_DES_TIPAPL, ADMPV_ESTADO)
VALUES('94', 'USSD', 'A');

insert into PCLUB.Admpt_Tipo_Aplic(ADMPV_COD_TIPAPL, ADMPV_DES_TIPAPL, ADMPV_ESTADO)
VALUES('95', 'MICLARO', 'A');

COMMIT;

