INSERT INTO USRSIAC.SIAC_TRANSACCION 
(TRANV_TRANSACCION,TRANV_PAGINA,TRANV_PAGINA_LECTURA,TRANV_ESTADO,TRANV_PAGINA_CASO)
VALUES 
('TRANSACCION_REGISTRO_CC','X','','1','');

INSERT INTO USRSIAC.SIAC_TIPI_TRANSACCION
(TRANV_TRANSACCION,TITRV_TIPO_CODE,TITRV_CLASE_CODE,TITRV_SUBCLASE_CODE,TITRV_ESTADO,TITRV_CASO)
VALUES
('TRANSACCION_REGISTRO_CC','12','1235','123508','1','');

COMMIT;