
INSERT INTO PCLUB.ADMPT_CANJE_SERVICIO ( ADMPV_COD_SERV ,ADMPV_DES_SERV,ADMPV_ESTADO,ADMPV_FEC_CREACION ,ADMPV_FLG_ACTIVO)
VALUES(150,'Cuenta Personal Recarga',1,SYSDATE,1);

INSERT INTO PCLUB.ADMPT_CANJE_SERVICIO ( ADMPV_COD_SERV ,ADMPV_DES_SERV,ADMPV_ESTADO,ADMPV_FEC_CREACION ,ADMPV_FLG_ACTIVO)
VALUES(536,'Tope de Consumo Cero',1,SYSDATE,0);

INSERT INTO PCLUB.ADMPT_CANJE_SERVICIO ( ADMPV_COD_SERV ,ADMPV_DES_SERV,ADMPV_ESTADO,ADMPV_FEC_CREACION ,ADMPV_FLG_ACTIVO)
VALUES(149,'Control de Consumo',1,SYSDATE,0);

INSERT INTO PCLUB.ADMPT_CANJE_SERVICIO ( ADMPV_COD_SERV ,ADMPV_DES_SERV,ADMPV_ESTADO,ADMPV_FEC_CREACION ,ADMPV_FLG_ACTIVO)
VALUES(537,'Tope de Consumo Automático',1,SYSDATE,0);

COMMIT;


