INSERT INTO PCLUB.ADMPT_CAT_CLIENTE(ADMPN_COD_CATCLI,ADMPV_COD_TPOCL,ADMPV_DESC,ADMPC_TIPO,ADMPN_TME_PUNTO,ADMPV_OPER_INI,ADMPV_OPER_FIN,ADMPN_LIM_INF,ADMPN_LIM_SUP,ADMPC_ESTADO,ADMPN_CXPT_PPAG,ADMPN_CXPT_CFIJ,ADMPN_CXPT_CADI,ADMPN_PTOANIV,ADMPN_CXPT_ADEB)
values(2,'4','Normal','T',12,'4','3',2500,0,'A',0,0,0,0,0);
COMMIT;