
insert into PCLUB.ADMPT_CONCEPTO (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO, ADMPC_TPO_OPER, ADMPC_PROC)
values ('99', 'DEVOLUCION DE CANJE FIJA', 'A', '', 'C', '', 'E', '1');

INSERT INTO PCLUB.ADMPT_CONCEPTO (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO, ADMPC_TPO_OPER, ADMPC_PROC)
values ('104', 'DEVOLUCION CANJE VENTA', 'A', '', 'C', '', 'E ', '1');

COMMIT;

