insert into PCLUB.admpt_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('17', 'ALTA DE CONTRATOS', 'A', 'ALTA_CONTRATOS_YYYYMMDD.CCL', 18, 'C');

insert into PCLUB.admpt_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('18', 'ANIVERSARIO CC', 'A', 'ANIVERSARIO_YYYYMMDD.CCL', 18, 'C');

insert into PCLUB.admpt_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('22', 'RENOVACION DE CONTRATO', 'A', 'RENOVACION_CONTRATOS_YYYYMMDD.CAL', 18, 'C');

insert into PCLUB.admpt_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('38', 'ICLARO', 'A', '', 18, 'C');

insert into PCLUB.admpt_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('19', 'BAJA CLIENTES', 'A', 'BAJA_CLIENTES_YYYYMMDD.CCL', 18, 'C');

insert into PCLUB.admpt_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('47', 'ALINIEACION DE SALDO DE CLIENTES CC', 'A', '', null, 'C');

insert into PCLUB.admpt_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('48', 'ALINIEACION DE SALDO DE CLIENTES IB', 'A', '', null, 'I');

insert into PCLUB.admpt_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('20', 'CAMBIO TITULARIDAD', 'A', 'CAMBIO_TIT_YYYYMMDD.CCL', null, 'C');

COMMIT;