insert into PCLUB.admpt_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO, ADMPC_TPO_OPER, ADMPC_PROC)
values ('167', 'TRANSFERENCIA CLARO A LATAM', 'A', '', 18, 'C', 'LATAM', 'E ', '1');

insert into PCLUB.admpt_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO, ADMPC_TPO_OPER, ADMPC_PROC)
values ('166', 'TRANSFERENCIA LATAM A CLARO', 'A', '', 18, 'C', 'LATAM', 'E ', '1');

commit;

