INSERT INTO PCLUB.ADMPT_CONCEPTO (ADMPV_COD_CPTO,ADMPV_DESC,ADMPC_ESTADO,ADMPC_TPO_PUNTO,ADMPC_TPO_OPER,ADMPC_PROC) VALUES(105	,'RETIRO BONO CHIP 8','A','B','S',1);
INSERT INTO PCLUB.ADMPT_CONCEPTO (ADMPV_COD_CPTO,ADMPV_DESC,ADMPC_ESTADO,ADMPC_TPO_PUNTO,ADMPC_TPO_OPER,ADMPC_PROC) VALUES(106	,'RETIRO BONO DE FIDELIDAD 6 MESES','A','B','S',1);
INSERT INTO PCLUB.ADMPT_CONCEPTO (ADMPV_COD_CPTO,ADMPV_DESC,ADMPC_ESTADO,ADMPC_TPO_PUNTO,ADMPC_TPO_OPER,ADMPC_PROC) VALUES(107	,'RETIRO BONO DE FIDELIDAD 12 MESES','A','B','S',1);
INSERT INTO PCLUB.ADMPT_CONCEPTO (ADMPV_COD_CPTO,ADMPV_DESC,ADMPC_ESTADO,ADMPC_TPO_PUNTO,ADMPC_TPO_OPER,ADMPC_PROC) VALUES(108	,'RETIRO BONO DE CHIP RESPUESTO PREPAGO','A','B','S',1);
INSERT INTO PCLUB.ADMPT_CONCEPTO (ADMPV_COD_CPTO,ADMPV_DESC,ADMPC_ESTADO,ADMPC_TPO_PUNTO,ADMPC_TPO_OPER,ADMPC_PROC) VALUES(109	,'RETIRO BONO CHIP 15','A','B','S',1);
INSERT INTO PCLUB.ADMPT_CONCEPTO (ADMPV_COD_CPTO,ADMPV_DESC,ADMPC_ESTADO,ADMPC_TPO_PUNTO,ADMPC_TPO_OPER,ADMPC_PROC) VALUES(110	,'RETIRO BONO PACK PREPAGO','A','B','S',1);

UPDATE PCLUB.ADMPT_BONO_CONFIG BC  	SET BC.ADMPV_COD_CPTO_SAL=105 WHERE BC.ADMPV_BONO='BONCHIP8' ;
UPDATE PCLUB.ADMPT_BONO_CONFIG BC   SET BC.ADMPV_COD_CPTO_SAL=106 WHERE BC.ADMPV_BONO='BONFID7M' ;
UPDATE PCLUB.ADMPT_BONO_CONFIG BC   SET BC.ADMPV_COD_CPTO_SAL=107 WHERE BC.ADMPV_BONO='BONFID13M' ;														 
UPDATE PCLUB.ADMPT_BONO_CONFIG BC   SET BC.ADMPV_COD_CPTO_SAL=108 WHERE BC.ADMPV_BONO='BONCHIPRESPUESTO' ;
UPDATE PCLUB.ADMPT_BONO_CONFIG BC   SET BC.ADMPV_COD_CPTO_SAL=109 WHERE BC.ADMPV_BONO='BONCHIP15' ;
UPDATE PCLUB.ADMPT_BONO_CONFIG BC   SET BC.ADMPV_COD_CPTO_SAL=110 WHERE BC.ADMPV_BONO='BONPACKPREPAGO' ;

COMMIT;
	





