INSERT INTO PCLUB.ADMPT_CONF_HISTORICO(ID_ESTADO_PROC,ESTADO_PROCESO,DESCRIPCION_ESTADO,FECHA_REGIST,ESTADO_EJECUCION)
VALUES(2,'B','BAJA',SYSDATE,1);
INSERT INTO PCLUB.ADMPT_CONF_HISTORICO(ID_ESTADO_PROC,ESTADO_PROCESO,DESCRIPCION_ESTADO,FECHA_REGIST,ESTADO_EJECUCION)
VALUES(1,'V','VENCIDO',SYSDATE,1);
INSERT INTO PCLUB.ADMPT_CONF_HISTORICO(ID_ESTADO_PROC,ESTADO_PROCESO,DESCRIPCION_ESTADO,FECHA_REGIST,ESTADO_EJECUCION)
VALUES(3,'C','CANCELADO',SYSDATE,1);
COMMIT;