insert into PCLUB.admpt_premio (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPN_MNTDCTO, ADMPV_COD_PAQDAT, ADMPV_COD_SERVTV)
values ('MILLASLATAM', '35', 'Millas Latam', 0, 0, 'A', null, null, '', 'ENE-18', '', null, '', '');

COMMIT;

