INSERT INTO PCLUB.ADMPT_TIPO_CLIENTE(ADMPV_COD_TPOCL, ADMPV_DESC, ADMPC_ESTADO, ADMPV_TIPO,
                               ADMPC_ENCUESTA, ADMPV_PRVENTA, ADMPC_TBLCLIENTE)
VALUES('9', 'Sin Tipo Cliente', 'A', 'SIN TIPO', '', '', '');
COMMIT;


INSERT INTO PCLUB.ADMPT_TIPOCONVENIO(ADMPV_COD_TPOCL, ADMPV_CONVENIO, ADMPV_DESC, ADMPN_PRIORIDAD,
                                     ADMPD_FEC_REG, ADMPD_FEC_MOD, ADMPV_USU_REG, ADMPV_USU_MOD)
VALUES('9', '0001', 'Comunidad Claro', 1, SYSDATE, '', '', '');
COMMIT;


INSERT INTO PCLUB.ADMPT_TIPOSERVICIO(ADMPV_COD_TPOCL, ADMPV_SERVICIO, ADMPV_DESC, ADMPN_PRIORIDAD,
                               ADMPD_FEC_REG, ADMPD_FEC_MOD, ADMPV_USU_REG, ADMPV_USU_MOD)
VALUES('9', '0077', 'Sin servicio', 1, SYSDATE, '', '', '');
COMMIT;
