--SCRIPTS : JCGT - 28/03/12
DECLARE
cIDCONCEPTO NUMBER;
BEGIN
  
  
  --Insertar el nuevo concepto DA(AFILICIACION DE DEBITO)
  SELECT MAX(TO_NUMBER(CC.ADMPV_COD_CPTO)) INTO cIDCONCEPTO
  FROM PCLUB.ADMPT_CONCEPTO CC;
  
  cIDCONCEPTO:=cIDCONCEPTO+1;
  
  INSERT INTO PCLUB.ADMPT_CONCEPTO(ADMPV_COD_CPTO,ADMPV_DESC,ADMPC_ESTADO,ADMPN_PER_CADU,ADMPC_TPO_PUNTO)
  VALUES(cIDCONCEPTO,'AFILIACION DEBITO','A',18,'C');
  
  --Actualiza el valor por punto para CC postpago
  UPDATE PCLUB.ADMPT_CAT_CLIENTE 
  SET ADMPN_CXPT_PPAG=3,
  ADMPN_CXPT_ADEB=3
  WHERE ADMPV_COD_TPOCL IN (1,2);
  
  --Actualiza parametro del rango de nro de dias de vencimiento
  UPDATE PCLUB.ADMPT_PARAMSIST 
  SET ADMPV_VALOR=0
  where ADMPV_DESC='DIAS_VENCIMIENTO_PAGO_CC';
  
  COMMIT;
  DBMS_OUTPUT.put_line('EXITO!!!!');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.put_line('ERROR!!!!');    
  
END;
/