CREATE OR REPLACE TYPE PCLUB.PEDIDO AS OBJECT
( ProdId          VARCHAR2(15),
  Campana         VARCHAR2(200),
  Puntos          NUMBER,
  Pago            NUMBER,
  Cantidad        NUMBER,
  TipoPremio      VARCHAR2(2),
  ServComercial   NUMBER,
  MontoRecarga    Number
)
;
/
CREATE OR REPLACE TYPE PCLUB.LISTA_PEDIDO AS VARRAY(100) OF PEDIDO
;
/
CREATE OR REPLACE TYPE PCLUB.DEVOLUCION AS OBJECT
( ID_CANJE         NUMBER,
  ID_CANJESEC      NUMBER,
  Cantidad         NUMBER
)
;
/
CREATE OR REPLACE TYPE PCLUB.LISTA_DEVOLUCION AS VARRAY(100) OF DEVOLUCION
;
/