create table PCLUB.ADMPT_CIB_TMP_DUPLICADO
(
  ADMPN_COD_CLI_IB NUMBER not null,
  ADMPV_TIPO_DOC   VARCHAR2(20) not null,
  ADMPV_NUM_DOC    VARCHAR2(20) not null,
  ADMPV_NUM_LINEA  VARCHAR2(20),
  ADMPV_COD_CLI    VARCHAR2(40),
  ADMPD_FEC_ACT    DATE,
  ADMPC_ESTADO     CHAR(1),
  ADMPN_FLG_DEBI   NUMBER(1),
  ADMPN_FLG_NUM    NUMBER(1),
  ADMPN_BONO_ACT   NUMBER(1),
  ADMPV_NOM_CLI    VARCHAR2(80),
  ADMPV_APE_CLI    VARCHAR2(80)
);

INSERT INTO PCLUB.ADMPT_CIB_TMP_DUPLICADO
SELECT IB.* FROM PCLUB.ADMPT_CLIENTEIB IB,
(
SELECT I.ADMPV_COD_CLI, COUNT(1) CANTIDAD FROM PCLUB.ADMPT_CLIENTEIB I
WHERE I.ADMPV_COD_CLI IS NOT NULL
--AND I.ADMPV_COD_CLI<>'1.10671650'
AND I.ADMPC_ESTADO='A' 
GROUP BY I.ADMPV_COD_CLI
HAVING COUNT(1)>1
) J
WHERE IB.ADMPV_COD_CLI = J.ADMPV_COD_CLI;
/