UPDATE PCLUB.ADMPT_BONO_CONFIG BC  SET BC.ADMPV_COD_CPTO_SAL=NULL WHERE BC.ADMPV_BONO='BONPACKPREPAGO';
UPDATE PCLUB.ADMPT_BONO_CONFIG BC  SET BC.ADMPV_COD_CPTO_SAL=NULL WHERE BC.ADMPV_BONO='BONCHIP8' ;
UPDATE PCLUB.ADMPT_BONO_CONFIG BC  SET BC.ADMPV_COD_CPTO_SAL=NULL WHERE BC.ADMPV_BONO='BONCHIP15' ;
UPDATE PCLUB.ADMPT_BONO_CONFIG BC  SET BC.ADMPV_COD_CPTO_SAL=NULL WHERE BC.ADMPV_BONO='BONFID7M' ;
UPDATE PCLUB.ADMPT_BONO_CONFIG BC  SET BC.ADMPV_COD_CPTO_SAL=NULL WHERE BC.ADMPV_BONO='BONFID13M' ;
UPDATE PCLUB.ADMPT_BONO_CONFIG BC  SET BC.ADMPV_COD_CPTO_SAL=NULL WHERE BC.ADMPV_BONO='BONCHIPRESPUESTO' ;
UPDATE PCLUB.ADMPT_BONO_CONFIG BC  SET BC.ADMPV_COD_CPTO_SAL=NULL WHERE BC.ADMPV_BONO='BONFID7M';
UPDATE PCLUB.ADMPT_BONO_CONFIG BC  SET BC.ADMPV_COD_CPTO_SAL=NULL WHERE BC.ADMPV_BONO='BONFID13M';

DELETE FROM PCLUB.ADMPT_CONCEPTO WHERE ADMPV_COD_CPTO IN (105,106,107,108,109,110);

COMMIT;
