UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '',
P.ADMPV_CANTIVR = '',
P.ADMPV_TPREMIO = ''
WHERE P.ADMPV_ID_PROCLA = 'U_MINONNET10';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '',
P.ADMPV_CANTIVR = '',
P.ADMPV_TPREMIO = ''
WHERE P.ADMPV_ID_PROCLA = 'U_MINONNET25';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '',
P.ADMPV_CANTIVR = '',
P.ADMPV_TPREMIO = ''
WHERE P.ADMPV_ID_PROCLA = 'U_MINONNET40';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '',
P.ADMPV_CANTIVR = '',
P.ADMPV_TPREMIO = ''
WHERE P.ADMPV_ID_PROCLA = 'U_PAQADU01';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '',
P.ADMPV_CANTIVR = '',
P.ADMPV_TPREMIO = ''
WHERE P.ADMPV_ID_PROCLA = 'U_PAQHBO01';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '',
P.ADMPV_CANTIVR = '',
P.ADMPV_TPREMIO = ''
WHERE P.ADMPV_ID_PROCLA = 'U_SMSCD50';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '',
P.ADMPV_CANTIVR = '',
P.ADMPV_TPREMIO = ''
WHERE P.ADMPV_ID_PROCLA = 'U_PAQHD01';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '',
P.ADMPV_CANTIVR = '',
P.ADMPV_TPREMIO = ''
WHERE P.ADMPV_ID_PROCLA = 'U_PAQINT100MB';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '',
P.ADMPV_CANTIVR = '',
P.ADMPV_TPREMIO = ''
WHERE P.ADMPV_ID_PROCLA = 'U_PAQINT200MB';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '',
P.ADMPV_CANTIVR = '',
P.ADMPV_TPREMIO = ''
WHERE P.ADMPV_ID_PROCLA = 'U_PAQMOV01';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '',
P.ADMPV_CANTIVR = '',
P.ADMPV_TPREMIO = ''
WHERE P.ADMPV_ID_PROCLA = 'U_SMSCD10';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '',
P.ADMPV_CANTIVR = '',
P.ADMPV_TPREMIO = ''
WHERE P.ADMPV_ID_PROCLA = 'U_SMSCD100';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '',
P.ADMPV_CANTIVR = '',
P.ADMPV_TPREMIO = ''
WHERE P.ADMPV_ID_PROCLA = 'U_SMSCD20';

COMMIT;
