DELETE PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'LATAM CONCEPTO TRANSF CLARO A LATAM';

DELETE PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'LATAM CONCEPTO TRANSF LATAM A CLARO';

UPDATE PCLUB.ADMPT_PARAMSIST SET ADMPV_VALOR = '1'
WHERE ADMPV_DESC = 'LATAM TBL PREMIO ID TRANS CC A KM';

COMMIT;

