DELETE FROM DBAUDIT.AUDITORIA_TRANSACCIONES 
WHERE TRACOD =<codigo de transaccion1>;

DELETE FROM DBAUDIT.AUDITORIA_TRANSACCIONES 
WHERE TRACOD =<codigo de transaccion2>;

DELETE FROM DBAUDIT.AUDITORIA_TRANSACCIONES 
WHERE TRACOD =<codigo de transaccion3>;

COMMIT;
