ALTER TABLE PCLUB.ADMPT_CONTRATOS DROP COLUMN ADMPV_ORIGEN;
DROP PACKAGE PCLUB.PKG_AFILIACIONES;
DROP PACKAGE PCLUB.PKG_DESAFILIACION;
DROP PACKAGE PCLUB.PKG_ACUMULACION;
DROP PACKAGE PCLUB.PKG_CONSALPUNTOS;
DROP PACKAGE PCLUB.PKG_CONSULTA_HISTORICO_CANJE;
DROP PACKAGE PCLUB.PKG_REALIZARCANJE;
DROP PACKAGE PCLUB.PKG_CONSULTARINFOPARTNERS;
DROP PACKAGE PCLUB.PKG_TRANSFORMAPUNTOS;