DELETE PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'LATAM RECORD TYPE SYSFT_LATAM_LOTE_CANJE_KM_CC';

DELETE PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'LATAM COMPANY ID SYSFT_LATAM_LOTE_CANJE_KM_CC';

DELETE PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'LATAM REC TYPE SYSFT_LATAM_CANJE_KM_CC';

DELETE PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'LATAM PROGRAM ID SYSFT_LATAM_CANJE_KM_CC';

DELETE PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'LATAM PUNTOS MINIMO PARA CANJE';

DELETE PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'LATAM EQUIVALENCIA CLARO PUNTOS';

DELETE PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'LATAM EQUIVALENCIA KM LATAM';

DELETE PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'LATAM TBL PREMIO ID TRANS CC A KM';

DELETE PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'LATAM PREFIJO SYSFT_LATAM_LOTE_CANJE_KM_CC';

DELETE PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'LATAM TIPO ARCHIVO SYSFT_LATAM_LOTE_CANJE_KM_CC';

DELETE PCLUB.admpt_concepto WHERE ADMPV_DESC = 'TRANSFERENCIA LATAM A CLARO';

DELETE PCLUB.SYSFT_LATAM_EQUIV_TIP_DOC WHERE SYLEV_TIPO_DOC_LATAM = 'DNIPE';

COMMIT;

