
DELETE FROM PCLUB.ADMPT_TIPO_PREMCLIE
WHERE ADMPV_COD_TPOPR = '29'
	  AND ADMPV_COD_TPOCL = '3';

UPDATE PCLUB.ADMPT_PREMIO 
SET ADMPV_DESC='PUNTOS FLEXIBLES' 
WHERE ADMPV_ID_PROCLA='U_DSCEQFLEX';

UPDATE PCLUB.ADMPT_TIPO_PREMIO
SET ADMPC_ESTADO = 'A'
WHERE ADMPV_COD_TPOPR = '31';

UPDATE PCLUB.ADMPT_PREMIO
SET ADMPC_ESTADO = 'A'
WHERE ADMPV_COD_TPOPR IN ('31','28')
      AND ADMPV_ID_PROCLA <> 'U_DSCEQUIPO';

INSERT INTO PCLUB.ADMPT_TIPO_PREMCLIE (ADMPV_COD_TPOPR, ADMPV_COD_TPOCL)
VALUES('31', '1');

INSERT INTO PCLUB.ADMPT_TIPO_PREMCLIE (ADMPV_COD_TPOPR, ADMPV_COD_TPOCL)
VALUES('31', '2');

INSERT INTO PCLUB.ADMPT_TIPO_PREMCLIE (ADMPV_COD_TPOPR, ADMPV_COD_TPOCL)
VALUES('31', '3');

COMMIT;
