DELETE FROM PCLUB.ADMPT_CONCEPTO C WHERE C.ADMPV_DESC = 'ANIVERSARIO HFC';
DELETE FROM PCLUB.ADMPT_PARAMSIST P WHERE P.ADMPV_DESC = 'PUNTOS_ANIVERSARIO_HFC';
COMMIT;

DROP TABLE PCLUB.ADMPT_TMP_PROM_DTH_HFC;
CREATE TABLE PCLUB.ADMPT_TMP_PROM_DTH_HFC
(
  ADMPV_COD_CLI    VARCHAR2(40),
  ADMPN_PUNTOS     NUMBER,
  ADMPV_SERVICIO   VARCHAR2(20),
  ADMPV_PERIODO    VARCHAR2(6),
  ADMPV_NOM_PROMO  VARCHAR2(150),
  ADMPD_FEC_REG    DATE,
  ADMPD_FEC_OPER   DATE,
  ADMPV_NOM_ARCH   VARCHAR2(150),
  ADMPC_COD_ERROR  CHAR(3),
  ADMPV_MSJE_ERROR VARCHAR2(400),
  ADMPN_SEQ        NUMBER,
  ADMPV_COD_TPOCL  VARCHAR2(2)
)
tablespace PCLUB_DATA
  pctfree 10
  pctused 40
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

CREATE OR REPLACE TRIGGER PCLUB.T_INS_TMP_PROM_DTH_HFC
BEFORE INSERT ON PCLUB.ADMPT_TMP_PROM_DTH_HFC REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.ADMPD_FEC_REG := SYSDATE;
END T_INS_TMP_PROM_DTH_HFC;
/

ALTER TABLE PCLUB.ADMPT_IMP_PROM_DTH_HFC DROP COLUMN ADMPV_MESVENCI;

DELETE FROM PCLUB.ADMPT_CONCEPTO WHERE ADMPV_TPO_CPTO = 'HFC - PROMO';
COMMIT;

DELETE FROM PCLUB.ADMPT_TIPO_PREMCLIE WHERE ADMPV_COD_TPOPR = '30' AND ADMPV_COD_TPOCL = '7';
COMMIT;
/


