DELETE FROM PCLUB.ADMPT_TIPO_CLIENTE TC WHERE TC.ADMPV_COD_TPOCL = '9';
COMMIT;

DELETE FROM PCLUB.ADMPT_TIPOCONVENIO TCO WHERE TCO.ADMPV_COD_TPOCL = '9';
COMMIT;

DELETE FROM PCLUB.ADMPT_TIPOSERVICIO TS WHERE TS.ADMPV_COD_TPOCL = '9';
COMMIT;
