DELETE FROM DBAUDIT.AUDITORIA_TRANSACCIONES 
WHERE TRACOD =<codigo de transaccion1>;

DELETE FROM DBAUDIT.AUDITORIA_TRANSACCIONES 
WHERE TRACOD =<codigo de transaccion2>;

DELETE FROM DBAUDIT.AUDITORIA_TRANSACCIONES 
WHERE TRACOD =<codigo de transaccion3>;

DELETE FROM DBAUDIT.AUDITORIA_TRANSACCIONES 
WHERE TRACOD =<codigo de transaccion4>;

DELETE FROM DBAUDIT.AUDITORIA_TRANSACCIONES 
WHERE TRACOD =<codigo de transaccion5>;

DELETE FROM DBAUDIT.AUDITORIA_TRANSACCIONES 
WHERE TRACOD =<codigo de transaccion6>;

DELETE FROM DBAUDIT.AUDITORIA_TRANSACCIONES 
WHERE TRACOD =<codigo de transaccion7>;

DELETE FROM DBAUDIT.AUDITORIA_TRANSACCIONES 
WHERE TRACOD =<codigo de transaccion8>;

DELETE FROM DBAUDIT.AUDITORIA_TRANSACCIONES 
WHERE TRACOD =<codigo de transaccion9>;

DELETE FROM DBAUDIT.AUDITORIA_TRANSACCIONES 
WHERE TRACOD =<codigo de transaccion10>;

COMMIT;
