--Periodo
INSERT INTO PCLUB.ADMPT_PERIODO VALUES('6','6 MESES');
COMMIT;

--Plan
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(10001,'TUN 2 plan 39',39);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(10002,'TUN 2 plan 59',59);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(10003,'TUN 2 plan 79',79);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(10004,'TUN 2 plan 99',99);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(10005,'TUN 2 plan 149',149);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(10006,'TUN 2 plan 199',199);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(10007,'TUN 2 plan 249',249);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(10008,'TUN 2 plan 319',319);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(10009,'TUN 2 plan 20',20);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(10010,'TUN 2 plan 25',25);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(10011,'TUN 2 plan 29',29);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(20001,'Plan Increible 90',0);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(20002,'Plan Increible 125',0);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(20003,'Plan Increible 175',0);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(20004,'Plan Increible 230',0);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(20005,'Plan Increible 335',0);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(30001,'Plan Iphone 0',143);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(30002,'Plan Iphone 1',186);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(30003,'Plan Iphone 2',244);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(30004,'Plan Iphone 3',301);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(30005,'Plan Iphone Ilimitado',474);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(40001,'Smart BB 69',69);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(40002,'Smart BB 99',99);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(40003,'Smart BB 129',129);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(40004,'Smart BB 149',149);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(40005,'Smart BB 159',159);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(50001,'Smart i 69',69);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(50002,'Smart i 99',99);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(50003,'Smart i 129',129);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(50004,'Smart i 149',149);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(50005,'Smart i 159',159);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(60001,'Combo RPC 49',0);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(60002,'Combo RPC 74',0);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(60003,'Combo RPC 79',0);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(60004,'Combo RPC 99',0);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(70001,'HABLA CLARO 2 plan 39',39);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(70002,'HABLA CLARO 2 plan 59',59);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(70003,'HABLA CLARO 2 plan 79',79);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(70004,'HABLA CLARO 2 plan 99',99);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(70005,'HABLA CLARO 2 plan 149',149);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(70006,'HABLA CLARO 2 plan 199',199);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(70007,'HABLA CLARO 2 plan 249',249);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(70008,'HABLA CLARO 2 plan 319',319);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(70009,'HABLA CLARO 2 plan 20',20);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(70010,'HABLA CLARO 2 plan 25',25);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(70011,'HABLA CLARO 2 plan 29',29);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(80001,'Internet Claro Ilimitado 1000',129);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(80002,'Internet Claro Ilimitado 1500',199);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(80003,'Internet Claro Ilimitado 700',99);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(80004,'Internet Claro Limitado 10GB',199);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(80005,'Internet Claro Limitado 2GB',79);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(80006,'Internet Claro Limitado 3GB',99);
insert into pclub.admpt_tipo_plan (admpn_cod_plan, admpv_des_plan, admpn_ptorencon) values(80007,'Internet Claro Limitado 5GB',129);
commit;

--Equipo

insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBAL600A','Alcatel 600A');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBAL708A','Alcatel 708A');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBAL8000','Alcatel 800');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBAL8800','Alcatel 880');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBBB8120','BLACKBERRY 8120');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBBB8220','Blackberry 8220 KICKSTAR');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBBB8520','Blackberry 8520');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBBB8700','Blackberry 8700');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBBB8900','Blackberry 8900');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBBB9100','Blackberry 9100');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBBB9300','Blackberry 9300');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBBB9700','Blackberry 9700');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBBB9800','Blackberry 9800');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBBB8320','BLACKBERRY 8320');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBIP3G32','IPHONE 32GB 3GS');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBIP4G16','IPHONE 4 16GB');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBIP4G32','IPHONE 4 32GB');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBIP3G08','IPHONE 8GB 3GS');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBLGM205','LG GM205');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBLGM210','LG GM210');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBLGM630','LG GM630');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBLGM600','LG GM600');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBLGK300','LG KF300');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBLGK570','LG KP570');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBLGM550','LG MU550');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBMOEM28','Motorola EM28');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBNK2730','NOKIA 2730');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBNK2630','Nokia 2630');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBNK5530','NOKIA 5530');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBNK5230','Nokia 5230');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBNK5800','Nokia 5800');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBNK6300','Nokia 6300');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBNKC300','Nokia C3');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBNKE630','Nokia E63');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBNKE710','Nokia E71');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBNKE720','Nokia E72');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBNKN960','Nokia N96');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBNKN970','Nokia N97 Mini');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBNKX300','Nokia X3');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBNKX600','Nokia X6');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBSC3200','Samsung C3200');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBSE1107','Samsung E1107 SOLAR');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBSE2210','Samsung E2210');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBSI6220','Samsung I6220 STAR TV');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBSI6370','Samsung I637 JACKIE');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBSM2310','Samsung M2310 CANCAN');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBSM2510','Samsung M2510 DISCO');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBSS3650','Samsung S3650 CORBY');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBSS5230','Samsung S5230 STAR');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBSS8500','Samsung S8500');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBSI9000','SAMSUNG I9000B');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBSU900L','Samsung U900L SOUL');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECC510','Sony Ericsson C510');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECC702','Sony Ericsson C702');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBESATIO','SONY ERICSSON SATIO');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECJ105','Sony Ericsson J105');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECK850','Sony Ericsson K850');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECP100','Sony Ericsson P1');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECR300','Sony Ericsson R300');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECW205','Sony Ericsson W205');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECW395','Sony Ericsson W395');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECW508','Sony Ericsson W508');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECW705','Sony Ericsson W705');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECW760','Sony Ericsson W760');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECW910','Sony Ericsson W910');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECW980','Sony Ericsson W980');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECX010','Sony Ericsson X10');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECX10M','Sony Ericsson X10 MINI');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBECX10P','Sony Ericsson X10 MINI PRO');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBTCM004','TOCS M004');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBUT1238','UTSTARCOM FM1238');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBVKI500','Verykool I500');
insert into pclub.admpt_equipo (admpv_cod_equ, admpv_dsc_equ) values('PBZTN280','ZTE N280 TV');
commit;