drop table PCLUB.CC_BLACKLIST_FIDELIDAD;
drop table PCLUB.CC_CONFIG_SMS;
drop table PCLUB.CC_FIDELIDAD;
drop table PCLUB.CC_SEGMENTO_BENEFICIO;
drop table PCLUB.CC_WHITELIST_FIDELIDAD;
drop table PCLUB.CC_SEGMENTO_FIDELIDAD;
drop table PCLUB.CC_BENEFICIO_FIDELIDAD;

DROP PACKAGE PCLUB.CC_PKG_FIDELIDAD; 
DROP PACKAGE PCLUB.PKG_CC_PROM_FIDELIDAD; 
