UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '1',
P.ADMPV_CANTIVR = '10',
P.ADMPV_TPREMIO = 'M'
WHERE P.ADMPV_ID_PROCLA = 'U_MINONNET10';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '1',
P.ADMPV_CANTIVR = '25',
P.ADMPV_TPREMIO = 'M'
WHERE P.ADMPV_ID_PROCLA = 'U_MINONNET25';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '1',
P.ADMPV_CANTIVR = '40',
P.ADMPV_TPREMIO = 'M'
WHERE P.ADMPV_ID_PROCLA = 'U_MINONNET40';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '1',
P.ADMPV_CANTIVR = 'ADULTO',
P.ADMPV_TPREMIO = 'F'
WHERE P.ADMPV_ID_PROCLA = 'U_PAQADU01';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '1',
P.ADMPV_CANTIVR = 'HBO',
P.ADMPV_TPREMIO = 'F'
WHERE P.ADMPV_ID_PROCLA = 'U_PAQHBO01';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '1',
P.ADMPV_CANTIVR = '50',
P.ADMPV_TPREMIO = 'M'
WHERE P.ADMPV_ID_PROCLA = 'U_SMSCD50';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '1',
P.ADMPV_CANTIVR = 'HD',
P.ADMPV_TPREMIO = 'F'
WHERE P.ADMPV_ID_PROCLA = 'U_PAQHD01';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '1',
P.ADMPV_CANTIVR = '100',
P.ADMPV_TPREMIO = 'M'
WHERE P.ADMPV_ID_PROCLA = 'U_PAQINT100MB';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '1',
P.ADMPV_CANTIVR = '200',
P.ADMPV_TPREMIO = 'M'
WHERE P.ADMPV_ID_PROCLA = 'U_PAQINT200MB';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '1',
P.ADMPV_CANTIVR = 'FOX+',
P.ADMPV_TPREMIO = 'F'
WHERE P.ADMPV_ID_PROCLA = 'U_PAQMOV01';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '1',
P.ADMPV_CANTIVR = '10',
P.ADMPV_TPREMIO = 'M'
WHERE P.ADMPV_ID_PROCLA = 'U_SMSCD10';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '1',
P.ADMPV_CANTIVR = '100',
P.ADMPV_TPREMIO = 'M'
WHERE P.ADMPV_ID_PROCLA = 'U_SMSCD100';

UPDATE PCLUB.ADMPT_PREMIO P
SET P.ADMPV_IVR = '1',
P.ADMPV_CANTIVR = '20',
P.ADMPV_TPREMIO = 'M'
WHERE P.ADMPV_ID_PROCLA = 'U_SMSCD20';

COMMIT;
