DECLARE
TYPE CUR_C IS REF CURSOR;
C1 CUR_C;
COD_CLI VARCHAR2(40);
MONTO NUMBER;
COD_CLIIB VARCHAR2(40);
SALDOS NUMBER;
SALDOS_KARDEX NUMBER;
FEC_ACT DATE;
BONO_ACT NUMBER;

BEGIN

OPEN C1 FOR
SELECT I.ADMPV_COD_CLI, COUNT(1) MONTO FROM PCLUB.ADMPT_CLIENTEIB I
WHERE I.ADMPV_COD_CLI IS NOT NULL
AND I.ADMPC_ESTADO='A'
GROUP BY I.ADMPV_COD_CLI
HAVING COUNT(1)>1;

LOOP
FETCH C1 INTO COD_CLI,MONTO;
EXIT WHEN C1%NOTFOUND;
SELECT S.ADMPN_SALDO_IB, S.ADMPN_COD_CLI_IB INTO SALDOS, COD_CLIIB
FROM PCLUB.ADMPT_SALDOS_CLIENTE S 
WHERE S.ADMPV_COD_CLI=COD_CLI AND S.ADMPC_ESTPTO_IB='A';

SELECT SUM(K.ADMPN_SLD_PUNTO) INTO SALDOS_KARDEX
FROM PCLUB.ADMPT_KARDEX K 
WHERE K.ADMPV_COD_CLI=COD_CLI
AND K.ADMPN_COD_CLI_IB IS NOT NULL
AND K.ADMPC_TPO_PUNTO='I';

UPDATE PCLUB.ADMPT_KARDEX K
SET K.ADMPN_COD_CLI_IB=COD_CLIIB
WHERE K.ADMPV_COD_CLI=COD_CLI
AND K.ADMPC_TPO_PUNTO='I'
AND K.ADMPN_COD_CLI_IB IS NOT NULL;

UPDATE PCLUB.ADMPT_SALDOS_CLIENTE S
SET S.ADMPN_SALDO_IB=SALDOS_KARDEX
WHERE S.ADMPV_COD_CLI=COD_CLI;

SELECT IB.ADMPD_FEC_ACT,IB.ADMPN_BONO_ACT INTO FEC_ACT, BONO_ACT
FROM PCLUB.ADMPT_CLIENTEIB IB
WHERE IB.ADMPV_COD_CLI=COD_CLI
AND IB.ADMPD_FEC_ACT=(SELECT MIN(I.ADMPD_FEC_ACT) FROM PCLUB.ADMPT_CLIENTEIB I
WHERE I.ADMPV_COD_CLI=COD_CLI);

UPDATE PCLUB.ADMPT_CLIENTEIB I
SET I.ADMPD_FEC_ACT = FEC_ACT, I.ADMPN_BONO_ACT=BONO_ACT
WHERE I.ADMPV_COD_CLI=COD_CLI AND I.ADMPN_COD_CLI_IB = COD_CLIIB;

DELETE FROM PCLUB.ADMPT_CLIENTEIB IB WHERE IB.ADMPN_COD_CLI_IB<>COD_CLIIB AND IB.ADMPV_COD_CLI = COD_CLI;
END LOOP;
CLOSE C1;
COMMIT;
END;
/