LOAD DATA
append into table PCLUB.ADMPT_TMP_PRXRCON_CC
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"'
trailing nullcols
(
ADMPV_COD_CLI CHAR
, ADMPC_TIP CHAR
, ADMPN_COD_CONTR CHAR 
, ADMPD_FEC_OPER date "yyyymmdd"
, ADMPV_NOM_ARCH CHAR
, ADMPN_SEQ  SEQUENCE(COUNT,1)
)
