LOAD DATA
append into table PCLUB.TEMP_CONCILIA_CC
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY  '"' 
TRAILING NULLCOLS
(
 ID_CONCIL CHAR,
 ID_ESNRIO CHAR,
 DSC_ESNRIO CHAR,
 COD_CLI CHAR,
 DNI_CLI CHAR,
 MONT_CLI,
 TIP_OPER CHAR,
 FEC_REG date "YYYYMMDD",
 NOM_ARCH CHAR,
 FEC_CARG "TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY')"
)

