LOAD DATA
append into table PCLUB.ADMPT_TMP_ANIV
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY ';'
TRAILING NULLCOLS
(
ADMPV_COD_CLI CHAR,
ADMPV_PERIODO CHAR,
ADMPD_FEC_OPER DATE "YYYYMMDD",
ADMPV_NOM_ARCH CHAR,
ADMPC_COD_ERROR CHAR,
ADMPV_MSJE_ERROR CHAR,
ADMPN_SEQ SEQUENCE(COUNT,1),
ADMPN_PUNTOS CHAR
)
