WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR CONTINUE;

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_MAESTRA_POSTPAGO_TP1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.TP_MAESTRA_POSTPAGO');
END;
/

WHENEVER SQLERROR EXIT 1;

CREATE TABLE DM.DW_MAESTRA_POSTPAGO_TP1 NOLOGGING AS
SELECT 
A.PRODUCT_NUMBER MSISDN ,A.CUSTOMER_ACCOUNT_ORIG CUSTOMER_ID, A.CONTRACT_NUMBER CO_ID,  
A.ID_CARD_VALUE NRO_DOCUMENTO,A.PRODUCT_START_DATE FCH_ACTIVACION,
CASE WHEN A.PRODUCT_STATUS = 'A' THEN 'ACTIVO' WHEN A.PRODUCT_STATUS = 'D' THEN 'DESACTIVO' WHEN A.PRODUCT_STATUS ='S' THEN 'SUSPENDIDO' END  STATUS,
CASE WHEN A.CUSTOMER_TYPE = 'CORPORATIVO' AND LENGTH(A.ID_CARD_VALUE) = 11 THEN 'CORPORATIVO' ELSE 'MASIVO' END POSTPAGO,
CASE WHEN A.CUSTOMER_DOC_TYPE_DESC = 'DNI' THEN 'DNI' WHEN A.CUSTOMER_DOC_TYPE_DESC IN ( 'Pasaporte', 'PASAPORTE') THEN 'PASAPORTE' 
WHEN A.CUSTOMER_DOC_TYPE_DESC = 'RUC' THEN 'RUC'
WHEN A.CUSTOMER_DOC_TYPE_DESC = 'CIP' THEN 'CIP' WHEN A.CUSTOMER_DOC_TYPE_DESC IN ( 'Carnet Extranjería', 'CARNÉ DE EXTRANJERÍA', 'CARNET EXTRANJERÍA') THEN 'CARNET EXTRANJERÍA' 
WHEN A.CUSTOMER_DOC_TYPE_DESC IN ( 'No Definido', 'NO DEFINIDO') THEN 'NO DEFINIDO' WHEN A.CUSTOMER_DOC_TYPE_DESC = 'CE' THEN 'CE' 
WHEN A.CUSTOMER_DOC_TYPE_DESC = 'C.E.' THEN 'CE'
WHEN A.CUSTOMER_DOC_TYPE_DESC IN ( 'No Precisado', 'NO PRECISADO') THEN 'NO PRECISADO' END TIPO_DOCUMENTO,
A.REASON_STATUS,
A.PERIOD MES
FROM DWA.DW_M_PRODUCT_HIST A
WHERE A.PERIOD = '&1'
AND A.PRODUCT_TYPE_DESC = 'TELEFONIA MOVIL'
AND A.AGREEMENT_MODE = 'POSTPAGO'
AND A.CUSTOMER_TYPE IN ( 'MASIVO', 'CORPORATIVO')
AND LENGTH (A.PRODUCT_NUMBER) = 11
AND A.ID_CARD_VALUE IS NOT NULL
AND A.CONTRACT_NUMBER IS NOT NULL
AND A.PRODUCT_NUMBER LIKE '519%'
AND (A.PRODUCT_END_DATE IS NULL OR TO_CHAR (PRODUCT_END_DATE, 'YYYYMM') = A.PERIOD);

CREATE TABLE DM.TP_MAESTRA_POSTPAGO NOLOGGING AS
select msisdn, customer_id, co_id, nro_documento, to_char(FCH_ACTIVACION, 'DD/MM/YYYY') AS FCH_ACTIVACION, STATUS, POSTPAGO, TIPO_DOCUMENTO, MES, REASON_STATUS
from DM.DW_MAESTRA_POSTPAGO_TP1;

DELETE FROM DWM.DW_MAESTRA_POSTPAGO
WHERE MES='&1';
COMMIT;

INSERT INTO DWM.DW_MAESTRA_POSTPAGO 
(
MSISDN, 
CUSTOMER_ID, 
CO_ID, 
NRO_DOCUMENTO, 
FCH_ACTIVACION, 
STATUS, 
POSTPAGO, 
TIPO_DOCUMENTO, 
MES, 
REASON_STATUS
)
SELECT 
MSISDN, 
CUSTOMER_ID, 
CO_ID, 
NRO_DOCUMENTO, 
FCH_ACTIVACION, 
STATUS, 
POSTPAGO, 
TIPO_DOCUMENTO, 
MES, 
REASON_STATUS
FROM DM.TP_MAESTRA_POSTPAGO;

COMMIT;

DROP TABLE DM.DW_MAESTRA_POSTPAGO_TP1 PURGE;
DROP TABLE DM.TP_MAESTRA_POSTPAGO PURGE;

EXIT;
