WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_CANT_X_MES_ITE_VAR_SPSS');
END;
/

ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/RRRR';
CREATE TABLE DM.DW_CANT_X_MES_ITE_VAR_SPSS NOLOGGING COMPRESS AS 
SELECT /*+ PARALLEL 4*/ TO_CHAR(CREATE_DATE,'YYYYMM') AS MES, COUNT(PHONE) AS VF2_155, PHONE AS MSISDN
FROM DWS.SA_TABLE_INTERACT
WHERE (S_REASON_2 LIKE 'VARIACIÓN%'
OR S_REASON_2 LIKE 'VARIACION%')
AND S_REASON_1 = 'POSTPAGO'
AND LENGTH (PHONE)= 9
AND SUBSTR(PHONE,'1','1')= '9'
AND TO_CHAR(CREATE_DATE,'YYYYMM') = '&1'
GROUP BY  TO_CHAR(CREATE_DATE,'YYYYMM'), PHONE;

INSERT INTO DWM.DW_CANT_X_MES_ITE_VAR_SPSS SELECT * FROM DM.DW_CANT_X_MES_ITE_VAR_SPSS; 
COMMIT;

DROP TABLE DM.DW_CANT_X_MES_ITE_VAR_SPSS PURGE;

EXIT;