WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/RRRR';

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_VF2_183_CARGO_FIJO');
END;
/

CREATE TABLE DM.DW_VF2_183_CARGO_FIJO NOLOGGING AS
SELECT B.MSISDN, B.CO_ID, B.MES, sum((A.FLAT_CHARGE * C.VAT_RATE) + A.FLAT_CHARGE) AS VF2_183
FROM DWA.DW_M_PRODUCT_HIST A, DWM.DW_MAESTRA_POSTPAGO B, DWO.DW_C_DATE C
WHERE A.CONTRACT_NUMBER = B.CO_ID
AND A.PRODUCT_NUMBER = B.MSISDN
AND TO_CHAR(A.PRODUCT_START_DATE, 'DD/MM/YYYY') = B.FCH_ACTIVACION
AND B.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND B.FCH_ACTIVACION IS NOT NULL
AND B.POSTPAGO IN ('CORPORATIVO', 'MASIVO')
AND A.PERIOD = '&1'
AND B.MES = '&1'
AND B.MES = C.PERIOD
AND C.DATE_VALUE = last_day(to_date('&1','YYYYMM'))
GROUP BY B.MSISDN, B.CO_ID, B.MES;

INSERT INTO DWM.DW_VF2_183_CARGO_FIJO SELECT * FROM DM.DW_VF2_183_CARGO_FIJO; 
COMMIT;

DROP TABLE DM.DW_VF2_183_CARGO_FIJO PURGE;

EXIT;