WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS2_PUNTOVENTA');
END;
/

CREATE TABLE DM.DW_SPSS2_PUNTOVENTA PARALLEL 2 AS
SELECT
PERIODO,
MSISDN,
VF2_380,
VF2_381,
VF2_379,
VF2_377
FROM
(
select  
'&1' AS PERIODO,
PRODUCT_NUMBER AS MSISDN,
PDV_PVU_DESC AS VF2_380,
PDV_REGION_DESC AS VF2_381,
PDV_DEPARTMENT_DESC AS VF2_379,
PDV_PVU_CHANNEL_DESC AS VF2_377,
ROW_NUMBER() OVER(PARTITION BY PRODUCT_NUMBER ORDER BY SALE_DATE DESC) RW
from DWA.DW_T_CUSTOMER_SALE  A
WHERE EXISTS (SELECT 1 FROM DWM.DW_MAESTRA_POSTPAGO B WHERE B.MSISDN=A.PRODUCT_NUMBER
AND B.MES='&1')
AND SALES_TYPE_DESC ='POSTPAGO'
and product_type_desc='MOVIL'
AND PRODUCT_NUMBER LIKE '519%'
and PROD_OFFER_ITEM_TYPE_IND = 'C'
) WHERE RW=1;

DELETE FROM DWM.DW_SPSS2_PUNTOVENTA WHERE PERIODO='&1';
COMMIT;
INSERT INTO DWM.DW_SPSS2_PUNTOVENTA SELECT * FROM DM.DW_SPSS2_PUNTOVENTA; 
COMMIT;

DROP TABLE DM.DW_SPSS2_PUNTOVENTA PURGE;

EXIT;