WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/RRRR';

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_BASE_RENO_1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_BASE_RENO_2');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_CANT_RENO_MES_LINEA');
END;
/

CREATE TABLE DM.DW_BASE_RENO_1 NOLOGGING COMPRESS AS
SELECT 
FECHA_VENTA,
DESC_CANAL , 
NRO_TELEFONO AS MSISDN,
IMEI,
SIMCARD,
SUBSTR(SEL.IMEI,4,8) TAC,
PLAZO_ACUERDO,
EQUIPO
FROM 
DM.DW_SELLOUT SEL
WHERE TO_CHAR(FECHA_VENTA, 'YYYYMM') = '&1'
AND DESC_TIPO_VENTA  = 'POSTPAGO' 
AND CLASE_VENTA = '04'
AND DESC_CANAL IS NOT NULL
AND NRO_TELEFONO IS NOT NULL
AND NRO_TELEFONO <> '0';

CREATE TABLE DM.DW_BASE_RENO_2 NOLOGGING COMPRESS AS
SELECT * FROM DM.DW_BASE_RENO_1 J
WHERE J.EQUIPO IS NOT NULL;

CREATE TABLE DM.DW_CANT_RENO_MES_LINEA NOLOGGING PARALLEL 2 COMPRESS AS
SELECT /*+PARALLEL 4*/ MES,MP.MSISDN, COUNT(J.EQUIPO) AS VF2_206
FROM DWM.DW_MAESTRA_POSTPAGO MP,
DM.DW_BASE_RENO_2 J
WHERE MP.MSISDN = J.MSISDN(+)
AND MP.MES = '&1'
GROUP BY  MES,MP.MSISDN;
ALTER TABLE DM.DW_CANT_RENO_MES_LINEA NOPARALLEL;

INSERT INTO DWM.DW_CANT_RENO_MES_LINEA SELECT * FROM DM.DW_CANT_RENO_MES_LINEA; 
COMMIT;

DROP TABLE DM.DW_BASE_RENO_1 PURGE;
DROP TABLE DM.DW_BASE_RENO_2 PURGE;
DROP TABLE DM.DW_CANT_RENO_MES_LINEA PURGE;

EXIT;