WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

DROP TABLE DM.DW_SPSS2_CELDA_CDR PURGE;


DECLARE
V_PERIODO  VARCHAR2(6);
V_QUERY    VARCHAR2(30000);

BEGIN

SELECT '&1' INTO V_PERIODO FROM DUAL;

V_QUERY:='';
V_QUERY:='CREATE TABLE DM.DW_SPSS2_CELDA_CDR nologging PARALLEL 2  AS   '||
' SELECT mes, tim_number, LAC AS VF2_234, CELDA AS VF2_230, departamento AS VF2_235 '||
' FROM DM.F_M_LINEAS_CELDA_CDR PARTITION (P_'||V_PERIODO||') A WHERE EXISTS (SELECT 1 FROM DM.DW_MAESTRA_POSTPAGO B ' ||
' WHERE B.MSISDN=TRIM(A.TIM_NUMBER) AND B.MES = '''||V_PERIODO||''') ';

EXECUTE IMMEDIATE V_QUERY;
END;
/

GRANT ALL ON DM.DW_SPSS2_CELDA_CDR TO DBLINK_DWO;

EXIT;