WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS2_VF2_186');
END;
/

CREATE TABLE DM.DW_SPSS2_VF2_186 AS
SELECT D.CO_ID, D.MES, CASE WHEN B.VIGENCIA_COMERCIAL = 'VIGENTE' THEN 'SI' WHEN B.VIGENCIA_COMERCIAL = 'NO VIGENTE' THEN 'NO' END AS VF2_186
FROM DMRED.CONTRACT_ALL A
INNER JOIN CLIINC.CATALOGO_PLANES B
ON A.TMCODE = B.TMCODE
INNER JOIN DMRED.CUSTOMER_ALL C
ON A.CUSTOMER_ID = C.CUSTOMER_ID
INNER JOIN DWM.DW_MAESTRA_POSTPAGO D
ON A.CO_ID = D.CO_ID
AND A.CUSTOMER_ID = D.CUSTOMER_ID
AND C.CUSTOMER_ID = D.CUSTOMER_ID
AND D.POSTPAGO IN ('CORPORATIVO', 'MASIVO')
AND D.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND D.MES = '&1';

DELETE FROM DWM.DW_SPSS2_VF2_186 WHERE MES='&1';
COMMIT;

INSERT INTO DWM.DW_SPSS2_VF2_186 SELECT * FROM DM.DW_SPSS2_VF2_186; 
COMMIT;

DROP TABLE DM.DW_SPSS2_VF2_186 PURGE;

EXIT;