WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

INSERT INTO dwm.DM_SPSS_LOCALIDAD_CONTRACT
SELECT * FROM dm.DM_SPSS_LOCALIDAD_CONTRACT@DBL_DWM;
COMMIT;

INSERT INTO dwm.DW_SPSS2_CELDA_CDR
SELECT * FROM dm.DW_SPSS2_CELDA_CDR@DBL_DWM;
COMMIT;

INSERT INTO dwm.DW_SPSS2_SEG_CAE_VF2_213
SELECT * FROM dm.DW_SPSS2_SEG_CAE_VF2_213@DBL_DWM;
COMMIT;

EXIT;