WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS2_VF2_216_SEG1_MAYO');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS2_VF2_216_SEG2_MAYO');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS2_VF2_216_SEG1_2_MAYO');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS2_VF2_216_MAYO_CAL');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS2_VF2_216_MAYO');


END;
/
CREATE TABLE DM.DW_SPSS2_VF2_216_SEG1_MAYO AS
SELECT periodo, ruc_dni,
COUNT(1) cant_fact,
COUNT(DISTINCT Fecha_Emision) cant_periodo_fact,
COUNT(case
when FEC_BLOQ IS NOT NULL then
1
else
null
end) cant_bloq,
sum(dias_b) dias_bloq,
case
when COUNT(1) >= 3 then
sum(dias_b) / (COUNT(DISTINCT Fecha_Emision) * 30)
end valor
FROM (SELECT '&1' AS PERIODO,
c.*,
NVL(round(DECODE(SIGN(NVL(C.FEC_DESBLOQ,
TO_DATE('01011990', 'DDMMYYYY')) -
C.FEC_BLOQ),
-1,
to_date('&1', 'yyyymm') - C.FEC_BLOQ,
C.FEC_DESBLOQ - C.FEC_BLOQ),
5),0) dias_b
FROM DWS.SA_TIM_FACT_CLIENT_HISTORY c
where 1 = 1
and TO_CHAR(FECHA_VENC, 'YYYYMM') < '&1'
AND FECHA_EMISION > =
ADD_MONTHS(TO_DATE('&1', 'YYYYMM'), (-1) * 6)
AND c.PLATAFORMA NOT IN 'FIJO'
AND C.RUC_DNI IS NOT NULL
AND C.RUC_DNI <> '0')
group by RUC_DNI, periodo;

CREATE TABLE DM.DW_SPSS2_VF2_216_SEG2_MAYO AS
SELECT periodo2,
ruc_dni AS RUC_DNI2,
COUNT(1) cant_fact2,
COUNT(DISTINCT Fecha_Emision) cant_periodo_fact2,
COUNT(case
when FEC_BLOQ IS NOT NULL then
1
else
null
end) cant_bloq2,
sum(dias_b) dias_bloq2,
case
when COUNT(1) >= 3 then
sum(dias_b) / (COUNT(DISTINCT Fecha_Emision) * 30)
end valor2
FROM (SELECT '&1' AS PERIODO2,
c.*,
NVL(round(DECODE(SIGN(NVL(C.FEC_DESBLOQ,TO_DATE('01011990', 'DDMMYYYY')) -C.FEC_BLOQ),
-1,
to_date('&1', 'yyyymm') - C.FEC_BLOQ,
C.FEC_DESBLOQ - C.FEC_BLOQ),5),0) dias_b
FROM DWS.SA_TIM_FACT_CLIENT_HISTORY c
where 1 = 1
and TO_CHAR(FECHA_VENC, 'YYYYMM') < '&1'
AND FECHA_EMISION > =
ADD_MONTHS(TO_DATE('&1', 'YYYYMM'), (-1) * 12)
AND c.PLATAFORMA NOT IN 'FIJO'
AND C.RUC_DNI IS NOT NULL 
AND C.RUC_DNI <> '0')
group by RUC_DNI, periodo2;

CREATE TABLE DM.DW_SPSS2_VF2_216_SEG1_2_MAYO AS
select B.PERIODO2, B.RUC_DNI2, A.CANT_FACT, A.CANT_PERIODO_FACT, A.CANT_BLOQ, A.DIAS_BLOQ, A.VALOR, 
B.CANT_FACT2, B.CANT_PERIODO_FACT2, B.CANT_BLOQ2, B.DIAS_BLOQ2, B.VALOR2
from DM.DW_SPSS2_VF2_216_SEG2_MAYO B  
LEFT JOIN DM.DW_SPSS2_VF2_216_SEG1_MAYO A
ON A.PERIODO = B.PERIODO2
AND A.RUC_DNI = B.RUC_DNI2;

CREATE TABLE DM.DW_SPSS2_VF2_216_MAYO_CAL AS
SELECT PERIODO2, RUC_DNI2, 
VALOR, VALOR2, CANT_FACT, CANT_PERIODO_FACT, CANT_BLOQ, DIAS_BLOQ, 
CANT_FACT2, CANT_PERIODO_FACT2, CANT_BLOQ2, DIAS_BLOQ2,
CASE WHEN VALOR < '0' THEN '0' WHEN VALOR <= '0.00001' THEN '5' WHEN VALOR > 0.116 THEN '1'
WHEN VALOR <= '0.0172' AND VALOR > 0.00001 THEN '4' WHEN VALOR <= '0.0394' AND VALOR > '0.0172' THEN '3' WHEN VALOR <= '0.116'
AND VALOR > '0.0394' THEN '2' END CALIF_VALOR,
CASE WHEN VALOR2 < '0' THEN '0' WHEN VALOR2 <= '0.00001'  THEN '5' WHEN VALOR2 > 0.116 THEN '1' 
WHEN VALOR2 <= '0.0172' AND VALOR2 > 0.00001 THEN '4' WHEN VALOR2 <= '0.0394' AND VALOR2 > '0.0172' THEN '3' WHEN VALOR2 <= '0.116'
AND VALOR2 > '0.0394' THEN '2'
END CALIF_VALOR_2
FROM DM.DW_SPSS2_VF2_216_SEG1_2_MAYO;

CREATE TABLE DM.DW_SPSS2_VF2_216_MAYO AS
SELECT PERIODO2, RUC_DNI2, 
CASE WHEN CANT_FACT>=3 THEN CALIF_VALOR WHEN cant_fact < 3 AND cant_fact2 >=3 THEN CALIF_VALOR_2 ELSE '-1' END  VF2_216
FROM DM.DW_SPSS2_VF2_216_MAYO_CAL;

INSERT INTO DWM.DW_SPSS2_VF2_216_MAYO SELECT * FROM DM.DW_SPSS2_VF2_216_MAYO; 
COMMIT;

DROP TABLE DM.DW_SPSS2_VF2_216_SEG1_MAYO PURGE;
DROP TABLE DM.DW_SPSS2_VF2_216_SEG2_MAYO PURGE;
DROP TABLE DM.DW_SPSS2_VF2_216_SEG1_2_MAYO PURGE;
DROP TABLE DM.DW_SPSS2_VF2_216_MAYO_CAL PURGE;
DROP TABLE DM.DW_SPSS2_VF2_216_MAYO PURGE;

EXIT;
