WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;
BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TEMP_TAG_1460_VF2_371');
END;
/
CREATE TABLE DM.DW_TEMP_TAG_1460_VF2_371 NOLOGGING AS
SELECT /*PARALLEL(8)*/ DISTINCT sa.msisdn,sa.period,
COUNT(CASE WHEN (CASE WHEN TIPOLLAMADA = '30' AND CALLTOTAL=0 THEN 1 ELSE 0 END)>0  THEN  (CALLNUMBER)  END)VF2_371,
COUNT(CASE WHEN (CASE WHEN SA.CALLDESTINATION NOT IN ('CLA', 'VIE', 'NEX', 'TM', 'VIR', 'TDP') AND SA.TARIFFZONE NOT LIKE 'FIJ%' AND SA.CALLTOTAL = 0  THEN 1 ELSE 0 END)>0 THEN (CALLNUMBER) END)VF2_311,                  
COUNT(CASE WHEN (CASE WHEN SA.CALLDESTINATION NOT IN ('CLA', 'VIE', 'NEX', 'TM', 'VIR', 'TDP') AND SA.TARIFFZONE LIKE 'FIJ%' AND SA.CALLTOTAL = 0  THEN 1 ELSE 0 END)>0 THEN (CALLNUMBER) END)VF2_314,                  
ROUND(SUM((CASE WHEN  SA.CALLDESTINATION NOT IN ('CLA', 'VIE', 'NEX', 'TM', 'VIR', 'TDP') AND SA.TARIFFZONE NOT LIKE 'FIJ%' AND  SA.CALLTOTAL = 0 
     THEN (CASE WHEN instr(SA.CALLDURATION,':',1,1) > 0 THEN (to_number(substr(SA.CALLDURATION,1 ,(instr(SA.CALLDURATION,':',1,1)-1))) * 60) +  to_number(substr(SA.CALLDURATION,(instr(SA.CALLDURATION,':',1,1)+ 1),length(SA.CALLDURATION)))
                WHEN instr(SA.CALLDURATION,'.',1,1) > 0 THEN (to_number(substr(SA.CALLDURATION,1 ,(instr(SA.CALLDURATION,'.',1,1)-1))) * 60) +  to_number(substr(SA.CALLDURATION,(instr(SA.CALLDURATION,'.',1,1)+ 1),length(SA.CALLDURATION)))
                ELSE to_number(sa.callduration) END)ELSE 0 END)) / 60, 2) VF2_336,
ROUND(SUM((CASE WHEN  SA.CALLDESTINATION NOT IN ('CLA', 'VIE', 'NEX', 'TM', 'VIR', 'TDP') AND SA.TARIFFZONE LIKE 'FIJ%' AND  SA.CALLTOTAL = 0 
     THEN (CASE WHEN instr(SA.CALLDURATION,':',1,1) > 0 THEN (to_number(substr(SA.CALLDURATION,1 ,(instr(SA.CALLDURATION,':',1,1)-1))) * 60) +  to_number(substr(SA.CALLDURATION,(instr(SA.CALLDURATION,':',1,1)+ 1),length(SA.CALLDURATION)))
                WHEN instr(SA.CALLDURATION,'.',1,1) > 0 THEN (to_number(substr(SA.CALLDURATION,1 ,(instr(SA.CALLDURATION,'.',1,1)-1))) * 60) +  to_number(substr(SA.CALLDURATION,(instr(SA.CALLDURATION,'.',1,1)+ 1),length(SA.CALLDURATION)))
                ELSE to_number(sa.callduration) END)ELSE 0 END)) / 60, 2) VF2_339                        
FROM DM.SA_TEMP_TAG_1460_SPSS2 SA
where SA.PERIOD = '&1'
GROUP BY SA.msisdn,SA.PERIOD;

DELETE FROM DWM.DW_TEMP_TAG_1460_VF2_371 WHERE PERIOD='&1';
COMMIT;

INSERT INTO DWM.DW_TEMP_TAG_1460_VF2_371 SELECT * FROM DM.DW_TEMP_TAG_1460_VF2_371; 
COMMIT;

DROP TABLE DM.DW_TEMP_TAG_1460_VF2_371 PURGE;

EXIT;
