WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DWM.DW_SPSS2_VF2_002_008');
END;
/
ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/RRRR';
CREATE TABLE DWM.DW_SPSS2_VF2_002_008 NOLOGGING AS
SELECT MSISDN, CO_ID, MES, VF2_008, VF2_002 FROM (
SELECT B.MSISDN, B.CO_ID, B.MES, A.PROD_OFFER_PLAN_DESC AS VF2_008, A.SALES_FLAT_CHARGE AS VF2_002, 
ROW_NUMBER() OVER (PARTITION BY B.MSISDN, B.CO_ID , B.MES ORDER BY A.PROD_OFFER_ITEM_TYPE_IND DESC) RA
FROM DWA.DW_T_CUSTOMER_SALE A
INNER JOIN DWM.DW_MAESTRA_POSTPAGO B
ON A.PRODUCT_NUMBER = B.MSISDN
AND A.CONTRACT_NUMBER = B.CO_ID
AND A.SALES_REASON_SC = '01'
AND B.POSTPAGO IN ('CORPORATIVO', 'MASIVO')
AND B.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND B.FCH_ACTIVACION IS NOT NULL
AND B.MES = '&1')
WHERE RA = 1;


EXIT;