WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'dm.DW_SPSS2_CALL_COMPETENCIA');
END;
/

CREATE TABLE dm.DW_SPSS2_CALL_COMPETENCIA nologging parallel 2 AS
select TO_CHAR(TO_DATE(A.FH_INI,'YYYY-MM-DD HH24:MI:SS'),'YYYYMM') PERIODO, A.NUMERO_A, COUNT(A.NUMERO_B) VF2_458
from clibaja.ab_acumludado_llam_claro A
WHERE TO_CHAR(TO_DATE(A.FH_INI,'YYYY-MM-DD HH24:MI:SS'),'YYYYMM')='&1'
GROUP BY TO_CHAR(TO_DATE(A.FH_INI,'YYYY-MM-DD HH24:MI:SS'),'YYYYMM'),A.NUMERO_A;

INSERT INTO DWM.DW_SPSS2_CALL_COMPETENCIA SELECT * FROM DM.DW_SPSS2_CALL_COMPETENCIA; 
COMMIT;

DROP TABLE DM.DW_SPSS2_CALL_COMPETENCIA PURGE;

EXIT;