WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

DROP TABLE DM.DW_SPSS2_CURSADO PURGE;
DROP TABLE DM.DW_VF2_192_f PURGE;
DROP TABLE DM.DW_SPSS2_TOPE_CONSUMO PURGE;
DROP TABLE DM.dw_spss2_f_m_lineas_celda_cdr PURGE;

DROP TABLE DM.DM_SPSS_LOCALIDAD_CONTRACT PURGE;
DROP TABLE DM.DW_SPSS2_CELDA_CDR PURGE;
DROP TABLE DM.DW_SPSS2_SEG_CAE_VF2_213 PURGE;

TRUNCATE TABLE DM.DW_MAESTRA_POSTPAGO;

EXIT;