WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;
--##############################################################################
--#                                                                            #
--#   NOMBRE         :                                                         #
--#                                                                            #
--#   AUTOR          :   < SUSAN DELGADO >                                     #
--#   FECHA          :   < 20/08/2018>                                         #
--#   FUNCION        :   < SQL PLANTILLA >                                     #
--#   TABLAS         :   <DM.DW_SPSS2_VF2_002_008>                            #
--#            <DM.DW_VF2_183_CARGO_FIJO>              #
--#            <DM.DW_MOT_ACT_VF2_007>                   #
--#            <DM.DW_SPSS2_VF2_009_FI_17>                 #
--#            <DM.DW_SPSS2_BLACKLIST_VF2_135_136>           #
--#            <DM.DW_SPSS2_VF2_186>                     #
--#                                                                            #
--#   COMENTARIO    :   <CREACION DE TABLAS TEMPORALES VARIABLES POSTPAGO>     #
--#                                                                            #
--#   DEPENDENCIAS  :   <>                                                     #
--#                                                                            #
--#  VERSION       :  1.0                                                      #
--#                : <FECHA> <PERSONA> : <DETALLE DE CAMBIOS>                  #
--##############################################################################

--#-------------------------------------------------------------------------------------------------------#  
--#  1.- DEFINICION DE PARAMETROS DINAMICOS                                                               #  
--#-------------------------------------------------------------------------------------------------------#  
--# <VARIABLE_NAME1> : VARIABLE CONFIGURADA EN LA APLICACION 
--# DM  
--# <P_DB_TBS_STAGING> 
--# <P_VAR_SCHEMA_DWS> 
--# <P_VAR_SCHEMA_USR_ADMIN>
--# <P_VAR_PROCESS_DATE> 
--#-------------------------------------------------------------------------------------------------------#  

--#-------------------------------------------------------------------------------------------------------#  
--#  2.INICIO - PROCESO DE ELIMINACION Y TRUNCADO DE TABLAS                                               #  
--#-------------------------------------------------------------------------------------------------------#  
 
----#-------------------------------------------------------------------------------------------------------#  
----#  2.1.- ELIMINACION DE TABLAS TEMPORALES                                                   #   
----#-------------------------------------------------------------------------------------------------------#  
---------------------------------------------------------------------------------------------------------------------
BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP0');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP2');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP3');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP3_1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP4');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP4_1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP5');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP6');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP6_1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP7');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP7_1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP8');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP9');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP10');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP11');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP12');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP13');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP14');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP15');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP16');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP17');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP18');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP19');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP19_1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP21');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP22');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP23');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP24');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP25');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP26');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP27');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS2_VF2_216_MAYO_TMP');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS2_CURSADO_TP');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_spss2_deuda_TMP');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS_VF2_166_167_TMP');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_spps2_porc_con_mb_sms');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP27');
END;
/

--#-------------------------------------------------------------------------------------------------------#  
--#  3.- EJECUCION - PROCESO DE CARGA                                       #   
--#-------------------------------------------------------------------------------------------------------#  

----#-------------------------------------------------------------------------------------------------------#  
----#  3.1.- CREACION DE TABLAS TEMPORALES                                    #   
----#-------------------------------------------------------------------------------------------------------#  

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP0 NOLOGGING PARALLEL 10 AS
SELECT A.*, C.VF2_006
FROM DWM.DW_MAESTRA_POSTPAGO A
LEFT JOIN DM.DM_SPSS_LOCALIDAD_CONTRACT C 
ON A.CO_ID = C.CO_ID AND A.MES = C.PERIODO
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL
AND A.MES ='&1';

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM DM.DW_TABLON_POSTPAGO_C_TP0;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_C_TP0: '||V_COUNT);
END;
/

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP1 NOLOGGING PARALLEL 10 AS
SELECT A.*, C.VF2_007
FROM DM.DW_TABLON_POSTPAGO_C_TP0 A
LEFT JOIN DM.DW_MOT_ACT_VF2_007 C 
ON A.CO_ID = C.CO_ID AND A.MES = C.MES
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP2 NOLOGGING PARALLEL 10 AS
SELECT A.*, C.VF2_009
FROM DM.DW_TABLON_POSTPAGO_C_TP1 A
LEFT JOIN DM.DW_SPSS2_VF2_009_FI_17 C 
ON A.CO_ID = C.CO_ID AND A.MES = C.MES AND A.MSISDN=C.MSISDN
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP3 NOLOGGING PARALLEL 10 AS
SELECT \*PARALLEL(8)*\ DISTINCT A.*,B.VF2_047 , B.VF2_049,C.VF2_048,C.VF2_050,D.VF2_053,D.VF2_055 , E.VF2_054
, E.VF2_056 , F.VF2_061 , F.VF2_063, G.VF2_062 , G.VF2_064
FROM DM.DW_TABLON_POSTPAGO_C_TP2  A 
LEFT JOIN DM.DW_BAJAS_2G_HP_POST  B ON A.MSISDN=B.TIM_NUMBER AND A.MES=B.MES
LEFT JOIN DM.DW_BAJAS_2G_POST_2  C ON A.MSISDN=C.TIM_NUMBER AND A.MES=C.MES
LEFT JOIN DM.DW_BAJAS_3G_HP_POST D ON A.MSISDN=D.TIM_NUMBER AND A.MES=D.MES 
LEFT JOIN DM.DW_SA_BASE_BAJAS_3G_2 E ON A.MSISDN=E.TIM_NUMBER AND A.MES=E.MES 
LEFT JOIN DM.DW_BAJAS_4G_HP_POST F ON A.MSISDN=F.TIM_NUMBER AND A.MES=F.MES 
LEFT JOIN DM.DW_BAJAS_4G_POST G ON A.MSISDN=G.TIM_NUMBER AND A.MES=G.MES 
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 
 
CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP3_1 NOLOGGING PARALLEL 10 AS
SELECT A.*, C.VF2_128
FROM DM.DW_TABLON_POSTPAGO_C_TP3 A
LEFT JOIN DM.DW_SAS_COMUNIDAD_NOV17 C 
ON A.MSISDN = '51'||C.MSISDN AND A.MES = C.PERIODO
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP4 NOLOGGING PARALLEL 10 AS
SELECT A.*, 
(CASE WHEN C.VF2_136 IS NULL THEN 'NO' ELSE C.VF2_136 END) VF2_136
FROM DM.DW_TABLON_POSTPAGO_C_TP3_1 A
LEFT JOIN dwm.DW_SPSS2_vf2_135_136 C 
ON A.MSISDN = C.MSISDN AND A.MES = C.PERIODO
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP4_1 nologging PARALLEL 10 as
SELECT a.*,c.VF2_139 
FROM DM.DW_TABLON_POSTPAGO_C_TP4 A
LEFT JOIN DM.DW_SPSS2_VF2_139_F c ON A.MES = c.PERIODO AND A.NRO_DOCUMENTO = c.NUMERO_DOC
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP5 NOLOGGING  PARALLEL 10 AS
SELECT A.*,  C.VF2_142, C.VF2_143, C.VF2_146
FROM  DM.DW_TABLON_POSTPAGO_C_TP4_1 A
LEFT JOIN DM.DW_postpago_fact_ubi_F C 
ON A.CUSTOMER_ID = C.CUSTOMER_ID AND A.MES = C.MES
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM DM.DW_TABLON_POSTPAGO_C_TP5;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_C_TP5: '||V_COUNT);
END;


CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP6 NOLOGGING PARALLEL 10 AS
SELECT A.*, C.VF2_144
FROM DM.DW_TABLON_POSTPAGO_C_TP5 A
LEFT JOIN DWM.dw_flag_bloqueos_periodo_spss C 
ON A.CO_ID = C.CO_ID AND A.MES = C.MES AND A.CUSTOMER_ID = C.CUSTOMER_ID
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 

/*\*
CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP6_1 NOLOGGING AS
SELECT A.*, C.VF2_147
FROM DM.DW_TABLON_POSTPAGO_C_TP6 A
LEFT JOIN DM.DW_spps_post_vf2_147 C 
ON A.CO_ID = C.CO_ID AND A.MES = C.MES AND A.CUSTOMER_ID = C.CUSTOMER_ID
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 

CREATE TABLE DM.DW_spss2_deuda_TMP NOLOGGING AS
SELECT PERIODO,CUSTOMER_ID,BILL_ID,NVL(VF2_160,0) VF2_160
FROM (
SELECT PERIODO,CUSTOMER_ID,BILL_ID,VF2_160,
ROW_NUMBER() OVER(PARTITION BY PERIODO,CUSTOMER_ID ORDER BY ROWNUM) RN
FROM DM.DW_spss2_deuda)
WHERE RN=1;


CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP7 nologging as
SELECT a.*, c.vf2_160
FROM DM.DW_TABLON_POSTPAGO_C_TP6_1 a
LEFT join DM.DW_spss2_deuda_TMP c 
on a.mes = c.periodo and a.customer_id = c.customer_id
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP7_1 NOLOGGING AS
SELECT A.*, C.DUE_DATE AS VF2_165
FROM DM.DW_TABLON_POSTPAGO_C_TP7 A
LEFT JOIN DM.DW_spps_vf2_165_F C 
ON A.CUSTOMER_ID = C.CUSTOMER_ID AND A.MES = C.PERIOD
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_SPSS_VF2_166_167_TMP NOLOGGING AS
SELECT DISTINCT MES,CUSTOMER_ID,VF2_166,VF2_167 FROM (
SELECT MES,CUSTOMER_ID,VF2_166,VF2_167,
ROW_NUMBER() OVER(PARTITION BY MES,CUSTOMER_ID ORDER BY ROWNUM) RN
FROM DM.DW_SPSS_VF2_166_167)
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP8 NOLOGGING AS
SELECT A.*, C.VF2_166, C.VF2_167
FROM  DM.DW_TABLON_POSTPAGO_C_TP7_1 A
LEFT JOIN DM.DW_SPSS_VF2_166_167_TMP C 
ON A.CUSTOMER_ID = C.CUSTOMER_ID AND A.MES = C.MES
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP9 NOLOGGING AS
SELECT A.*, C.VF2_186
FROM  DM.DW_TABLON_POSTPAGO_C_TP8 A
LEFT JOIN DM.DW_SPSS2_VF2_186 C 
ON A.CO_ID = C.CO_ID AND A.MES = C.MES
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL  ; 

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP10 nologging as
SELECT a.*,c.VF2_213  
FROM DM.DW_TABLON_POSTPAGO_C_TP9 A
LEFT JOIN DM.DW_SPSS2_SEG_CAE_VF2_213 c ON A.MES = c.MES AND A.NRO_DOCUMENTO = c.RUC
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM DM.DW_TABLON_POSTPAGO_C_TP10;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_C_TP10: '||V_COUNT);
END;
/

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP11 nologging as
SELECT DISTINCT
a.msisdn,
a.customer_id,
a.co_id,
a.nro_documento,
a.fch_activacion,
a.status,
a.postpago,
a.tipo_documento,
a.mes,
a.reason_status,
a.vf2_006,
a.vf2_007,
a.vf2_009,
a.vf2_047,
a.vf2_049,
a.vf2_048,
a.vf2_050,
a.vf2_053,
a.vf2_055,
a.vf2_054,
a.vf2_056,
a.vf2_061,
a.vf2_063,
a.vf2_062,
a.vf2_064,
a.vf2_128,
a.vf2_136,
a.vf2_139,
a.vf2_142,
a.vf2_143,
a.vf2_146,
a.vf2_144,
a.vf2_147,
a.vf2_160,
a.vf2_165,
a.vf2_166,
a.vf2_167,
a.vf2_186,
a.vf2_213
,c.VF2_214
FROM DM.DW_TABLON_POSTPAGO_C_TP10 A
LEFT JOIN DM.DW_SPSS2_VF2_214 c 
ON a.MES = c.periodo AND a.nro_documento = c.ruc
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_SPSS2_VF2_216_MAYO_TMP NOLOGGING AS
SELECT DISTINCT PERIODO2,RUC_DNI2, VF2_216 FROM (
SELECT PERIODO2,RUC_DNI2, VF2_216,
ROW_NUMBER() OVER(PARTITION BY PERIODO2,RUC_DNI2 ORDER BY ROWNUM) RN
FROM DM.DW_SPSS2_VF2_216_MAYO)
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP12 nologging as
SELECT a.*, c.VF2_216
FROM DM.DW_TABLON_POSTPAGO_C_TP11 a
LEFT JOIN DM.DW_SPSS2_VF2_216_MAYO_TMP c 
ON a.mes = c.periodo2 AND a.nro_documento = c.ruc_dni2
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;


CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP13 nologging as
SELECT a.*
,c.VF2_228
,c.VF2_307
,c.VF2_332
,c.VF2_334
,c.VF2_338
,c.VF2_357
,c.VF2_358
,c.VF2_375
FROM DM.DW_TABLON_POSTPAGO_C_TP12 A
LEFT JOIN DM.DW_SPSS2_TAG_1460_VF2_228_375 c 
ON a.MES = c.period AND a.msisdn = c.msisdn
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP14 NOLOGGING AS
SELECT A.*, C.VF2_234, C.VF2_230, C.VF2_235
from DM.DW_TABLON_POSTPAGO_C_TP13 a
left join DM.DW_SPSS2_CELDA_CDR c on a.msisdn = C.Tim_Number and a.mes = c.mes
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP15 nologging as
SELECT a.*,c.VF2_237,c.VF2_238 
FROM DM.DW_TABLON_POSTPAGO_C_TP14 A
LEFT JOIN DM.DW_spps2_porc_con_min c
ON a.MES = c.periodo AND a.msisdn = c.msisdn AND a.co_id = c.co_id
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM DM.DW_TABLON_POSTPAGO_C_TP15;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_C_TP15: '||V_COUNT);
END;
/

CREATE TABLE DM.T$_spps2_porc_con_mb_sms nologging AS
select distinct periodo,msisdn,co_id,vf2_240
from (
select periodo,msisdn,co_id,vf2_240,
ROW_NUMBER() OVER(PARTITION BY periodo,msisdn,co_id ORDER BY rownum) RN
from DM.DW_spps2_porc_con_mb_sms)
where RN=1;


CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP16 nologging as
SELECT a.*,c.vf2_240
FROM DM.DW_TABLON_POSTPAGO_C_TP15 A
LEFT JOIN DM.T$_spps2_porc_con_mb_sms c
ON a.MES = c.periodo AND a.msisdn = c.msisdn AND a.co_id = c.co_id
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP17 nologging as
SELECT a.*,b.vf2_244
FROM DM.DW_TABLON_POSTPAGO_C_TP16 A
LEFT JOIN DM.DW_F2_C_M_GPRS_ENE B  ON        A.MSISDN=B.MSISDN AND A.MES=B.MES
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_SPSS2_CURSADO_TP NOLOGGING AS
SELECT DISTINCT TIM_NUMBER, PERIODO,
VF2_257
, VF2_258
, VF2_259
, VF2_260
, VF2_261
, VF2_263
, VF2_268
, VF2_269
, VF2_271
, VF2_279
, VF2_280
, VF2_281
, VF2_282
, VF2_283
, VF2_286
, VF2_437
, VF2_440 FROM (
SELECT DISTINCT TIM_NUMBER, PERIODO,
VF2_257
, VF2_258
, VF2_259
, VF2_260
, VF2_261
, VF2_263
, VF2_268
, VF2_269
, VF2_271
, VF2_279
, VF2_280
, VF2_281
, VF2_282
, VF2_283
, VF2_286
, VF2_437
, VF2_440
, ROW_NUMBER() OVER(PARTITION BY TIM_NUMBER, PERIODO ORDER BY ROWNUM) RN
FROM DM.DW_SPSS2_CURSADO)
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP18 NOLOGGING AS
SELECT A.*
, c.VF2_257
, c.VF2_258
, c.VF2_259
, c.VF2_260
, c.VF2_261
, c.VF2_263
, c.VF2_268
, c.VF2_269
, c.VF2_271
, c.VF2_279
, c.VF2_280
, c.VF2_281
, c.VF2_282
, c.VF2_283
, c.VF2_286
, c.VF2_437
, c.VF2_440
from DM.DW_TABLON_POSTPAGO_C_TP17 a
left join DM.DW_SPSS2_CURSADO_TP c 
on a.msisdn = trim(c.tim_number) and a.mes = trim(c.periodo)
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP19 nologging AS 
SELECT \*parallel(8)*\ a.*
, X.VF2_262
, X.VF2_284
, X.VF2_285
, X.VF2_372
, X.VF2_376
FROM DM.DW_TABLON_POSTPAGO_C_TP18 A
LEFT JOIN DM.DW_SPSS2_TEMP_TAG_1470_F X ON  A.MSISDN=X.MSISDN AND A.MES=X.PERIODO
WHERE A.POSTPAGO = 'CORPORATIVO' 
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP19_1 nologging AS 
SELECT \*parallel(8)*\ a.*
, X.VF2_302
, X.VF2_305
FROM DM.DW_TABLON_POSTPAGO_C_TP19 A
LEFT JOIN DM.DW_SPSS2_TRAFICO_PLAN_2 X ON  A.MSISDN='51'||X.MSISDN AND A.MES=X.PERIOD
WHERE A.POSTPAGO = 'CORPORATIVO' 
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP21 nologging AS 
SELECT \*parallel(8)*\ a.*
,X.VF2_315
,X.VF2_340
,X.VF2_359
,X.VF2_360
,X.VF2_365
,X.VF2_366
,X.VF2_370
,X.VF2_374
FROM DM.DW_TABLON_POSTPAGO_C_TP19_1 A
LEFT JOIN DM.DW_SPSS2_TASADO_DEMANDA X ON  A.MSISDN=X.served_number AND A.MES=X.fecha
WHERE A.POSTPAGO = 'CORPORATIVO' 
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM DM.DW_TABLON_POSTPAGO_C_TP21;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_C_TP21: '||V_COUNT);
END;
/

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP22 nologging as
SELECT a.*
, C.VF2_323
, C.VF2_348
, C.VF2_361
, C.VF2_362
, C.VF2_367
, C.VF2_368
, C.VF2_369
, C.VF2_373
FROM DM.DW_TABLON_POSTPAGO_C_TP21 a
LEFT JOIN DM.DW_TRAFICO_GRANEL C 
ON A.MES = C.PERIODO AND A.MSISDN = C.MSISDN
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP23 nologging AS 
SELECT \*parallel(8)*\ a.*
, X.VF2_377
, X.VF2_379
, X.VF2_381
FROM DM.DW_TABLON_POSTPAGO_C_TP22 A
LEFT JOIN DM.DW_SPSS2_PUNTOVENTA X ON  A.MSISDN=X.MSISDN AND A.MES=X.periodo
WHERE A.POSTPAGO = 'CORPORATIVO' 
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP24 NOLOGGING AS
SELECT A.*
, C.VF2_386
, C.VF2_391
FROM DM.DW_TABLON_POSTPAGO_C_TP23 A
LEFT JOIN DM.dw_spss2_eq_trafico C ON A.MSISDN = C.MSISDN AND A.MES = C.PERIODO
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP25 NOLOGGING AS
SELECT A.*, C.cant_dias as VF2_436
FROM DM.DW_TABLON_POSTPAGO_C_TP24 A
LEFT JOIN DM.DW_TRAFICO_LLAMADAS_SAL_SPSS C 
ON a.MES = c.periodo AND a.msisdn = '51'||c.msisdn
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP26 NOLOGGING AS
SELECT A.*,  VF2_371
FROM DM.DW_TABLON_POSTPAGO_C_TP25 A
LEFT JOIN DM.DW_TEMP_TAG_1460_VF2_371 C 
ON a.MES = c.period AND a.msisdn = '51'||c.msisdn
WHERE A.POSTPAGO = 'CORPORATIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_C_TP27 NOLOGGING AS
select distinct
MSISDN,
CUSTOMER_ID,
CO_ID,
NRO_DOCUMENTO,
FCH_ACTIVACION,
STATUS,
POSTPAGO,
TIPO_DOCUMENTO,
MES,
REASON_STATUS,
VF2_006,
VF2_007,
VF2_009,
VF2_047,
VF2_049,
VF2_048,
VF2_050,
VF2_053,
VF2_055,
VF2_054,
VF2_056,
VF2_061,
VF2_063,
VF2_062,
VF2_064,
VF2_128,
VF2_136,
VF2_139,
VF2_142,
VF2_143,
VF2_146,
VF2_144,
VF2_147,
VF2_160,
VF2_165,
VF2_166,
VF2_167,
VF2_186,
VF2_213,
VF2_214,
VF2_216,
VF2_228,
VF2_307,
VF2_332,
VF2_334,
VF2_338,
VF2_357,
VF2_358,
VF2_375,
VF2_234,
VF2_230,
VF2_235,
VF2_237,
VF2_238,
VF2_240,
VF2_244,
VF2_257,
VF2_258,
VF2_259,
VF2_260,
VF2_261,
VF2_263,
VF2_268,
VF2_269,
VF2_271,
VF2_279,
VF2_280,
VF2_281,
VF2_282,
VF2_283,
VF2_286,
VF2_437,
VF2_440,
VF2_262,
VF2_284,
VF2_285,
VF2_372,
VF2_376,
VF2_302,
VF2_305,
VF2_315,
VF2_340,
VF2_359,
VF2_360,
VF2_365,
VF2_366,
VF2_370,
VF2_374,
VF2_323,
VF2_348,
VF2_361,
VF2_362,
VF2_367,
VF2_368,
VF2_369,
VF2_373,
VF2_377,
VF2_379,
VF2_381,
VF2_386,
VF2_391,
VF2_436,
VF2_371
from DM.DW_TABLON_POSTPAGO_C_TP26*/;



DECLARE
e_validacion EXCEPTION;
v_inicial NUMBER:= 0;
v_final NUMBER:= 1;
BEGIN
SELECT COUNT(1) INTO v_inicial FROM DM.DW_TABLON_POSTPAGO_C_TP0;
SELECT COUNT(1) INTO v_final FROM DM.DW_TABLON_POSTPAGO_C_TP27;
IF v_inicial <> v_final THEN
RAISE e_validacion;
END IF;
EXCEPTION 
WHEN e_validacion THEN
RAISE_APPLICATION_ERROR(-20101,'DIFERENCIA DE CANTIDADES EN LAS TEMPORALES');
END;
/


 
----#-------------------------------------------------------------------------------------------------------#  
----#  4.- ELIMINACION DE TABLAS TEMPORALES                                                   #   
----#-------------------------------------------------------------------------------------------------------#  
--------------------------------------------------------------------------------------------------------------------
BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP0');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP2');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP3');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP3_1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP4');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP4_1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP5');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP6');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP6_1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP7');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP7_1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP8');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP9');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP10');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP11');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP12');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP13');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP14');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP15');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP16');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP17');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP18');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP19');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP19_1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP21');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP22');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP23');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP24');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP25');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_C_TP26');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS2_VF2_216_MAYO_TMP');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS2_CURSADO_TP');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_spss2_deuda_TMP');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS_VF2_166_167_TMP');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_spps2_porc_con_mb_sms');

END;
/


EXIT;