WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP1 NOLOGGING AS
SELECT A.*, C.VF2_002
FROM DWM.DW_MAESTRA_POSTPAGO A
LEFT JOIN DWM.DW_SPSS2_VF2_002_008 C 
ON A.CO_ID = C.CO_ID AND A.MES = C.MES
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL
AND A.MES ='&1';

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM dm.DW_TABLON_POSTPAGO_M_TP1;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_M_TP1: '||V_COUNT);
END;
/

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP2 NOLOGGING AS
SELECT A.*,
VF2_015
FROM DM.DW_TABLON_POSTPAGO_M_TP1 A
LEFT JOIN DWM.DW_SPSS2_VF2_015 C 
ON A.MES = C.PERIODO AND A.MSISDN = '51'||C.MSISDN
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP3 NOLOGGING AS
SELECT A.*
,vf2_017
,vf2_018
,vf2_257
,vf2_258
,vf2_264
,vf2_265
,vf2_271
,vf2_281
,vf2_282
,vf2_286
,vf2_439
,vf2_440
FROM DM.DW_TABLON_POSTPAGO_M_TP2 A
LEFT JOIN DWM.DW_SPSS2_CURSADO C 
ON A.MES = C.PERIODO AND A.MSISDN = C.TIM_NUMBER
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP4 NOLOGGING AS
SELECT A.*,
VF2_030
FROM DM.DW_TABLON_POSTPAGO_M_TP3 A
LEFT JOIN DWM.DW_BLOQUEO_VF2_030_F C 
ON A.MES = C.PERIODO AND A.CO_ID = C.CO_ID
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP5 NOLOGGING AS
SELECT A.*,
VF2_035
FROM DM.DW_TABLON_POSTPAGO_M_TP4 A
LEFT JOIN DWM.DW_BLOQUEO_VF2_035 C 
ON A.MES = C.PERIODO AND A.CO_ID = C.CO_ID
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM dm.DW_TABLON_POSTPAGO_M_TP5;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_M_TP5: '||V_COUNT);
END;
/

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP6 NOLOGGING AS
SELECT A.*, C.VF2_144
FROM DM.DW_TABLON_POSTPAGO_M_TP5 A
LEFT JOIN DWM.dw_flag_bloqueos_periodo_spss C 
ON A.CO_ID = C.CO_ID AND A.MES = C.MES AND A.CUSTOMER_ID = C.CUSTOMER_ID
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;	

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP7 NOLOGGING AS
SELECT A.*, C.VF2_152
FROM DM.DW_TABLON_POSTPAGO_M_TP6 A
LEFT JOIN DWM.DW_CANT_ITERA_TIP_CONS_SPSS C 
ON A.MES = C.MES AND A.MSISDN = '51'||C.MSISDN
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;	

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP8 NOLOGGING AS
SELECT A.*, C.VF2_155
FROM DM.DW_TABLON_POSTPAGO_M_TP7 A
LEFT JOIN DWM.DW_CANT_X_MES_ITE_VAR_SPSS C 
ON A.MES = C.MES AND A.MSISDN = '51'||C.MSISDN
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP9 NOLOGGING AS
SELECT A.*, C.VF2_160
FROM DM.DW_TABLON_POSTPAGO_M_TP8 A
LEFT JOIN DWM.DW_spss2_deuda C 
on a.mes = c.periodo and a.customer_id = c.customer_id
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;	

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP10 NOLOGGING AS
SELECT A.*, C.DUE_DATE AS VF2_165
FROM DM.DW_TABLON_POSTPAGO_M_TP9 A
LEFT JOIN DWM.DW_spps_vf2_165_F C 
ON A.CUSTOMER_ID = C.CUSTOMER_ID AND A.MES = C.PERIOD
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM dm.DW_TABLON_POSTPAGO_M_TP10;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_M_TP10: '||V_COUNT);
END;
/

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP11 NOLOGGING AS
SELECT A.*, C.VF2_167
FROM DM.DW_TABLON_POSTPAGO_M_TP10 A
LEFT JOIN DWM.dw_spss_vf2_166_167 C 
ON A.CUSTOMER_ID = C.CUSTOMER_ID AND A.MES = C.MES
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP12 NOLOGGING AS
SELECT A.*, C.SNCODE VF2_175
FROM DM.DW_TABLON_POSTPAGO_M_TP11 A
LEFT JOIN DWM.DW_vf2_175_masivo C 
ON A.MSISDN = '51'||C.LINEA AND A.MES = C.PERIODO
AND A.CO_ID = C.CO_ID
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP13 NOLOGGING AS
SELECT A.*, C.VF2_183
FROM DM.DW_TABLON_POSTPAGO_M_TP12 A
LEFT JOIN DWM.DW_VF2_183_CARGO_FIJO C 
on a.mes = c.mes and a.co_id = c.co_id
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP14 NOLOGGING AS
SELECT A.*, C.VF2_192
FROM DM.DW_TABLON_POSTPAGO_M_TP13 A
LEFT JOIN DWM.DW_VF2_192_f C 
on a.mes = c.mes and a.co_id = c.co_id
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP15 nologging as
SELECT a.*, 
VF2_206
FROM DM.DW_TABLON_POSTPAGO_M_TP14 a
LEFT JOIN DWM.DW_CANT_RENO_MES_LINEA c 
ON a.mes = c.mes AND a.msisdn = c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;  

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM dm.DW_TABLON_POSTPAGO_M_TP15;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_M_TP15: '||V_COUNT);
END;
/

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP16 nologging as
SELECT a.*, c.VF2_216
FROM DM.DW_TABLON_POSTPAGO_M_TP15 a
LEFT JOIN DWM.DW_SPSS2_VF2_216_MAYO c 
ON a.mes = c.periodo2 AND a.nro_documento = c.ruc_dni2
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;    

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP17 nologging as
SELECT a.*, c.VF2_223
FROM DM.DW_TABLON_POSTPAGO_M_TP16 a
LEFT JOIN DWM.DW_SPSS2_TOPE_CONSUMO c 
ON a.mes = c.periodo AND a.msisdn = c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;    

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP18 nologging as
SELECT a.*, 
c.VF2_224,
c.vf2_247,  
c.vf2_297
FROM DM.DW_TABLON_POSTPAGO_M_TP17 a
LEFT JOIN DWM.DW_SPSS2_TRAFICO_PLAN_2 c 
ON a.mes = c.period AND a.msisdn ='51'|| c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;  

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP19 nologging as
SELECT a.*
, VF2_228
, VF2_307
, VF2_308
, VF2_332
, VF2_375
FROM DM.DW_TABLON_POSTPAGO_M_TP18 a
LEFT JOIN DWM.dw_SPSS2_TAG_1460_VF2_228_375 c 
ON a.mes = c.period AND a.msisdn =c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP20 nologging as
SELECT a.*, 
VF2_236
FROM DM.DW_TABLON_POSTPAGO_M_TP19 a
LEFT JOIN DWM.dw_spps2_porc_con_mb_sms c 
ON a.mes = c.PERIODO AND a.msisdn = c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM dm.DW_TABLON_POSTPAGO_M_TP20;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_M_TP20: '||V_COUNT);
END;
/

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP21 nologging as
SELECT a.*, 
VF2_244,
VF2_250
FROM DM.DW_TABLON_POSTPAGO_M_TP20 a
LEFT JOIN DWM.DW_F2_C_M_GPRS_ENE c 
ON a.mes = c.mes AND a.msisdn = c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP22 nologging as
SELECT a.*, 
VF2_285,
VF2_376
FROM DM.DW_TABLON_POSTPAGO_M_TP21 a
LEFT JOIN DWM.DW_SPSS2_TEMP_TAG_1470_F c 
ON a.mes = c.PERIODO AND a.msisdn = c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP23 nologging as
SELECT a.*, 
VF2_340,
VF2_365,
VF2_366,
VF2_374
FROM DM.DW_TABLON_POSTPAGO_M_TP22 a
LEFT JOIN DWM.DW_SPSS2_TASADO_DEMANDA c 
ON a.mes = c.fecha AND a.msisdn = c.served_number
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP24 nologging as
SELECT a.*, 
VF2_348,
VF2_367,
VF2_368,
VF2_373,
vf2_441,
vf2_442, 
vf2_443, 
vf2_444, 
vf2_445, 
vf2_446, 
vf2_447, 
vf2_448, 
vf2_449, 
vf2_450, 
vf2_451, 
vf2_452
FROM DM.DW_TABLON_POSTPAGO_M_TP23 a
LEFT JOIN DWM.DW_TRAFICO_GRANEL C 
ON A.MES = C.PERIODO AND A.MSISDN = C.MSISDN
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP25 NOLOGGING AS
SELECT A.*, C.VF2_391
FROM DM.DW_TABLON_POSTPAGO_M_TP24 A
LEFT JOIN DWM.dw_spss2_eq_trafico C ON A.MSISDN = C.MSISDN AND A.MES = C.PERIODO
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM dm.DW_TABLON_POSTPAGO_M_TP25;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_M_TP25: '||V_COUNT);
END;
/

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP26 NOLOGGING AS
SELECT A.*, C.cant_dias as VF2_436
FROM DM.DW_TABLON_POSTPAGO_M_TP25 A
LEFT JOIN DWM.DW_TRAFICO_LLAMADAS_SAL_SPSS C 
ON a.MES = c.periodo AND a.msisdn = '51'||c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP27 NOLOGGING AS
SELECT A.*, C.VF2_458
FROM DM.DW_TABLON_POSTPAGO_M_TP26 A
LEFT JOIN DWM.DW_SPSS2_CALL_COMPETENCIA C 
ON A.MSISDN=C.NUMERO_A AND A.MES=C.PERIODO
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP28 NOLOGGING AS
SELECT A.*, C.VF2_047
FROM DM.DW_TABLON_POSTPAGO_M_TP27 A
LEFT JOIN DWM.DW_BAJAS_2G_HP_POST C 
ON A.MSISDN=C.TIM_NUMBER AND A.MES=C.MES
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP29 NOLOGGING AS
SELECT A.*, C.VF2_053
FROM DM.DW_TABLON_POSTPAGO_M_TP28 A
LEFT JOIN DWM.DW_BAJAS_3G_HP_POST C 
ON A.MSISDN=C.TIM_NUMBER AND A.MES=C.MES
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP30 NOLOGGING AS
SELECT A.*, C.VF2_061
FROM DM.DW_TABLON_POSTPAGO_M_TP29 A
LEFT JOIN DWM.DW_BAJAS_4G_HP_POST C 
ON A.MSISDN=C.TIM_NUMBER AND A.MES=C.MES
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

DECLARE
e_validacion EXCEPTION;
v_inicial NUMBER:= 0;
v_final NUMBER:= 1;
BEGIN
SELECT COUNT(1) INTO v_inicial FROM dm.DW_TABLON_POSTPAGO_M_TP1;
SELECT COUNT(1) INTO v_final FROM dm.DW_TABLON_POSTPAGO_M_TP30;
IF v_inicial <> v_final THEN
RAISE e_validacion;
END IF;
EXCEPTION 
WHEN e_validacion THEN
RAISE_APPLICATION_ERROR(-20101,'DIFERENCIA DE CANTIDADES EN LAS TEMPORALES');
END;
/

DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP1 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP2 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP3 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP4 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP5 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP6 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP7 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP8 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP9 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP10 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP11 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP12 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP13 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP14 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP15 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP16 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP17 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP18 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP19 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP20 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP21 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP22 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP23 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP24 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP25 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP26 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP27 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP28 PURGE;
DROP TABLE DM.DW_TABLON_POSTPAGO_M_TP29 PURGE;


SET HEADING OFF
SET LINESIZE 410
SET TIMING OFF
SET ECHO OFF
SET PAGESIZE 0
SET TERMOUT OFF
SET FEEDBACK OFF

SPOOL TABLON_POSTPAGO_MASIVO_SUMA.csv

SELECT MES,
COUNT(VF2_002),
COUNT(VF2_018),
COUNT(VF2_030),
COUNT(VF2_047),
COUNT(VF2_053),
COUNT(VF2_061),
COUNT(VF2_144),
COUNT(VF2_152),
COUNT(VF2_160),
COUNT(VF2_183),
COUNT(VF2_206),
COUNT(VF2_216),
COUNT(VF2_224),
COUNT(VF2_228),
COUNT(VF2_236),
COUNT(VF2_244),
COUNT(VF2_250),
COUNT(VF2_258),
COUNT(VF2_265),
COUNT(VF2_271),
COUNT(VF2_281),
COUNT(VF2_282),
COUNT(VF2_285),
COUNT(VF2_286),
COUNT(VF2_307),
COUNT(VF2_308),
COUNT(VF2_332),
COUNT(VF2_340),
COUNT(VF2_348),
COUNT(VF2_365),
COUNT(VF2_366),
COUNT(VF2_367),
COUNT(VF2_368),
COUNT(VF2_373),
COUNT(VF2_374),
COUNT(VF2_375),
COUNT(VF2_376),
COUNT(VF2_440),
COUNT(VF2_458)
FROM DM.DW_TABLON_POSTPAGO_M_TP30
GROUP BY MES; 

SPOOL TABLON_POSTPAGO_MASIVO_COUNT.csv

SELECT MES,
SUM(VF2_002),
SUM(VF2_018),
SUM(VF2_030),
SUM(VF2_047),
SUM(VF2_053),
SUM(VF2_061),
SUM(VF2_144),
SUM(VF2_152),
SUM(VF2_160),
SUM(VF2_183),
SUM(VF2_206),
SUM(VF2_216),
SUM(VF2_224),
SUM(VF2_228),
SUM(VF2_236),
SUM(VF2_244),
SUM(VF2_250),
SUM(VF2_258),
SUM(VF2_265),
SUM(VF2_271),
SUM(VF2_281),
SUM(VF2_282),
SUM(VF2_285),
SUM(VF2_286),
SUM(VF2_307),
SUM(VF2_308),
SUM(VF2_332),
SUM(VF2_340),
SUM(VF2_348),
SUM(VF2_365),
SUM(VF2_366),
SUM(VF2_367),
SUM(VF2_368),
SUM(VF2_373),
SUM(VF2_374),
SUM(VF2_375),
SUM(VF2_376),
SUM(VF2_440),
SUM(VF2_458)
FROM DM.DW_TABLON_POSTPAGO_M_TP30
GROUP BY MES;

SPOOL OUT;

EXIT;