WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_BLOQUEO_DIAS_VF2_030_F');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_BLOQUEO_VF2_030_F');
END;
/
ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/RRRR';
CREATE TABLE DM.DW_BLOQUEO_DIAS_VF2_030_F NOLOGGING AS
SELECT A.co_id,
A.CUSTOMER_ID,
MAX(A.TICKLER_NUMBER) TICKLER_NUMBER,
TO_CHAR(A.created_date, 'YYYYMMDD') DIA,
MAX(CASE WHEN tickler_code IN ('BLOQ_COB', 'SUSP_COB') THEN 1 ELSE 0 END) vf2_030
FROM DMRED.TICKLER_RECORDS A
WHERE TO_CHAR(A.CREATED_DATE, 'YYYYMM') = '&1'
AND A.CO_ID IS NOT NULL
AND tickler_code IS NOT NULL
AND TICKLER_CODE NOT IN ('SYSTEM', 'WARNING', 'BLOQ_PER', 'BLOQ_ROB', 'BLOQ_DSC')
AND short_description <> 'ALINEACION PKG111'
GROUP BY A.co_id, A.CUSTOMER_ID, TO_CHAR(A.CREATED_DATE, 'YYYYMMDD');

CREATE TABLE DM.DW_BLOQUEO_VF2_030_F NOLOGGING AS
SELECT T.co_id,
SUBSTR(R.DIA,1,6) PERIODO,
SUM(R.vf2_030) vf2_030
FROM DMRED.TICKLER_RECORDS T,
DM.DW_BLOQUEO_DIAS_VF2_030_F R
WHERE T.co_id = R.co_id
AND T.CUSTOMER_ID = R.CUSTOMER_ID
AND T.TICKLER_NUMBER = R.TICKLER_NUMBER
AND T.tickler_code IN ('BLOQ_COB', 'SUSP_COB')
GROUP BY SUBSTR(R.DIA,1,6), T.co_id;


INSERT INTO DWM.DW_BLOQUEO_VF2_030_F SELECT * FROM DM.DW_BLOQUEO_VF2_030_F; 
COMMIT;

DROP TABLE DM.DW_BLOQUEO_VF2_030_F PURGE;
DROP TABLE DM.DW_BLOQUEO_DIAS_VF2_030_F PURGE;

EXIT;