WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

DROP TABLE DM.DW_SPSS2_TOPE_CONSUMO PURGE;

DECLARE

  V_PERIODO  VARCHAR2(6);
  V_QUERY    VARCHAR2(30000);
  v_MsgError VARCHAR2(130);
  LD_FECINI  DATE;
  LD_FECFIN  DATE;
  V_PERIODO_SMES VARCHAR2(10);
  i          NUMBER;
  x          NUMBER;
  y          NUMBER;

BEGIN

SELECT TO_CHAR(ADD_MONTHS(SYSDATE, -1), 'YYYYMM') INTO V_PERIODO FROM DUAL;
  
    Execute Immediate 'ALTER SESSION SET NLS_DATE_FORMAT=''DD/MM/RR'''; 
  
    V_QUERY := '';     
    V_QUERY := 'CREATE TABLE DM.DW_SPSS2_TOPE_CONSUMO NOLOGGING  PARALLEL 2 AS '|| 
'SELECT PERIODO, MSISDN, VF2_223, SNCODE, TMCODE, spcode FROM '|| 
'(select '||V_PERIODO||' AS PERIODO, A.MSISDN, ' ||
'CASE WHEN A.SNCODE=''101'' THEN ''Consumo Adicional Flexible'' WHEN '||
  'A.SNCODE=''1706'' THEN ''Consumo Exacto'' WHEN A.SNCODE=''1707''THEN ''Consumo Adicional'' ELSE '|| 
  'NULL end as VF2_223,A.SNCODE, B.TMCODE,a.spcode, '||
  'ROW_NUMBER() OVER (PARTITION BY A.MSISDN ORDER BY A.SERV_VALID_FROM_DATE DESC) RW '||
'from  dm.f_m_contrato_servicio partitioN (p_'||V_PERIODO||') A, DM.DW_COM_D_PLANTARIFARIO B  WHERE '||  
'A.sncode in (''101'',''1706'',''1707'') and A.status=''A'' AND A.IDPLANTARIFARIO=B.IDPLANTARIFARIO) WHERE RW=1';

      EXECUTE IMMEDIATE V_QUERY;


EXCEPTION
  WHEN NO_DATA_FOUND THEN
    v_MsgError := 'Proceso Nro. 03 no se ejecuto correctamente.';
    DBMS_OUTPUT.PUT_LINE(v_MsgError);
        DBMS_OUTPUT.PUT_LINE(v_query);
  WHEN OTHERS THEN
    v_MsgError := 'Error ' || 'ORA' || SqlCode || ' ' ||substr(SQLERRM, 1, 100);
     DBMS_OUTPUT.PUT_LINE(v_MsgError);
       DBMS_OUTPUT.PUT_LINE(v_query);
END;
/

GRANT ALL ON DM.DW_SPSS2_TOPE_CONSUMO TO DBLINK_DWO;

EXIT;