WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;
BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'Dm.DW_SA_BASE_BAJAS_3G_2');
END;
/

CREATE TABLE Dm.DW_SA_BASE_BAJAS_3G_2 AS
SELECT B.MES, B.TIM_NUMBER, A.ACC_PS VF2_054, A.RET_PS VF2_056, A.TH_DL VF2_058 , A.TH_UL VF2_059
FROM DWS.SA_BASE_BAJAS_3G A
INNER JOIN USRPWC.F_M_LINEAS_CELDA_CDR B
ON A.LAC = B.LAC
AND A.CELL_ID = B.CELDA
AND REPLACE (A.PERIODO,'-','') = B.MES
WHERE B.MES = '&1';

DELETE FROM DWM.DW_SA_BASE_BAJAS_3G_2 WHERE MES='&1';
COMMIT;
INSERT INTO DWM.DW_SA_BASE_BAJAS_3G_2 SELECT * FROM DM.DW_SA_BASE_BAJAS_3G_2; 
COMMIT;

DROP TABLE DM.DW_SA_BASE_BAJAS_3G_2 PURGE;

EXIT;