WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;
BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS2_BLACKLIST_VF2_135_136');
END;
/

CREATE TABLE DM.DW_SPSS2_BLACKLIST_VF2_135_136 NOLOGGING PARALLEL 2 AS
select /*+ parallel(2)*/ '&1' AS PERIODO,B.MSISDN,
(CASE WHEN SUM(CASE WHEN  B.fuente='INDECOPI' THEN 1 ELSE 0 END)>0 THEN 'SI' ELSE 'NO' END) Vf2_135,
(CASE WHEN SUM(CASE WHEN  B.fuente='SIAC' THEN 1 ELSE 0 END)>0 THEN 'SI' ELSE 'NO' END) Vf2_136
from DM.BLIST_TELEFONOS B 
WHERE TO_CHAR(FECHA_REGISTRO, 'YYYYMM') = '&1'
AND EXISTS (SELECT 1 FROM DWM.DW_MAESTRA_POSTPAGO a 
where a.msisdn=b.msisdn and TO_DATE(a.fch_activacion,'DD/MM/YYYY')=trunc(b.fec_activacion) AND A.MES = '&1' )
GROUP BY B.MSISDN;

DELETE FROM DWM.DW_SPSS2_BLACKLIST_VF2_135_136 WHERE PERIODO='&1';
COMMIT;

INSERT INTO DWM.DW_SPSS2_BLACKLIST_VF2_135_136 SELECT * FROM DM.DW_SPSS2_BLACKLIST_VF2_135_136; 
COMMIT;

DROP TABLE DM.DW_SPSS2_BLACKLIST_VF2_135_136 PURGE;

EXIT;