WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_SPSS2_VF2_139_F');
END;
/

CREATE TABLE DM.DW_SPSS2_VF2_139_F PARALLEL 2 AS
SELECT 
PERIODO,
TDOCV_DESCRIPCION,
NUMERO_DOC,
VF2_139
FROM
(
SELECT 
SOLIN_CODIGO,
'&1' AS PERIODO,
SOLID_FEC_REG as FECHA,
trim(CLIEC_NUM_DOC) as NUMERO_DOC,
B.TDOCV_DESCRIPCION,
CASE TRIEC_CODIGO
WHEN '4' THEN 'SIN HC'
WHEN '3' THEN 'ALTO'
WHEN '2' THEN 'MEDIO'
WHEN '1' THEN 'BAJO'
ELSE NULL
 END VF2_139,
ROW_NUMBER() OVER (PARTITION BY trim(CLIEC_NUM_DOC) ORDER BY SOLID_FEC_REG desc) RW
FROM DWS.SA_SECT_SOLICITUD A
INNER JOIN dws.sa_sect_tipo_documento B
ON A.tdocc_codigo = B.tdocc_codigo
WHERE TRUNC(SOLID_FEC_REG) < ADD_MONTHS(TO_DATE('&1','YYYYMM'),1)
)
WHERE RW=1;

DELETE FROM DWM.DW_SPSS2_VF2_139_F WHERE PERIODO='&1';
COMMIT;

INSERT INTO DWM.DW_SPSS2_VF2_139_F SELECT * FROM DM.DW_SPSS2_VF2_139_F; 
COMMIT;

DROP TABLE DM.DW_SPSS2_VF2_139_F PURGE;

EXIT;