WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_CANT_ITERA_TIP_CONS_SPSS');
END;
/

CREATE TABLE DM.DW_CANT_ITERA_TIP_CONS_SPSS NOLOGGING COMPRESS AS 
SELECT TO_CHAR(CREATE_DATE,'YYYYMM') AS MES, COUNT(CREATE_DATE) AS VF2_152, PHONE AS MSISDN
FROM DWS.SA_TABLE_INTERACT 
WHERE (S_REASON_2 LIKE '%INFORMACION%'
OR S_REASON_2 LIKE '%INFORMACIÓN%') AND TO_CHAR(CREATE_DATE,'YYYYMM')  = '&1'
AND S_REASON_1 = 'POSTPAGO'
AND LENGTH (PHONE)= 9
AND SUBSTR(PHONE,'1','1')= '9'
GROUP BY TO_CHAR(CREATE_DATE,'YYYYMM'), PHONE;

INSERT INTO DWM.DW_CANT_ITERA_TIP_CONS_SPSS SELECT * FROM DM.DW_CANT_ITERA_TIP_CONS_SPSS; 
COMMIT;

DROP TABLE DM.DW_CANT_ITERA_TIP_CONS_SPSS PURGE;

EXIT;
