
WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;
--##############################################################################
--#                                                                            #
--#   NOMBRE         :                                                         #
--#                                                                            #
--#   AUTOR          :   < SUSAN DELGADO >                                     #
--#   FECHA          :   < 20/08/2018>                                         #
--#   FUNCION        :   < SQL PLANTILLA >                                     #
--#   TABLAS         :   <DM.DW_SPSS2_VF2_002_008>                            #
--#						 <DM.DW_VF2_183_CARGO_FIJO>						   #
--#						 <DM.DW_MOT_ACT_VF2_007>					     	   #
--#						 <DM.DW_SPSS2_VF2_009_FI_17>					       #
--#						 <DM.DW_SPSS2_BLACKLIST_VF2_135_136>				   #
--#						 <DM.DW_SPSS2_VF2_186>							       #
--#                                                                            #
--#   COMENTARIO    :   <CREACION DE TABLAS TEMPORALES VARIABLES POSTPAGO>     #
--#                                                                            #
--#   DEPENDENCIAS  :   <>                                                     #
--#                                                                            #
--#  VERSION       :  1.0                                                      #
--#                : <FECHA> <PERSONA> : <DETALLE DE CAMBIOS>                  #
--##############################################################################

--#-------------------------------------------------------------------------------------------------------#  
--#  1.- DEFINICION DE PARAMETROS DINAMICOS                                                               #  
--#-------------------------------------------------------------------------------------------------------#  
--# <VARIABLE_NAME1> : VARIABLE CONFIGURADA EN LA APLICACION 
--# DM  
--# <P_DB_TBS_STAGING> 
--# <P_VAR_SCHEMA_DWS> 
--# <P_VAR_SCHEMA_USR_ADMIN>
--# <P_VAR_PROCESS_DATE> 
--#-------------------------------------------------------------------------------------------------------#  

--#-------------------------------------------------------------------------------------------------------#  
--#  2.INICIO - PROCESO DE ELIMINACION Y TRUNCADO DE TABLAS                                               #  
--#-------------------------------------------------------------------------------------------------------#  
 
----#-------------------------------------------------------------------------------------------------------#  
----#  2.1.- ELIMINACION DE TABLAS TEMPORALES                              							        #   
----#-------------------------------------------------------------------------------------------------------#  

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP2');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP3');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP4');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP5');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP6');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP7');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP8');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP9');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP10');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP11');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP12');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP13');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP14');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP15');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP16');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP17');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP18');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP19');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP20');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP21');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP22');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP23');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP24');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP25');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP26');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP27');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP28');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP29');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP30');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_VF2_002_008');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_VF2_015');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_BLOQUEO_VF2_030_F');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_CURSADO');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_BLOQUEO_VF2_035');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_flag_bloqueos_periodo_spss');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_CANT_ITERA_TIP_CONS_SPSS');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_CANT_X_MES_ITE_VAR_SPSS');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_spss2_deuda');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_spss_vf2_166_167');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_vf2_175_masivo');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_VF2_183_CARGO_FIJO');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_VF2_192_f');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_CANT_RENO_MES_LINEA');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_VF2_216_MAYO');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_TOPE_CONSUMO');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_TRAFICO_PLAN_2');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_TAG_1460_VF2_228_375');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_spps2_porc_con_mb_sms');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_TEMP_TAG_1470_F');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_TASADO_DEMANDA');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_TRAFICO_GRANEL');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_spss2_eq_trafico');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_TRAFICO_LLAMADAS_SAL_SPSS');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_CALL_COMPETENCIA');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_BAJAS_2G_HP_POST');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_BAJAS_3G_HP_POST');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_BAJAS_4G_HP_POST');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_spps_vf2_165_F');
END;
/


--#-------------------------------------------------------------------------------------------------------#  
--#  3.- EJECUCION - PROCESO DE CARGA 														  			  #   
--#-------------------------------------------------------------------------------------------------------#  

----#-------------------------------------------------------------------------------------------------------#  
----#  3.1.- CREACION DE TABLAS TEMPORALES														  			#   
----#-------------------------------------------------------------------------------------------------------#  

CREATE TABLE DM.T$_SPSS2_VF2_002_008 nologging AS
SELECT DISTINCT MES,CO_ID,VF2_002,VF2_008
FROM (
SELECT DISTINCT MES,CO_ID,VF2_002,VF2_008,
ROW_NUMBER() OVER(PARTITION BY MES,CO_ID ORDER BY ROWNUM) RN
FROM DM.DW_SPSS2_VF2_002_008
WHERE MES='201809')
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP1 NOLOGGING AS
SELECT A.*, C.VF2_002
FROM DWM.DW_MAESTRA_POSTPAGO A
LEFT JOIN DM.T$_SPSS2_VF2_002_008 C 
ON A.CO_ID = C.CO_ID AND A.MES = C.MES
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL
AND A.MES ='201809';

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM DM.DW_TABLON_POSTPAGO_M_TP1;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_M_TP1: '||V_COUNT);
END;
/

CREATE TABLE DM.T$_SPSS2_VF2_015 NOLOGGING AS
SELECT PERIODO, MSISDN, VF2_015 
FROM (SELECT PERIODO,MSISDN,VF2_015,
ROW_NUMBER() OVER(PARTITION BY PERIODO,MSISDN ORDER BY ROWNUM) RN
FROM DM.DW_SPSS2_VF2_015
WHERE PERIODO='201809')
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP2 NOLOGGING AS
SELECT A.*,
VF2_015
FROM DM.DW_TABLON_POSTPAGO_M_TP1 A
LEFT JOIN DM.T$_SPSS2_VF2_015 C 
ON A.MES = C.PERIODO AND A.MSISDN = '51'||C.MSISDN
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.t$_SPSS2_CURSADO NOLOGGING AS
SELECT PERIODO,TIM_NUMBER
,vf2_017
,vf2_018
,vf2_257
,vf2_258
,vf2_264
,vf2_265
,vf2_271
,vf2_281
,vf2_282
,vf2_286
,vf2_439
,vf2_440 FROM (
SELECT PERIODO,TIM_NUMBER 
,vf2_017
,vf2_018
,vf2_257
,vf2_258
,vf2_264
,vf2_265
,vf2_271
,vf2_281
,vf2_282
,vf2_286
,vf2_439
,vf2_440
,ROW_NUMBER() OVER(PARTITION BY PERIODO,TIM_NUMBER ORDER BY ROWNUM) RN
FROM DM.DW_SPSS2_CURSADO
WHERE PERIODO='201809')
WHERE RN=1;


CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP3 NOLOGGING AS
SELECT A.*
,vf2_017
,vf2_018
,vf2_257
,vf2_258
,vf2_264
,vf2_265
,vf2_271
,vf2_281
,vf2_282
,vf2_286
,vf2_439
,vf2_440
FROM DM.DW_TABLON_POSTPAGO_M_TP2 A
LEFT JOIN DM.t$_SPSS2_CURSADO C 
ON A.MES = C.PERIODO AND A.MSISDN = C.TIM_NUMBER
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.T$_BLOQUEO_VF2_030_F NOLOGGING AS
SELECT DISTINCT PERIODO, CO_ID,VF2_030
FROM (SELECT PERIODO, CO_ID,VF2_030
,ROW_NUMBER() OVER(PARTITION BY PERIODO, CO_ID ORDER BY ROWNUM) RN
FROM DM.DW_BLOQUEO_VF2_030_F
WHERE PERIODO='201809')
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP4 NOLOGGING AS
SELECT A.*,
VF2_030
FROM DM.DW_TABLON_POSTPAGO_M_TP3 A
LEFT JOIN DM.T$_BLOQUEO_VF2_030_F C 
ON A.MES = C.PERIODO AND A.CO_ID = C.CO_ID
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.T$_BLOQUEO_VF2_035 NOLOGGING AS
SELECT DISTINCT PERIODO, CO_ID, VF2_035
FROM (
SELECT PERIODO, CO_ID, VF2_035
,ROW_NUMBER() OVER(PARTITION BY PERIODO, CO_ID ORDER BY ROWNUM) RN
FROM DM.DW_BLOQUEO_VF2_035
WHERE PERIODO='201809')
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP5 NOLOGGING AS
SELECT A.*,
VF2_035
FROM DM.DW_TABLON_POSTPAGO_M_TP4 A
LEFT JOIN DM.T$_BLOQUEO_VF2_035 C 
ON A.MES = C.PERIODO AND A.CO_ID = C.CO_ID
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM DM.DW_TABLON_POSTPAGO_M_TP5;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_M_TP5: '||V_COUNT);
END;
/

CREATE TABLE DM.t$_flag_bloqueos_periodo_spss NOLOGGING AS
SELECT DISTINCT MES,CO_ID,CUSTOMER_ID,VF2_144
FROM (
SELECT MES,CO_ID,CUSTOMER_ID,VF2_144
,ROW_NUMBER() OVER(PARTITION BY MES,CO_ID,CUSTOMER_ID ORDER BY ROWNUM) RN
FROM DM.dw_flag_bloqueos_periodo_spss
WHERE MES='201809'
)
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP6 NOLOGGING AS
SELECT A.*, C.VF2_144
FROM DM.DW_TABLON_POSTPAGO_M_TP5 A
LEFT JOIN DM.dw_flag_bloqueos_periodo_spss C 
ON A.CO_ID = C.CO_ID AND A.MES = C.MES AND A.CUSTOMER_ID = C.CUSTOMER_ID
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;	

CREATE TABLE DM.t$_CANT_ITERA_TIP_CONS_SPSS NOLOGGING AS
SELECT DISTINCT MES,MSISDN,VF2_152
FROM (
SELECT MES,MSISDN,VF2_152,
ROW_NUMBER() OVER(PARTITION BY MES,MSISDN ORDER BY ROWNUM) RN
FROM DM.DW_CANT_ITERA_TIP_CONS_SPSS 
WHERE MES='201809')
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP7 NOLOGGING AS
SELECT A.*, C.VF2_152
FROM DM.DW_TABLON_POSTPAGO_M_TP6 A
LEFT JOIN DM.t$_CANT_ITERA_TIP_CONS_SPSS C 
ON A.MES = C.MES AND A.MSISDN = '51'||C.MSISDN
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;	

CREATE TABLE DM.T$_CANT_X_MES_ITE_VAR_SPSS NOLOGGING AS
SELECT DISTINCT MES,MSISDN,VF2_155
FROM (
SELECT MES,MSISDN,VF2_155,
ROW_NUMBER() OVER(PARTITION BY MES,MSISDN ORDER BY ROWNUM) RN
FROM DM.DW_CANT_X_MES_ITE_VAR_SPSS
WHERE MES='201809')
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP8 NOLOGGING AS
SELECT A.*, C.VF2_155
FROM DM.DW_TABLON_POSTPAGO_M_TP7 A
LEFT JOIN DM.T$_CANT_X_MES_ITE_VAR_SPSS C 
ON A.MES = C.MES AND A.MSISDN = '51'||C.MSISDN
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.T$_spss2_deuda NOLOGGING AS
SELECT MES,customer_id, VF2_160
FROM (
SELECT MES,customer_id, VF2_160,
ROW_NUMBER() OVER(PARTITION BY MES,customer_id ORDER BY ROWNUM) RN 
FROM DM.T$_DEUDA_MAS
WHERE MES='201809'
)
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP9 NOLOGGING AS
SELECT A.*, C.VF2_160
FROM DM.DW_TABLON_POSTPAGO_M_TP8 A
LEFT JOIN DM.T$_spss2_deuda C 
on a.mes = c.MES and a.customer_id = c.customer_id
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;	

CREATE TABLE DM.T$_spps_vf2_165_F NOLOGGING AS
SELECT PERIOD,CUSTOMER_ID, DUE_DATE
FROM (
SELECT PERIOD,CUSTOMER_ID, DUE_DATE,
ROW_NUMBER() OVER(PARTITION BY period,customer_id ORDER BY ROWNUM) RN 
FROM DM.DW_spss_vf2_165_F
WHERE PERIOD='201809')
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP10 NOLOGGING AS
SELECT A.*, C.DUE_DATE AS VF2_165
FROM DM.DW_TABLON_POSTPAGO_M_TP9 A
LEFT JOIN DM.T$_spps_vf2_165_F C 
ON A.CUSTOMER_ID = C.CUSTOMER_ID AND A.MES = C.PERIOD
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM DM.DW_TABLON_POSTPAGO_M_TP10;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_M_TP10: '||V_COUNT);
END;
/

CREATE TABLE DM.T$_spss_vf2_166_167 NOLOGGING AS
SELECT MES,CUSTOMER_ID,VF2_167
FROM (
SELECT MES,CUSTOMER_ID,VF2_167,
ROW_NUMBER() OVER(PARTITION BY MES,CUSTOMER_ID ORDER BY ROWNUM) RN 
FROM DM.dw_spss_vf2_166_167
WHERE MES='201809'
)
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP11 NOLOGGING AS
SELECT A.*, C.VF2_167
FROM DM.DW_TABLON_POSTPAGO_M_TP10 A
LEFT JOIN DM.T$_spss_vf2_166_167 C 
ON A.CUSTOMER_ID = C.CUSTOMER_ID AND A.MES = C.MES
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.T$_vf2_175_masivo NOLOGGING AS
SELECT PERIODO,LINEA, CO_ID,SNCODE FROM (
SELECT PERIODO,LINEA, CO_ID,SNCODE,
ROW_NUMBER() OVER(PARTITION BY PERIODO,LINEA, CO_ID ORDER BY ROWNUM) RN 
FROM DM.DW_vf2_175_masivo
WHERE PERIODO='201809')
WHERE RN=1;


CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP12 NOLOGGING AS
SELECT A.*, C.SNCODE VF2_175
FROM DM.DW_TABLON_POSTPAGO_M_TP11 A
LEFT JOIN DM.T$_vf2_175_masivo C 
ON A.MSISDN = '51'||C.LINEA AND A.MES = C.PERIODO
AND A.CO_ID = C.CO_ID
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO'
)
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.T$_VF2_183_CARGO_FIJO NOLOGGING AS
SELECT mes,co_id, VF2_183
FROM (
SELECT mes,co_id, VF2_183,
ROW_NUMBER() OVER(PARTITION BY mes,co_id ORDER BY ROWNUM) RN 
FROM DM.DW_VF2_183_CARGO_FIJO
WHERE mes='201809')
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP13 NOLOGGING AS
SELECT A.*, C.VF2_183
FROM DM.DW_TABLON_POSTPAGO_M_TP12 A
LEFT JOIN DM.T$_VF2_183_CARGO_FIJO C 
on a.mes = c.mes and a.co_id = c.co_id
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.T$_VF2_192_f NOLOGGING AS
SELECT mes, co_id, VF2_192
FROM (
SELECT mes, co_id, VF2_192,
ROW_NUMBER() OVER(PARTITION BY mes,co_id ORDER BY ROWNUM) RN 
FROM DM.DW_VF2_192_f
WHERE mes='201809')
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP14 NOLOGGING AS
SELECT A.*, C.VF2_192
FROM DM.DW_TABLON_POSTPAGO_M_TP13 A
LEFT JOIN DM.T$_VF2_192_f C 
on a.mes = c.mes and a.co_id = c.co_id
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.T$_CANT_RENO_MES_LINEA NOLOGGING AS
SELECT mes, msisdn, VF2_206
FROM (
SELECT mes, msisdn, VF2_206,
ROW_NUMBER() OVER(PARTITION BY mes, msisdn ORDER BY ROWNUM) RN
FROM DM.DW_CANT_RENO_MES_LINEA
WHERE mes='201809')
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP15 nologging as
SELECT a.*, 
VF2_206
FROM DM.DW_TABLON_POSTPAGO_M_TP14 a
LEFT JOIN DM.T$_CANT_RENO_MES_LINEA c 
ON a.mes = c.mes AND a.msisdn = c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;  

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM DM.DW_TABLON_POSTPAGO_M_TP15;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_M_TP15: '||V_COUNT);
END;
/

CREATE TABLE DM.T$_SPSS2_VF2_216_MAYO NOLOGGING AS
SELECT periodo2, ruc_dni2, VF2_216
FROM (
SELECT periodo2, ruc_dni2, VF2_216,
ROW_NUMBER() OVER(PARTITION BY periodo2, ruc_dni2 ORDER BY ROWNUM) RN
FROM DM.DW_SPSS2_VF2_216_MAYO
WHERE periodo2='201809'
)
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP16 nologging as
SELECT a.*, c.VF2_216
FROM DM.DW_TABLON_POSTPAGO_M_TP15 a
LEFT JOIN DM.T$_SPSS2_VF2_216_MAYO c 
ON a.mes = c.periodo2 AND a.nro_documento = c.ruc_dni2
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;    

CREATE TABLE DM.T$_SPSS2_TOPE_CONSUMO NOLOGGING AS
SELECT periodo, msisdn, VF2_223
FROM (
SELECT periodo, msisdn, VF2_223,
ROW_NUMBER() OVER(PARTITION BY periodo, msisdn ORDER BY ROWNUM) RN
FROM DM.DW_SPSS2_TOPE_CONSUMO
WHERE periodo='201809'
) 
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP17 nologging as
SELECT a.*, c.VF2_223
FROM DM.DW_TABLON_POSTPAGO_M_TP16 a
LEFT JOIN DM.T$_SPSS2_TOPE_CONSUMO c 
ON a.mes = c.periodo AND a.msisdn = c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 

CREATE TABLE DM.T$_SPSS2_TRAFICO_PLAN_2 NOLOGGING AS
SELECT period, msisdn, VF2_224, vf2_247, vf2_297 FROM (
SELECT period, msisdn, VF2_224, vf2_247, vf2_297,
ROW_NUMBER() OVER(PARTITION BY period, msisdn ORDER BY ROWNUM) RN
FROM DM.DW_SPSS2_TRAFICO_PLAN_2
WHERE period='201809')
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP18 nologging as
SELECT a.*, 
c.VF2_224,
c.vf2_247,  
c.vf2_297
FROM DM.DW_TABLON_POSTPAGO_M_TP17 a
LEFT JOIN DM.T$_SPSS2_TRAFICO_PLAN_2 c 
ON a.mes = c.period AND a.msisdn ='51'|| c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;  

CREATE TABLE DM.T$_SPSS2_TAG_1460_VF2_228_375 NOLOGGING AS
SELECT period, msisdn, VF2_228
, VF2_307
, VF2_308
, VF2_332
, VF2_375
FROM (
SELECT period, msisdn, VF2_228
, VF2_307
, VF2_308
, VF2_332
, VF2_375,
ROW_NUMBER() OVER(PARTITION BY period, msisdn ORDER BY ROWNUM) RN
FROM dm.dw_SPSS2_TAG_1460_VF2_228_375
WHERE period='201809')
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP19 nologging as
SELECT a.*
, VF2_228
, VF2_307
, VF2_308
, VF2_332
, VF2_375
FROM DM.DW_TABLON_POSTPAGO_M_TP18 a
LEFT JOIN DM.T$_SPSS2_TAG_1460_VF2_228_375 c 
ON a.mes = c.period AND a.msisdn =c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 

CREATE TABLE DM.T$_spps2_porc_con_mb_sms NOLOGGING AS
SELECT PERIODO, msisdn,VF2_236
FROM (
SELECT PERIODO, msisdn, VF2_236,
ROW_NUMBER() OVER(PARTITION BY PERIODO, msisdn ORDER BY ROWNUM) RN
FROM DM.dw_spps2_porc_con_mb_sms
WHERE periodo='201809'
)
WHERE RN=1;


CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP20 nologging as
SELECT a.*, 
VF2_236
FROM DM.DW_TABLON_POSTPAGO_M_TP19 a
LEFT JOIN DM.T$_spps2_porc_con_mb_sms c 
ON a.mes = c.PERIODO AND a.msisdn = c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM DM.DW_TABLON_POSTPAGO_M_TP20;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_M_TP20: '||V_COUNT);
END;
/

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP21 nologging as
SELECT a.*, 
VF2_244,
VF2_250
FROM DM.DW_TABLON_POSTPAGO_M_TP20 a
LEFT JOIN DM.DW_F2_C_M_GPRS_ENE c 
ON a.mes = c.mes AND a.msisdn = c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.T$_SPSS2_TEMP_TAG_1470_F NOLOGGING AS
SELECT PERIODO, msisdn, VF2_285, VF2_376 FROM (
SELECT PERIODO, msisdn, VF2_285, VF2_376,
ROW_NUMBER() OVER(PARTITION BY PERIODO, msisdn ORDER BY ROWNUM) RN
FROM DM.DW_SPSS2_TEMP_TAG_1470_F
WHERE periodo='201809')
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP22 nologging as
SELECT a.*, 
VF2_285,
VF2_376
FROM DM.DW_TABLON_POSTPAGO_M_TP21 a
LEFT JOIN DM.T$_SPSS2_TEMP_TAG_1470_F c 
ON a.mes = c.PERIODO AND a.msisdn = c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.T$_SPSS2_TASADO_DEMANDA NOLOGGING AS
SELECT fecha, served_number, VF2_340, VF2_365, VF2_366,VF2_374
FROM (
SELECT fecha, served_number, VF2_340, VF2_365, VF2_366,VF2_374,
ROW_NUMBER() OVER(PARTITION BY fecha, served_number ORDER BY ROWNUM) RN
FROM DM.DW_SPSS2_TASADO_DEMANDA
WHERE fecha='201809'
)
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP23 nologging as
SELECT a.*, 
VF2_340,
VF2_365,
VF2_366,
VF2_374
FROM DM.DW_TABLON_POSTPAGO_M_TP22 a
LEFT JOIN DM.T$_SPSS2_TASADO_DEMANDA c 
ON a.mes = c.fecha AND a.msisdn = c.served_number
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 

CREATE TABLE DM.T$_TRAFICO_GRANEL NOLOGGING AS
SELECT PERIODO, MSISDN,
VF2_348,
VF2_367,
VF2_368,
VF2_373,
vf2_441,
vf2_442, 
vf2_443, 
vf2_444, 
vf2_445, 
vf2_446, 
vf2_447, 
vf2_448, 
vf2_449, 
vf2_450, 
vf2_451, 
vf2_452
FROM (
SELECT PERIODO, MSISDN,
VF2_348,
VF2_367,
VF2_368,
VF2_373,
vf2_441,
vf2_442, 
vf2_443, 
vf2_444, 
vf2_445, 
vf2_446, 
vf2_447, 
vf2_448, 
vf2_449, 
vf2_450, 
vf2_451, 
vf2_452,
ROW_NUMBER() OVER(PARTITION BY PERIODO, MSISDN ORDER BY ROWNUM) RN
FROM DM.DW_TRAFICO_GRANEL
WHERE PERIODO='201809'
)
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP24 nologging as
SELECT a.*, 
VF2_348,
VF2_367,
VF2_368,
VF2_373,
vf2_441,
vf2_442, 
vf2_443, 
vf2_444, 
vf2_445, 
vf2_446, 
vf2_447, 
vf2_448, 
vf2_449, 
vf2_450, 
vf2_451, 
vf2_452
FROM DM.DW_TABLON_POSTPAGO_M_TP23 a
LEFT JOIN DM.T$_TRAFICO_GRANEL C 
ON A.MES = C.PERIODO AND A.MSISDN = C.MSISDN
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO', 'SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL; 

CREATE TABLE DM.T$_spss2_eq_trafico NOLOGGING AS
SELECT DISTINCT MSISDN, PERIODO, VF2_391
FROM (
SELECT MSISDN, PERIODO, VF2_391,
ROW_NUMBER() OVER(PARTITION BY MSISDN, PERIODO ORDER BY ROWNUM) RN
FROM DM.dw_spss2_eq_trafico
WHERE PERIODO='201809')
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP25 NOLOGGING AS
SELECT A.*, C.VF2_391
FROM DM.DW_TABLON_POSTPAGO_M_TP24 A
LEFT JOIN DM.T$_spss2_eq_trafico C ON A.MSISDN = C.MSISDN AND A.MES = C.PERIODO
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

DECLARE 
V_COUNT NUMBER:=0;
BEGIN
SELECT COUNT(1) INTO V_COUNT FROM DM.DW_TABLON_POSTPAGO_M_TP25;
DBMS_OUTPUT.PUT_LINE('DW_TABLON_POSTPAGO_M_TP25: '||V_COUNT);
END;
/

CREATE TABLE DM.T$_TRAFICO_LLAMADAS_SAL_SPSS NOLOGGING AS
SELECT periodo, msisdn, cant_dias
FROM 
(
SELECT periodo, msisdn, cant_dias,
ROW_NUMBER() OVER(PARTITION BY periodo, msisdn ORDER BY ROWNUM) RN
FROM DM.DW_TRAFICO_LLAMADAS_SAL_SPSS
WHERE PERIODO='201809'
)
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP26 NOLOGGING AS
SELECT A.*, C.cant_dias as VF2_436
FROM DM.DW_TABLON_POSTPAGO_M_TP25 A
LEFT JOIN DM.T$_TRAFICO_LLAMADAS_SAL_SPSS C 
ON a.MES = c.periodo AND a.msisdn = '51'||c.msisdn
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.T$_SPSS2_CALL_COMPETENCIA NOLOGGING AS
SELECT NUMERO_A, PERIODO, VF2_458
FROM (
SELECT NUMERO_A, PERIODO, VF2_458,
ROW_NUMBER() OVER(PARTITION BY NUMERO_A, PERIODO ORDER BY ROWNUM) RN
FROM DM.DW_SPSS2_CALL_COMPETENCIA
WHERE PERIODO='201809'
)
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP27 NOLOGGING AS
SELECT A.*, C.VF2_458
FROM DM.DW_TABLON_POSTPAGO_M_TP26 A
LEFT JOIN DM.T$_SPSS2_CALL_COMPETENCIA C 
ON A.MSISDN=C.NUMERO_A AND A.MES=C.PERIODO
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.T$_BAJAS_2G_HP_POST NOLOGGING AS
SELECT TIM_NUMBER, MES, VF2_047
FROM (
SELECT TIM_NUMBER, MES, VF2_047,
ROW_NUMBER() OVER(PARTITION BY TIM_NUMBER, MES ORDER BY ROWNUM) RN
FROM DM.DW_BAJAS_2G_HP_POST
WHERE MES='201809'
)
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP28 NOLOGGING AS
SELECT A.*, C.VF2_047
FROM DM.DW_TABLON_POSTPAGO_M_TP27 A
LEFT JOIN DM.T$_BAJAS_2G_HP_POST C 
ON A.MSISDN=C.TIM_NUMBER AND A.MES=C.MES
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.T$_BAJAS_3G_HP_POST NOLOGGING AS
SELECT TIM_NUMBER, MES, VF2_053
FROM (
SELECT TIM_NUMBER, MES, VF2_053,
ROW_NUMBER() OVER(PARTITION BY TIM_NUMBER, MES ORDER BY ROWNUM) RN
FROM DM.DW_BAJAS_3G_HP_POST
WHERE MES='201809'
)
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP29 NOLOGGING AS
SELECT A.*, C.VF2_053
FROM DM.DW_TABLON_POSTPAGO_M_TP28 A
LEFT JOIN DM.T$_BAJAS_3G_HP_POST C 
ON A.MSISDN=C.TIM_NUMBER AND A.MES=C.MES
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;

CREATE TABLE DM.T$_BAJAS_4G_HP_POST NOLOGGING AS
SELECT TIM_NUMBER, MES, VF2_061
FROM (
SELECT TIM_NUMBER, MES, VF2_061,
ROW_NUMBER() OVER(PARTITION BY TIM_NUMBER, MES ORDER BY ROWNUM) RN
FROM DM.DW_BAJAS_4G_HP_POST
WHERE MES='201809'
)
WHERE RN=1;

CREATE TABLE DM.DW_TABLON_POSTPAGO_M_TP30 NOLOGGING AS
SELECT DISTINCT
A.MSISDN,
A.CUSTOMER_ID,
A.CO_ID,
A.NRO_DOCUMENTO,
A.FCH_ACTIVACION,
A.STATUS,
A.POSTPAGO,
A.TIPO_DOCUMENTO,
A.MES,
A.REASON_STATUS,
A.VF2_002,
A.VF2_015,
A.VF2_017,
A.VF2_018,
A.VF2_257,
A.VF2_258,
A.VF2_264,
A.VF2_265,
A.VF2_271,
A.VF2_281,
A.VF2_282,
A.VF2_286,
A.VF2_439,
A.VF2_440,
A.VF2_030,
A.VF2_035,
A.VF2_144,
A.VF2_152,
A.VF2_155,
A.VF2_160,
A.VF2_165,
A.VF2_167,
A.VF2_175,
A.VF2_183,
A.VF2_192,
A.VF2_206,
A.VF2_216,
A.VF2_223,
A.VF2_224,
A.VF2_247,
A.VF2_297,
A.VF2_228,
A.VF2_307,
A.VF2_308,
A.VF2_332,
A.VF2_375,
A.VF2_236,
A.VF2_244,
A.VF2_250,
A.VF2_285,
A.VF2_376,
A.VF2_340,
A.VF2_365,
A.VF2_366,
A.VF2_374,
A.VF2_348,
A.VF2_367,
A.VF2_368,
A.VF2_373,
A.VF2_441,
A.VF2_442,
A.VF2_443,
A.VF2_444,
A.VF2_445,
A.VF2_446,
A.VF2_447,
A.VF2_448,
A.VF2_449,
A.VF2_450,
A.VF2_451,
A.VF2_452,
A.VF2_391,
A.VF2_436,
A.VF2_458,
A.VF2_047,
A.VF2_053,
C.VF2_061
FROM DM.DW_TABLON_POSTPAGO_M_TP29 A
LEFT JOIN DM.T$_BAJAS_4G_HP_POST C 
ON A.MSISDN=C.TIM_NUMBER AND A.MES=C.MES
WHERE A.POSTPAGO = 'MASIVO'
AND A.STATUS IN ('ACTIVO','SUSPENDIDO')
AND A.FCH_ACTIVACION IS NOT NULL;


DECLARE
e_validacion EXCEPTION;
v_inicial NUMBER:= 0;
v_final NUMBER:= 1;
BEGIN
SELECT COUNT(1) INTO v_inicial FROM DM.DW_TABLON_POSTPAGO_M_TP1;
SELECT COUNT(1) INTO v_final FROM DM.DW_TABLON_POSTPAGO_M_TP30;
IF v_inicial <> v_final THEN
RAISE e_validacion;
END IF;
EXCEPTION 
WHEN e_validacion THEN
RAISE_APPLICATION_ERROR(-20101,'DIFERENCIA DE CANTIDADES EN LAS TEMPORALES');
END;
/



----#-------------------------------------------------------------------------------------------------------#  
----#  4.- ELIMINACION DE TABLAS TEMPORALES                              							        #   
----#-------------------------------------------------------------------------------------------------------#  

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP1');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP2');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP3');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP4');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP5');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP6');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP7');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP8');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP9');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP10');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP11');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP12');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP13');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP14');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP15');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP16');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP17');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP18');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP19');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP20');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP21');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP22');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP23');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP24');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP25');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP26');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP27');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP28');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.DW_TABLON_POSTPAGO_M_TP29');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_VF2_002_008');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_VF2_015');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_BLOQUEO_VF2_030_F');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_CURSADO');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_BLOQUEO_VF2_035');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_flag_bloqueos_periodo_spss');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_CANT_ITERA_TIP_CONS_SPSS');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_CANT_X_MES_ITE_VAR_SPSS');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_spss2_deuda');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_spss_vf2_166_167');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_vf2_175_masivo');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_VF2_183_CARGO_FIJO');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_VF2_192_f');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_CANT_RENO_MES_LINEA');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_VF2_216_MAYO');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_TOPE_CONSUMO');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_TRAFICO_PLAN_2');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_TAG_1460_VF2_228_375');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_spps2_porc_con_mb_sms');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_TEMP_TAG_1470_F');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_TASADO_DEMANDA');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_TRAFICO_GRANEL');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_spss2_eq_trafico');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_TRAFICO_LLAMADAS_SAL_SPSS');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_SPSS2_CALL_COMPETENCIA');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_BAJAS_2G_HP_POST');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_BAJAS_3G_HP_POST');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_BAJAS_4G_HP_POST');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_spps_vf2_165_F');
END;
/

EXIT;