WHENEVER SQLERROR EXIT 1;

SET ECHO ON;
SET SERVEROUTPUT ON;
SET TIMING ON;

WHENEVER SQLERROR EXIT 1;


BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.t$_maestra_bajas');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_CONT_BAJAS_FI');
END;
/


create table DM.t$_maestra_bajas as
select * from DWM.DW_MAESTRA_POSTPAGO
where mes ='&1';

CREATE TABLE DM.T$_CONT_BAJAS_FI AS
SELECT A.MSISDN, A.CUSTOMER_ID, A.CO_ID, A.NRO_DOCUMENTO, A.FCH_ACTIVACION, A.STATUS, A.POSTPAGO, A.TIPO_DOCUMENTO, A.MES, A.REASON_STATUS AS VF2_029,
B.FECHABAJA AS VF2_027,
case when A.reason_status in ('Desactivacion Port OUT', 'A solicitud Cliente') then 'Voluntario'
else 'Involuntario' end as Categoria_Baja
FROM DM.t$_maestra_bajas A
INNER JOIN DM.F_M_CONTRATO B
ON A.CO_ID = B.CO_ID
WHERE A.MES = '&1'
AND B.MES = '&1' 
AND A.MES = B.MES
AND A.STATUS = 'DESACTIVO';

DELETE FROM DWM.DW_SPSS_BAJAS_M
WHERE MES='&1';
COMMIT;

INSERT INTO DWM.DW_SPSS_BAJAS_M
SELECT * FROM DM.T$_CONT_BAJAS_FI
WHERE POSTPAGO='MASIVO';
COMMIT;

BEGIN
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.t$_maestra_bajas');
DM.PKG_MGR_DWO_UTIL.PRC_DROP_TABLE(X_DES_TABLA => 'DM.T$_CONT_BAJAS_FI');
END;
/

EXIT;