


DECLARE

PFEC_PROC_FORMAT_ISO NUMBER:=0;
STR VARCHAR2(20000):='';
TABLA_NOMBRE_TEMP VARCHAR2(30):='T$_SA_SAP_MAKT_F';	
TABLA_NOMBRE_TEMP0 VARCHAR2(30):='T$_DATOS_CLI';
TABLA_NOMBRE_TEMP1 VARCHAR2(30):='T$_IRIS_CUST_APAGON_REN_RK';	
TABLA_NOMBRE_TEMP2 VARCHAR2(30):='T$_IRIS_CUST_APAGON_REN';	
TABLA_NOMBRE_TEMP3 VARCHAR2(30):='T$_IRIS_CUST_INCREM';	
TABLA_NOMBRE_TEMP4 VARCHAR2(30):='T$_IRIS_EAI_CONTRATO_DOL_HIST';	
TABLA_NOMBRE_TEMP5 VARCHAR2(30):='T$_IRIS_EAI_CONTRATO_DOL_H_F';	
TABLA_NOMBRE_TEMP6 VARCHAR2(30):='T$_IRIS_T$_ACTIVACION_PRE';	
TABLA_NOMBRE_TEMP7 VARCHAR2(30):='T$_IRIS_CONTACT_EMAIL';	
TABLA_NOMBRE_TEMP8 VARCHAR2(30):='T$_IRIS_CONTACT_EMAIL_F';	
TABLA_NOMBRE_TEMP9 VARCHAR2(30):='T$_F_PRODUCT_MOV_PRE';	
TABLA_NOMBRE_TEMP10 VARCHAR2(30):='T$_SPOOL_PREPAGO_MOV';

CANT_REGIST_PROCESAD0 NUMBER;
FECHA VARCHAR2(8):='';

BEGIN

SELECT DWO.PKG_FRAME_IDEAS_REPORT.FN_FEC_PROC_FORMAT_ISO INTO PFEC_PROC_FORMAT_ISO FROM DUAL; /* IMPORTANTE CAPTURAR ESTE VALOR */

SELECT '20170506' INTO FECHA FROM DUAL;

STR:='FECHA: ' || FECHA || ' *** REGISTRO: ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

-------------------------------------------------------------------------------------------------------------------------------------------------------------------

--CREACION DE LA TABLA TEMP1
STR:='INICIA CREACION DE LA TABLA: ' || TABLA_NOMBRE_TEMP || ' *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='CREATE TABLE DM.' || TABLA_NOMBRE_TEMP || ' NOLOGGING COMPRESS TABLESPACE WORKAREA_RECO AS
SELECT * FROM(
SELECT S1.*,
       ROW_NUMBER() OVER(PARTITION BY  S1.MATNR ORDER BY S1.SPRAS DESC) AS RK         
FROM DWS.SA_SAP_MAKT S1) WHERE RK = 1';
        
EXECUTE IMMEDIATE (STR);

STR:='TABLA: *** '|| USER || '.'|| TABLA_NOMBRE_TEMP||' *** FUE CREADA  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);
-------------------------------------------------------------------------------------------------------------------------------------------------------------------

--CREACION DE LA TABLA TEMP2
STR:='INICIA CREACION DE LA TABLA: '|| TABLA_NOMBRE_TEMP0 || ' *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='CREATE TABLE DM.' || TABLA_NOMBRE_TEMP0 ||  ' NOLOGGING COMPRESS TABLESPACE WORKAREA_RECO AS 
SELECT IDSEGMENTO, MSISDN, TIPO_DOCUMENTO, NRO_DOCUMENTO, NOMBRES, APELLIDOS, IDDEPARTAMENTO 
FROM DM.F_M_ABONADOS S1 WHERE S1.MES = '||FECHA||'';

EXECUTE IMMEDIATE (STR);

STR:='TABLA: *** '|| USER || '.'|| TABLA_NOMBRE_TEMP0||' *** FUE CREADA  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
STR:='INICIA CREACION DE LA TABLA: '|| TABLA_NOMBRE_TEMP1 || ' *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='CREATE TABLE DM.' || TABLA_NOMBRE_TEMP1 || ' TABLESPACE DWO_DATA  NOLOGGING  AS 
SELECT S1.* FROM (
SELECT S1.ID_CARD_VALUE,
       S1.FULL_NAME,
       S1.RAZON_SOCIAL,
       S1.GIVEN_NAME,
       UPPER(TRIM(S1.FATHER_NAME) || '' '' || TRIM(S1.MOTHER_NAME)) AS LAST_NAME,
       S1.CUSTOMER_TYPE_SC,
       S1.CUSTOMER_TYPE_DESC,
       S1.CUSTOMER_DOC_TYPE_SC,
       S1.CUSTOMER_DOC_TYPE_DESC,
       S1.FLG_RENIEC,
       S1.FLG_VALID,
       S1.GENDER_IND,
       S1.DATE_OF_BIRTH,
       S1.SOURCE_SYSTEM_DESC,
       ROW_NUMBER() OVER(PARTITION BY  S1.ID_CARD_VALUE,S1.CUSTOMER_DOC_TYPE_DESC ORDER BY S1.FLG_RENIEC,S1.FLG_VALID DESC) AS RK  
FROM DWA.DW_M_CUSTOMER S1
WHERE S1.SOURCE_SYSTEM_DESC IN(''APAGON'',''RENIEC'')) S1';

EXECUTE IMMEDIATE (STR);

STR:='TABLA: *** '|| USER || '.'|| TABLA_NOMBRE_TEMP1||' *** FUE CREADA  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);
------------------------------------------------------------------------------------------------------------------------------------------------------------------

STR:='INICIA CREACION DE LA TABLA: '|| TABLA_NOMBRE_TEMP2 || ' *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='CREATE TABLE DM.' || TABLA_NOMBRE_TEMP2 || ' NOLOGGING TABLESPACE DWO_DATA  AS 
SELECT * FROM ' || TABLA_NOMBRE_TEMP1 || ' WHERE RK=1';

EXECUTE IMMEDIATE (STR);

STR:='TABLA: *** '|| USER || '.'|| TABLA_NOMBRE_TEMP2||' *** FUE CREADA  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
STR:='INICIA CREACION DE LA TABLA: '|| TABLA_NOMBRE_TEMP3 || ' *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='CREATE TABLE DM.' || TABLA_NOMBRE_TEMP3 || ' NOLOGGING TABLESPACE DWO_DATA  AS 
SELECT S1.* FROM (
SELECT S1.ID_CARD_VALUE,
       S1.FULL_NAME,
       S1.RAZON_SOCIAL,
       S1.GIVEN_NAME,
       UPPER(TRIM(S1.FATHER_NAME) || '' ''|| TRIM(S1.MOTHER_NAME)) LAST_NAME,
       S1.CUSTOMER_TYPE_SC,
       S1.CUSTOMER_TYPE_DESC,
       S1.CUSTOMER_DOC_TYPE_SC,
       S1.CUSTOMER_DOC_TYPE_DESC,
       S1.FLG_RENIEC,
       S1.FLG_VALID,
       S1.GENDER_IND,
       S1.DATE_OF_BIRTH,
       S1.SOURCE_SYSTEM_DESC,
       ROW_NUMBER() OVER (PARTITION BY  S1.ID_CARD_VALUE,S1.CUSTOMER_DOC_TYPE_DESC ORDER BY S1.FLG_RENIEC,S1.FLG_VALID DESC) AS RK  
FROM DWA.DW_M_CUSTOMER S1 
WHERE S1.SOURCE_SYSTEM_DESC NOT IN (''APAGON'',''RENIEC'')
AND NOT EXISTS(SELECT 1 FROM ' || TABLA_NOMBRE_TEMP2 || ' S2 
                        WHERE S1.ID_CARD_VALUE = S2.ID_CARD_VALUE
                        AND NVL(S1.CUSTOMER_DOC_TYPE_DESC,''-1'') = NVL(S2.CUSTOMER_DOC_TYPE_DESC,''-1'')))S1  WHERE S1.RK =1';

EXECUTE IMMEDIATE (STR);

STR:='TABLA: *** '|| USER || '.'|| TABLA_NOMBRE_TEMP3||' *** FUE CREADA  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);


------------------------------------------------------------------------------------------------------------------------------------------------------------------

STR:='INICIA EL TRUNCATE DE LA TABLA: DM.R$_IRIS_CLIENTE_UNICO *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

--DM.PKG_MGR_DWO_UTIL.prc_truncate_table(X_DES_TABLA => 'dm.R$_IRIS_CLIENTE_UNICO');
STR:='TRUNCATE TABLE dm.R$_IRIS_CLIENTE_UNICO DROP ALL STORAGE';
EXECUTE IMMEDIATE (STR);


STR:='TABLA: *** DM.R$_IRIS_CLIENTE_UNICO *** ISO TRUNCATE  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
STR:='INICIA EL INSERT A LA TABLA: DM.R$_IRIS_CLIENTE_UNICO *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='INSERT /*+ APPEND */ INTO DM.R$_IRIS_CLIENTE_UNICO
(ID_CARD_VALUE, 
FULL_NAME, 
GIVEN_NAME,
LAST_NAME,
CUSTOMER_TYPE_SC, 
CUSTOMER_TYPE_DESC, 
CUSTOMER_DOC_TYPE_SC, 
CUSTOMER_DOC_TYPE_DESC, 
GENDER_IND, 
DATE_OF_BIRTH)
SELECT /*+ PARALLEL 3 */ DISTINCT 
S1.ID_CARD_VALUE,
NVL(S1.FULL_NAME,S1.RAZON_SOCIAL) AS FULL_NAME,
GIVEN_NAME,
LAST_NAME,
S1.CUSTOMER_TYPE_SC, 
S1.CUSTOMER_TYPE_DESC, 
S1.CUSTOMER_DOC_TYPE_SC, 
S1.CUSTOMER_DOC_TYPE_DESC, 
S1.GENDER_IND, 
S1.DATE_OF_BIRTH
FROM '|| TABLA_NOMBRE_TEMP3||'  S1 
WHERE S1.CUSTOMER_DOC_TYPE_DESC = ''DNI''';

EXECUTE IMMEDIATE (STR);
COMMIT;

STR:='TABLA: *** DM.R$_IRIS_CLIENTE_UNICO *** ISO INSERT  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);
-------------------------------------------------------------------------------------------------------------------------------------------------------------------


STR:='INICIA EL INSERT A LA TABLA: DM.R$_IRIS_CLIENTE_UNICO *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='INSERT /*+ APPEND */ INTO DM.R$_IRIS_CLIENTE_UNICO
(ID_CARD_VALUE, 
FULL_NAME, 
GIVEN_NAME,
LAST_NAME,
CUSTOMER_TYPE_SC, 
CUSTOMER_TYPE_DESC, 
CUSTOMER_DOC_TYPE_SC, 
CUSTOMER_DOC_TYPE_DESC, 
GENDER_IND, 
DATE_OF_BIRTH)
SELECT /*+ PARALLEL 3 */ DISTINCT 
S1.ID_CARD_VALUE,
NVL(S1.FULL_NAME,S1.RAZON_SOCIAL) AS FULL_NAME,
GIVEN_NAME,
LAST_NAME,
S1.customer_type_sc, 
S1.customer_type_desc, 
S1.customer_doc_type_sc, 
S1.customer_doc_type_desc, 
S1.gender_ind, 
S1.date_of_birth
FROM '|| TABLA_NOMBRE_TEMP3||'  S1 WHERE S1.CUSTOMER_DOC_TYPE_DESC = ''RUC''
AND NOT EXISTS(SELECT 1 FROM DM.R$_IRIS_CLIENTE_UNICO S2 WHERE S1.ID_CARD_VALUE = S2.ID_CARD_VALUE)';
EXECUTE IMMEDIATE (STR);
COMMIT;

STR:='TABLA: *** DM.R$_IRIS_CLIENTE_UNICO *** ISO INSERT  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

-----------------------------------------------------------------------------------------------------------
STR:='INICIA EL INSERT A LA TABLA: DM.R$_IRIS_CLIENTE_UNICO *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='INSERT /*+ APPEND */ INTO DM.R$_IRIS_CLIENTE_UNICO
(id_card_value, 
full_name, 
GIVEN_NAME,
LAST_NAME,
customer_type_sc, 
customer_type_desc, 
customer_doc_type_sc, 
customer_doc_type_desc, 
gender_ind, 
date_of_birth)
SELECT /*+ PARALLEL 3 */ DISTINCT 
S1.ID_CARD_VALUE,
NVL(S1.FULL_NAME,S1.RAZON_SOCIAL) AS FULL_NAME,
GIVEN_NAME,
LAST_NAME,
S1.customer_type_sc, 
S1.customer_type_desc, 
S1.customer_doc_type_sc, 
S1.customer_doc_type_desc, 
S1.gender_ind, 
S1.date_of_birth
FROM '|| TABLA_NOMBRE_TEMP3||'  S1 WHERE S1.CUSTOMER_DOC_TYPE_DESC = ''CARNÉ DE EXTRANJERÍA''
AND NOT EXISTS(SELECT 1 FROM DM.R$_IRIS_CLIENTE_UNICO S2 WHERE S1.ID_CARD_VALUE = S2.ID_CARD_VALUE)';
EXECUTE IMMEDIATE (STR);
COMMIT;

STR:='TABLA: *** DM.R$_IRIS_CLIENTE_UNICO *** ISO INSERT  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);
----------------------------------------------------------------------------------------------------------------------
STR:='INICIA EL INSERT A LA TABLA: DM.R$_IRIS_CLIENTE_UNICO *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='INSERT /*+ APPEND */ INTO DM.R$_IRIS_CLIENTE_UNICO
(id_card_value, 
full_name, 
GIVEN_NAME,
LAST_NAME,
customer_type_sc, 
customer_type_desc, 
customer_doc_type_sc, 
customer_doc_type_desc, 
gender_ind, 
date_of_birth)
SELECT /*+ PARALLEL 3 */ 
DISTINCT 
S1.ID_CARD_VALUE,
NVL(S1.FULL_NAME,S1.RAZON_SOCIAL) AS FULL_NAME,
GIVEN_NAME,
LAST_NAME,
S1.customer_type_sc, 
S1.customer_type_desc, 
S1.customer_doc_type_sc, 
S1.customer_doc_type_desc, 
S1.gender_ind, 
S1.date_of_birth
FROM '|| TABLA_NOMBRE_TEMP3||' S1 WHERE S1.CUSTOMER_DOC_TYPE_DESC = ''PASAPORTE''
AND NOT EXISTS(SELECT 1 FROM DM.R$_IRIS_CLIENTE_UNICO S2 WHERE S1.ID_CARD_VALUE = S2.ID_CARD_VALUE)';
EXECUTE IMMEDIATE (STR);
COMMIT;


STR:='TABLA: *** DM.R$_IRIS_CLIENTE_UNICO *** ISO INSERT  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);
-------------------------------------------------------------------------------------------------------------------------

STR:='INICIA EL INSERT A LA TABLA: DM.R$_IRIS_CLIENTE_UNICO *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='INSERT /*+ APPEND */ INTO DM.R$_IRIS_CLIENTE_UNICO
(id_card_value, 
full_name, 
GIVEN_NAME,
LAST_NAME,
customer_type_sc, 
customer_type_desc, 
customer_doc_type_sc, 
customer_doc_type_desc, 
gender_ind, 
date_of_birth)
SELECT /*+ PARALLEL 3 */ DISTINCT 
S1.ID_CARD_VALUE,
NVL(S1.FULL_NAME,S1.RAZON_SOCIAL) AS FULL_NAME,
GIVEN_NAME,
LAST_NAME,
S1.customer_type_sc, 
S1.customer_type_desc, 
S1.customer_doc_type_sc, 
S1.customer_doc_type_desc, 
S1.gender_ind, 
S1.date_of_birth
FROM '|| TABLA_NOMBRE_TEMP3||' S1 
WHERE NOT EXISTS(SELECT 1 FROM DM.R$_IRIS_CLIENTE_UNICO S2 WHERE S1.ID_CARD_VALUE = S2.ID_CARD_VALUE)
AND S1.CUSTOMER_DOC_TYPE_DESC IS NOT NULL';
EXECUTE IMMEDIATE (STR);
COMMIT;

STR:='TABLA: *** DM.R$_IRIS_CLIENTE_UNICO *** ISO INSERT  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);
--------------------------------------------------------------------------------------------------------------------

STR:='INICIA CREACION DE LA TABLA: ' || TABLA_NOMBRE_TEMP4 || ' *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='CREATE TABLE ' || TABLA_NOMBRE_TEMP4 || ' NOLOGGING TABLESPACE DWO_DATA PARALLEL 3 AS
SELECT * FROM (
SELECT LPAD(S1.TELEFONO,11,''51'') AS NRO_TELEFONO,
S1.*,ROW_NUMBER() OVER(PARTITION BY S1.TELEFONO ORDER BY (S1.FECHAACTIVACION) DESC) AS RK
FROM DWS.SA_EAI_CONTRATO_DOL_HIST S1 )';

EXECUTE IMMEDIATE (STR);

STR:='TABLA: *** '|| USER || '.'|| TABLA_NOMBRE_TEMP4||' *** FUE CREADA  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

---------------------------------------------------------------------------------------------------------

STR:='INICIA CREACION DE LA TABLA: ' || TABLA_NOMBRE_TEMP5 || ' *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='CREATE TABLE ' || TABLA_NOMBRE_TEMP5 || ' NOLOGGING TABLESPACE DWO_DATA PARALLEL 3 AS
SELECT * FROM '|| TABLA_NOMBRE_TEMP4||' S1 WHERE RK = 1';

EXECUTE IMMEDIATE (STR);

STR:='TABLA: *** '|| USER || '.'|| TABLA_NOMBRE_TEMP5||' *** FUE CREADA  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

---------------------------------------------------------------------------------------------------------

STR:='INICIA CREACION DE LA TABLA: ' || TABLA_NOMBRE_TEMP6 || ' *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='CREATE TABLE '|| TABLA_NOMBRE_TEMP6||' NOLOGGING COMPRESS PARALLEL 3 TABLESPACE DWO_DATA AS 
SELECT S1.NRO_TELEFONO,
       S1.PLAN_COMERCIAL, --PLAN_COMERCIAL,    
       S22.DESCDEPARTAMENTO AS DEPARTAMENTO_ACTIVACION,        
       S21.MARCA AS MARCA, --
       S21.MODELO, ---     
       -----------SEC-----------------
       CASE WHEN S1.EQUIPO_SERIE IS NOT NULL AND S1.CHIP_SERIE IS NOT NULL THEN ''P''
            WHEN S1.EQUIPO_SERIE IS NOT NULL AND S1.CHIP_SERIE IS NULL THEN ''E''
            WHEN S1.EQUIPO_SERIE IS NULL AND S1.CHIP_SERIE IS NOT NULL THEN ''C''
       END AS TIPO_VENTA_CHIP_PACK, --
       S1.PDV_DEPARTAMENTO AS DEPARTAMENTO_PTOVENTA --
FROM dwa.ica_ic_movil_det PARTITION(p_'||FECHA||') s1  
LEFT JOIN DWA.RTM_EQUIPOS_ICA S21 ON(S1.EQUIPO_CODIGO  = S21.EQUIPO)
LEFT JOIN '|| TABLA_NOMBRE_TEMP0 ||' S23 ON(S1.NRO_TELEFONO = S23.MSISDN)
LEFT JOIN DM.DW_SUS_D_DEPARTAMENTO S22 ON(S23.IDDEPARTAMENTO = S22.IDDEPARTAMENTO)
LEFT JOIN DM.DW_SUS_D_SEGMENTO S24 ON(S23.IDSEGMENTO = S24.IDSEGMENTO)
LEFT JOIN '|| TABLA_NOMBRE_TEMP ||' S25 ON( S1.EQUIPO_CODIGO = S25.MATNR)
WHERE S1.TIPO_OPERACION IN(''ACTIVACIÓN'',''ACTIVACION PORT IN'')
AND S1.MODALIDAD_CONTRACTUAL  =''PREPAGO'' 
AND S1.EQUIPO_SERIE IS NOT NULL';

EXECUTE IMMEDIATE (STR);

STR:='TABLA: *** '|| USER || '.'|| TABLA_NOMBRE_TEMP6 ||' *** FUE CREADA  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

------------------------------------------------------------------------------------------------------------------

STR:='INICIA CREACION DE LA TABLA: ' || TABLA_NOMBRE_TEMP7 || ' *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='CREATE TABLE '|| TABLA_NOMBRE_TEMP7 ||' NOLOGGING TABLESPACE DWO_DATA COMPRESS PARALLEL 3 AS
	SELECT TRIM(S1.X_DOC_NUM) AS NRO_DOCUMENTO,
       S1.UPDATE_STAMP,
       S1.E_MAIL AS CORREO_ELECTRONICO,
       ''51''|| S1.PHONE AS NRO_TELEFONO,
       (TRIM(S1.S_FIRST_NAME)) AS NOMBRES,
       (TRIM(S1.S_LAST_NAME)) AS APELLIDO_PATERNO,       
       UPPER(S1.X_DOC_TYPE) AS TIPO_DOCUMENTO,
       S1.X_BIRTHDAY AS FECHA_NACIMIENTO,
       ROW_NUMBER() OVER(PARTITION BY TRIM(S1.X_DOC_NUM) ORDER BY S1.UPDATE_STAMP DESC) AS RK
FROM DWS.SA_TABLE_CONTACT S1 WHERE S1.E_MAIL IS NOT NULL'; 

EXECUTE IMMEDIATE (STR);

STR:='TABLA: *** '|| USER || '.'|| TABLA_NOMBRE_TEMP7 ||' *** FUE CREADA  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

------------------------------------------------------------------------------------------------------------------
STR:='INICIA CREACION DE LA TABLA: ' || TABLA_NOMBRE_TEMP8 || ' *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='CREATE TABLE ' || TABLA_NOMBRE_TEMP8 || ' NOLOGGING TABLESPACE DWO_DATA COMPRESS PARALLEL 3 AS
SELECT * FROM ' || TABLA_NOMBRE_TEMP7 || ' WHERE RK = 1';

EXECUTE IMMEDIATE (STR);

STR:='TABLA: *** '|| USER || '.'|| TABLA_NOMBRE_TEMP8 ||' *** FUE CREADA  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);
------------------------------------------------------------------------------------------------------------------


STR:='INICIA CREACION DE LA TABLA: ' || TABLA_NOMBRE_TEMP9 || ' *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='CREATE TABLE ' || TABLA_NOMBRE_TEMP9 || ' NOLOGGING TABLESPACE DWO_DATA COMPRESS PARALLEL 3 AS
SELECT S1.ID_CARD_VALUE,
       S1.CUST_DOC_TYPE_DESC,
       S1.CUST_LEGAL_ENTITY_NAME,
       S1.PRODUCT_NUMBER,
       S1.PRODUCT_STATUS,
       S1.AGREEMENT_MODE,
       S1.PROD_OFFER_NAME AS TIPO_PLAN
FROM DWA.F_M_PRODUCT S1 WHERE S1.AGREEMENT_MODE = ''PREPAGO''
AND S1.GROUP_SERVICE = ''MOVIL'' AND S1.PRODUCT_STATUS NOT IN (''D'',''P'')';/*SE EXCLUYE PREACTIVOS Y DESACTIVOS*/

EXECUTE IMMEDIATE (STR);

STR:='TABLA: *** '|| USER || '.'|| TABLA_NOMBRE_TEMP9 ||' *** FUE CREADA  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

------------------------------------------------------------------------------------------------------------------

STR:='INICIA CREACION DE LA TABLA: ' || TABLA_NOMBRE_TEMP10 || ' *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);

STR:='CREATE TABLE ' || TABLA_NOMBRE_TEMP10 || ' NOLOGGING TABLESPACE WORKAREA_RECO COMPRESS PARALLEL 3 AS
SELECT S1.PRODUCT_NUMBER AS NRO_LINEA,
       S1.AGREEMENT_MODE AS MODALIDAD_CONTRACTUAL,
       TO_CHAR(NVL(S2.FECHAACTIVACION,S2.FECHAENVIO),''DD/MM/YYYY HH24:MI:SS'') AS FECHA_DOL, --CAMBIAR FORMATO DE FECHA
       S1.ID_CARD_VALUE AS DOCUMENTO,       
       S1.CUST_DOC_TYPE_DESC AS TIPO_DOCUMENTO,  
	   REPLACE(REPLACE(REPLACE(S4.GIVEN_NAME,CHR(10),''''),CHR(13),''''),''|'','''') AS NOMBRES,
	   REPLACE(REPLACE(REPLACE(S4.LAST_NAME,CHR(10),''''),CHR(13),''''),''|'','''') AS APELLIDOS,
       S4.DATE_OF_BIRTH AS FECHA_NACIMIENTO, 
	   REPLACE(REPLACE(REPLACE(S4.GENDER_IND,CHR(10),''''),CHR(13),''''),''|'','''') AS SEXO,
	   REPLACE(REPLACE(REPLACE(S3.CORREO_ELECTRONICO,CHR(10),''''),CHR(13),''''),''|'','''') AS EMAIL,
       S5.TIPO_VENTA_CHIP_PACK,
       S5.MARCA AS MARCA_EQUIP_VENTA,
       S5.MODELO AS MODELO_EQUIP_VENTA,
       S5.DEPARTAMENTO_PTOVENTA   AS DEPART_VENTA,
       S5.DEPARTAMENTO_ACTIVACION AS DEPART_ACTIVACION,
       S1.TIPO_PLAN,
       CASE WHEN S1.PRODUCT_STATUS = ''A'' THEN ''ACTIVO''
            WHEN S1.PRODUCT_STATUS = ''G'' THEN ''GRACE''
            WHEN S1.PRODUCT_STATUS = ''R'' THEN ''RECYCLE''
         ELSE S1.PRODUCT_STATUS
       END AS ESTADO_IN6
FROM T$_F_PRODUCT_MOV_PRE S1
LEFT JOIN ' || TABLA_NOMBRE_TEMP5 || ' S2 ON(S1.PRODUCT_NUMBER = S2.NRO_TELEFONO)
LEFT JOIN ' || TABLA_NOMBRE_TEMP8 || ' S3 ON(S1.ID_CARD_VALUE = S3.NRO_DOCUMENTO)
LEFT JOIN DM.R$_IRIS_CLIENTE_UNICO S4 ON(S1.ID_CARD_VALUE = S4.ID_CARD_VALUE)
LEFT JOIN ' || TABLA_NOMBRE_TEMP6 || ' S5 ON(S1.PRODUCT_NUMBER =S5.NRO_TELEFONO)';

EXECUTE IMMEDIATE (STR);

STR:='TABLA: *** '|| USER || '.' || TABLA_NOMBRE_TEMP10 || ' *** FUE CREADA  *** ' || TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS');
DBMS_OUTPUT.PUT_LINE(STR);


------------------------------------------------------------------------------------------------------------------
END;
/

   
