--ELIMINAR TABLA DE DETALLECANJE

ALTER TABLE PCLUB.ADMPT_CANJE_DETALLEFIJA
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_CANJE_DETALLEFIJA CASCADE CONSTRAINTS;

--ELIMINAR TABLA DE RELACION KARDEX CANJE

DROP TABLE PCLUB.ADMPT_CANJEDT_KARDEXFIJA CASCADE CONSTRAINTS;

--ELIMINAR TABLA CANJEFIJA

ALTER TABLE PCLUB.ADMPT_CANJEFIJA
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_CANJEFIJA CASCADE CONSTRAINTS;

--ELIMINAR TABLA KARDEXFIJA

DROP TABLE PCLUB.ADMPT_KARDEXFIJA CASCADE CONSTRAINTS;

--ELIMINACION DE LA TABLA SALDOSFIJA

DROP TABLE PCLUB.ADMPT_SALDOS_CLIENTEFIJA CASCADE CONSTRAINTS;

--ELIMINACION DE LA TABLA CLIENTE´RODUCTO

ALTER TABLE PCLUB.ADMPT_CLIENTEPRODUCTO
DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_CLIENTEPRODUCTO CASCADE CONSTRAINTS;

--eliminacion de la tabla para clientes de tipo fija
ALTER TABLE PCLUB.ADMPT_CLIENTEFIJA
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_CLIENTEFIJA CASCADE CONSTRAINTS;

--ELIMINACION COLUMNA AGREGADA de la tabla tipo_doc para agregar el campo 

ALTER TABLE PCLUB.ADMPT_TIPO_DOC
DROP COLUMN ADMPV_EQU_FIJA;

--ELIMINACION DE LA TABLA TIPO SERVICIO

ALTER TABLE PCLUB.ADMPT_TIPOSERV_DTH_HFC
DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_TIPOSERV_DTH_HFC CASCADE CONSTRAINTS;

--eliminacion de la tabla que registra los parametros enviados desde SGA

DROP TABLE PCLUB.ADMPT_IMP_PREMODIF_CLIENTE CASCADE CONSTRAINTS;

--ELIMINAR COLUIMNAS TABLA CONCEPTO
ALTER TABLE PCLUB.ADMPT_CONCEPTO
DROP COLUMN ADMPV_TPO_CPTO;

ALTER TABLE PCLUB.ADMPT_CONCEPTO
DROP COLUMN ADMPC_TPO_OPER;

--MODIFICAR LA TABLA PREMIO 
ALTER TABLE PCLUB.ADMPT_PREMIO
DROP COLUMN ADMPV_COD_SERVTV;

--ELIMINAR TABLA TMP DE FACTURACION

DROP TABLE PCLUB.ADMPT_TMP_PAGO_HFC CASCADE CONSTRAINTS;

--ELIMINAR LA TABLA AUX DE FACTURA

DROP TABLE PCLUB.ADMPT_AUX_PAGO_HFC CASCADE CONSTRAINTS;

--ELIMINAR TABLA IMP DE FACTURA

ALTER TABLE PCLUB.ADMPT_IMP_PAGO_HFC
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_IMP_PAGO_HFC CASCADE CONSTRAINTS;

--ELIMINAR TABLA TMP PARA P´ROMOCION

DROP TABLE PCLUB.ADMPT_TMP_PROM_DTH_HFC CASCADE CONSTRAINTS;

--ELIMINAR TABLA AUX PARA PROMOCION

DROP TABLE PCLUB.ADMPT_AUX_PROM_DTH_HFC CASCADE CONSTRAINTS;

--ELIMINAR TABLA IMP PARA PROMOCION

ALTER TABLE PCLUB.ADMPT_IMP_PROM_DTH_HFC
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_IMP_PROM_DTH_HFC CASCADE CONSTRAINTS;

--ELIMINAR TABLA TMP PARA REGULARIZACION

DROP TABLE PCLUB.ADMPT_TMP_REGDTH_HFC CASCADE CONSTRAINTS;

--ELIMINAR TABLA AUX PARA REGULARIZACION

DROP TABLE PCLUB.ADMPT_AUX_REGDTH_HFC CASCADE CONSTRAINTS;

--ELIMINAR TABLA IMP PARA REGULARIZACION

ALTER TABLE PCLUB.ADMPT_IMP_REGDTH_HFC
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_IMP_REGDTH_HFC CASCADE CONSTRAINTS;

--ELIMINAR TABLA TMP DE CAMBIO DE TITULAR

DROP TABLE PCLUB.ADMPT_TMP_CAMBTIT_HFC CASCADE CONSTRAINTS;

--ELIMINAR TABLA AUX DE CAMBIO DE TITULAR

DROP TABLE PCLUB.ADMPT_AUX_CAMBTIT_HFC CASCADE CONSTRAINTS;

--ELIMINAR TABLA IMP DE CAMBIO DE TITULAR

DROP TABLE PCLUB.ADMPT_IMP_CAMBTIT_HFC CASCADE CONSTRAINTS;

--ELIMINAR TABLA TMP DE MIGRACION

DROP TABLE PCLUB.ADMPT_TMP_ALTACLI_HFC CASCADE CONSTRAINTS;

--ELIMINAR TABLA AUX DE MIGRACION

DROP TABLE PCLUB.ADMPT_AUX_ALTACLI_HFC CASCADE CONSTRAINTS;

--ELIMINAR TABLA IMP DE MIGRACION

DROP TABLE PCLUB.ADMPT_IMP_ALTACLI_HFC CASCADE CONSTRAINTS;


--ELIMINAR TABLA 

DROP TABLE PCLUB.ADMPT_TIPOS CASCADE CONSTRAINTS;

