LOAD DATA
append into table PCLUB.ADMPT_TMP_ANIVERSDTH
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY ';'
TRAILING NULLCOLS
(
ADMPV_COD_CLI_PROD CHAR,
ADMPV_CUST_ID CHAR,
ADMPD_COD_SERV CHAR,
ADMPV_TIPO_DOC CHAR,
ADMPV_NUM_DOC CHAR,
ADMPD_FEC_OPER DATE "YYYYMMDD",
ADMPV_NOM_ARCH CHAR,
ADMPV_MSJE_ERROR CHAR,
ADMPN_SEQ SEQUENCE(COUNT,1)
)


 