LOAD DATA
append into table PCLUB.ADMPT_TMP_CAMBTIT_DTH
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY ';' 
TRAILING NULLCOLS
(
ADMPV_COD_CLI_PROD   CHAR,
ADMPV_NUM_DOC		 CHAR,
ADMPV_NOM_ARCH		 CHAR,
ADMPD_FEC_OPER	     DATE "YYYYMMDD"
)
