
CREATE OR REPLACE TRIGGER PCLUB.T_CANJE_DETALLEFIJA
BEFORE UPDATE ON PCLUB.ADMPT_CANJE_DETALLEFIJA REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.ADMPD_FEC_MOD := SYSDATE;
END T_CANJE_DETALLEFIJA;
/