CREATE OR REPLACE TRIGGER FIDELIDAD.T_INS_PROGPROMCLIENTE
BEFORE INSERT ON FIDELIDAD.SFYRT_PROGPROMCLIENTE REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.PPCLD_FECREG := SYSDATE;
:NEW.PPCLD_FECTRX := TRUNC(SYSDATE);
END T_INS_PROGPROMCLIENTE;
/