CREATE OR REPLACE TRIGGER PCLUB.T_INS_FEC_TMPCUPONERA
BEFORE INSERT ON PCLUB.ADMPT_TMP_CUPONERA REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
WHEN (
new.ADMPD_FEC_PROC  IS NULL
      )
BEGIN
  SELECT SYSDATE
  INTO   :new.ADMPD_FEC_PROC
  FROM   dual;
END;
/
