CREATE OR REPLACE TRIGGER FIDELIDAD.T_INS_PROGPROMLOTE
BEFORE INSERT ON FIDELIDAD.SFYRT_PROGPROMLOTE REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.PPLTD_FECREG := SYSDATE;
END T_INS_PROGPROMLOTE;
/