
CREATE OR REPLACE TRIGGER PCLUB.T_INS_CANJE_DETALLEFIJA
BEFORE INSERT ON PCLUB.ADMPT_CANJE_DETALLEFIJA REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.ADMPD_FEC_REG := SYSDATE;
END T_INS_CANJE_DETALLEFIJA;
/