CREATE OR REPLACE TRIGGER FIDELIDAD.T_INS_PROMOCIONSERVICIO
BEFORE INSERT ON FIDELIDAD.SFYRT_PROMOCIONSERVICIO REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.PROSD_FECREG := SYSDATE;
END T_INS_PROMOCIONSERVICIO;
/