CREATE OR REPLACE TRIGGER fidelidad.T_UPD_MSG_ENVIOSMS
BEFORE UPDATE ON fidelidad.CPRET_MSG_ENVIOSMS REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.CPRED_FECHAMOD := SYSDATE;
END T_UPD_MSG_ENVIOSMS;
/