CREATE OR REPLACE TRIGGER FIDELIDAD.T_UPD_PROMOCIONCAB
BEFORE UPDATE ON FIDELIDAD.SFYRT_PROMOCIONCAB REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.PROMD_FECMOD := SYSDATE;
END T_UPD_PROMOCIONCAB;
/