CREATE OR REPLACE TRIGGER PCLUB.T_UPD_CABENCUESTA
BEFORE UPDATE ON PCLUB.ADMPT_CABENCUESTA REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.ADMPD_FEC_MOD := SYSDATE;
END T_UPD_CABENCUESTA;
/