CREATE OR REPLACE TRIGGER FIDELIDAD.T_UPD_PROMOCIONSERVICIO
BEFORE UPDATE ON FIDELIDAD.SFYRT_PROMOCIONSERVICIO REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.PROSD_FECMOD := SYSDATE;
END T_UPD_PROMOCIONSERVICIO;
/