CREATE OR REPLACE TRIGGER PCLUB.T_UPD_MOVENCUESTA
BEFORE UPDATE ON PCLUB.ADMPT_MOVENCUESTA REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.ADMPD_FEC_MOD := SYSDATE;
END T_UPD_MOVENCUESTA;
/