CREATE OR REPLACE TRIGGER PCLUB.CLUBTRU_ADMPT_PARAM
BEFORE UPDATE ON PCLUB.T_ADMPT_PARAM REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.PARD_FEC_MOD := SYSDATE;
:NEW.PARV_USU_MOD := USER;
END CLUBTRU_ADMPT_PARAM;
/