create or replace package body PCLUB.PKG_CC_TRANFERENCIA is

PROCEDURE ADMPSS_CREA_TRASNFERENCIA
(
  K_TIPO_DOC      IN  VARCHAR2,
  K_NUM_DOC       IN  VARCHAR2,
  K_BOLSA         IN  VARCHAR2,
  K_TIPO          IN  VARCHAR2,
  K_PUNTOS        IN  NUMBER,
  K_PTO_VENTA     IN  VARCHAR2,
  K_ASESOR        IN  VARCHAR2,
  K_NOTAS         IN  VARCHAR2,
  K_ORIGEN        IN  VARCHAR2,
  K_ID_TRANSCLARO OUT NUMBER,
  K_VALOR         OUT VARCHAR2,
  K_MSJERROR      OUT VARCHAR2
)
AS

V_PUNTOS_CONVERTIDOS NUMBER:= K_PUNTOS;
V_CONS_CONVERSION    NUMBER;

BEGIN

  /*IF K_TIPO = 'I' THEN

    SELECT
      TO_NUMBER(TP.ADMPV_VALOR,'99.99') INTO V_CONS_CONVERSION
    FROM
      ADMPT_PARAMSIST TP
    WHERE
      TP.ADMPV_DESC = 'UNIDAD_CONVERSION_BONO_A_CC';

    V_PUNTOS_CONVERTIDOS := V_CONS_CONVERSION * K_PUNTOS;

  END IF;*/

  INSERT INTO ADMPT_TRANSFERENCIA
  (
    ADMPV_TIPO_DOC,
    ADMPV_NUM_DOC,
    ADMPV_BOLSA,
    ADMPV_TIPO,
    ADMPN_PUNTOS,
    ADMPV_PTO_VENTA,
    ADMPV_ASESOR,
    ADMPV_ESTADO,
    ADMPD_FECHA,
    ADMPV_NOTAS,
    ADMPV_ORIGEN
  )
  VALUES
  (
    K_TIPO_DOC,
    K_NUM_DOC,
    K_BOLSA,
    K_TIPO,
    V_PUNTOS_CONVERTIDOS,
    K_PTO_VENTA,
    K_ASESOR,
    'CREADO',
    SYSDATE,
    K_NOTAS,
    K_ORIGEN
  ) RETURNING ADMPN_ID_TRANSCLARO INTO K_ID_TRANSCLARO;

  K_VALOR := '0';
  K_MSJERROR := '';

  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    K_VALOR := '';
    K_MSJERROR := to_char(SQLCODE) || '-' || SUBSTR(SQLERRM,1,400);

END ADMPSS_CREA_TRASNFERENCIA;

PROCEDURE ADMPSS_TRASNFIERE_PTOS
(
  K_ID_TRANSCLARO  IN  NUMBER,
  K_ID_TRANSBONUS  IN  VARCHAR2,
  K_TIPO_DOC       IN  VARCHAR2,
  K_NUM_DOC        IN  VARCHAR2,
  K_BOLSA          IN  VARCHAR2,
  K_TIPO           IN  VARCHAR2,
  K_PUNTOS         IN  NUMBER,
  K_RESP_LOYALTY   IN  VARCHAR2,
  K_VALOR          OUT VARCHAR2,
  K_MSJERROR       OUT VARCHAR2
)
AS

  --VARIABLES
  V_COD_CPTO           NUMBER;
  V_ID_KARDEX          NUMBER;
  V_PUNTOS_REQUERIDOS  NUMBER := K_PUNTOS;
  V_PUNTOS_TRANS_CLI   NUMBER :=0;
  V_COD_CLIENTE        VARCHAR2(40);
  V_COD_CLIENTE_IB     VARCHAR2(40);
  V_SALDO              NUMBER;
  V_CONS_CONVERSION    NUMBER;
  V_ORIGEN             VARCHAR2(40);

  -- EXEPCIONES
  NO_CLIENTE            EXCEPTION;
  NO_SALDO              EXCEPTION;
  NO_PARAMETROS         EXCEPTION;
  NO_BUSQ_CLIENTE       EXCEPTION;
  NO_SALDO_INSUFICIENTE EXCEPTION;
  NO_ERROR_PARAM_BOLSA  EXCEPTION;
  NO_ERROR_PARAM_TIPO   EXCEPTION;

  -- EXEPCIONES NO_PARAM
  NO_PARAM_IDTRANSCLARO EXCEPTION;
  NO_PARAM_TIPODOC      EXCEPTION;
  NO_PARAM_NUMDOC       EXCEPTION;
  NO_PARAM_BOLSA        EXCEPTION;
  NO_PARAM_TIPO         EXCEPTION;
  NO_PARAM_PUNTOS       EXCEPTION;

  TYPE r_Kardex IS RECORD (
       ID_KARDEX  NUMBER,
       COD_CLI_IB NUMBER,
       COD_CLI    VARCHAR2(40),
       SLD_PUNTO  NUMBER,
       TPO_PUNTO  CHAR(1),
       ANT_COD_CLI VARCHAR2(40)
       );

  TYPE t_Kardex  IS TABLE OF r_Kardex;
  V_TABLEKARDEX t_Kardex;

BEGIN

  -- INICIO VALIDACIONES

  IF K_ID_TRANSCLARO IS NULL OR K_ID_TRANSCLARO = 0 THEN
     RAISE NO_PARAM_IDTRANSCLARO;
  END IF;

  IF K_TIPO_DOC IS NULL OR K_TIPO_DOC = '' THEN
     RAISE NO_PARAM_TIPODOC;
  END IF;

  IF K_NUM_DOC IS NULL OR K_NUM_DOC = '' THEN
     RAISE NO_PARAM_NUMDOC;
  END IF;

  IF K_BOLSA IS NULL OR K_BOLSA = '' THEN
     RAISE NO_PARAM_BOLSA;
  END IF;

  IF  K_BOLSA <> 'POSTPAGO' AND K_BOLSA <> 'PREPAGO' THEN
     RAISE NO_ERROR_PARAM_BOLSA;
  END IF;

  IF K_TIPO IS NULL OR K_TIPO = '' THEN
     RAISE NO_PARAM_TIPO;
  END IF;

  IF K_TIPO <> 'I' AND K_TIPO <> 'S' THEN
     RAISE NO_ERROR_PARAM_TIPO;
  END IF;

  IF K_PUNTOS IS NULL OR K_PUNTOS = 0 THEN
     RAISE NO_PARAM_PUNTOS;
  END IF;

  ADMPSI_ES_CLIENTE(K_TIPO_DOC,K_NUM_DOC,K_BOLSA,V_COD_CLIENTE,V_COD_CLIENTE_IB,V_SALDO,K_VALOR,K_MSJERROR);

  IF (K_VALOR <> '0' OR K_VALOR IS NULL) AND (K_MSJERROR <> '' OR K_MSJERROR IS NOT NULL)THEN
     RAISE NO_BUSQ_CLIENTE;
  END IF;

  IF V_COD_CLIENTE IS NULL THEN
     RAISE NO_CLIENTE;
  END IF;

  -- FIN VALIDACIONES

  -- INGRESO DE PUNTOS DE BONUS A CLARO
  IF K_TIPO = 'I' THEN

SELECT
      TO_NUMBER(TP.ADMPV_VALOR,'99.99') INTO V_CONS_CONVERSION
    FROM
      ADMPT_PARAMSIST TP
    WHERE
      TP.ADMPV_DESC = 'UNIDAD_CONVERSION_BONO_A_CC';

    V_PUNTOS_REQUERIDOS := V_CONS_CONVERSION * K_PUNTOS;

    SELECT NVL(ADMPV_COD_CPTO,0) INTO V_COD_CPTO FROM PCLUB.ADMPT_CONCEPTO WHERE ADMPV_DESC = 'TRANSFERENCIA BONUS A CLARO';

    SELECT NVL(PCLUB.ADMPT_KARDEX_SQ.NEXTVAL,0) INTO V_ID_KARDEX FROM DUAL;

    IF V_COD_CPTO <> 0 AND V_ID_KARDEX <> 0 THEN

      -- INSERTA EL MOVIMIENTO EN LA TABLA KARDEX
      INSERT INTO ADMPT_KARDEX
      (
        ADMPN_ID_KARDEX,
        ADMPN_COD_CLI_IB,
        ADMPV_COD_CLI,
        ADMPV_COD_CPTO,
        ADMPD_FEC_TRANS,
        ADMPN_PUNTOS,
        ADMPV_NOM_ARCH,
        ADMPC_TPO_OPER,
        ADMPC_TPO_PUNTO,
        ADMPN_SLD_PUNTO,
        ADMPC_ESTADO
      )
      VALUES
      (
        V_ID_KARDEX,
        V_COD_CLIENTE_IB,
        V_COD_CLIENTE,
        V_COD_CPTO,
        TO_DATE(TO_CHAR(SYSDATE, 'DD/MM/YYYY'), 'DD/MM/YYYY'),
        V_PUNTOS_REQUERIDOS,
        '',
        'E',
        'C',
        V_PUNTOS_REQUERIDOS,
        'A' -- CONSULTAR SOBRE EL TIPO DE OPERACION
      );

      -- ACTUALIZA SALDOS_CLIENTE
      UPDATE
        ADMPT_SALDOS_CLIENTE
      SET
        ADMPN_SALDO_CC =  V_PUNTOS_REQUERIDOS + (SELECT NVL(ADMPN_SALDO_CC, 0) FROM PCLUB.ADMPT_SALDOS_CLIENTE WHERE ADMPV_COD_CLI = V_COD_CLIENTE)
      WHERE
        ADMPV_COD_CLI = V_COD_CLIENTE;

      -- INSERTA EL MOVIMIENTO EN LA TABLA KARDEX_TRANS
      INSERT INTO ADMPT_TRANS_KARDEX
      (
        ADMPN_ID_TRANSCLARO,
        ADMPN_ID_KARDEX,
        ADMPN_PUNTOS,
        ADMPV_TPO_KARDEX,
        ADMPN_FECHA
      )
      VALUES
      (
        K_ID_TRANSCLARO,
        V_ID_KARDEX,
        V_PUNTOS_REQUERIDOS,
        'E',
        SYSDATE
      );

      -- ACTUALIZA LA TABLA TRANSFERENCIA
      UPDATE
        ADMPT_TRANSFERENCIA
      SET
        ADMPV_ID_TRANSBONUS = K_ID_TRANSBONUS,
        ADMPV_ESTADO        = 'REALIZADA',
        ADMPV_RESP_LOYALTY  = K_RESP_LOYALTY
      WHERE
        ADMPN_ID_TRANSCLARO = K_ID_TRANSCLARO;

    END IF;

    K_VALOR := '0';
    K_MSJERROR := '';
    COMMIT;

  -- SALIDA DE PUNTOS DE CLARO A BONUS
  ELSIF K_TIPO = 'S' THEN

    -- VALIDA SI SUFICIENTE SALDO
    IF V_SALDO = 0 THEN
       RAISE NO_SALDO;
    END IF;

    IF K_PUNTOS > V_SALDO THEN
       RAISE NO_SALDO_INSUFICIENTE;
    END IF;

    -- DESCUENTO DE PUNTOS DE LOS ANTERIOES KARDEX DE ENTRADA
    SELECT
      /*+ index(CL IDX_TDOC_NDOC)*/
      KA.ADMPN_ID_KARDEX,
      KA.ADMPN_COD_CLI_IB,
      KA.ADMPV_COD_CLI,
      KA.ADMPN_SLD_PUNTO,
      KA.ADMPC_TPO_PUNTO,
      LEAD(KA.ADMPV_COD_CLI) OVER(ORDER BY
      DECODE(KA.ADMPC_TPO_PUNTO, 'I', 1, 'L', 2, 'C', 3),  CL.ADMPD_FEC_ACTIV, KA.ADMPV_COD_CLI, KA.ADMPN_ID_KARDEX ASC) AS ANT_COD_CLI
    BULK COLLECT INTO
      V_TABLEKARDEX
    FROM
      ADMPT_KARDEX KA
      INNER JOIN ADMPT_CLIENTE CL ON KA.ADMPV_COD_CLI = CL.ADMPV_COD_CLI AND CL.ADMPC_ESTADO = 'A'
    WHERE
      CL.ADMPV_TIPO_DOC = K_TIPO_DOC AND
      CL.ADMPV_NUM_DOC = K_NUM_DOC AND
      KA.ADMPC_ESTADO = 'A' AND
      KA.ADMPC_TPO_OPER = 'E'AND
      ((K_BOLSA = 'POSTPAGO' AND CL.ADMPV_COD_TPOCL IN ('1','2','4')) OR
      ( K_BOLSA  = 'PREPAGO' AND CL.ADMPV_COD_TPOCL = '3' ))
    ORDER BY
      DECODE(KA.ADMPC_TPO_PUNTO, 'I', 1, 'L', 2, 'C', 3),
      CL.ADMPD_FEC_ACTIV,
      KA.ADMPV_COD_CLI,
      KA.ADMPN_ID_KARDEX ASC;

    <<LOOP1>>
    FOR IDX IN V_TABLEKARDEX.FIRST .. V_TABLEKARDEX.LAST  LOOP

      IF V_TABLEKARDEX(IDX).SLD_PUNTO <= V_PUNTOS_REQUERIDOS THEN

        UPDATE
          ADMPT_KARDEX
        SET
          ADMPN_SLD_PUNTO = 0,
          ADMPC_ESTADO = 'C'
        WHERE
          ADMPN_ID_KARDEX = V_TABLEKARDEX(IDX).ID_KARDEX;

        -- ACTUALIZA SALDOS_CLIENTE
        IF V_TABLEKARDEX(IDX).TPO_PUNTO  = 'C' OR V_TABLEKARDEX(IDX).TPO_PUNTO = 'L' THEN

          UPDATE
            ADMPT_SALDOS_CLIENTE
          SET
            ADMPN_SALDO_CC = -V_TABLEKARDEX(IDX).SLD_PUNTO + (SELECT NVL(ADMPN_SALDO_CC, 0) FROM PCLUB.ADMPT_SALDOS_CLIENTE WHERE ADMPV_COD_CLI = V_TABLEKARDEX(IDX).COD_CLI)
          WHERE
            ADMPV_COD_CLI = V_TABLEKARDEX(IDX).COD_CLI;

        ELSIF V_TABLEKARDEX(IDX).TPO_PUNTO = 'I' THEN

          UPDATE
            ADMPT_SALDOS_CLIENTE
          SET
            ADMPN_SALDO_IB = -V_TABLEKARDEX(IDX).SLD_PUNTO + (SELECT NVL(ADMPN_SALDO_IB, 0) FROM PCLUB.ADMPT_SALDOS_CLIENTE WHERE ADMPN_COD_CLI_IB = V_TABLEKARDEX(IDX).COD_CLI_IB)
          WHERE
            ADMPN_COD_CLI_IB = V_TABLEKARDEX(IDX).COD_CLI_IB;

        END IF;

        -- INSERTA EL MOVIMIENTO EN LA TABLA KARDEX_TRANS
        INSERT INTO ADMPT_TRANS_KARDEX
        (
          ADMPN_ID_TRANSCLARO,
          ADMPN_ID_KARDEX,
          ADMPN_PUNTOS,
          ADMPV_TPO_KARDEX,
          ADMPN_FECHA
        )
        VALUES
        (
          K_ID_TRANSCLARO,
          V_TABLEKARDEX(IDX).ID_KARDEX,
          V_TABLEKARDEX(IDX).SLD_PUNTO,
          'D',
          SYSDATE
        );

        V_PUNTOS_TRANS_CLI := V_PUNTOS_TRANS_CLI + V_TABLEKARDEX(IDX).SLD_PUNTO;
        V_PUNTOS_REQUERIDOS := V_PUNTOS_REQUERIDOS - V_TABLEKARDEX(IDX).SLD_PUNTO;

      ELSIF V_TABLEKARDEX(IDX).SLD_PUNTO > V_PUNTOS_REQUERIDOS THEN

        UPDATE
          ADMPT_KARDEX
        SET
          ADMPN_SLD_PUNTO = V_TABLEKARDEX(IDX).SLD_PUNTO - V_PUNTOS_REQUERIDOS
        WHERE
          ADMPN_ID_KARDEX = V_TABLEKARDEX(IDX).ID_KARDEX;

        -- ACTUALIZA SALDOS_CLIENTE
        IF V_TABLEKARDEX(IDX).TPO_PUNTO  = 'C' OR V_TABLEKARDEX(IDX).TPO_PUNTO = 'L' THEN

          UPDATE
            ADMPT_SALDOS_CLIENTE
          SET
            ADMPN_SALDO_CC = -V_PUNTOS_REQUERIDOS + (SELECT NVL(ADMPN_SALDO_CC, 0) FROM PCLUB.ADMPT_SALDOS_CLIENTE WHERE ADMPV_COD_CLI = V_TABLEKARDEX(IDX).COD_CLI)
          WHERE
            ADMPV_COD_CLI = V_TABLEKARDEX(IDX).COD_CLI;

        ELSIF V_TABLEKARDEX(IDX).TPO_PUNTO = 'I' THEN

          UPDATE
            ADMPT_SALDOS_CLIENTE
          SET
            ADMPN_SALDO_IB = -V_PUNTOS_REQUERIDOS + (SELECT NVL(ADMPN_SALDO_IB, 0) FROM PCLUB.ADMPT_SALDOS_CLIENTE WHERE ADMPN_COD_CLI_IB = V_TABLEKARDEX(IDX).COD_CLI_IB)
          WHERE
            ADMPN_COD_CLI_IB = V_TABLEKARDEX(IDX).COD_CLI_IB;

        END IF;

        -- INSERTA EL MOVIMIENTO EN LA TABLA KARDEX_TRANS
        INSERT INTO ADMPT_TRANS_KARDEX
        (
          ADMPN_ID_TRANSCLARO,
          ADMPN_ID_KARDEX,
          ADMPN_PUNTOS,
          ADMPV_TPO_KARDEX,
          ADMPN_FECHA
        )
        VALUES
        (
          K_ID_TRANSCLARO,
          V_TABLEKARDEX(IDX).ID_KARDEX,
          V_PUNTOS_REQUERIDOS,
          'D',
          SYSDATE
        );

        V_PUNTOS_TRANS_CLI:= V_PUNTOS_TRANS_CLI + V_PUNTOS_REQUERIDOS;
        V_PUNTOS_REQUERIDOS := 0;

      END IF;

      IF V_TABLEKARDEX(IDX).ANT_COD_CLI <> V_TABLEKARDEX(IDX).COD_CLI OR V_PUNTOS_REQUERIDOS = 0  THEN

        SELECT NVL(ADMPV_COD_CPTO,0) INTO V_COD_CPTO FROM PCLUB.ADMPT_CONCEPTO WHERE ADMPV_DESC = 'TRANSFERENCIA CLARO A BONUS';

        SELECT NVL(PCLUB.ADMPT_KARDEX_SQ.NEXTVAL,0) INTO V_ID_KARDEX FROM DUAL;

        -- INSERTA EL MOVIMIENTO EN LA TABLA KARDEX
        INSERT INTO ADMPT_KARDEX
        (
          ADMPN_ID_KARDEX,
          ADMPN_COD_CLI_IB,
          ADMPV_COD_CLI,
          ADMPV_COD_CPTO,
          ADMPD_FEC_TRANS,
          ADMPN_PUNTOS,
          ADMPV_NOM_ARCH,
          ADMPC_TPO_OPER,
          ADMPC_TPO_PUNTO,
          ADMPN_SLD_PUNTO,
          ADMPC_ESTADO
        )
        VALUES
        (
          V_ID_KARDEX,
          V_TABLEKARDEX(IDX).COD_CLI_IB,
          V_TABLEKARDEX(IDX).COD_CLI,
          V_COD_CPTO,
          TO_DATE(TO_CHAR(SYSDATE, 'DD/MM/YYYY'), 'DD/MM/YYYY'),
          (-1)*V_PUNTOS_TRANS_CLI,
          '',
          'S',
          'C',
          0,
          'C' -- CONSULTAR SOBRE EL TIPO DE OPERACION
        );

        -- INSERTA EL MOVIMIENTO EN LA TABLA KARDEX_TRANS
        INSERT INTO ADMPT_TRANS_KARDEX
        (
          ADMPN_ID_TRANSCLARO,
          ADMPN_ID_KARDEX,
          ADMPN_PUNTOS,
          ADMPV_TPO_KARDEX,
          ADMPN_FECHA
        )
        VALUES
        (
          K_ID_TRANSCLARO,
          V_ID_KARDEX,
          V_PUNTOS_TRANS_CLI,
          'S',
          SYSDATE
        );

        V_PUNTOS_TRANS_CLI := 0;

      END IF;

      EXIT LOOP1 WHEN  V_PUNTOS_REQUERIDOS = 0;

    END LOOP LOOP1;

    IF V_PUNTOS_REQUERIDOS = 0 THEN

      K_VALOR := '0';
      K_MSJERROR := '';
      COMMIT;

      SELECT ADMPV_ORIGEN INTO V_ORIGEN
      FROM ADMPT_TRANSFERENCIA T
      WHERE ADMPN_ID_TRANSCLARO = K_ID_TRANSCLARO;

      IF TRIM(UPPER(V_ORIGEN)) = 'BONUS' THEN

        UPDATE
          ADMPT_TRANSFERENCIA
        SET
          ADMPV_ID_TRANSBONUS = K_ID_TRANSBONUS,
          ADMPV_ESTADO       = 'REALIZADA',
          ADMPV_RESP_LOYALTY  = K_RESP_LOYALTY
        WHERE
          ADMPN_ID_TRANSCLARO = K_ID_TRANSCLARO;

        COMMIT;

      END IF;

    ELSE

    ROLLBACK;
      K_VALOR := '03';
      K_MSJERROR:='Los puntos descontados no concuerdan con los puntos solicitados.';
      ADMPSI_ACT_TRANS_MSGERROR(K_ID_TRANSCLARO,K_MSJERROR);

    END IF;

  END IF;

EXCEPTION
  WHEN NO_PARAM_IDTRANSCLARO THEN
    K_VALOR:='98';
    K_MSJERROR:='El parámetro ID_TRANSCLARO es obligatorio para realizar la transferencia.';
  WHEN NO_PARAM_TIPODOC THEN
    K_VALOR:='98';
    K_MSJERROR:='El parámetro TIPO_DOC es obligatorio para realizar la transferencia.';
  WHEN NO_PARAM_NUMDOC THEN
    K_VALOR:='98';
    K_MSJERROR:='El parámetro NUM_DOC es obligatorio para realizar la transferencia.';
  WHEN NO_PARAM_BOLSA THEN
    K_VALOR:='98';
    K_MSJERROR:='El parámetro BOLSA es obligatorio para realizar la transferencia.';
  WHEN NO_PARAM_TIPO THEN
    K_VALOR:='98';
    K_MSJERROR:='El parámetro TIPO es obligatorio para realizar la transferencia.';
  WHEN NO_PARAM_PUNTOS THEN
    K_VALOR:='98';
    K_MSJERROR:='El parámetro PUNTOS es obligatorio para realizar la transferencia.';
  WHEN NO_ERROR_PARAM_BOLSA THEN
    K_VALOR:='98';
    K_MSJERROR:='Los únicos valores aceptados por el parámetro BOLSA son POSTPAGO o PREPAGO.';
  WHEN NO_ERROR_PARAM_TIPO THEN
    K_VALOR:='98';
    K_MSJERROR:='Los únicos valores aceptados por el parámetro TIPO son I o S.';
  WHEN NO_BUSQ_CLIENTE THEN
    ROLLBACK;
    K_VALOR := '02';
    ADMPSI_ACT_TRANS_MSGERROR(K_ID_TRANSCLARO,'El Tipo y número de documento no existen en Claro Club');
    IF K_MSJERROR = '' OR K_MSJERROR IS NULL THEN K_MSJERROR:= 'El Tipo y número de documento no existen en Claro Club'; END IF;
  WHEN NO_CLIENTE THEN
    ROLLBACK;
    K_VALOR := '01';
    ADMPSI_ACT_TRANS_MSGERROR(K_ID_TRANSCLARO,'El Tipo y número de documento no existen en Claro Club');
    IF K_MSJERROR = '' OR K_MSJERROR IS NULL THEN K_MSJERROR:= 'El Tipo y número de documento no existen en Claro Club'; END IF;
  WHEN NO_SALDO THEN
    ROLLBACK;
    K_VALOR := '02';
    K_MSJERROR:='No hay saldo disponible para realizar la tranferencia a Bonus.';
    ADMPSI_ACT_TRANS_MSGERROR(K_ID_TRANSCLARO,'No tiene Saldo Suficiente');
  WHEN NO_SALDO_INSUFICIENTE THEN
    ROLLBACK;
    K_VALOR := '03';
    K_MSJERROR:='No hay saldo suficiente para realizar la tranferencia a Bonus. Su saldo actual es ' || V_SALDO || '.';
    ADMPSI_ACT_TRANS_MSGERROR(K_ID_TRANSCLARO,'No tiene Saldo Suficiente');
  WHEN OTHERS THEN
    ROLLBACK;
    K_VALOR := '99';
    K_MSJERROR := to_char(SQLCODE) || '-' || SUBSTR(SQLERRM,1,400);

END ADMPSS_TRASNFIERE_PTOS;

PROCEDURE ADMPSS_ACT_TRASNFERENCIA
(
  K_ID_TRANSCLARO  IN  NUMBER,
  K_ID_TRANSBONUS  IN  VARCHAR2,
  K_RESP_LOYALTY   IN  VARCHAR2,
  K_VALOR          OUT VARCHAR2,
  K_MSJERROR       OUT VARCHAR2
)
AS
BEGIN

  UPDATE
    ADMPT_TRANSFERENCIA
  SET
    ADMPV_ID_TRANSBONUS = K_ID_TRANSBONUS,
    ADMPV_ESTADO       = 'REALIZADA',
    ADMPV_RESP_LOYALTY  = K_RESP_LOYALTY
  WHERE
    ADMPN_ID_TRANSCLARO = K_ID_TRANSCLARO;

  K_VALOR := '0';
  K_MSJERROR := '';

  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    K_VALOR := '';
    K_MSJERROR := to_char(SQLCODE) || '-' || SUBSTR(SQLERRM,1,400);

END ADMPSS_ACT_TRASNFERENCIA;

PROCEDURE ADMPSS_CAN_TRASNFERENCIA
(
  K_ID_TRANSCLARO  IN  NUMBER,
  K_ID_TRANSBONUS  IN  VARCHAR2,
  K_RESP_LOYALTY   IN  VARCHAR2,
  K_VALOR          OUT VARCHAR2,
  K_MSJERROR       OUT VARCHAR2
)
AS

V_TOTALPUNTOS NUMBER:=0;
V_TRANSPUNTOS NUMBER;
V_TRANSESTADO VARCHAR2(20);
V_ORIGEN      VARCHAR2(40);

BEGIN

  -- VALIDA SI LA TRANSFERENCIA FUE ANULADO
  SELECT
    T1.ADMPN_PUNTOS,
    T1.ADMPV_ESTADO,
    T1.ADMPV_ORIGEN
  INTO
    V_TRANSPUNTOS,
    V_TRANSESTADO,
    V_ORIGEN
  FROM
    ADMPT_TRANSFERENCIA T1
  WHERE
    T1.ADMPN_ID_TRANSCLARO = K_ID_TRANSCLARO;


  IF V_TRANSESTADO = 'CREADO' OR ( V_ORIGEN = 'BONUS' AND V_TRANSESTADO = 'REALIZADA' ) THEN

    -- COMIENZA A DEVOLVER LOS PUNTOS DE LA TRANSFERENCIA QUE VA SER ANULADA
    FOR REG IN
    (
      SELECT
        TK.ADMPN_ID_TRANSCLARO,
        TK.ADMPN_ID_KARDEX,
        TK.ADMPN_PUNTOS,
        NVL(K.ADMPN_COD_CLI_IB, 0) AS ADMPN_COD_CLI_IB,
        NVL(K.ADMPV_COD_CLI, 0)    AS ADMPV_COD_CLI,
        NVL(K.ADMPC_TPO_PUNTO, 0)  AS ADMPC_TPO_PUNTO
      FROM
        ADMPT_TRANS_KARDEX TK
        INNER JOIN ADMPT_KARDEX K ON TK.ADMPN_ID_KARDEX = K.ADMPN_ID_KARDEX
      WHERE
        TK.ADMPN_ID_TRANSCLARO = K_ID_TRANSCLARO AND
        TK.ADMPV_TPO_KARDEX = 'D'
    ) LOOP

        -- DEVUELVE LOS PUNTOS QUE FUERON DESCONTADOS AL KARDEX
      UPDATE
        ADMPT_KARDEX
      SET
        ADMPC_ESTADO    = 'A',
        ADMPN_SLD_PUNTO = REG.ADMPN_PUNTOS + (SELECT NVL(ADMPN_SLD_PUNTO, 0) FROM ADMPT_KARDEX WHERE ADMPN_ID_KARDEX = REG.ADMPN_ID_KARDEX)
      WHERE
        ADMPN_ID_KARDEX = REG.ADMPN_ID_KARDEX;

      -- CLIENTE CLARO O LOYALTY
      IF REG.ADMPC_TPO_PUNTO = 'C' OR REG.ADMPC_TPO_PUNTO = 'L' THEN

        UPDATE
          ADMPT_SALDOS_CLIENTE
        SET
          ADMPN_SALDO_CC  = REG.ADMPN_PUNTOS +
                    (SELECT NVL(ADMPN_SALDO_CC, 0) FROM ADMPT_SALDOS_CLIENTE WHERE ADMPV_COD_CLI = REG.ADMPV_COD_CLI),
          ADMPC_ESTPTO_CC = 'A'
        WHERE
          ADMPV_COD_CLI = REG.ADMPV_COD_CLI;

      ELSE
        -- CLIENTE INTERBANK
        IF REG.ADMPC_TPO_PUNTO = 'I' THEN

          UPDATE
            ADMPT_SALDOS_CLIENTE
          SET
            ADMPN_SALDO_IB  = REG.ADMPN_PUNTOS +
                        (SELECT NVL(ADMPN_SALDO_IB, 0) FROM ADMPT_SALDOS_CLIENTE WHERE ADMPV_COD_CLI = REG.ADMPV_COD_CLI AND ADMPN_COD_CLI_IB = REG.ADMPN_COD_CLI_IB),
            ADMPC_ESTPTO_IB = 'A'
          WHERE
            ADMPV_COD_CLI = REG.ADMPV_COD_CLI AND
             ADMPN_COD_CLI_IB = REG.ADMPN_COD_CLI_IB;

        END IF;

      END IF;

      V_TOTALPUNTOS := V_TOTALPUNTOS + REG.ADMPN_PUNTOS;

    END LOOP;

    IF V_TOTALPUNTOS = V_TRANSPUNTOS THEN

      -- ELIMINA EL REGISTRO DE SALIDA DE PUNTOS EN LA TABLA KARDEX
      DELETE
      FROM
         ADMPT_KARDEX T1
      WHERE
         EXISTS
         (
          SELECT
            ADMPN_ID_KARDEX
          FROM
            ADMPT_TRANS_KARDEX T2
          WHERE
            T2.ADMPN_ID_KARDEX = T1.ADMPN_ID_KARDEX AND
            T2.ADMPN_ID_TRANSCLARO = K_ID_TRANSCLARO AND
            T2.ADMPV_TPO_KARDEX = 'S'
         );

      UPDATE
        ADMPT_TRANSFERENCIA
      SET
        ADMPV_ID_TRANSBONUS = K_ID_TRANSBONUS,
        ADMPV_ESTADO       = 'ANULADO',
        ADMPV_COMENTARIO  = 'Transferencia anulada a solicitud de BONUS el ' || to_char(sysdate,'dd/mm/yyyy HH24:MI:SS a.m.'),
        ADMPV_RESP_LOYALTY  = K_RESP_LOYALTY
      WHERE
        ADMPN_ID_TRANSCLARO = K_ID_TRANSCLARO;

      K_VALOR := '0';
      K_MSJERROR := '';

      COMMIT;

    ELSE

      ROLLBACK;
      K_VALOR := '1';
      K_MSJERROR := 'Error el valor de puntos que fueron devueltos no es el mismo valor de la transferencia.';

    END IF;

  ELSE

    K_VALOR := '2';
    CASE
      WHEN V_TRANSESTADO = 'ANULADO' THEN
        K_MSJERROR := 'Error la transferencia fue anulada anteriormente.';
      WHEN V_TRANSESTADO = 'NO VIABLE' THEN
        K_MSJERROR := 'Error la transferencia fue considerada no viable imposible realizar la devolución de puntos.';
      WHEN V_TRANSESTADO = 'REALIZADA' THEN
        K_MSJERROR := 'Error la transferencia fue realizada correctamente.';
    END CASE;

  END IF;

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    K_VALOR := '';
    K_MSJERROR := to_char(SQLCODE) || '-' || SUBSTR(SQLERRM,1,400);

END ADMPSS_CAN_TRASNFERENCIA;

PROCEDURE ADMPSS_CON_TRASNFERENCIA
(
  K_TIPO_DOC     IN  VARCHAR2,
  K_NUM_DOC      IN  VARCHAR2,
  K_TIPO_MOV     IN  VARCHAR2,
  K_FECHA_INICIO IN  VARCHAR2,
  K_FECHA_FINAL  IN  VARCHAR2,
  K_CURSOR       OUT K_REF_CURSOR,
  K_VALOR        OUT VARCHAR2,
  K_MSJERROR     OUT VARCHAR2
)
AS
BEGIN

  OPEN K_CURSOR FOR
  SELECT
    ADMPN_ID_TRANSCLARO AS ID_TRANSCLARO,
    ADMPV_ID_TRANSBONUS AS ID_TRANSBONUS,
    ADMPN_PUNTOS AS PUNTOS,
    ADMPV_BOLSA AS BOLSA,
    ADMPV_PTO_VENTA AS PTO_VENTA,
    ADMPV_ASESOR AS ASESOR,
    ADMPV_ORIGEN AS ORIGEN
  FROM
    ADMPT_TRANSFERENCIA
  WHERE
    ADMPV_TIPO_DOC = K_TIPO_DOC       AND
    ADMPV_NUM_DOC  = K_NUM_DOC        AND
    ADMPV_TIPO     = K_TIPO_MOV       AND
    ADMPV_ESTADO   = 'REALIZADA'      AND
    ADMPD_FECHA    >= TO_DATE(K_FECHA_INICIO,'DD/MM/YYYY') AND
    ADMPD_FECHA    < TO_DATE(K_FECHA_FINAL,'DD/MM/YYYY')+1
  ORDER BY
      ADMPD_FECHA DESC;

  K_VALOR := '0';
  K_MSJERROR := '';

EXCEPTION
  WHEN OTHERS THEN
    K_VALOR := '';
    K_MSJERROR := to_char(SQLCODE) || '-' || SQLERRM;

END ADMPSS_CON_TRASNFERENCIA;

PROCEDURE ADMPSI_ES_CLIENTE
(
  K_TIPO_DOC       IN  VARCHAR2,
  K_NUM_DOC        IN  VARCHAR2,
  K_BOLSA          IN  VARCHAR2,
  K_COD_CLIENTE    OUT VARCHAR2,
  K_COD_CLIENTE_IB OUT VARCHAR2,
  K_SALDO          OUT NUMBER,
  K_VALOR          OUT NUMBER,
  K_MSJERROR       OUT VARCHAR2
)
AS

V_FLAG_CLARO NUMBER;
K_FLAG_SALDO NUMBER;
NO_PARAMETRO_TIPO EXCEPTION;
NO_PARAMETRO_NDOC EXCEPTION;
NO_PARAMETRO_BOLSA EXCEPTION;
NO_CUENTA_CLIENTES EXCEPTION;
NO_ERROR_PARAM_BOLSA EXCEPTION;

BEGIN

  IF K_TIPO_DOC IS NULL OR K_TIPO_DOC = '' THEN
     RAISE NO_PARAMETRO_TIPO;
  END IF;

  IF K_NUM_DOC IS NULL OR K_NUM_DOC = '' THEN
     RAISE NO_PARAMETRO_NDOC;
  END IF;

  IF K_BOLSA IS NULL OR K_BOLSA = '' THEN
     RAISE NO_PARAMETRO_BOLSA;
  END IF;

  IF  K_BOLSA <> 'POSTPAGO' AND K_BOLSA <> 'PREPAGO' THEN
     RAISE NO_ERROR_PARAM_BOLSA;
  END IF;

  -- VALIDA SI EXISTE CLIENTE
  IF K_BOLSA = 'POSTPAGO' THEN

    SELECT
      COUNT(*) INTO V_FLAG_CLARO
    FROM
      ADMPT_CLIENTE T1
    WHERE
      T1.ADMPV_TIPO_DOC  = K_TIPO_DOC AND
      T1.ADMPV_NUM_DOC   = K_NUM_DOC  AND
      T1.ADMPC_ESTADO     = 'A'        AND
      T1.ADMPV_COD_TPOCL IN (1,2,4);

    IF V_FLAG_CLARO >0 THEN

      SELECT
        MAX(T1.ADMPV_COD_CLI) INTO K_COD_CLIENTE
      FROM
        ADMPT_CLIENTE  T1
      WHERE
        T1.ADMPV_TIPO_DOC = K_TIPO_DOC AND
        T1.ADMPV_NUM_DOC  = K_NUM_DOC  AND
        T1.ADMPC_ESTADO    = 'A'        AND
        T1.ADMPV_COD_TPOCL IN (1,2,4)  AND
        T1.ADMPD_FEC_ACTIV IN
                          (
                            SELECT
                              MIN(ADMPD_FEC_ACTIV)
                            FROM
                              ADMPT_CLIENTE T2
                            WHERE
                              T2.ADMPV_TIPO_DOC = K_TIPO_DOC AND
                              T2.ADMPV_NUM_DOC  = K_NUM_DOC  AND
                              T2.ADMPC_ESTADO    = 'A'        AND
                              T2.ADMPV_COD_TPOCL IN (1,2,4)
                           );

    ELSE

      K_VALOR := '2';
      K_MSJERROR := 'El cliente no existe en el servicio PostPago, Control o B2E ClaroClub.';

    END IF;

   ELSIF K_BOLSA = 'PREPAGO' THEN

    SELECT
      COUNT(*) INTO V_FLAG_CLARO
    FROM
      ADMPT_CLIENTE T1
    WHERE
      T1.ADMPV_TIPO_DOC  = K_TIPO_DOC AND
      T1.ADMPV_NUM_DOC   = K_NUM_DOC  AND
      T1.ADMPC_ESTADO     = 'A'        AND
      T1.ADMPV_COD_TPOCL = 3;

    IF V_FLAG_CLARO >0 THEN

      SELECT
        MAX(T1.ADMPV_COD_CLI)  INTO K_COD_CLIENTE
      FROM
        ADMPT_CLIENTE  T1
      WHERE
        T1.ADMPV_TIPO_DOC = K_TIPO_DOC AND
        T1.ADMPV_NUM_DOC  = K_NUM_DOC  AND
        T1.ADMPC_ESTADO    = 'A'        AND
        T1.ADMPV_COD_TPOCL = 3         AND
        T1.ADMPD_FEC_ACTIV IN
                          (
                            SELECT
                              MIN(ADMPD_FEC_ACTIV)
                            FROM
                              ADMPT_CLIENTE T2
                            WHERE
                              T2.ADMPV_TIPO_DOC = K_TIPO_DOC AND
                              T2.ADMPV_NUM_DOC  = K_NUM_DOC  AND
                              T2.ADMPC_ESTADO    = 'A'        AND
                              T2.ADMPV_COD_TPOCL = 3
                           );

    ELSE

      K_VALOR := '2';
      K_MSJERROR := 'El cliente no existe en el servicio Prepago ClaroClub.';

    END IF;

  END IF;

  -- EXISTE EN CLARO
  IF V_FLAG_CLARO >0 THEN

    -- VALIDA SI EXISTE CLIENTE EN IBK
    SELECT
      MAX(TIB.ADMPN_COD_CLI_IB) INTO K_COD_CLIENTE_IB
    FROM
      ADMPT_CLIENTEIB TIB
      RIGHT JOIN ADMPT_CLIENTE T ON TIB.ADMPV_COD_CLI = T.ADMPV_COD_CLI
    WHERE
      T.ADMPV_COD_CLI = K_COD_CLIENTE AND
      (TIB.ADMPC_ESTADO    = 'A' OR TIB.ADMPC_ESTADO IS NULL);

    -- VALIDA SI CLIENTE TIENE UNA CUENTA ASOCIADA
    SELECT
      COUNT(*) INTO K_FLAG_SALDO
    FROM
      ADMPT_CLIENTE T1
      INNER JOIN ADMPT_SALDOS_CLIENTE T2 ON T1.ADMPV_COD_CLI = T2.ADMPV_COD_CLI
    WHERE
      T1.ADMPC_ESTADO = 'A'          AND
      T2.ADMPC_ESTPTO_CC = 'A'       AND
      T1.ADMPV_NUM_DOC =  K_NUM_DOC  AND
      T1.ADMPV_TIPO_DOC = K_TIPO_DOC AND
      ((K_BOLSA = 'POSTPAGO' AND T1.ADMPV_COD_TPOCL IN ('1','2','4')) OR
      ( K_BOLSA = 'PREPAGO' AND T1.ADMPV_COD_TPOCL = '3' ));

    IF K_FLAG_SALDO = 0 THEN
       RAISE NO_CUENTA_CLIENTES;
    END IF;

    -- OBTIENE SALDO DE LOS CLIENTES
    IF K_BOLSA = 'POSTPAGO' THEN

      SELECT
       SUM(T2.ADMPN_SALDO_CC) + SUM(T2.ADMPN_SALDO_IB) INTO K_SALDO
      FROM
       ADMPT_CLIENTE T1
       INNER JOIN ADMPT_SALDOS_CLIENTE T2 ON T1.ADMPV_COD_CLI = T2.ADMPV_COD_CLI
      WHERE
       T1.ADMPC_ESTADO = 'A'          AND
       T2.ADMPC_ESTPTO_CC = 'A'       AND
       T1.ADMPV_NUM_DOC =  K_NUM_DOC  AND
       T1.ADMPV_TIPO_DOC = K_TIPO_DOC AND
       T1.ADMPV_COD_TPOCL IN (1,2,4);

    ELSIF K_BOLSA = 'PREPAGO' THEN

      SELECT
       SUM(T2.ADMPN_SALDO_CC) + SUM(T2.ADMPN_SALDO_IB) INTO K_SALDO
      FROM
       ADMPT_CLIENTE T1
       INNER JOIN ADMPT_SALDOS_CLIENTE T2 ON T1.ADMPV_COD_CLI = T2.ADMPV_COD_CLI
      WHERE
       T1.ADMPC_ESTADO = 'A'          AND
       T2.ADMPC_ESTPTO_CC = 'A'       AND
       T1.ADMPV_NUM_DOC =  K_NUM_DOC  AND
       T1.ADMPV_TIPO_DOC = K_TIPO_DOC AND
       T1.ADMPV_COD_TPOCL = 3;

    END IF;

  END IF;

  IF K_SALDO IS NULL THEN
     K_SALDO := 0;
  END IF;

  IF K_VALOR IS NULL OR K_VALOR = '' THEN
    K_VALOR := '0';
    K_MSJERROR := '';
  END IF;

EXCEPTION
  WHEN NO_PARAMETRO_TIPO THEN
    K_VALOR:='';
    K_MSJERROR:='El parámetro TIPO_DOC es obligatorio para realizar la consulta de cliente ClaroClub.';
  WHEN NO_PARAMETRO_NDOC THEN
    K_VALOR:='';
    K_MSJERROR:='El parámetro NUM_DOC es obligatorio para realizar la consulta de cliente ClaroClub.';
  WHEN NO_PARAMETRO_BOLSA THEN
    K_VALOR:='';
    K_MSJERROR:='El parámetro BOLSA es obligatorio para realizar la consulta de cliente ClaroClub.';
  WHEN NO_ERROR_PARAM_BOLSA THEN
    K_VALOR:='';
    K_MSJERROR:='Los únicos valores aceptados por el parámetro BOLSA son POSTPAGO o PREPAGO.';
  WHEN NO_CUENTA_CLIENTES THEN
    K_VALOR:='';
    K_MSJERROR:='El cliente no cuenta con ningún registro en la tabla saldos.';
  WHEN OTHERS THEN
    K_VALOR := '';
    K_MSJERROR := to_char(SQLCODE) || '-' || SUBSTR(SQLERRM,1,400);

END ADMPSI_ES_CLIENTE;


PROCEDURE ADMPSI_GETCLIENTESPREPAGO
(
  K_TIPO_DOC       IN  VARCHAR2,
  K_NUM_DOC        IN  VARCHAR2,
  K_CURSOR         OUT K_REF_CURSOR,
  K_VALOR            OUT NUMBER,
  K_MSJERROR       OUT VARCHAR2
)
AS
BEGIN

  OPEN K_CURSOR FOR
  SELECT
    T.ADMPV_COD_CLI AS COD_CLI_PREPAGO
  FROM
    ADMPT_CLIENTE T
  WHERE
    T.ADMPV_TIPO_DOC = K_TIPO_DOC       AND
    T.ADMPV_NUM_DOC  = K_NUM_DOC        AND
    T.ADMPC_ESTADO   = 'A'              AND
    T.ADMPV_COD_TPOCL = '3'
  ORDER BY
      T.ADMPD_FEC_ACTIV;

  K_VALOR := '0';
  K_MSJERROR := '';

EXCEPTION
  WHEN OTHERS THEN
    K_VALOR := '';
    K_MSJERROR := to_char(SQLCODE) || '-' || SQLERRM;

END ADMPSI_GETCLIENTESPREPAGO;

--****************************************************************
-- Nombre SP           :  ADMPSI_GETPARAMSIST
-- Propósito           :  Devuelve el valor correspondiete a la descripcion
-- Input               :  K_DESC
-- Output              :  K_VALOR
-- Creado por          :  (Teamsoft) Jose Jimenez
-- Fec Creación        :  04/01/2011
-- Fec Actualización   :
--****************************************************************
PROCEDURE ADMPSI_GETPARAMSIST
(
  K_DESC IN VARCHAR2,
  K_VALOR OUT VARCHAR2,
  K_MSJERROR OUT VARCHAR2
)
AS
V_CANTREG  INTEGER;
BEGIN

  SELECT
    COUNT(*) INTO V_CANTREG
  FROM
    PCLUB.ADMPT_PARAMSIST
  WHERE
    ADMPV_DESC = K_DESC;


  IF V_CANTREG > 0 THEN

    SELECT
       ADMPV_valor INTO K_VALOR
    FROM
       PCLUB.ADMPT_PARAMSIST
    WHERE
       ADMPV_DESC = K_DESC;

  K_MSJERROR := '';

  ELSE

    K_VALOR := '';
    K_MSJERROR := 'EL PARAMETRO NO EXISTE EN LA TABLA';

  END IF;

EXCEPTION
   WHEN OTHERS THEN
     K_VALOR := '';
     K_MSJERROR := to_char(SQLCODE) || '-' || SUBSTR(SQLERRM,1,400);

END ADMPSI_GETPARAMSIST;

PROCEDURE ADMPSI_GETTIPODOC
(
  K_CURSOR OUT K_REF_CURSOR
)
AS
BEGIN

  OPEN K_CURSOR FOR
  SELECT
    T.ADMPV_COD_TPDOC AS codigo,
    UPPER(T.ADMPV_DSC_DOCUM) AS descripcion,
    T.ADMPV_COD_EQUIV AS codigo_aux
  FROM
    ADMPT_TIPO_DOC T
  ORDER BY
     codigo_aux;

END ADMPSI_GETTIPODOC;

PROCEDURE ADMPSI_ACT_TRANS_MSGERROR
(
  K_ID_TRANSCLARO  IN  NUMBER,
  K_RESP_CLARO     IN  VARCHAR2
)
AS
BEGIN

  UPDATE
    ADMPT_TRANSFERENCIA
  SET
    ADMPV_ESTADO       = 'NO VIABLE',
    ADMPV_RESP_CLARO  = K_RESP_CLARO
  WHERE
    ADMPN_ID_TRANSCLARO = K_ID_TRANSCLARO;

  COMMIT;

END ADMPSI_ACT_TRANS_MSGERROR;

end PKG_CC_TRANFERENCIA;
/
