insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('28', 'ANIVERSARIO PREPAGO', 'A', '', 18, 'C');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('29', 'ACTIVACION PREPAGO', 'A', '', 18, 'C');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('30', 'CAMBIO TITULAR PREPAGO', 'A', '', 18, 'C');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('31', 'MESES SIN RECARGA PREPAGO', 'A', '', 18, 'C');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('32', 'BAJA CLIENTE PREPAGO', 'A', '', null, 'C');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('39', 'INGRESO POR BAJA CLIENTE PREPAGO', 'A', '', 18, 'C');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('45', 'INGRESO POR BAJA CLIENTE PREPAGO IB', 'A', '', 18, 'I');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('40', 'MIGRACIONES PREPAGO A POSTPAGO IB', 'A', '', 18, 'I');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('33', 'VENCIMIENTO DE PUNTO PREPAGO', 'A', '', null, 'C');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('34', 'MIGRACIONES PREPAGO A POSTPAGO CC', 'A', '', 18, 'C');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('35', 'MIGRACIONES POSTPAGO A PREPAGO CC', 'A', '', 18, 'C');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('36', 'BONO POR MIGRACIONES PREPAGO A POSTPAGO', 'A', '', 18, 'C');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('37', 'PENALIDAD POR MIGRACIONES POSTPAGO A PREPAGO', 'A', '', null, 'C');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('41', 'MIGRACIONES POSTPAGO A PREPAGO IB', 'A', '', 18, 'I');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('42', 'PROMO PREPAGO', 'A', '', 18, 'C');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('43', 'SALIDA POR TRANSFERENCIA DE PUNTOS CC', 'A', '', 0, 'C');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('44', 'SALIDA POR TRANSFERENCIA DE PUNTOS IB', 'A', '', 0, 'I');

insert into pclub.ADMPT_concepto (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('27', 'RECARGAS PREPAGO', 'A', '', 18, 'C');


insert into pclub.admpt_paramsist (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
values ('15 ', 'MESES_ANIVERSARIO', '12');

insert into pclub.admpt_paramsist (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
values ('16 ', 'MONTO_ANIVERSARIO', '10');

insert into pclub.admpt_paramsist (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
values ('8  ', 'PUNTOS_ANIVERSARIO_PREPAGO', '100');

insert into pclub.admpt_paramsist (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
values ('9  ', 'PUNTOS_ACTIVACION_PREPAGO', '20');

insert into pclub.admpt_paramsist (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
values ('17 ', 'PRE_ACTIVACION_TC', '500');

insert into pclub.admpt_paramsist (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
values ('11 ', 'MESES_SIN_RECARGA', '12');

insert into pclub.admpt_paramsist (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
values ('12 ', 'PUNTOS_MIGRACION_PREPAGO_POSTPAGO', '100');

insert into pclub.admpt_paramsist (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
values ('13 ', 'PUNTOS_MIGRACION_POSTPAGO_PREPAGO', '-150');

insert into pclub.admpt_paramsist (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
values ('14 ', 'PUNTOS_RECARGA_PREPAGO', '3');

commit;