insert into PCLUB.ADMPT_CONCEPTO (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
values ('38', 'ICLARO', 'A', '', 18, 'C');
COMMIT;

insert into PCLUB.ADMPT_CAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_DSC_CAT, ADMPV_ESTADO)
values ('04', 'REGULARIZACIÓN', 'A');
insert into PCLUB.ADMPT_CAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_DSC_CAT, ADMPV_ESTADO)
values ('03', 'PROMOCIÓN', 'A');
insert into PCLUB.ADMPT_CAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_DSC_CAT, ADMPV_ESTADO)
values ('02', 'CAMBIO TITULARIDAD', 'A');
insert into PCLUB.ADMPT_CAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_DSC_CAT, ADMPV_ESTADO)
values ('01', 'ASIGNACIÓN', 'A');
insert into PCLUB.ADMPT_CAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_DSC_CAT, ADMPV_ESTADO)
values ('05', 'TRANSFERENCIA A BONUS', 'A');
insert into PCLUB.ADMPT_CAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_DSC_CAT, ADMPV_ESTADO)
values ('06', 'TRASFERENCIA DE  BONUS', 'A');
COMMIT;

insert into PCLUB.ADMPT_DETCAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_COD_CPTO)
values ('01', '12');
insert into PCLUB.ADMPT_DETCAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_COD_CPTO)
values ('01', '13');
insert into PCLUB.ADMPT_DETCAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_COD_CPTO)
values ('01', '11');
insert into PCLUB.ADMPT_DETCAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_COD_CPTO)
values ('01', '7');
insert into PCLUB.ADMPT_DETCAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_COD_CPTO)
values ('01', '26');
insert into PCLUB.ADMPT_DETCAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_COD_CPTO)
values ('02', '20');
insert into PCLUB.ADMPT_DETCAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_COD_CPTO)
values ('03', '8');
insert into PCLUB.ADMPT_DETCAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_COD_CPTO)
values ('03', '17');
insert into PCLUB.ADMPT_DETCAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_COD_CPTO)
values ('03', '18');
insert into PCLUB.ADMPT_DETCAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_COD_CPTO)
values ('03', '22');
insert into PCLUB.ADMPT_DETCAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_COD_CPTO)
values ('03', '38');
insert into PCLUB.ADMPT_DETCAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_COD_CPTO)
values ('04', '9');
insert into PCLUB.ADMPT_DETCAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_COD_CPTO)
values ('05', '25');
insert into PCLUB.ADMPT_DETCAT_CONCEPTO (ADMPV_COD_CAT, ADMPV_COD_CPTO)
values ('06', '24');
COMMIT;

