 /* ADMPT_PARAMSIST */

DECLARE 
IDPARAM CHAR(3);
 
BEGIN

SELECT TO_CHAR(MAX(TO_NUMBER(P.ADMPC_COD_PARAM)+1)) INTO IDPARAM
FROM 	 PCLUB.ADMPT_PARAMSIST P;

INSERT INTO PCLUB.ADMPT_PARAMSIST (ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR) VALUES (IDPARAM, 'CANT_REG_COMMIT_PROC_FIDELIZ', '30');

UPDATE PCLUB.ADMPT_BONO BO
    SET  ADMPV_TYPEBONO='F'
WHERE ADMPV_BONO IN (
                      SELECT DISTINCT(ADMPV_BONO)
                      FROM   PCLUB.ADMPT_BONO_CONFIG A
                      WHERE  A.ADMPV_COD_CPTO IN ('95','96')
                     );
COMMIT;

END;
/