-- INSERTS SEGMENTOS

INSERT INTO PCLUB.ADMPT_SEGMENTO_CC (ADMV_COD_SEG,ADMV_DESC_SEG,ADMV_USR_REG,ADMD_FEC_REG)
VALUES ('A','A',NULL,SYSDATE);

INSERT INTO PCLUB.ADMPT_SEGMENTO_CC (ADMV_COD_SEG,ADMV_DESC_SEG,ADMV_USR_REG,ADMD_FEC_REG)
VALUES ('B','B',NULL,SYSDATE);

INSERT INTO PCLUB.ADMPT_SEGMENTO_CC (ADMV_COD_SEG,ADMV_DESC_SEG,ADMV_USR_REG,ADMD_FEC_REG)
VALUES ('C','C',NULL,SYSDATE);

COMMIT;
