--insertar descripcion de errores en la tabla generica

INSERT INTO PCLUB.ADMPT_TIPO_CLIENTE
   (ADMPV_COD_TPOCL, ADMPV_DESC, ADMPC_ESTADO)
 VALUES
   ('6', 'DTH POSTPAGO', 'A');
INSERT INTO PCLUB.ADMPT_TIPO_CLIENTE
   (ADMPV_COD_TPOCL, ADMPV_DESC, ADMPC_ESTADO)
 VALUES
   ('7', 'HFC POSTPAGO', 'A');

INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (0, 'La transacción se realizó con éxito. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (1, 'Ocurrió un error en la transacción. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (2, 'Cliente no existe en DWH. No se va insertar. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (3, 'Cliente ya existe en Claro Club. No se va insertar. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (4, 'Error en parametro(s) de entrada. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (5, 'Error en saldos del cliente. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (6, 'El cliente se encuentra con estado de BAJA ó no existe. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (7, 'El cliente tiene servicio(s) asociados con estado de BAJA. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (8, 'Los servicio(s) asociados al cliente ya se encuentran registrados. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (9, 'No se encontró el concepto. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (10, 'El cliente no se encuentra categorizado. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (11, 'No se puede realizar el cambio de plan, no existen servicios asociados. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (12, 'Error al actualizar el canje. No hay coincidencia en la lista de canje. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (13, 'El premio no coincide con el tipo de cliente. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (14, 'Inconsistencia de datos, favor de revisar a detalle. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (15, 'La clave ingresada es incorrecta. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (16, 'No existen registro a eliminar con el identificador proporcionado. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (17, 'No se procesaron los datos. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (18, 'No hay saldo disponible para realizar la transferencia. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (19, 'Los puntos a transferir deben ser mayor que 0. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (20, 'La línea no le pertenece al cliente. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (21, 'Problemas con el descuento de puntos. Favor de revisar. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (22, 'Error en la transferencia. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (23, 'No Existe ninguna campaña Activa para el Tipo de Cliente');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (24, 'No hay Saldo Disponible para el Canje');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (25, 'Los Puntos a Canjear es mayor al Saldo Disponible');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (26, 'El Cliente no Tiene Puntos Claro Club');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (27, 'No existen servicios para realizar la transaccion. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (28, 'El canje proporcionado no se encuentra registrado. ');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (29, 'Usted realizo el maximo de consultas. Favor intentelo en minutos');
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR, ADMPV_DES_ERROR)
 VALUES
   (30, 'La promocion ya caduco.');
   
--INSERCION EN LA TABLA CONCEPTO
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('59', 'PROMOCION DTH', 'A', 18, 
    'C', 'DTH');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO, ADMPC_TPO_OPER)
 VALUES
   ('53', 'CARGO FIJO NORMAL HFC', 'A', 18, 
    'C', 'HFC', 'E ');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('60', 'PROMOCION HFC', 'A', 18, 
    'C', 'HFC');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO, ADMPC_TPO_OPER)
 VALUES
   ('54', 'PRONTO PAGO NORMAL HFC', 'A', 18, 
    'C', 'HFC', 'E ');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO, ADMPC_TPO_OPER)
 VALUES
   ('55', 'CANJE DTH', 'A', 
    'C', 'DTH', 'S ');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO, ADMPC_TPO_OPER)
 VALUES
   ('56', 'CANJE HFC', 'A', 
    'C', 'HFC', 'S ');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO, ADMPC_TPO_OPER)
 VALUES
   ('57', 'CAMBIO TITULARIDAD DTH', 'A', 'CAMBIO_TIT_DTH_YYYYMMDD.CCL', 18, 
    'C', 'DTH', 'S ');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO, ADMPC_TPO_OPER)
 VALUES
   ('58', 'CAMBIO TITULARIDAD HFC', 'A', 'CAMBIO_TIT_HFC_YYYYMMDD.CCL', 18, 
    'C', 'HFC', 'S ');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('62', 'VENCIMIENTO DE PUNTOS DTH', 'A', 18, 
    'C', 'DTH');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('63', 'VENCIMIENTO DE PUNTOS HFC', 'A', 18, 
    'C', 'HFC');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('64', 'TRANSFERENCIA DTH A POSTPAGO', 'A', 18, 
    'C', 'DTH');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('65', 'TRANSFERENCIA DTH A PREPAGO', 'A', 18, 
    'C', 'DTH');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('66', 'TRANSFERENCIA HFC A POSTPAGO', 'A', 18, 
    'C', 'HFC');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('67', 'TRANSFERENCIA HFC A PREPAGO', 'A', 18, 
    'C', 'HFC');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('68', 'BAJA CLIENTE DTH', 'A', 'C', 'DTH');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('69', 'BAJA CLIENTE HFC', 'A', 'C', 'HFC');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('70', 'INGRESO POR BAJA CLIENTE DTH', 'A', 18, 
    'C', 'DTH');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('71', 'INGRESO POR BAJA CLIENTE HFC', 'A', 18, 
    'C', 'HFC');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('72', 'REGULARIZACION DTH', 'A', 18, 
    'C', 'DTH');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('73', 'REGULARIZACION HFC', 'A', 18, 
    'C', 'HFC');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO, ADMPC_TPO_OPER)
 VALUES
   ('74', 'PRONTO PAGO NORMAL DTH', 'A', 'BONUS_PAGOS_YYYYMMDD', 18, 
    'C', 'DTH', 'E ');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPV_NOM_ARCH, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO, ADMPC_TPO_OPER)
 VALUES
   ('75', 'CARGO FIJO NORMAL DTH', 'A', 'BONUS_PAGOS_YYYYMMDD', 18, 
    'C', 'DTH', 'E ');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES
   ('80', 'CAMBIO PLAN HFC', 'A', 18, 
    'C', 'HFC');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
 VALUES
   ('77', 'POSTPAGO - TRANSFERENCIA DE DTH', 'A', 18, 'C');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
 VALUES
   ('76', 'POSTPAGO - TRANSFERENCIA DE HFC', 'A', 18, 'C');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
 VALUES
   ('79', 'PREPAGO - TRANSFERENCIA DE DTH', 'A', 18, 'C');
INSERT INTO PCLUB.ADMPT_CONCEPTO
   (ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO)
 VALUES
   ('78', 'PREPAGO - TRANSFERENCIA DE HFC', 'A', 18, 'C');
   
--insertar en la tabla tipo doc 
INSERT INTO PCLUB.ADMPT_TIPO_DOC
   (ADMPV_COD_TPDOC, ADMPV_DSC_DOCUM, ADMPV_EQU_FIJA)
 VALUES
   ('6', 'LIBRETA MILITAR', '003');

--insertar en la tabla tipode servicios
INSERT INTO PCLUB.ADMPT_TIPOSERV_DTH_HFC
   (ADMPV_COD_TPOCL, ADMPV_SERVICIO, ADMPV_DESC, ADMPN_PRIORIDAD)
 VALUES
   ('6', '0062', 'Cable', 1);
INSERT INTO PCLUB.ADMPT_TIPOSERV_DTH_HFC
   (ADMPV_COD_TPOCL, ADMPV_SERVICIO, ADMPV_DESC, ADMPN_PRIORIDAD)
 VALUES
   ('7', '0004', 'Telefonia', 1);
INSERT INTO PCLUB.ADMPT_TIPOSERV_DTH_HFC
   (ADMPV_COD_TPOCL, ADMPV_SERVICIO, ADMPV_DESC, ADMPN_PRIORIDAD)
 VALUES
   ('7', '0062', 'Cable', 2);
INSERT INTO PCLUB.ADMPT_TIPOSERV_DTH_HFC
   (ADMPV_COD_TPOCL, ADMPV_SERVICIO, ADMPV_DESC, ADMPN_PRIORIDAD)
 VALUES
   ('7', '0006', 'Internet', 3);

INSERT INTO PCLUB.ADMPT_CAT_CLIENTE
   (ADMPN_COD_CATCLI, ADMPV_COD_TPOCL, ADMPV_DESC, ADMPC_TIPO, ADMPN_TME_PUNTO, ADMPV_OPER_INI, ADMPV_OPER_FIN, ADMPN_LIM_INF, ADMPN_LIM_SUP, ADMPC_ESTADO, ADMPN_CXPT_PPAG, ADMPN_CXPT_CFIJ, ADMPN_PTOANIV)
 VALUES(2, '6', 'Normal', 'T', 12,'4', '3', 2500, 0, 'A',3, 2, 100);
INSERT INTO PCLUB.ADMPT_CAT_CLIENTE
   (ADMPN_COD_CATCLI, ADMPV_COD_TPOCL, ADMPV_DESC, ADMPC_TIPO, ADMPN_TME_PUNTO, ADMPV_OPER_INI, ADMPV_OPER_FIN, ADMPN_LIM_INF, ADMPN_LIM_SUP, ADMPC_ESTADO, ADMPN_CXPT_PPAG, ADMPN_CXPT_CFIJ, ADMPN_PTOANIV)
 VALUES(2, '7', 'Normal', 'T', 12,'4', '3', 2500, 0, 'A',3, 2, 100);

INSERT INTO PCLUB.ADMPT_TIPO_PREMIO(ADMPV_COD_TPOPR, ADMPV_DESC, ADMPC_ESTADO, ADMPN_ORDEN)
 VALUES ('22', 'Paquete Television HFC', 'A', 12);

INSERT INTO PCLUB.ADMPT_PREMIO
   (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_COD_SERVC, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPV_COD_SERVTV)
 VALUES('PAQMOV01HFC', '22', 'Paquete Movie City', 210, 0,'A', 0, 0, 'T', 'May-12','HMOVIE', 'PAQMOV01HFC');
INSERT INTO PCLUB.ADMPT_PREMIO
   (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPV_COD_SERVTV)
 VALUES('PAQHBO01HFC', '22', 'Paquete HBO', 240, 0,'A', 0, 'T', 'May-12','HBO', 'PAQHBO01HFC');
INSERT INTO PCLUB.ADMPT_PREMIO
   (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPV_COD_SERVTV)
 VALUES('PAQADU01HFC', '22', 'Paquete Adulto', 240, 0,'A', 0, 'T', 'May-12','HADULTO', 'PAQADU01HFC');
INSERT INTO PCLUB.ADMPT_PREMIO
   (ADMPV_ID_PROCLA, ADMPV_COD_TPOPR, ADMPV_DESC, ADMPN_PUNTOS, ADMPN_PAGO, ADMPC_ESTADO, ADMPN_MNT_RECAR, ADMPC_APL_PUNTO, ADMPV_CAMPANA, ADMPV_CLAVE, ADMPV_COD_SERVTV)
 VALUES('PAQHD01HFC', '22', 'Paquete HD', 270, 0,'A', 0, 'T', 'May-12','HHD', 'PAQHD01HFC');

INSERT INTO PCLUB.ADMPT_TIPO_PREMCLIE
   (ADMPV_COD_TPOPR, ADMPV_COD_TPOCL)
 VALUES('22', '7');   

--TRANSACCION X CLIENTE
INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE
   (ADMPV_TRANSACCION, ADMPV_COD_TPOCL)
 VALUES
   ('TRANSACCION_PROMO_REGULARIZ', '7');
INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE
   (ADMPV_TRANSACCION, ADMPV_COD_TPOCL)
 VALUES
   ('TRANSACCION_CANJE', '7');
INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE
   (ADMPV_TRANSACCION, ADMPV_COD_TPOCL)
 VALUES
   ('TRANSACCION_TRANSFERENCIA', '7');
INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE
   (ADMPV_TRANSACCION, ADMPV_COD_TPOCL)
 VALUES
   ('TRANSACCION_CON_CANJE', '7');

COMMIT;

