
INSERT INTO PCLUB.ADMPT_CONCEPTO(ADMPV_COD_CPTO, ADMPV_DESC, ADMPC_ESTADO, ADMPN_PER_CADU, ADMPC_TPO_PUNTO, ADMPV_TPO_CPTO)
 VALUES('52', 'ANIVERSARIO DTH', 'A', 18,'C', 'DTH');

INSERT INTO PCLUB.ADMPT_PARAMSIST(ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
 VALUES('205', 'PUNTOS_ANIVERSARIO_DTH', '50');
 
INSERT INTO PCLUB.ADMPT_PARAMSIST(ADMPC_COD_PARAM,ADMPV_DESC,ADMPV_VALOR)
 VALUES('220','DIAS_VIGENCIA_SERVICIO_DTH','15');

INSERT INTO PCLUB.ADMPT_PARAMSIST(ADMPC_COD_PARAM, ADMPV_DESC, ADMPV_VALOR)
 VALUES('221', 'REG_ANIVERSARIO_DTH', 'S');
  
INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE
   (ADMPV_TRANSACCION, ADMPV_COD_TPOCL)
 VALUES ('TRANSACCION_ESTADO_CUENTA', '7');
 
INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE
   (ADMPV_TRANSACCION, ADMPV_COD_TPOCL)
 VALUES ('TRANSACCION_PROMO_REGULARIZ', '6');
 
INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE
   (ADMPV_TRANSACCION, ADMPV_COD_TPOCL)
 VALUES ('TRANSACCION_CANJE', '6');
 
INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE
   (ADMPV_TRANSACCION, ADMPV_COD_TPOCL)
 VALUES ('TRANSACCION_TRANSFERENCIA', '6');
 
INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE
   (ADMPV_TRANSACCION, ADMPV_COD_TPOCL)
 VALUES ('TRANSACCION_ESTADO_CUENTA', '6');
 
INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE
   (ADMPV_TRANSACCION, ADMPV_COD_TPOCL)
 VALUES ('TRANSACCION_CON_CANJE', '6');
 
INSERT INTO PCLUB.ADMPT_TIPO_PREMIO(ADMPV_COD_TPOPR,ADMPV_DESC,ADMPC_ESTADO,ADMPN_ORDEN) VALUES('21','Paquete Television DTH','A',11);
            
/*CORRER SOLO PARA PRODUCCION, NO CORRER EN PCLUBDES, YO YA LO CORRI CON LOS CODIGOS DE PRUEBA*/
INSERT INTO PCLUB.ADMPT_PREMIO(ADMPV_ID_PROCLA,ADMPV_COD_TPOPR,ADMPV_DESC,ADMPN_PUNTOS,ADMPN_PAGO,ADMPC_ESTADO,ADMPN_MNT_RECAR,ADMPC_APL_PUNTO, ADMPV_CAMPANA,ADMPV_COD_SERVTV)
VALUES('PAQMOV01DTH','21','Paquete Movie City',210,0,'A',0,'T','May-12','838');

INSERT INTO PCLUB.ADMPT_PREMIO(ADMPV_ID_PROCLA,ADMPV_COD_TPOPR,ADMPV_DESC,ADMPN_PUNTOS,ADMPN_PAGO,ADMPC_ESTADO,ADMPN_MNT_RECAR,ADMPC_APL_PUNTO, ADMPV_CAMPANA,ADMPV_COD_SERVTV)
VALUES('PAQHBO01DTH','21','Paquete HBO',240,0,'A',0,'T','May-12','839');

INSERT INTO PCLUB.ADMPT_PREMIO(ADMPV_ID_PROCLA,ADMPV_COD_TPOPR,ADMPV_DESC,ADMPN_PUNTOS,ADMPN_PAGO,ADMPC_ESTADO,ADMPN_MNT_RECAR,ADMPC_APL_PUNTO, ADMPV_CAMPANA,ADMPV_COD_SERVTV)
VALUES('PAQADU01DTH','21','Paquete Adulto',240,0,'A',0,'T','May-12','840');

INSERT INTO PCLUB.ADMPT_PREMIO(ADMPV_ID_PROCLA,ADMPV_COD_TPOPR,ADMPV_DESC,ADMPN_PUNTOS,ADMPN_PAGO,ADMPC_ESTADO,ADMPN_MNT_RECAR,ADMPC_APL_PUNTO, ADMPV_CAMPANA,ADMPV_COD_SERVTV)
VALUES('PAQHD01DTH','21','Paquete HD',270,0,'A',0,'T','May-12','841');

INSERT INTO PCLUB.ADMPT_PREMIO(ADMPV_ID_PROCLA,ADMPV_COD_TPOPR,ADMPV_DESC,ADMPN_PUNTOS,ADMPN_PAGO,ADMPC_ESTADO,ADMPN_MNT_RECAR,ADMPC_APL_PUNTO, ADMPV_CAMPANA,ADMPV_COD_SERVTV)
VALUES('GRILLAPLUS01DTH','21','Grilla Plus',90,0,'A',0,'T','May-12','842');

INSERT INTO PCLUB.ADMPT_TIPO_PREMCLIE(ADMPV_COD_TPOPR,ADMPV_COD_TPOCL)
VALUES('21','6');

INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR,ADMPV_DES_ERROR)VALUES(32,'NO SE PUEDE REALIZAR EL CANJE DEL MISMO PAQUETE ANTES DE 24 HORAS DEL CANJE') ;
 
INSERT INTO PCLUB.ADMPT_ERRORES_CC(ADMPN_COD_ERROR,ADMPV_DES_ERROR)VALUES(33,'LOS PUNTOS NO SE ENCUENTRAN ALINEADOS') ;
 
COMMIT;

