INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE (ADMPV_TRANSACCION, ADMPV_COD_TPOCL, ADMPD_FEC_REG, ADMPV_USU_REG)
VALUES('TRANSACCION_DSCTO_SEGMENTACION', '2', SYSDATE, NULL);

INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE (ADMPV_TRANSACCION, ADMPV_COD_TPOCL, ADMPD_FEC_REG, ADMPV_USU_REG)
VALUES('TRANSACCION_DSCTO_SEGMENTACION', '3', SYSDATE, NULL);

INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE (ADMPV_TRANSACCION, ADMPV_COD_TPOCL, ADMPD_FEC_REG, ADMPV_USU_REG)
VALUES('TRANSACCION_DSCTO_SEGMENTACION', '6', SYSDATE, NULL);

INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE (ADMPV_TRANSACCION, ADMPV_COD_TPOCL, ADMPD_FEC_REG, ADMPV_USU_REG)
VALUES('TRANSACCION_DSCTO_SEGMENTACION', '7', SYSDATE, NULL);

INSERT INTO PCLUB.ADMPT_TRANSAC_X_CLIENTE (ADMPV_TRANSACCION, ADMPV_COD_TPOCL, ADMPD_FEC_REG, ADMPV_USU_REG)
VALUES('TRANSACCION_DSCTO_SEGMENTACION', '8', SYSDATE, NULL);

COMMIT;
