insert into PCLUB.ADMPT_PROCESO (ADMPV_IDPROC, ADMPV_DESC, ADMPV_ESTADO, ADMPD_FEC_REG, ADMPV_USU_REG, ADMPD_FEC_MOD, ADMPV_USU_MOD)
values ('RP', 'Venta Reposición Prepago - DAC', 'A', SYSDATE, 'ADMIN', null, '');

insert into PCLUB.ADMPT_PROCESO (ADMPV_IDPROC, ADMPV_DESC, ADMPV_ESTADO, ADMPD_FEC_REG, ADMPV_USU_REG, ADMPD_FEC_MOD, ADMPV_USU_MOD)
values ('RD', 'Venta Renovación Postpago - DAC', 'A', SYSDATE, 'ADMIN', null, '');

insert into PCLUB.ADMPT_PROC_CANJE (ADMPV_IDPROC, ADMPV_COD_TPOCL, ADMPV_PRIORIDAD, ADMV_USR_REG, ADMV_USR_MOD, ADMD_FEC_REG, ADMD_FEC_MOD)
values ('RP', '3', 1, 'ADMIN', '', SYSDATE, null);

insert into PCLUB.ADMPT_PROC_CANJE (ADMPV_IDPROC, ADMPV_COD_TPOCL, ADMPV_PRIORIDAD, ADMV_USR_REG, ADMV_USR_MOD, ADMD_FEC_REG, ADMD_FEC_MOD)
values ('RP', '1', 2, 'ADMIN', '', SYSDATE, null);

insert into PCLUB.ADMPT_PROC_CANJE (ADMPV_IDPROC, ADMPV_COD_TPOCL, ADMPV_PRIORIDAD, ADMV_USR_REG, ADMV_USR_MOD, ADMD_FEC_REG, ADMD_FEC_MOD)
values ('RP', '2', 2, 'ADMIN', '', SYSDATE, null);

insert into PCLUB.ADMPT_PROC_CANJE (ADMPV_IDPROC, ADMPV_COD_TPOCL, ADMPV_PRIORIDAD, ADMV_USR_REG, ADMV_USR_MOD, ADMD_FEC_REG, ADMD_FEC_MOD)
values ('RP', '7', 3, 'ADMIN', '', SYSDATE, null);

insert into PCLUB.ADMPT_PROC_CANJE (ADMPV_IDPROC, ADMPV_COD_TPOCL, ADMPV_PRIORIDAD, ADMV_USR_REG, ADMV_USR_MOD, ADMD_FEC_REG, ADMD_FEC_MOD)
values ('RP', '6', 4, 'ADMIN', '', SYSDATE, null);

insert into PCLUB.ADMPT_PROC_CANJE (ADMPV_IDPROC, ADMPV_COD_TPOCL, ADMPV_PRIORIDAD, ADMV_USR_REG, ADMV_USR_MOD, ADMD_FEC_REG, ADMD_FEC_MOD)
values ('VR', '2', 1, 'ADMIN', '', SYSDATE, null);

insert into PCLUB.ADMPT_PROC_CANJE (ADMPV_IDPROC, ADMPV_COD_TPOCL, ADMPV_PRIORIDAD, ADMV_USR_REG, ADMV_USR_MOD, ADMD_FEC_REG, ADMD_FEC_MOD)
values ('VR', '1', 1, 'ADMIN', '', SYSDATE, null);

insert into PCLUB.ADMPT_PROC_CANJE (ADMPV_IDPROC, ADMPV_COD_TPOCL, ADMPV_PRIORIDAD, ADMV_USR_REG, ADMV_USR_MOD, ADMD_FEC_REG, ADMD_FEC_MOD)
values ('VR', '3', 2, 'ADMIN', '', SYSDATE, null);

insert into PCLUB.ADMPT_PROC_CANJE (ADMPV_IDPROC, ADMPV_COD_TPOCL, ADMPV_PRIORIDAD, ADMV_USR_REG, ADMV_USR_MOD, ADMD_FEC_REG, ADMD_FEC_MOD)
values ('VR', '7', 3, 'ADMIN', '', SYSDATE, null);

insert into PCLUB.ADMPT_PROC_CANJE (ADMPV_IDPROC, ADMPV_COD_TPOCL, ADMPV_PRIORIDAD, ADMV_USR_REG, ADMV_USR_MOD, ADMD_FEC_REG, ADMD_FEC_MOD)
values ('VR', '6', 4, 'ADMIN', '', SYSDATE, null);

COMMIT;