--ELIMINAR LOS REGISTROS DE LA TABLA ERRORES
TRUNCATE TABLE PCLUB.ADMPT_ERRORES_CC;

DELETE FROM PCLUB.ADMPT_CONCEPTO
WHERE ADMPV_COD_CPTO IN ('59','53','60','54','55','56','57','58','62','63','64','65','66','67','68','69','70','71','72','73','74','75','76','77','78','79','80');

DELETE FROM PCLUB.ADMPT_TIPO_DOC
WHERE ADMPV_COD_TPDOC='6';

TRUNCATE TABLE PCLUB.ADMPT_TIPOSERV_DTH_HFC;

DELETE FROM PCLUB.ADMPT_CAT_CLIENTE
WHERE ADMPN_COD_CATCLI=2
AND ADMPV_COD_TPOCL='6';

DELETE FROM PCLUB.ADMPT_CAT_CLIENTE
WHERE ADMPN_COD_CATCLI=2
AND ADMPV_COD_TPOCL='7';

DELETE FROM PCLUB.ADMPT_PREMIO WHERE ADMPV_COD_TPOPR='22';
DELETE FROM PCLUB.ADMPT_TIPO_PREMIO WHERE ADMPV_COD_TPOPR='22';

DELETE FROM PCLUB.ADMPT_TIPO_PREMCLIE WHERE ADMPV_COD_TPOPR='22';

DELETE FROM PCLUB.ADMPT_TIPO_CLIENTE
WHERE ADMPV_COD_TPOCL IN ('6','7');

DELETE FROM PCLUB.ADMPT_TRANSAC_X_CLIENTE
WHERE ADMPV_TRANSACCION='TRANSACCION_PROMO_REGULARIZ';
   
DELETE FROM PCLUB.ADMPT_TRANSAC_X_CLIENTE
WHERE ADMPV_TRANSACCION='TRANSACCION_CANJE';
   
DELETE FROM PCLUB.ADMPT_TRANSAC_X_CLIENTE
WHERE ADMPV_TRANSACCION='TRANSACCION_TRANSFERENCIA';

DELETE FROM PCLUB.ADMPT_TRANSAC_X_CLIENTE
WHERE ADMPV_TRANSACCION='TRANSACCION_CON_CANJE';

COMMIT;