
UPDATE  PCLUB.ADMPT_TIPO_DOC
SET ADMPV_EQU_FIJA=NULL
WHERE ADMPV_COD_TPDOC='1'; 

UPDATE  PCLUB.ADMPT_TIPO_DOC
SET ADMPV_EQU_FIJA=NULL
WHERE ADMPV_COD_TPDOC='2'; 

UPDATE  PCLUB.ADMPT_TIPO_DOC
SET ADMPV_EQU_FIJA=NULL
WHERE ADMPV_COD_TPDOC='4'; 

UPDATE  PCLUB.ADMPT_TIPO_DOC
SET ADMPV_EQU_FIJA=NULL
WHERE ADMPV_COD_TPDOC='5'; 

COMMIT;