DELETE PCLUB.ADMPT_CONCEPTO C
WHERE C.ADMPV_COD_CPTO='52';

DELETE PCLUB.ADMPT_PARAMSIST P
WHERE P.ADMPC_COD_PARAM IN ('205','220','221');


DELETE PCLUB.ADMPT_TRANSAC_X_CLIENTE
WHERE ADMPV_TRANSACCION='TRANSACCION_PROMO_REGULARIZ' AND
           ADMPV_COD_TPOCL=  '6';
     
DELETE PCLUB.ADMPT_TRANSAC_X_CLIENTE
WHERE ADMPV_TRANSACCION='TRANSACCION_CANJE' AND
           ADMPV_COD_TPOCL=  '6';
 
DELETE PCLUB.ADMPT_TRANSAC_X_CLIENTE
WHERE ADMPV_TRANSACCION='TRANSACCION_TRANSFERENCIA' AND
           ADMPV_COD_TPOCL=  '6';
    
DELETE PCLUB.ADMPT_TRANSAC_X_CLIENTE
WHERE ADMPV_TRANSACCION='TRANSACCION_ESTADO_CUENTA' AND
           ADMPV_COD_TPOCL=  '6'; 
 
DELETE PCLUB.ADMPT_TRANSAC_X_CLIENTE
WHERE ADMPV_TRANSACCION='TRANSACCION_CON_CANJE' AND
           ADMPV_COD_TPOCL=  '6'; 

DELETE PCLUB.ADMPT_TIPO_PREMCLIE
WHERE ADMPV_COD_TPOPR='21'
AND ADMPV_COD_TPOCL='6';
        
DELETE PCLUB.ADMPT_PREMIO
WHERE ADMPV_COD_TPOPR='21';

DELETE PCLUB.ADMPT_TIPO_PREMIO
WHERE ADMPV_COD_TPOPR='21';

DELETE FROM PCLUB. ADMPT_ERRORES_CC WHERE ADMPN_COD_ERROR =32;
DELETE FROM PCLUB. ADMPT_ERRORES_CC WHERE ADMPN_COD_ERROR =33;

COMMIT;