/* Se necesita antiguos insert de la tabla PCLUB.ADMPT_TIPO_PREMIO*/


-- Eleminamos registros de tipo cliente IB y Postpago
DELETE FROM PCLUB.ADMPT_TIPO_CLIENTE WHERE ADMPV_COD_TPOCL = '5';

DELETE FROM PCLUB.ADMPT_TIPO_CLIENTE WHERE ADMPV_COD_TPOCL = '2';

COMMIT;

-- Eliminamos regristros de conceptos
DELETE FROM PCLUB.ADMPT_CONCEPTO WHERE ADMPV_COD_CPTO = '14';

DELETE FROM PCLUB.ADMPT_CONCEPTO WHERE ADMPV_COD_CPTO = '15';

DELETE FROM PCLUB.ADMPT_CONCEPTO WHERE ADMPV_COD_CPTO = '16';

COMMIT;

-- Eliminamos registros de parametros
DELETE FROM PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'PUNTO_CC_BONOREN_ESPECIAL';

DELETE FROM PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'V_SEGMENTO';

DELETE FROM PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'V_PERIODO';

DELETE FROM PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC = 'CONSIDERA_PUNTOS_IB';

COMMIT;

DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MINONNET80';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S6DSCEQSOL30';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S6DSCEQSOL300';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S6DSCEQSOL40';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S6DSCEQSOL400';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S6DSCEQSOL5';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S6DSCEQSOL50';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S6DSCEQSOL600';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'SMSCD10';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'SMSCD100';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'SMSCD1000';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'SMSCD20';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCEQSOL100';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCEQSOL20';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCEQSOL200';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCEQSOL30';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCEQSOL300';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCEQSOL40';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCEQSOL400';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCEQSOL50';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCEQSOL600';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00002';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00006';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00024';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00063';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00112';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00113';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00144';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00157';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00280';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00295';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00298';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00343';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00419';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00447';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00456';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00457';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00461';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00464';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00466';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00518';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00578';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MINONNET10';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MINONNET100';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MINONNET25';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MINONNET40';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MINONNET65';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'RECSOL10';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'RECSOL120';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'RECSOL20';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'RECSOL30';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'RECSOL40';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'RECSOL60';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S1DSCEQSOL10';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S1DSCEQSOL100';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S1DSCEQSOL20';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S1DSCEQSOL200';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S1DSCEQSOL30';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S1DSCEQSOL300';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S1DSCEQSOL40';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S1DSCEQSOL400';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S1DSCEQSOL5';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S1DSCEQSOL50';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S1DSCEQSOL600';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S2DSCEQSOL10';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S2DSCEQSOL100';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S2DSCEQSOL20';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S2DSCEQSOL200';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S2DSCEQSOL30';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S2DSCEQSOL300';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S2DSCEQSOL40';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S2DSCEQSOL400';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S2DSCEQSOL5';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S2DSCEQSOL50';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S2DSCEQSOL600';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S3DSCEQSOL10';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S3DSCEQSOL100';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S3DSCEQSOL20';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S3DSCEQSOL200';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S3DSCEQSOL30';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S3DSCEQSOL300';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S3DSCEQSOL40';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S3DSCEQSOL400';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S3DSCEQSOL5';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S3DSCEQSOL50';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S3DSCEQSOL600';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S4DSCEQSOL10';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S4DSCEQSOL100';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S4DSCEQSOL20';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S4DSCEQSOL200';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S4DSCEQSOL30';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S4DSCEQSOL300';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S4DSCEQSOL40';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S4DSCEQSOL400';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S4DSCEQSOL5';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S4DSCEQSOL50';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S4DSCEQSOL600';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S5DSCEQSOL10';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S5DSCEQSOL100';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S5DSCEQSOL20';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S5DSCEQSOL200';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S5DSCEQSOL30';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S5DSCEQSOL300';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S5DSCEQSOL40';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S5DSCEQSOL400';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S5DSCEQSOL5';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S5DSCEQSOL50';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S5DSCEQSOL600';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S6DSCEQSOL10';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S6DSCEQSOL100';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S6DSCEQSOL20';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'S6DSCEQSOL200';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'SMSCD200';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'SMSCD300';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'SMSCD400';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'SMSCD50';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'SMSCD500';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'RECPOSSOL20';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'BONRENESPE';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'RECPOSSOL10';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'RECPOSSOL30';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'RECPOSSOL40';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'RECPOSSOL60';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'RECPOSSOL120';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCALTAEQ1';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCALTAEQ5';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCALTAEQ10';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCALTAEQ20';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCALTAEQ30';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCALTAEQ40';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCALTAEQ50';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCALTAEQ100';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCALTAEQ200';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCALTAEQ300';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCALTAEQ400';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCALTAEQ600';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'COMBMER01';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'COMBMER02';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'COMBMER03';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCREPST5';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCREPST600';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCREPST400';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCREPST300';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCREPST200';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCREPST100';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCREPST50';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCREPST40';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCREPST30';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCREPST20';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'DSCREPST10';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00707';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00710';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00711';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00712';
DELETE FROM PCLUB.ADMPT_PREMIO_TEST P WHERE ADMPV_ID_PROCLA = 'MECLA00713';

COMMIT;

