--SCRIPTS  		:	ELIMINACION DE DATOS INSERTADORS
--AUTOR			:	HENRY HERRERA CH
--PROPOSITO		:	ELIMINACION DE DATOS

DELETE  FROM PCLUB.ADMPT_PROMOCION;
DELETE 	FROM PCLUB.ADMPT_PREMIO_PROMO ;
DELETE 	FROM PCLUB.ADMPT_TIP_PREMIOPROMO;
DELETE	FROM PCLUB.ADMPT_PARAMSIST WHERE ADMPV_DESC='MAX_PREMIO_PROMO';
DELETE  FROM PCLUB.ADMPT_MENSAJE WHERE ADMPV_VALOR='PROMOCIONRULETA';
COMMIT;
