--SCRIPTS    :  ELIMINACION DE DATOS INSERTADOS EN TABLAS : ADMPT_TIPO_PREMIO Y ADMPT_PREMIO
--AUTOR      :  SUSANA RAMOS G
--PROPOSITO  :  ELIMINACION DE DATOS


/*------DATOS TIPO PREMIO POR CLIENTE-------*/
DELETE FROM PCLUB.ADMPT_TIPO_PREMCLIE WHERE ADMPV_COD_TPOPR IN ('20');

/*------------ DATOS PREMIO----------------*/
DELETE  FROM PCLUB.ADMPT_PREMIO WHERE admpv_cod_tpopr IN ('12','20');

/*------------ DATOS TIPO DE PREMIO----------*/
DELETE FROM PCLUB.admpt_tipo_premio WHERE admpv_cod_tpopr IN ('20');

COMMIT;
