
    DELETE PCLUB.ADMPT_MENSAJE
    WHERE ADMPN_COD_SMS BETWEEN 15 AND 28;

   DELETE PCLUB.ADMPT_PARAMSIST
   WHERE ADMPC_COD_PARAM IN ('210','211','212','213','214','215');
   
   DELETE PCLUB.ADMPT_TIPOS
   WHERE ADMPV_COD_TIPO IN ('7','8');
   
   COMMIT;