grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_LOY_CANJE to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_LOY_CANJEDET to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_LOY_CLIENTE to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_LOY_MOVTOS to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_LOY_SALDOS to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_LOY_DETMOVSAL to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_CAT_CONCEPTO to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_DETCAT_CONCEPTO to USRPCLUB;

grant EXECUTE on PCLUB.PKG_CC_IMPLOYALTY to USRPCLUB;
