grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_AUX_PAGO_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_TMP_PAGO_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_IMP_PAGO_CC to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_AUX_ALTACON_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_TMP_ALTACON_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_IMP_ALTACON_CC to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_AUX_ALTACLI_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_TMP_ALTACLI_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_IMP_ALTACLI_CC to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_AUX_PROM to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_TMP_PROM to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_IMP_PROM to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_AUX_ANIV to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_TMP_ANIV to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_IMP_ANIV to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_AUX_CMBTIT_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_TMP_CMBTIT_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_IMP_CMBTIT_CC to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_AUX_RENCONT_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_TMP_RENCONT_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_IMP_RENCONT_CC to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_AUX_BAJACLI_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_TMP_BAJACLI_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_IMP_BAJACLI_CC to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_AUX_NOFACT_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_TMP_NOFACT_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_IMP_NOFACT_CC to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_AUX_PRXRCON_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_TMP_PRXRCON_CC to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_IMP_PRXRCON_CC to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_EXP_PROXRCO_CC to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_AUX_REGULARIZA to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_TMP_REGULARIZA to USRPCLUB;
grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_IMP_REGULARIZA to USRPCLUB;

grant DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_EXP_PTOFACTUR to USRPCLUB;

grant EXECUTE on PCLUB.PKG_CC_PROCACUMULA to USRPCLUB;

grant SELECT on pclub.ADMPT_PAGOCC_SQ to USRPCLUB;
grant SELECT on pclub.ADMPT_ALTACONT_SQ to USRPCLUB;
grant SELECT on pclub.ADMPT_ALTACLI_SQ to USRPCLUB;
grant SELECT on pclub.ADMPT_PROM_SQ to USRPCLUB;
grant SELECT on pclub.ADMPT_ANIV_SQ to USRPCLUB;
grant SELECT on pclub.ADMPT_CAMBIOTT_SQ to USRPCLUB;
grant SELECT on pclub.ADMPT_RENCONT_SQ to USRPCLUB;
grant SELECT on pclub.admpt_baja_sq to USRPCLUB;
grant SELECT on pclub.admpt_nofac_sq to USRPCLUB;
grant SELECT on pclub.ADMPT_PRXRCON_SQ to USRPCLUB;
grant SELECT on pclub.Admpt_Expproxren_Sq to USRPCLUB;
grant SELECT on pclub.ADMPT_REGULA_SQ to USRPCLUB;

