GRANT EXECUTE ON PCLUB.PKG_CC_CANJEVTA TO USREAIPCLUB;
GRANT EXECUTE ON PCLUB.T_SALDOXTIPOCLIE TO USREAIPCLUB;
GRANT EXECUTE ON PCLUB.T_TBLSALDOXTIPOCLIE TO USREAIPCLUB;
GRANT EXECUTE ON PCLUB.PKG_CC_CANJEVTA TO USRSISACT;
GRANT EXECUTE ON PCLUB.PKG_CC_TRANSACCION TO USRSISACT;