--usuario USRPCLUB(ejecuta las shells), debe tener acceso sobre PKG_CC_BONOS:
GRANT EXECUTE ON PCLUB.PKG_CC_BONOS TO USRPCLUB;

--acceso total sobre las tablas temporales de carga de datos:
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_ALTA_XRECARGA_PRE TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_BONOFIDEL_PRE TO USRPCLUB;

GRANT EXECUTE ON PCLUB.PKG_CC_BONOS TO USRCLAROCLUB;
GRANT EXECUTE ON PCLUB.PKG_CC_BONOS TO USREAIPCLUB;
GRANT EXECUTE ON PCLUB.PKG_CC_BONOS TO USPROCPCLUB;
