GRANT EXECUTE ON PCLUB.PKG_CC_CONSULTA TO USREAIPCLUB;

--PERMISOS PARA EL USUSARIO PARA USO DE TABLAS TEMPORALES DE LOS SHELL(SQLLOADER)
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_ALTACLI_DTH TO  USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_PAGO_DTH TO  USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_BAJACLI_DTH TO  USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_ANIVERSDTH TO  USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_CAMBTIT_DTH TO  USRPCLUB;

--PERMISOS PARA EL USUSARIO PARA INSERCION EN TABLAS TEMPORALES DE LOS SHELL(SQLLOADER) - HFC
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_ALTACLI_HFC TO  USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_PAGO_HFC TO  USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_PROM_DTH_HFC TO  USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_REGDTH_HFC TO  USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_CAMBTIT_HFC TO  USRPCLUB;
--REGULARIZACION PARA HFC
GRANT EXECUTE ON PCLUB.PEDIDO_HFC TO USREAIPCLUB;
GRANT EXECUTE ON PCLUB.LISTA_PEDIDO_HFC TO USREAIPCLUB;
GRANT EXECUTE ON PCLUB.CLI_PRODUCTO TO USREAIPCLUB;
GRANT EXECUTE ON PCLUB.LISTA_CLI_PRODUCTO TO USREAIPCLUB;
GRANT EXECUTE ON PCLUB.PKG_CC_TRANSACCIONFIJA TO USREAIPCLUB;

