--usuario del aplicativo debe tener acceso para la ejecución del paquete PKG_CC_ENCUESTA
GRANT EXECUTE ON PCLUB.PKG_CC_ENCUESTA TO USRCLAROCLUB;

--PERMISO PARA EL USUARIO USREAIPCLUB(INTEGRACION) SOBRE EL PAQUETE PKG_CC_ENCUESTA
GRANT EXECUTE ON PCLUB.PKG_CC_ENCUESTA TO USREAIPCLUB;

--usuario USRPCLUB(ejecuta las shells), debe tener acceso sobre PKG_CC_ENCUESTA:
GRANT EXECUTE ON PCLUB.PKG_CC_ENCUESTA TO USRPCLUB;

-- usuario del aplicativo debe tener acceso total sobre las tablas de encuesta
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_ENCUESTA TO USRCLAROCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_PREGUNTA TO USRCLAROCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_RESPUESTA TO USRCLAROCLUB;

--Usuario que se conectan directamente a las Tablas via Shells
GRANT SELECT ON PCLUB.ADMPT_CABENCUESTA TO USRPCLUB;
GRANT SELECT ON PCLUB.ADMPT_MOVENCUESTA TO USRPCLUB;