GRANT EXECUTE ON fidelidad.CC_PKG_FID_CHURN TO usrfidelidad;

GRANT SELECT,INSERT,DELETE,UPDATE ON fidelidad.CPRET_MOVCHURN TO usrfidelidad;
GRANT SELECT,INSERT,DELETE,UPDATE ON fidelidad.CPRET_TMP_MOVCHURN TO usrfidelidad;
GRANT SELECT,INSERT,DELETE,UPDATE ON fidelidad.CPRET_TMP_REP_MOVCHURN TO usrfidelidad;