--usuario USRPCLUB(ejecuta las shells), debe tener acceso sobre PKG_CC_PTOSTFI:
GRANT EXECUTE ON PCLUB.PKG_CC_PTOSTFI TO USRPCLUB;

--usuario USRCLAROCLUB(ejecuta el aplicativo), debe tener acceso sobre PKG_CC_TRANSACCION:
GRANT EXECUTE ON PCLUB.PKG_CC_TRANSACCION TO USRCLAROCLUB;

--acceso total sobre las tablas temporales de carga de datos:
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_AUX_ALTACLI_TFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_AUX_ANIVERSTFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_AUX_BAJACLI_TFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_AUX_PROMOCIONTFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_AUX_RECARGATFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_AUX_REGULARIZATFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_AUX_SINRECARGATFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_ALTACLI_TFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_ANIVERSTFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_BAJACLI_TFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_PROMOCIONTFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_RECARGATFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_REGULARIZATFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_SINRECARGATFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_TFICMBTIT TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_ALTACLI_TFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_ANIVERSTFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_BAJACLI_TFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_PROMOCIONTFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_RECARGATFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_REGULARIZATFI TO USRPCLUB;
GRANT SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_SINRECARGATFI TO USRPCLUB;
