--PERMISO PARA EL USUARIO USREAIPCLUB(INTEGRACION) SOBRE EL PAQUETE PTOSFIJA
GRANT EXECUTE ON PCLUB.PKG_CC_PTOSFIJA TO USREAIPCLUB;

--PERMISO PARA EL USUARIO USREAIPCLUB(INTEGRACION) SOBRE LOS TIPOS CREADOS EN CC
GRANT EXECUTE ON PCLUB.CLI_PRODUCTO TO USREAIPCLUB;
GRANT EXECUTE ON PCLUB.LISTA_CLI_PRODUCTO TO USREAIPCLUB;

--PERMISO PARA EL USUARIO USRSGA(SGA) SOBRE EL PAQUETE PTOSFIJA
GRANT EXECUTE ON PCLUB.PKG_CC_PTOSFIJA TO USRSGA;

--PERMISO PARA EL USUARIO USRPCLUB(SHELL) SOBRE EL PAQUETE PTOSFIJA
GRANT EXECUTE ON PCLUB.PKG_CC_PTOSFIJA TO USRPCLUB;

--PERMISO PARA EL USUARIO USRCLAROCLUB(APLICATIVO) SOBRE LOS PAQUETES
GRANT EXECUTE ON PCLUB.PKG_CLAROCLUB TO USRCLAROCLUB;
GRANT EXECUTE ON PCLUB.PKG_CC_PREPAGO TO USRCLAROCLUB;
GRANT EXECUTE ON PCLUB.PKG_CC_PTOSFIJA TO USRCLAROCLUB;
GRANT EXECUTE ON PCLUB.PKG_CC_TRANSACCIONFIJA TO USRCLAROCLUB;


