GRANT EXECUTE ON FIDELIDAD.PKG_FYR_PROMOCION_TRX TO USRPROMO;
GRANT EXECUTE ON FIDELIDAD.PKG_FYR_UTILITARIO TO USRPROMO;
GRANT SELECT,INSERT,DELETE,UPDATE ON FIDELIDAD.SFYRT_PROGPROMLOTE TO USRPROMO;
GRANT EXECUTE ON FIDELIDAD.PKG_FYR_PROMOCION_TRX TO USRPROMOHFC;