--PERMISO PARA EL USUARIO USREAIPCLUB(INTEGRACION) SOBRE EL PAQUETE PTOSFIJA
REVOKE EXECUTE ON PCLUB.PKG_CC_PTOSFIJA FROM USREAIPCLUB;

--PERMISO PARA EL USUARIO USREAIPCLUB(INTEGRACION) SOBRE LOS TIPOS CREADOS EN CC
REVOKE EXECUTE ON PCLUB.CLI_PRODUCFROM FROM USREAIPCLUB;
REVOKE EXECUTE ON PCLUB.LISTA_CLI_PRODUCFROM FROM USREAIPCLUB;

--PERMISO PARA EL USUARIO USRSGA(SGA) SOBRE EL PAQUETE PTOSFIJA
REVOKE EXECUTE ON PCLUB.PKG_CC_PTOSFIJA FROM USRSGA;

--PERMISO PARA EL USUARIO USRPCLUB(SHELL) SOBRE EL PAQUETE PTOSFIJA
REVOKE EXECUTE ON PCLUB.PKG_CC_PTOSFIJA FROM USRPCLUB;

--PERMISO PARA EL USUARIO USRCLAROCLUB(APLICATIVO) SOBRE LOS PAQUETES
REVOKE EXECUTE ON PCLUB.PKG_CLAROCLUB FROM USRCLAROCLUB;
REVOKE EXECUTE ON PCLUB.PKG_CC_PREPAGO FROM USRCLAROCLUB;
REVOKE EXECUTE ON PCLUB.PKG_CC_PTOSFIJA FROM USRCLAROCLUB;
REVOKE EXECUTE ON PCLUB.PKG_CC_TRANSACCIONFIJA FROM USRCLAROCLUB;