REVOKE EXECUTE ON PCLUB.PKG_CC_CONSULTA FROM USREAIPCLUB;

--PERMISOS PARA EL USUSARIO PARA USO DE TABLAS TEMPORALES DE LOS SHELL(SQLLOADER)
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_ALTACLI_DTH FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_PAGO_DTH FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_BAJACLI_DTH FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_ANIVERSDTH FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_CAMBTIT_DTH FROM USRPCLUB;

--PERMISOS PARA EL USUSARIO PARA USO DE TABLAS TEMPORALES DE LOS SHELL(SQLLOADER) - HFC
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_ALTACLI_HFC FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_PAGO_HFC FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_PROM_DTH_HFC FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_REGDTH_HFC FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_CAMBTIT_HFC FROM  USRPCLUB;
--REGULARIZACION PARA HFC
REVOKE EXECUTE ON PCLUB.PEDIDO_HFC FROM USREAIPCLUB;
REVOKE EXECUTE ON PCLUB.LISTA_PEDIDO_HFC FROM USREAIPCLUB;
REVOKE EXECUTE ON PCLUB.CLI_PRODUCTO FROM USREAIPCLUB;
REVOKE EXECUTE ON PCLUB.LISTA_CLI_PRODUCTO FROM USREAIPCLUB;
REVOKE EXECUTE ON PCLUB.PKG_CC_TRANSACCIONFIJA FROM USREAIPCLUB;

