REVOKE DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_TIPO_PREMCLIE to USRPCLUB;

REVOKE DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_CANJE to USRPCLUB;

REVOKE DELETE, INSERT, SELECT, UPDATE ON PCLUB.ADMPT_CANJE_DETALLE to USRPCLUB;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PCLUB.ADMPT_CANJEDT_KARDEX to USRPCLUB;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PCLUB.ADMPT_DETACUTMP to USRPCLUB;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PCLUB.ADMPT_PRCANJTMP to USRPCLUB;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PCLUB.ADMPT_DETMOVTMP to USRPCLUB;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PCLUB.ADMPT_DATOSCLITMP to USRPCLUB;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PCLUB.admpt_data_temp to USRPCLUB;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PCLUB.ADMPT_PERIODO to USRPCLUB;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PCLUB.ADMPT_BON_RENOVESPEC to USRPCLUB;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PCLUB.ADMPT_EQUIPO to USRPCLUB;

REVOKE DELETE, INSERT, SELECT, UPDATE ON  PCLUB.ADMPT_SEGMENTO to USRPCLUB;

REVOKE EXECUTE on PCLUB.PKG_CC_TRANSACCION to USRPCLUB;

REVOKE SELECT on pclub.ADMPT_DTACTM_SQ to USRPCLUB;

REVOKE SELECT on pclub.ADMPT_PRCJTM_SQ to USRPCLUB;

REVOKE SELECT on PCLUB.ADMPT_BONESP_SQ to USRPCLUB;

REVOKE SELECT on pclub.ADMPT_CANJE_SQ to USRPCLUB;