REVOKE EXECUTE ON PCLUB.PKG_CC_CANJEVTA FROM USREAIPCLUB;
REVOKE EXECUTE ON PCLUB.T_TBLSALDOXTIPOCLIE FROM USREAIPCLUB;
REVOKE EXECUTE ON PCLUB.T_SALDOXTIPOCLIE FROM USREAIPCLUB;
REVOKE EXECUTE ON PCLUB.PKG_CC_CANJEVTA FROM USRSISACT;
REVOKE EXECUTE ON PCLUB.PKG_CC_TRANSACCION FROM USRSISACT;

