REVOKE EXECUTE ON FIDELIDAD.PKG_FYR_PROMOCION_TRX FROM USRPROMO;
REVOKE EXECUTE ON FIDELIDAD.PKG_FYR_UTILITARIO FROM USRPROMO;
REVOKE SELECT,INSERT,DELETE,UPDATE ON FIDELIDAD.SFYRT_PROGPROMLOTE FROM USRPROMO;
REVOKE EXECUTE ON FIDELIDAD.PKG_FYR_PROMOCION_TRX FROM USRPROMOHFC;