REVOKE EXECUTE ON fidelidad.CC_PKG_FID_CHURN FROM usrfidelidad;

REVOKE SELECT,INSERT,DELETE,UPDATE ON fidelidad.CPRET_MOVCHURN FROM usrfidelidad;
REVOKE SELECT,INSERT,DELETE,UPDATE ON fidelidad.CPRET_TMP_MOVCHURN FROM usrfidelidad;
REVOKE SELECT,INSERT,DELETE,UPDATE ON fidelidad.CPRET_TMP_REP_MOVCHURN FROM usrfidelidad;