REVOKE EXECUTE ON PCLUB.PKG_CC_BONOS FROM USRPCLUB;

REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_ALTA_XRECARGA_PRE FROM  USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_BONOFIDEL_PRE FROM  USRPCLUB;

REVOKE EXECUTE ON PCLUB.PKG_CC_BONOS FROM USRCLAROCLUB;
REVOKE EXECUTE ON PCLUB.PKG_CC_BONOS FROM USREAIPCLUB;
REVOKE EXECUTE ON PCLUB.PKG_CC_BONOS FROM USPROCPCLUB;