--usuario USRPCLUB(ejecuta las shells), debe tener acceso sobre PKG_CC_PTOSTFI:
REVOKE EXECUTE ON PCLUB.PKG_CC_PTOSTFI FROM USRPCLUB;

--usuario USRCLAROCLUB(ejecuta el aplicativo), debe tener acceso sobre PKG_CC_TRANSACCION:
REVOKE EXECUTE ON PCLUB.PKG_CC_TRANSACCION FROM USRCLAROCLUB;

--acceso total sobre las tablas temporales de carga de datos:
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_AUX_ALTACLI_TFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_AUX_ANIVERSTFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_AUX_BAJACLI_TFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_AUX_PROMOCIONTFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_AUX_RECARGATFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_AUX_REGULARIZATFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_AUX_SINRECARGATFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_ALTACLI_TFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_ANIVERSTFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_BAJACLI_TFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_PROMOCIONTFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_RECARGATFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_REGULARIZATFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_SINRECARGATFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_IMP_TFICMBTIT FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_ALTACLI_TFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_ANIVERSTFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_BAJACLI_TFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_PROMOCIONTFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_RECARGATFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_REGULARIZATFI FROM USRPCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_TMP_SINRECARGATFI FROM USRPCLUB;
