--usuario del aplicativo debe tener acceso para la ejecución del paquete PKG_CC_ENCUESTA
REVOKE EXECUTE ON PCLUB.PKG_CC_ENCUESTA FROM USRCLAROCLUB;

--PERMISO PARA EL USUARIO USREAIPCLUB(INTEGRACION) SOBRE EL PAQUETE PKG_CC_ENCUESTA
REVOKE EXECUTE ON PCLUB.PKG_CC_ENCUESTA FROM USREAIPCLUB;

--usuario USRPCLUB(ejecuta las shells), debe tener acceso sobre PKG_CC_ENCUESTA:
REVOKE EXECUTE ON PCLUB.PKG_CC_ENCUESTA FROM USRPCLUB;

-- usuario del aplicativo debe tener acceso total sobre las tablas de encuesta
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_ENCUESTA FROM USRCLAROCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_PREGUNTA FROM USRCLAROCLUB;
REVOKE SELECT,INSERT,DELETE,UPDATE ON PCLUB.ADMPT_RESPUESTA FROM USRCLAROCLUB;

--Usuario que se conectan directamente a las Tablas via Shells
REVOKE SELECT ON PCLUB.ADMPT_CABENCUESTA FROM USRPCLUB;
REVOKE SELECT ON PCLUB.ADMPT_MOVENCUESTA FROM USRPCLUB;