ALTER TABLE PCLUB.ADMPT_IMP_VTOBONO
ADD CONSTRAINT PK_VTOBONO_01 PRIMARY KEY (ADMPV_COD_CLI, ADMPN_TIP_PRE, ADMPV_COD_CTO)
USING INDEX 
TABLESPACE PCLUB_INDX
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE
(
  INITIAL 64K
  NEXT 1M
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
);