CREATE INDEX PCLUB.IDX_ESTADO_FEC_TRANS ON PCLUB.ADMPT_KARDEX (ADMPC_ESTADO, ADMPD_FEC_TRANS) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645
    PCTINCREASE 0 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT)
  TABLESPACE PCLUB_INDX;

CREATE INDEX PCLUB.IDX_FECCORTA ON PCLUB.ADMPT_BONO_KARDEX(FECCORTA) 
  PCTFREE 10 
  INITRANS 2 
  MAXTRANS 255 
  COMPUTE STATISTICS 
  STORAGE(
          INITIAL 65536 
          NEXT 1048576 
          MINEXTENTS 1 
          MAXEXTENTS 2147483645
          PCTINCREASE 0 
          FREELISTS 1 
          FREELIST GROUPS 1 
          BUFFER_POOL DEFAULT)
  TABLESPACE PCLUB_INDX;  
  
  
  CREATE INDEX PCLUB.IDX_ADMPT_TMP_PRERECARGA_02 ON PCLUB.ADMPT_TMP_PRERECARGA (ADMPV_COD_CLI) 
  PCTFREE 10 
  INITRANS 2 
  MAXTRANS 255 
  COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 
			NEXT 1048576 
			MINEXTENTS 1 
			MAXEXTENTS 2147483645
			PCTINCREASE 0 
			FREELISTS 1 
			FREELIST GROUPS 1 
			BUFFER_POOL DEFAULT)
  TABLESPACE PCLUB_INDX;