DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIENTE_SVR_001;
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIENTE_SVR_002;
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIENTE_SVR_003;
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIENTE_SVR_004;
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIENTE_SVR_005;  
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIESERV_SVR_001;
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIESERV_SVR_002;
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIESERV_SVR_003;
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIESRV_SVR_002;
DROP INDEX PCLUB.IX_ADMPT_TMP_ALTACLIESERV_001;  
DROP INDEX PCLUB.IX_ADMPT_IMP_ACLIESERV_SVR_001;
DROP INDEX PCLUB.IX_ADMPT_IMP_ACLIESERV_SVR_002;
DROP INDEX PCLUB.IX_ADMPT_IMP_ACLIESERV_SVR_003;
DROP INDEX PCLUB.IX_ADMPT_TMP_PAGO_FACT_001;
DROP INDEX PCLUB.IX_ADMPT_TMP_PAGO_FACT_002;
DROP INDEX PCLUB.IX_ADMPT_TMP_PAGO_FACT_003;
DROP INDEX PCLUB.IX_ADMPT_TMP_ANIV_CC_001;
DROP INDEX PCLUB.IX_ADMPT_TMP_ANIV_CC_002;
DROP INDEX PCLUB.IX_ADMPT_TMP_ANIV_CC_003;
DROP INDEX PCLUB.IX_ADMPT_TMP_ANIV_CC_004;  
DROP INDEX PCLUB.IDX_CONCEPTO_02;  
DROP INDEX PCLUB.IX_ADMPT_CLIENTEPRODUCTO_02;  
DROP INDEX PCLUB.IDX_CLIENTEFIJA_001;  
DROP INDEX PCLUB.IX_ADMPT_CLIENTEFIJA_001;
DROP INDEX PCLUB.IX_ADMPT_TMP_BAJA_CC_001;
DROP INDEX PCLUB.IX_ADMPT_TMP_BAJA_CC_002;
DROP INDEX PCLUB.IX_ADMPT_TMP_BAJA_CC_003;
DROP INDEX PCLUB.IX_ADMPT_TMP_BAJA_CC_004;  
DROP INDEX PCLUB.IX_ADMPT_CLIENTEFIJA_002;


DROP INDEX PCLUB.IX_ADMPT_TMP_CPLAN_HFCB_001;
DROP INDEX PCLUB.IX_ADMPT_TMP_CPLAN_HFCB_002;
DROP INDEX PCLUB.IX_ADMPT_TMP_CPLAN_HFCB_003;
DROP INDEX PCLUB.IX_ADMPT_TMP_CPLAN_HFCB_004;

DROP INDEX PCLUB.IX_ADMPT_CTL_CANJES_001;

DROP INDEX PCLUB.IX_ADMPT_ALTACLIENTE_RPT_001;
DROP INDEX PCLUB.IX_ADMPT_ALTACLIENTE_RPT_002;
DROP INDEX PCLUB.IX_ADMPT_ALTACLIENTE_RPT_003;

DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIENTE_RPT_001;
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIENTE_RPT_002;
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIENTE_RPT_003;
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIENTE_RPT_004;
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIENTE_RPT_005;
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIENTE_RPT_006;


DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIESRV_RPT_001;    
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIESRV_RPT_002;
DROP INDEX PCLUB.IX_ADMPT_TMP_ACLIESRV_RPT_003;
DROP INDEX PCLUB.IX_ADMPT_ALTACLISRV_RPT_001;
DROP INDEX PCLUB.IX_ADMPT_ALTACLISRV_RPT_002;
DROP INDEX PCLUB.IX_ADMPT_ALTACLISRV_RPT_003;


DROP INDEX PCLUB.IX_ADMPT_IMP_ACLIESERV_RPT_001;
DROP INDEX PCLUB.IX_ADMPT_IMP_ACLIESERV_RPT_002;
DROP INDEX PCLUB.IX_ADMPT_IMP_ACLIESERV_RPT_003;


DROP INDEX PCLUB.IX_ADMPT_TMP_PAGOFACT_RPT_001;
DROP INDEX PCLUB.IX_ADMPT_TMP_PAGOFACT_RPT_002;
DROP INDEX PCLUB.IX_ADMPT_TMP_PAGOFACT_RPT_003;


DROP INDEX PCLUB.IX_ADMPT_TMP_ANIV_RPT_001;
DROP INDEX PCLUB.IX_ADMPT_TMP_ANIV_RPT_002;
DROP INDEX PCLUB.IX_ADMPT_TMP_ANIV_RPT_003;
DROP INDEX PCLUB.IX_ADMPT_TMP_ANIV_RPT_004;
DROP INDEX PCLUB.IX_ADMPT_TMP_ANIV_RPT_005;
DROP INDEX PCLUB.IX_ADMPT_TMP_ANIV_RPT_006;
DROP INDEX PCLUB.IX_ADMPT_TMP_ANIV_RPT_007;