  drop index PCLUB.IX_TMP_PRESINRECARGA_01;
  drop index  PCLUB.IX_TMP_PRESINRECARGA_02;
  drop index PCLUB.IX_TMP_PRESINRECARGA_03;
  drop index PCLUB.IX_TMP_PRESINRECARGA_04;
  drop index PCLUB.IX_TMP_PRESINRECARGA_05;
  drop index PCLUB.IX_TMP_PRESINRECARGA_06;
  drop index PCLUB.IX_PREDESAFIL_NORECAR_001;
  drop index PCLUB.IX_PREDESAFIL_NORECAR_002;
  drop index PCLUB.IX_PREDESAFIL_NORECAR_003;
  drop index PCLUB.IX_PREDESAFIL_NORECAR_004;
  drop index PCLUB.IX_PREDESAFIL_NORECAR_005;
  drop index PCLUB.IX_PREDESAFIL_NORECAR_006;
  drop index PCLUB.IX_PREDESAFIL_NORECAR_007;
  drop index PCLUB.IX_PREDESAFIL_NORECAR_008;





  