-- Drop indexes-----
drop index PCLUB.IX_ADMPT_IMP_REGDTH_HFC_001;
Drop Index PCLUB.IX_ADMPT_TMP_PAGO_CC_002;
Drop Index PCLUB.IX_ADMPT_AUX_PAGO_CC_001;
Drop Index PCLUB.IX_ADMPT_AUX_PAGO_CC_002;
Drop Index PCLUB.IX_ADMPT_SMS_TELEFONOS_001;
Drop Index PCLUB.IX_ADMPT_IMP_PAGO_CC_002;
drop index PCLUB.IX_ADMPT_TMP_ALTACLI_TFI_003;

drop index PCLUB.IX_ADMPT_IMP_ALTACLI_TFI_002;

drop index PCLUB.IX_ADMPT_AUX_ALTACLI_TFI_002;
drop index PCLUB.IX_ADMPT_AUX_ALTACLI_CC_001;

drop index PCLUB.IX_ADMPT_TMP_ALTACLI_CC_001;

