
CREATE OR REPLACE TYPE PCLUB.T_BONOCONFIG AS OBJECT
(BONO VARCHAR2(20),
 PUNTOS NUMBER,
 COD_CPTO VARCHAR2(2),
 DIASVIGEN NUMBER,
 COD_TPOPR VARCHAR2(2)
);
/

CREATE OR REPLACE TYPE PCLUB.T_TBLBONOCONFIG AS TABLE OF T_BONOCONFIG;
/