/*SCRIPTS PARA LOS OBJETOS DE BD*/

CREATE OR REPLACE TYPE PCLUB.CLI_PRODUCTO AS OBJECT
(
  COD_CLI_PROD VARCHAR2(40),
  DESC_PRODUCTO VARCHAR2(40)
);

/

CREATE OR REPLACE TYPE PCLUB.LISTA_CLI_PRODUCTO
AS VARRAY (10) OF CLI_PRODUCTO;

/

--CREAR TIPOS PARA CANJES

CREATE OR REPLACE TYPE PCLUB.PEDIDO_HFC  AS OBJECT
( ProdId          VARCHAR2(15),
  Campana         VARCHAR2(200),
  Puntos          NUMBER,
  Pago            NUMBER,
  Cantidad        NUMBER,
  TipoPremio      VARCHAR2(2),
  ServComercial   NUMBER,
  MontoRecarga    Number,
  CodPaqDat       VARCHAR2(50),
  CodServTV        VARCHAR2(20)
);

/

CREATE OR REPLACE TYPE PCLUB.LISTA_PEDIDO_HFC AS VARRAY(100) OF PEDIDO_HFC;

/