CREATE SYNONYM USRPCLUB.ADMPT_AUX_ACCAMO_IB FOR PCLUB.ADMPT_AUX_ACCAMO_IB;

CREATE SYNONYM USRPCLUB.ADMPT_AUX_DEBITO_IB FOR PCLUB.ADMPT_AUX_DEBITO_IB;

CREATE SYNONYM USRPCLUB.ADMPT_AUX_FACADE_IB FOR PCLUB.ADMPT_AUX_FACADE_IB;

CREATE SYNONYM USRPCLUB.ADMPT_AUX_PROM FOR PCLUB.ADMPT_AUX_PROM;

CREATE SYNONYM USRPCLUB.ADMPT_AUX_REGULARIZA FOR PCLUB.ADMPT_AUX_REGULARIZA;

CREATE SYNONYM USRPCLUB.ADMPT_CANJE FOR PCLUB.ADMPT_CANJE;

CREATE SYNONYM USRPCLUB.ADMPT_CANJEDT_KARDEX FOR PCLUB.ADMPT_CANJEDT_KARDEX;

CREATE SYNONYM USRPCLUB.ADMPT_CANJE_DETDELETE FOR PCLUB.ADMPT_CANJE_DETALLE;

CREATE SYNONYM USRPCLUB.ADMPT_CAT_CLIENTE FOR PCLUB.ADMPT_CAT_CLIENTE;

CREATE SYNONYM USRPCLUB.ADMPT_CLIENTE FOR PCLUB.ADMPT_CLIENTE;

CREATE SYNONYM USRPCLUB.ADMPT_CLIENTEIB FOR PCLUB.ADMPT_CLIENTEIB;

CREATE SYNONYM USRPCLUB.ADMPT_CLIREF_IB FOR PCLUB.ADMPT_CLIREF_IB;

CREATE SYNONYM USRPCLUB.ADMPT_CONCEPTO FOR PCLUB.ADMPT_CONCEPTO;

CREATE SYNONYM USRPCLUB.ADMPT_EXP_PROXRCO_CC FOR PCLUB.ADMPT_EXP_PROXRCO_CC;

CREATE SYNONYM USRPCLUB.ADMPT_EXP_PUNTOS_IB_BONUS FOR PCLUB.ADMPT_EXP_PUNTOS_IB_BONUS;

CREATE SYNONYM USRPCLUB.ADMPT_EXP_TELEVNT_CC FOR PCLUB.ADMPT_EXP_TELEVNT_CC;

CREATE SYNONYM USRPCLUB.ADMPT_IMP_ACCAMO_IB FOR PCLUB.ADMPT_IMP_ACCAMO_IB;

CREATE SYNONYM USRPCLUB.ADMPT_IMP_ALTACLI_CC FOR PCLUB.ADMPT_IMP_ALTACLI_CC;

CREATE SYNONYM USRPCLUB.ADMPT_IMP_ALTACON_CC FOR PCLUB.ADMPT_IMP_ALTACON_CC;

CREATE SYNONYM USRPCLUB.ADMPT_IMP_BAJACLI_CC FOR PCLUB.ADMPT_IMP_BAJACLI_CC;

CREATE SYNONYM USRPCLUB.ADMPT_IMP_BONTRAN_CC FOR PCLUB.ADMPT_IMP_BONTRAN_CC;

CREATE SYNONYM USRPCLUB.ADMPT_IMP_CMBTIT_CC FOR PCLUB.ADMPT_IMP_CMBTIT_CC;

CREATE SYNONYM USRPCLUB.ADMPT_IMP_DEBITO_IB FOR PCLUB.ADMPT_IMP_DEBITO_IB;

CREATE SYNONYM USRPCLUB.ADMPT_IMP_FACADE_IB FOR PCLUB.ADMPT_IMP_FACADE_IB;

CREATE SYNONYM USRPCLUB.ADMPT_IMP_NOFACT_CC FOR PCLUB.ADMPT_IMP_NOFACT_CC;

CREATE SYNONYM USRPCLUB.ADMPT_IMP_PAGO_CC FOR PCLUB.ADMPT_IMP_PAGO_CC;

CREATE SYNONYM USRPCLUB.ADMPT_IMP_PROM FOR PCLUB.ADMPT_IMP_PROM FOR PCLUB;

CREATE SYNONYM USRPCLUB.ADMPT_IMP_PRXRCON_CC FOR PCLUB.ADMPT_IMP_PRXRCON_CC;

CREATE SYNONYM USRPCLUB.ADMPT_IMP_REGULARIZA FOR PCLUB.ADMPT_IMP_REGULARIZA;

CREATE SYNONYM USRPCLUB.ADMPT_IMP_RENCONT_CC FOR PCLUB.ADMPT_IMP_RENCONT_CC;

CREATE SYNONYM USRPCLUB.ADMPT_KARDEX FOR PCLUB.ADMPT_KARDEX;

CREATE SYNONYM USRPCLUB.ADMPT_PARAMSIST FOR PCLUB.ADMPT_PARAMSIST;

CREATE SYNONYM USRPCLUB.ADMPT_PREMIO FOR PCLUB.ADMPT_PREMIO;

CREATE SYNONYM USRPCLUB.ADMPT_SALDOS_CLIENTE FOR PCLUB.ADMPT_SALDOS_CLIENTE;

CREATE SYNONYM USRPCLUB.ADMPT_SEG_CLIENTE FOR PCLUB.ADMPT_SEG_CLIENTE;

CREATE SYNONYM USRPCLUB.ADMPT_SEG_PREMIO FOR PCLUB.ADMPT_SEG_PREMIO;

CREATE SYNONYM USRPCLUB.ADMPT_TIPO_CLIENTE FOR PCLUB.ADMPT_TIPO_CLIENTE;

CREATE SYNONYM USRPCLUB.ADMPT_TIPO_DOC FOR PCLUB.ADMPT_TIPO_DOC;

CREATE SYNONYM USRPCLUB.ADMPT_TIPO_PLAN FOR PCLUB.ADMPT_TIPO_PLAN;

CREATE SYNONYM USRPCLUB.ADMPT_TIPO_PREMIO FOR PCLUB.ADMPT_TIPO_PREMIO;

CREATE SYNONYM USRPCLUB.ADMPT_TMP_ACCAMO_IB FOR PCLUB.ADMPT_TMP_ACCAMO_IB;

CREATE SYNONYM USRPCLUB.ADMPT_TMP_ALTACLI_CC FOR PCLUB.ADMPT_TMP_ALTACLI_CC;

CREATE SYNONYM USRPCLUB.ADMPT_TMP_BONAC FOR PCLUB.ADMPT_TMP_BONAC;

CREATE SYNONYM USRPCLUB.ADMPT_TMP_CMBTIT_CC FOR PCLUB.ADMPT_TMP_CMBTIT_CC;

CREATE SYNONYM USRPCLUB.ADMPT_TMP_DEBITO_IB FOR PCLUB.ADMPT_TMP_DEBITO_IB;

CREATE SYNONYM USRPCLUB.ADMPT_TMP_FACADE_IB FOR PCLUB.ADMPT_TMP_FACADE_IB;

CREATE SYNONYM USRPCLUB.ADMPT_TMP_PAGO_CC FOR PCLUB.ADMPT_TMP_PAGO_CC;

CREATE SYNONYM USRPCLUB.ADMPT_TMP_PROM FOR PCLUB.ADMPT_TMP_PROM;

CREATE SYNONYM USRPCLUB.ADMPT_TMP_REGULARIZA FOR PCLUB.ADMPT_TMP_REGULARIZA;







CREATE SYNONYM USRPCLUB.PKG_CLAROCLUB FOR PCLUB.PKG_CLAROCLUB;



CREATE SYNONYM USRPCLUB.ADMPT_AACAMO_SQ FOR PCLUB.ADMPT_AACAMO_SQ;

CREATE SYNONYM USRPCLUB.ADMPT_AFACAD_SQ FOR PCLUB.ADMPT_AFACAD_SQ;

CREATE SYNONYM USRPCLUB.ADMPT_AFACAD_SQ FOR PCLUB.ADMPT_AFACAD_SQ;

CREATE SYNONYM USRPCLUB.ADMPT_CLI_CC_SQ FOR PCLUB.ADMPT_CLI_CC_SQ;

CREATE SYNONYM USRPCLUB.ADMPT_CLI_IB_SQ FOR PCLUB.ADMPT_CLI_IB_SQ;

CREATE SYNONYM USRPCLUB.ADMPT_DEB_IB_SQ FOR PCLUB.ADMPT_DEB_IB_SQ;

CREATE SYNONYM USRPCLUB.ADMPT_KARDEX_SQ FOR PCLUB.ADMPT_KARDEX_SQ;

CREATE SYNONYM USRPCLUB.ADMPT_PROM_SQ FOR PCLUB.ADMPT_PROM_SQ;

CREATE SYNONYM USRPCLUB.ADMPT_REGULA_SQ FOR PCLUB.ADMPT_REGULA_SQ;

CREATE SYNONYM USRPCLUB.ADMPT_SLD_CL_SQ FOR PCLUB.ADMPT_SLD_CL_SQ;

CREATE SYNONYM USRPCLUB.ADMPT_T_PLAN_SQ FOR PCLUB.ADMPT_T_PLAN_SQ;
