CREATE SYNONYM USRPCLUB.PKG_CC_TRANSACCION FOR PCLUB.PKG_CC_TRANSACCION;

CREATE SYNONYM USRPCLUB.ADMPT_DTACTM_SQ FOR PCLUB.ADMPT_DTACTM_SQ;

CREATE SYNONYM USRPCLUB.ADMPT_PRCJTM_SQ FOR PCLUB.ADMPT_PRCJTM_SQ;

CREATE SYNONYM USRPCLUB.ADMPT_BONESP_SQ FOR PCLUB.ADMPT_BONESP_SQ;

CREATE SYNONYM USRPCLUB.ADMPT_CANJE_SQ FOR PCLUB.ADMPT_CANJE_SQ; 