DROP SYNONYM USRPCLUB.PKG_CC_TRANSACCION;

DROP SYNONYM USRPCLUB.ADMPT_DTACTM_SQ;

DROP SYNONYM USRPCLUB.ADMPT_PRCJTM_SQ;

DROP SYNONYM USRPCLUB.ADMPT_BONESP_SQ;

DROP SYNONYM USRPCLUB.ADMPT_CANJE_SQ;