
/* ADMPT_CAMPANHA */

ALTER TABLE PCLUB.ADMPT_CAMPANHA
ADD ADMPV_TPO_CLIE VARCHAR2(2);

comment on column PCLUB.ADMPT_CAMPANHA.ADMPV_TPO_CLIE
  is 'COD. TIPO DE CLIENTE';

/* ADMPT_KARDEXFIJA */

ALTER TABLE PCLUB.ADMPT_KARDEXFIJA
MODIFY ADMPV_COD_CPTO VARCHAR2(3);