-- ADMPT_PREMIO
    ALTER TABLE PCLUB.ADMPT_PREMIO ADD ADMPV_IVR VARCHAR2(2);
    ALTER TABLE PCLUB.ADMPT_PREMIO ADD ADMPV_CANTIVR VARCHAR2(20);
    ALTER TABLE PCLUB.ADMPT_PREMIO ADD ADMPV_TPREMIO VARCHAR2(2);