-- ALTER TABLE 

ALTER TABLE PCLUB.ADMPT_TMP_ALTACLI_TFI
ADD admpv_cod_nv_cli VARCHAR2(40);

ALTER TABLE PCLUB.ADMPT_TMP_ALTACLI_TFI 
ADD ADMPD_FEC_ACTIV date;

ALTER TABLE PCLUB.ADMPT_TMP_ALTACLI_TFI
ADD ADMPV_TIPO_CLI VARCHAR2(3);

ALTER TABLE PCLUB.ADMPT_AUX_ALTACLI_TFI
ADD ADMPV_TIPO_CLI VARCHAR2(3);

ALTER TABLE PCLUB.ADMPT_IMP_ALTACLI_TFI
ADD admpv_cod_nv_cli VARCHAR2(40);

ALTER TABLE PCLUB.ADMPT_IMP_ALTACLI_TFI 
ADD ADMPD_FEC_ACTIV date;

ALTER TABLE PCLUB.ADMPT_IMP_ALTACLI_TFI
ADD ADMPV_TIPO_CLI VARCHAR2(3);



