-- ADMPT_PREMIO
      ALTER TABLE PCLUB.ADMPT_PREMIO DROP COLUMN ADMPV_IVR;
      ALTER TABLE PCLUB.ADMPT_PREMIO DROP COLUMN ADMPV_CANTIVR;
      ALTER TABLE PCLUB.ADMPT_PREMIO DROP COLUMN ADMPV_TPREMIO;