ALTER TABLE PCLUB.ADMPT_IMP_ACCAMO_IB ADD (ADMPD_FEC_VTA   DATE);
ALTER TABLE PCLUB.ADMPT_AUX_ACCAMO_IB ADD (ADMPD_FEC_VTA   DATE);

DROP TABLE PCLUB.ADMPT_TMP_ACCAMO_IB;
create table PCLUB.ADMPT_TMP_ACCAMO_IB
(
  ADMPC_COD_TRANS  CHAR(3),
  ADMPV_TIPO_DOC   VARCHAR2(20),
  ADMPV_NUM_DOC    VARCHAR2(20),
  ADMPV_NOM_PRI    VARCHAR2(20),
  ADMPV_NOM_SEG    VARCHAR2(20),
  ADMPV_APE_PAT    VARCHAR2(40),
  ADMPV_APE_MAT    VARCHAR2(40),
  ADMPV_NUM_LINEA  VARCHAR2(20),
  ADMPD_FEC_ACT    DATE,
  ADMPC_ACEP_BONO  CHAR(1),
  ADMPD_FEC_VTA   DATE,
  ADMPD_FEC_OPER   DATE,
  ADMPV_NOM_ARCH   VARCHAR2(150),
  ADMPC_COD_ERROR  CHAR(3),
  ADMPV_MSJE_ERROR VARCHAR2(400),
  ADMPN_SEQ        NUMBER
);

