ALTER TABLE PCLUB.ADMPT_CONCEPTO MODIFY ADMPV_COD_CPTO VARCHAR2(3);
ALTER TABLE PCLUB.ADMPT_KARDEX MODIFY ADMPV_COD_CPTO VARCHAR2(3);

ALTER TABLE PCLUB.ADMPT_KARDEX ADD ADMPN_TIP_PREMIO NUMBER;
ALTER TABLE PCLUB.ADMPT_KARDEX ADD ADMPD_FEC_VCMTO DATE;
ALTER TABLE PCLUB.ADMPT_KARDEX ADD ADMPV_USU_REG VARCHAR2(20);
ALTER TABLE PCLUB.ADMPT_KARDEX ADD ADMPV_USU_MOD VARCHAR2(20);

/* ADMPT_CANJE */
ALTER TABLE PCLUB.ADMPT_CANJE ADD ADMPN_TIPCANJE NUMBER;
ALTER TABLE PCLUB.ADMPT_CANJE ADD ADMPN_TIPPREMCJE NUMBER;

/* ADMPT_TIPO_PREMIO */
ALTER TABLE PCLUB.ADMPT_TIPO_PREMIO ADD ADMPN_GRUPO NUMBER;

/* ADMPT_IMP_PRESINRECARGA */
ALTER TABLE PCLUB.ADMPT_IMP_PRESINRECARGA ADD ADMPV_NOMARCHIVO VARCHAR2(50);
ALTER TABLE PCLUB.ADMPT_IMP_PRESINRECARGA ADD ADMPD_USU_REG VARCHAR2(20);
ALTER TABLE PCLUB.ADMPT_IMP_PRESINRECARGA ADD ADMPV_CODERROR VARCHAR2(10);
ALTER TABLE PCLUB.ADMPT_IMP_PRESINRECARGA ADD ADMPC_ESTADOSMS CHAR(1);
ALTER TABLE PCLUB.ADMPT_IMP_PRESINRECARGA ADD ADMPD_FEC_MOD DATE;
ALTER TABLE PCLUB.ADMPT_IMP_PRESINRECARGA ADD ADMPD_USU_MOD VARCHAR2(20);
ALTER TABLE PCLUB.ADMPT_IMP_PRESINRECARGA ADD ADMPD_FEC_ENVIOSMS DATE;

/* ADMPT_TMP_PRESINRECARGA */
ALTER TABLE PCLUB.ADMPT_TMP_PRESINRECARGA ADD ADMPN_SEC NUMBER NOT NULL;
ALTER TABLE PCLUB.ADMPT_TMP_PRESINRECARGA ADD ADMPV_NOMARCHIVO VARCHAR2(50) NOT NULL;
ALTER TABLE PCLUB.ADMPT_TMP_PRESINRECARGA ADD ADMPC_ESTADO CHAR(1);
ALTER TABLE PCLUB.ADMPT_TMP_PRESINRECARGA ADD ADMPV_CODERROR VARCHAR2(10);
ALTER TABLE PCLUB.ADMPT_TMP_PRESINRECARGA ADD ADMPD_FEC_REG DATE;