ALTER TABLE PCLUB.ADMPT_CANJE ADD ADMPV_COD_TIPAPL	VARCHAR2(2);
ALTER TABLE PCLUB.ADMPT_CANJE ADD ADMPV_CLAVE	VARCHAR2(100);	
ALTER TABLE PCLUB.ADMPT_CANJE ADD ADMPV_MENSAJE	VARCHAR2(50);	
ALTER TABLE PCLUB.ADMPT_CANJE ADD ADMPV_TICKET	VARCHAR2(50);	
ALTER TABLE PCLUB.ADMPT_CANJE ADD ADMPV_NUM_LINEA	VARCHAR2(20);	
ALTER TABLE PCLUB.ADMPT_CANJE ADD ADMPV_ID_GPRS	VARCHAR2(100);
ALTER TABLE PCLUB.ADMPT_PRCANJTMP ADD ADMPV_ID_GPRS	VARCHAR2(100);
ALTER TABLE PCLUB.ADMPT_TIPO_DOC ADD ADMPV_EQU_DWH 	VARCHAR2(50);