-- ALTER TABLES

-- CANJE
ALTER TABLE PCLUB.ADMPT_CANJE
ADD ADMPV_CODSEGMENTO VARCHAR2(5);

ALTER TABLE PCLUB.ADMPT_CANJE
ADD ADMPV_USU_ASEG VARCHAR2(10);

-- CANJE DETALLE
ALTER TABLE PCLUB.ADMPT_CANJE_DETALLE
ADD ADMPN_VALSEGMENTO VARCHAR2(5);

ALTER TABLE PCLUB.ADMPT_CANJE_DETALLE
ADD ADMPN_PUNTOSDSCTO NUMBER;

-- CANJE FIJA
ALTER TABLE PCLUB.ADMPT_CANJEFIJA
ADD ADMPV_CODSEGMENTO VARCHAR2(5);

ALTER TABLE PCLUB.ADMPT_CANJEFIJA
ADD ADMPV_USU_ASEG VARCHAR2(10);

-- CANJE DETALLE FIJA
ALTER TABLE PCLUB.ADMPT_CANJE_DETALLEFIJA
ADD ADMPN_VALSEGMENTO VARCHAR2(5);

ALTER TABLE PCLUB.ADMPT_CANJE_DETALLEFIJA
ADD ADMPN_PUNTOSDSCTO NUMBER;

