
CREATE TABLE PCLUB.ADMPT_TMP_CAMBTIT_DTH
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(20 BYTE),
  ADMPD_FEC_ACT       DATE,
  ADMPC_COD_ERROR     CHAR(3 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(400 BYTE),
  ADMPN_SEQ           NUMBER,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPD_FEC_OPER      DATE
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

COMMENT ON COLUMN PCLUB.ADMPT_TMP_CAMBTIT_DTH.ADMPV_COD_CLI_PROD IS 'Codigo de cliente producto';
COMMENT ON COLUMN PCLUB.ADMPT_TMP_CAMBTIT_DTH.ADMPV_NUM_DOC IS 'Nro. de documento';
COMMENT ON COLUMN PCLUB.ADMPT_TMP_CAMBTIT_DTH.ADMPD_FEC_ACT IS 'Fecha';
COMMENT ON COLUMN PCLUB.ADMPT_TMP_CAMBTIT_DTH.ADMPC_COD_ERROR IS 'Codigo de error';
COMMENT ON COLUMN PCLUB.ADMPT_TMP_CAMBTIT_DTH.ADMPV_MSJE_ERROR IS 'Descripcion de error';
COMMENT ON COLUMN PCLUB.ADMPT_TMP_CAMBTIT_DTH.ADMPN_SEQ IS 'Secuencia de carga';
COMMENT ON COLUMN PCLUB.ADMPT_TMP_CAMBTIT_DTH.ADMPV_NOM_ARCH IS 'Nombre del archivo';
COMMENT ON COLUMN PCLUB.ADMPT_TMP_CAMBTIT_DTH.ADMPD_FEC_OPER IS 'Fecha de operacion';



CREATE TABLE PCLUB.ADMPT_AUX_CAMBTIT_DTH
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(20 BYTE),
  ADMPD_FEC_ACT       DATE,
  ADMPC_COD_ERROR     CHAR(3 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(400 BYTE),
  ADMPN_SEQ           NUMBER,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPD_FEC_OPER      DATE
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );
            

CREATE TABLE PCLUB.ADMPT_IMP_CAMBTIT_DTH
(
  ADMPN_ID_FILA       NUMBER                    NOT NULL,
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(20 BYTE),
  ADMPD_FEC_ACT       DATE,
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPC_COD_ERROR     CHAR(3 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(100 BYTE),
  ADMPD_FCH_TRANS     DATE,
  ADMPN_SEQ           NUMBER
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE UNIQUE INDEX PCLUB.PK_ADMPT_IMP_CMBTIT_DTH_HFC ON PCLUB.ADMPT_IMP_CAMBTIT_DTH
(ADMPN_ID_FILA)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE PCLUB.ADMPT_IMP_CAMBTIT_DTH ADD (
  CONSTRAINT PK_ADMPT_IMP_CMBTIT_DTH_HFC
  PRIMARY KEY
  (ADMPN_ID_FILA)
  USING INDEX PCLUB.PK_ADMPT_IMP_CMBTIT_DTH_HFC);


CREATE TABLE PCLUB.ADMPT_TMP_ALTACLI_DTH
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_TIPO_DOC      VARCHAR2(20 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(20 BYTE),
  ADMPV_NOM_CLI       VARCHAR2(80 BYTE),
  ADMPV_APE_CLI       VARCHAR2(80 BYTE),
  ADMPC_SEXO          CHAR(1 BYTE),
  ADMPV_EST_CIVIL     VARCHAR2(20 BYTE),
  ADMPV_EMAIL         VARCHAR2(80 BYTE),
  ADMPV_PROV          VARCHAR2(30 BYTE),
  ADMPV_DEPA          VARCHAR2(40 BYTE),
  ADMPV_DIST          VARCHAR2(200 BYTE),
  ADMPD_FEC_ACT       DATE,
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPV_COD_ERROR     CHAR(3 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(400 BYTE),
  ADMPN_SEQ           NUMBER,
  ADMPV_CICL_FACT     VARCHAR2(2 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE TABLE PCLUB.ADMPT_AUX_ALTACLI_DTH
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_TIPO_DOC      VARCHAR2(20 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(20 BYTE),
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX PCLUB.IDX_AUXDTH_CODCLIPROD ON PCLUB.ADMPT_AUX_ALTACLI_DTH
(ADMPV_COD_CLI_PROD)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX PCLUB.IDX_AUXDTH_TIPNUM_DOC ON PCLUB.ADMPT_AUX_ALTACLI_DTH
(ADMPV_TIPO_DOC, ADMPV_NUM_DOC)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );
                      

CREATE TABLE PCLUB.ADMPT_IMP_ALTACLI_DTH
(
  ADMPV_FILA          NUMBER,
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_TIPO_DOC      VARCHAR2(20 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(20 BYTE),
  ADMPV_NOM_CLI       VARCHAR2(80 BYTE),
  ADMPV_APE_CLI       VARCHAR2(80 BYTE),
  ADMPC_SEXO          CHAR(1 BYTE),
  ADMPV_EST_CIVIL     VARCHAR2(20 BYTE),
  ADMPV_EMAIL         VARCHAR2(80 BYTE),
  ADMPV_PROV          VARCHAR2(30 BYTE),
  ADMPV_DEPA          VARCHAR2(40 BYTE),
  ADMPV_DIST          VARCHAR2(200 BYTE),
  ADMPD_FEC_ACT       DATE,
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPV_COD_ERROR     CHAR(3 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(400 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE UNIQUE INDEX PCLUB.PK_ADMPT_IMP_ALTACLI_DTH ON PCLUB.ADMPT_IMP_ALTACLI_DTH
(ADMPV_FILA)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE PCLUB.ADMPT_IMP_ALTACLI_DTH ADD (
  CONSTRAINT PK_ADMPT_IMP_ALTACLI_DTH
  PRIMARY KEY
  (ADMPV_FILA)
  USING INDEX PCLUB.PK_ADMPT_IMP_ALTACLI_DTH);


CREATE TABLE PCLUB.ADMPT_TMP_BAJACLI_DTH
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPD_FCH_BAJA      DATE,
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPC_COD_ERROR     CHAR(3 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(400 BYTE),
  ADMPN_SEQ           NUMBER
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE TABLE PCLUB.ADMPT_AUX_BAJACLI_DTH
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPD_FCH_BAJA      DATE,
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX PCLUB.IDX_BAJADTH_CODCLIPROD ON PCLUB.ADMPT_AUX_BAJACLI_DTH
(ADMPV_COD_CLI_PROD)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX PCLUB.IDX_BAJADTH_FECBAJA ON PCLUB.ADMPT_AUX_BAJACLI_DTH
(ADMPD_FCH_BAJA)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE TABLE PCLUB.ADMPT_IMP_BAJACLI_DTH
(
  ADMPN_ID_FILA       NUMBER                    NOT NULL,
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPD_FCH_BAJA      DATE,
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPC_COD_ERROR     CHAR(3 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(400 BYTE),
  ADMPD_FCH_TRANS     DATE,
  ADMPN_SEQ           NUMBER
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE UNIQUE INDEX PCLUB.PK_ADMPT_IMP_BAJACLIDTH ON PCLUB.ADMPT_IMP_BAJACLI_DTH
(ADMPN_ID_FILA)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE PCLUB.ADMPT_IMP_BAJACLI_DTH ADD (
  CONSTRAINT PK_ADMPT_IMP_BAJACLIDTH
  PRIMARY KEY
  (ADMPN_ID_FILA)
  USING INDEX PCLUB.PK_ADMPT_IMP_BAJACLIDTH);


CREATE TABLE PCLUB.ADMPT_TMP_PAGO_DTH
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_PERIODO       VARCHAR2(6 BYTE),
  ADMPN_DIAS_VENC     NUMBER,
  ADMPN_MNT_CGOFIJ    NUMBER,
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPN_PUNTOS        NUMBER,
  ADMPC_COD_ERROR     CHAR(3 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(400 BYTE),
  ADMPN_SEQ           NUMBER
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE TABLE PCLUB.ADMPT_AUX_PAGO_DTH
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_PERIODO       VARCHAR2(6 BYTE),
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX PCLUB.IDX_PAGODTH_CODCLIPROD ON PCLUB.ADMPT_AUX_PAGO_DTH
(ADMPV_COD_CLI_PROD)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX PCLUB.IDX_PAGODTH_PERIODO ON PCLUB.ADMPT_AUX_PAGO_DTH
(ADMPV_PERIODO)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );
           
 
CREATE TABLE PCLUB.ADMPT_IMP_PAGO_DTH
(
  ADMPN_ID_FILA       NUMBER                    NOT NULL,
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_PERIODO       VARCHAR2(6 BYTE),
  ADMPN_DIAS_VENC     NUMBER,
  ADMPN_MNT_CGOFIJ    NUMBER,
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPN_PUNTOS        NUMBER,
  ADMPC_COD_ERROR     CHAR(3 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(400 BYTE),
  ADMPD_FCH_TRANS     DATE,
  ADMPN_SEQ           NUMBER
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE UNIQUE INDEX PCLUB.PK_ADMPT_IMP_PAGO_DTH ON PCLUB.ADMPT_IMP_PAGO_DTH
(ADMPN_ID_FILA)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE PCLUB.ADMPT_IMP_PAGO_DTH ADD (
  CONSTRAINT PK_ADMPT_IMP_PAGO_DTH
  PRIMARY KEY
  (ADMPN_ID_FILA)
  USING INDEX PCLUB.PK_ADMPT_IMP_PAGO_DTH);
          
 
CREATE TABLE PCLUB.ADMPT_TMP_ANIVERSDTH
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_CUST_ID       VARCHAR2(40 BYTE),
  ADMPD_COD_SERV      VARCHAR2(40 BYTE),
  ADMPV_TIPO_DOC      VARCHAR2(10 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(20 BYTE),
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(400 BYTE),
  ADMPN_SEQ           NUMBER
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX PCLUB.IDX_ANIVDTH_CODCLIPROD ON PCLUB.ADMPT_TMP_ANIVERSDTH
(ADMPV_COD_CLI_PROD)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX PCLUB.IDX_ANIVDTH_FEC_OPER ON PCLUB.ADMPT_TMP_ANIVERSDTH
(ADMPD_FEC_OPER)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE TABLE PCLUB.ADMPT_AUX_ANIVERSDTH
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_CUST_ID       VARCHAR2(40 BYTE),
  ADMPD_COD_SERV      VARCHAR2(40 BYTE),
  ADMPV_TIPO_DOC      VARCHAR2(10 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(20 BYTE),
  ADMPD_FEC_OPER      DATE
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE TABLE PCLUB.ADMPT_IMP_ANIVERSDTH
(
  ADMPN_ID_FILA       NUMBER,
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_CUST_ID       VARCHAR2(40 BYTE),
  ADMPD_COD_SERV      VARCHAR2(40 BYTE),
  ADMPV_TIPO_DOC      VARCHAR2(10 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(20 BYTE),
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(400 BYTE),
  ADMPN_SEQ           NUMBER
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE UNIQUE INDEX PCLUB.PK_ADMPT_IMP_ANIVERSDTH ON PCLUB.ADMPT_IMP_ANIVERSDTH
(ADMPN_ID_FILA)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE PCLUB.ADMPT_IMP_ANIVERSDTH ADD (
  CONSTRAINT PK_ADMPT_IMP_ANIVERSDTH
  PRIMARY KEY
  (ADMPN_ID_FILA)
  USING INDEX PCLUB.PK_ADMPT_IMP_ANIVERSDTH);


ALTER TABLE PCLUB.ADMPT_AUX_PROM_DTH_HFC  
ADD (ADMPN_PTOS_ORI NUMBER);
ALTER TABLE PCLUB.ADMPT_AUX_REGDTH_HFC  
ADD(ADMPN_PTOS_ORI NUMBER);


ALTER TABLE PCLUB.ADMPT_IMP_PROM_DTH_HFC  
ADD(ADMPN_PTOS_ORI NUMBER);
ALTER TABLE PCLUB.ADMPT_IMP_REGDTH_HFC  
ADD(ADMPN_PTOS_ORI NUMBER);
