--Tabla de clientes, para registrar a clientes de tipo fijo.
CREATE TABLE PCLUB.ADMPT_CLIENTEFIJA
(
  ADMPV_COD_CLI     VARCHAR2(40 BYTE)           NOT NULL,
  ADMPV_COD_SEGCLI  VARCHAR2(2 BYTE),
  ADMPN_COD_CATCLI  NUMBER,
  ADMPV_TIPO_DOC    VARCHAR2(20 BYTE),
  ADMPV_NUM_DOC     VARCHAR2(20 BYTE),
  ADMPV_NOM_CLI     VARCHAR2(80 BYTE),
  ADMPV_APE_CLI     VARCHAR2(200 BYTE),
  ADMPC_SEXO        CHAR(1 BYTE),
  ADMPV_EST_CIVIL   VARCHAR2(20 BYTE),
  ADMPV_EMAIL       VARCHAR2(100 BYTE),
  ADMPV_PROV        VARCHAR2(50 BYTE),
  ADMPV_DEPA        VARCHAR2(40 BYTE),
  ADMPV_DIST        VARCHAR2(200 BYTE),
  ADMPD_FEC_ACTIV   DATE,
  ADMPC_ESTADO      CHAR(1 BYTE),
  ADMPV_COD_TPOCL   VARCHAR2(2 BYTE),
  ADMPD_FEC_REG     DATE                        NOT NULL,
  ADMPD_FEC_MOD     DATE,
  ADMPV_USU_REG     VARCHAR2(20 BYTE),
  ADMPV_USU_MOD     VARCHAR2(20 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPV_COD_CLI IS 'Código Cliente Formato: TipoDoc.NroDoc.TipoCliente';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPV_COD_SEGCLI IS 'Segmento del Cliente';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPN_COD_CATCLI IS 'Categoria del Cliente por default es 2 Normal';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPV_TIPO_DOC IS 'Tipo Documento';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPV_NUM_DOC IS 'Nro Documento';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPV_NOM_CLI IS 'Nombre del Cliente';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPV_APE_CLI IS 'Apellido del Cliente';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPC_SEXO IS 'Sexo';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPV_EST_CIVIL IS 'Estado Civil';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPV_EMAIL IS 'Email';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPV_PROV IS 'Provincia';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPV_DEPA IS 'Departamento';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPV_DIST IS 'Distrito';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPD_FEC_ACTIV IS 'Fecha  Registro a Claro Club';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPC_ESTADO IS 'Estado del Cliente A: Activo / B: Baja ';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEFIJA.ADMPV_COD_TPOCL IS 'Tipo Cliente (7) HFC Postpago';


ALTER TABLE PCLUB.ADMPT_CLIENTEFIJA ADD CONSTRAINT PK_ADMPT_CLIENTEFIJA
  PRIMARY KEY
  (ADMPV_COD_CLI)
  USING INDEX
    TABLESPACE PCLUB_INDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               );

CREATE INDEX PCLUB.IDX_CLIENTEFIJA_TIP_NUM_DOC ON PCLUB.ADMPT_CLIENTEFIJA
(ADMPV_NUM_DOC, ADMPV_TIPO_DOC)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


--CREACION DE TABLA CLIENTEPRODUCTO

CREATE TABLE PCLUB.ADMPT_CLIENTEPRODUCTO
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE)         NOT NULL,
  ADMPV_COD_CLI       VARCHAR2(40 BYTE),
  ADMPV_SERVICIO      VARCHAR2(20 BYTE),
  ADMPV_ESTADO_SERV   VARCHAR2(2 BYTE),
  ADMPV_FEC_ULTANIV   DATE,
  ADMPD_FEC_REG       DATE,
  ADMPV_USU_REG       VARCHAR2(20 BYTE),
  ADMPD_FEC_MOD       DATE,
  ADMPV_USU_MOD       VARCHAR2(20 BYTE),
  ADMPV_INDICEGRUPO   VARCHAR2(2 BYTE),
  ADMPV_CICL_FACT     VARCHAR2(2 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEPRODUCTO.ADMPV_COD_CLI_PROD IS 'Codigo del producto que es enviado por el SGA';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEPRODUCTO.ADMPV_COD_CLI IS 'Codigo del Cliente';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEPRODUCTO.ADMPV_SERVICIO IS 'Codigo del Servicio por ejemplo: cable, telefonia, internet';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEPRODUCTO.ADMPV_ESTADO_SERV IS 'Estado del servicio';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEPRODUCTO.ADMPV_FEC_ULTANIV IS 'Ultima fecha de entrega de puntos por aniversario';

COMMENT ON COLUMN PCLUB.ADMPT_CLIENTEPRODUCTO.ADMPV_INDICEGRUPO IS 'Agrupador de Servicio solo aplica para HFC';

ALTER TABLE PCLUB.ADMPT_CLIENTEPRODUCTO ADD CONSTRAINT PK_ADMPT_CLIENTEPRODUCTO
  PRIMARY KEY
  (ADMPV_COD_CLI_PROD)
  USING INDEX
    TABLESPACE PCLUB_INDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               );

ALTER TABLE PCLUB.ADMPT_CLIENTEPRODUCTO ADD (
  CONSTRAINT FK_ADMPV_COD_CLI_CP 
  FOREIGN KEY (ADMPV_COD_CLI) 
  REFERENCES PCLUB.ADMPT_CLIENTEFIJA (ADMPV_COD_CLI));

CREATE INDEX PCLUB.IDX_CODCLIE_CLIEPRODUCTO ON PCLUB.ADMPT_CLIENTEPRODUCTO
(ADMPV_COD_CLI)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--Modificacion de la tabla tipo_doc para agregar el campo 
ALTER TABLE PCLUB.ADMPT_TIPO_DOC
ADD ADMPV_EQU_FIJA VARCHAR2(50);


--CREACION DE LA TABLA SALDOSFIJA, CONTIENE LOS PUNTOS QUE TIENE EL CLIENTE

CREATE TABLE PCLUB.ADMPT_SALDOS_CLIENTEFIJA
(
  ADMPN_ID_SALDO      NUMBER                    NOT NULL,
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPN_COD_CLI_IB    NUMBER,
  ADMPN_SALDO_CC      NUMBER,
  ADMPN_SALDO_IB      NUMBER,
  ADMPC_ESTPTO_CC     CHAR(1 BYTE),
  ADMPC_ESTPTO_IB     CHAR(1 BYTE),
  ADMPD_FEC_REG       DATE,
  ADMPD_FEC_MOD       DATE,
  ADMPV_USU_REG       VARCHAR2(20 BYTE),
  ADMPV_USU_MOD       VARCHAR2(20 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

COMMENT ON COLUMN PCLUB.ADMPT_SALDOS_CLIENTEFIJA.ADMPN_ID_SALDO IS 'Identificador de Saldo de cliente un autonumerico';

COMMENT ON COLUMN PCLUB.ADMPT_SALDOS_CLIENTEFIJA.ADMPV_COD_CLI_PROD IS 'Codigo de cliente';

COMMENT ON COLUMN PCLUB.ADMPT_SALDOS_CLIENTEFIJA.ADMPN_COD_CLI_IB IS 'codigo de cliente IB';

COMMENT ON COLUMN PCLUB.ADMPT_SALDOS_CLIENTEFIJA.ADMPN_SALDO_CC IS 'Saldos Claro Club';

COMMENT ON COLUMN PCLUB.ADMPT_SALDOS_CLIENTEFIJA.ADMPN_SALDO_IB IS 'Saldos IBK';

COMMENT ON COLUMN PCLUB.ADMPT_SALDOS_CLIENTEFIJA.ADMPC_ESTPTO_CC IS 'Puntos Claro Club';

COMMENT ON COLUMN PCLUB.ADMPT_SALDOS_CLIENTEFIJA.ADMPC_ESTPTO_IB IS 'Puntos IBK';


ALTER TABLE PCLUB.ADMPT_SALDOS_CLIENTEFIJA ADD CONSTRAINT PK_ADMPT_SALDOS_CLIENTEFIJA
  PRIMARY KEY
  (ADMPN_ID_SALDO)
  USING INDEX
    TABLESPACE PCLUB_INDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               );


CREATE INDEX PCLUB.IDX_COD_CLIIB_SALFIJA ON PCLUB.ADMPT_SALDOS_CLIENTEFIJA
(ADMPN_COD_CLI_IB)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX PCLUB.IDX_COD_CLI_SALFIJA ON PCLUB.ADMPT_SALDOS_CLIENTEFIJA
(ADMPV_COD_CLI_PROD)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE PCLUB.ADMPT_SALDOS_CLIENTEFIJA ADD (
  CONSTRAINT FK_ADMPV_COD_CLI_PROD_CF
  FOREIGN KEY (ADMPV_COD_CLI_PROD) 
  REFERENCES PCLUB.ADMPT_CLIENTEPRODUCTO (ADMPV_COD_CLI_PROD));

--CREACION DE LA TABLA DE TIPO DE SERVICIOS PARA HFC Y DTH

CREATE TABLE PCLUB.ADMPT_TIPOSERV_DTH_HFC
(
  ADMPV_COD_TPOCL  VARCHAR2(2 BYTE)             NOT NULL,
  ADMPV_SERVICIO   VARCHAR2(20 BYTE)            NOT NULL,
  ADMPV_DESC       VARCHAR2(50 BYTE),
  ADMPN_PRIORIDAD  NUMBER
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE UNIQUE INDEX PCLUB.PK_ADMPT_TIPOSERV_DTH_HFC ON PCLUB.ADMPT_TIPOSERV_DTH_HFC
(ADMPV_COD_TPOCL, ADMPV_SERVICIO)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE PCLUB.ADMPT_TIPOSERV_DTH_HFC ADD (
  CONSTRAINT PK_ADMPT_TIPOSERV_DTH_HFC
  PRIMARY KEY
  (ADMPV_COD_TPOCL, ADMPV_SERVICIO)
  USING INDEX PCLUB.PK_ADMPT_TIPOSERV_DTH_HFC);

--Tabla de registro de parametros que se ingresan desde el SGA

CREATE TABLE PCLUB.ADMPT_IMP_PREMODIF_CLIENTE
(
  ADMPN_ID_FILA      NUMBER                     NOT NULL,
  ADMPV_FLAG         VARCHAR2(10 BYTE),
  ADMPV_COD_TPOCL    VARCHAR2(2 BYTE),
  ADMPV_COD_CLIPROD  VARCHAR2(500 BYTE),
  ADMPV_TIPO_DOC     VARCHAR2(20 BYTE),
  ADMPV_NUM_DOC      VARCHAR2(20 BYTE),
  ADMPV_COD_ERROR    CHAR(3 BYTE),
  ADMPV_MSJE_ERROR   VARCHAR2(400 BYTE),
  ADMPD_FCH_TRANS    DATE
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

--CREACION DE LA TABLA KARDEXFIJA

CREATE TABLE PCLUB.ADMPT_KARDEXFIJA
(
  ADMPN_ID_KARDEX     NUMBER                    NOT NULL,
  ADMPN_COD_CLI_IB    NUMBER,
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_COD_CPTO      VARCHAR2(2 BYTE),
  ADMPD_FEC_TRANS     DATE,
  ADMPN_PUNTOS        NUMBER,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPC_TPO_OPER      CHAR(1 BYTE),
  ADMPC_TPO_PUNTO     CHAR(1 BYTE),
  ADMPN_SLD_PUNTO     NUMBER,
  ADMPC_ESTADO        CHAR(1 BYTE),
  ADMPD_FEC_REG       DATE,
  ADMPD_FEC_MOD       DATE,
  ADMPV_DESC_PROM     VARCHAR2(200 BYTE),
  ADMPV_USU_REG       VARCHAR2(20 BYTE),
  ADMPV_USU_MOD       VARCHAR2(20 BYTE),
  ADMPV_ID_CANJE      NUMBER
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

COMMENT ON COLUMN PCLUB.ADMPT_KARDEXFIJA.ADMPN_ID_KARDEX IS 'Correlativo Kardex';

COMMENT ON COLUMN PCLUB.ADMPT_KARDEXFIJA.ADMPN_COD_CLI_IB IS 'Codigo de Cliente IBK';

COMMENT ON COLUMN PCLUB.ADMPT_KARDEXFIJA.ADMPV_COD_CLI_PROD IS 'Codigo de Cliente';

COMMENT ON COLUMN PCLUB.ADMPT_KARDEXFIJA.ADMPV_COD_CPTO IS 'Codigo del Concepto';

COMMENT ON COLUMN PCLUB.ADMPT_KARDEXFIJA.ADMPD_FEC_TRANS IS 'Fecha Transacción';

COMMENT ON COLUMN PCLUB.ADMPT_KARDEXFIJA.ADMPN_PUNTOS IS 'Puntos asignados';

COMMENT ON COLUMN PCLUB.ADMPT_KARDEXFIJA.ADMPV_NOM_ARCH IS 'Nombre del archivo que se usa en el proceso';

COMMENT ON COLUMN PCLUB.ADMPT_KARDEXFIJA.ADMPC_TPO_OPER IS 'E=Entrada, S=Salida';

COMMENT ON COLUMN PCLUB.ADMPT_KARDEXFIJA.ADMPC_TPO_PUNTO IS 'I=Interbank , C=Claroclub, L=Loyalty';

COMMENT ON COLUMN PCLUB.ADMPT_KARDEXFIJA.ADMPN_SLD_PUNTO IS 'El saldo de puntos que quedan';

COMMENT ON COLUMN PCLUB.ADMPT_KARDEXFIJA.ADMPC_ESTADO IS 'V =
Vencidos A =Activo
C = Canjeado
';

COMMENT ON COLUMN PCLUB.ADMPT_KARDEXFIJA.ADMPV_DESC_PROM IS 'Descripción de la promoción';

COMMENT ON COLUMN PCLUB.ADMPT_KARDEXFIJA.ADMPV_ID_CANJE IS 'Codigo del Canje';


ALTER TABLE PCLUB.ADMPT_KARDEXFIJA ADD CONSTRAINT PK_ADMPT_KARDEXFIJA
  PRIMARY KEY
  (ADMPN_ID_KARDEX)
  USING INDEX
    TABLESPACE PCLUB_INDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               );


CREATE INDEX PCLUB.IDX_ADMPV_COD_CLI_PROD_KF ON PCLUB.ADMPT_KARDEXFIJA
(ADMPV_COD_CLI_PROD)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX PCLUB.IDX_ADMPI_FEC_TRANSFIJA ON PCLUB.ADMPT_KARDEXFIJA
(ADMPD_FEC_TRANS)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX PCLUB.IDX_ADMPI_TIPO_OPERFIJA ON PCLUB.ADMPT_KARDEXFIJA
(ADMPC_TPO_OPER)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


--CREAR TABLA CANJEFIJA

CREATE TABLE PCLUB.ADMPT_CANJEFIJA
(
  ADMPV_ID_CANJE       NUMBER                   NOT NULL,
  ADMPV_COD_CLI        VARCHAR2(40 BYTE)        NOT NULL,
  ADMPV_PTO_VENTA      VARCHAR2(10 BYTE),
  ADMPD_FEC_CANJE      DATE,
  ADMPV_HRA_CANJE      VARCHAR2(8 BYTE),
  ADMPV_NUM_DOC        VARCHAR2(20 BYTE),
  ADMPV_COD_TPOCL      VARCHAR2(2 BYTE),
  ADMPV_COD_ASESO      VARCHAR2(16 BYTE),
  ADMPV_NOM_ASESO      VARCHAR2(60 BYTE),
  ADMPC_TPO_OPER       CHAR(1 BYTE),
  ADMPN_ID_KARDEX      NUMBER,
  ADMPV_DEV_IDCANJE    NUMBER,
  ADMPV_COD_TIPAPL     VARCHAR2(10 BYTE),
  ADMPV_CLAVE          VARCHAR2(100 BYTE),
  ADMPV_MENSAJE        VARCHAR2(1000 BYTE),
  ADMPD_FEC_REG        DATE                     NOT NULL,
  ADMPD_FEC_MOD        DATE,
  ADMPV_USU_REG        VARCHAR2(20 BYTE),
  ADMPV_USU_MOD        VARCHAR2(20 BYTE),
  ADMPV_PREMIO_LINEA   CHAR(1 BYTE),
  ADMPV_TIPO_LINEA     VARCHAR2(2 BYTE),
  ADMPV_NUM_LINEA      VARCHAR2(20 BYTE),
  ADMPV_INTERACTID     VARCHAR2(40 BYTE),
  ADMPV_NUM_LINEA_SMS  VARCHAR2(40 BYTE),
  ADMPV_COD_CLI_PROD   VARCHAR2(40 BYTE),
  ADMPV_DIREC_CLIPROD  VARCHAR2(200 BYTE),
  ADMPV_COD_SERV_SGA   VARCHAR2(40 BYTE),
  ADMPV_NOTAS          VARCHAR2(255 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          5M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_ID_CANJE IS 'CORRELATIVO CANJE FIJA';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_COD_CLI IS 'CODIGO CLIENTE FIJA';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_PTO_VENTA IS 'PUNTO DE VENTA DONDE SE REALIZÓ EL CANJE';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPD_FEC_CANJE IS 'FECHA DEL CANJE';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_HRA_CANJE IS 'HORA DEL CANJE';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_NUM_DOC IS 'NRO DOCUMENTO DEL CLIENTE';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_COD_TPOCL IS 'TIPO DE CLIENTE: (7) HFC';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_COD_ASESO IS 'CODIGO DEL ASESOR QUE REALIZA EL CANJE';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_NOM_ASESO IS 'NOMBRE DEL ASESOR QUE REALIZA EL CANJE';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPC_TPO_OPER IS 'TIPO DE OPERACION: (C) CANJE / (D) DEVOLUCION';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPN_ID_KARDEX IS 'VALIDAR SI LO VAMOS A USAR';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_DEV_IDCANJE IS 'VALIDAR SI LO VAMOS A USAR';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_COD_TIPAPL IS 'TIPO DE APLICACION QUE REGISTRA EL CANJE EJM (SISAP)';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_CLAVE IS 'CLAVE USADA EN EL CANJE VIA SMS';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_MENSAJE IS 'MENSAJE DE RTPA AL CLIENTE AL REALIZAR EL CANJE VIA SMS';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPD_FEC_REG IS 'CAMPO AUDITORIA FECHA REGISTRO';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPD_FEC_MOD IS 'CAMPO AUDITORIA FECHA ACTUALIZACION';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_USU_REG IS 'CAMPO AUDITORIA USUARIO REGISTRO';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_USU_MOD IS 'CAMPO AUDITORIA USUARIO ACTUALIZACION';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_PREMIO_LINEA IS '(1)SI INCLUYE LINEA / (0) NO INCLUYE LINEA -> LINEA /FLAG QUE IDENTIFICA SI EL CANJE INCLUYE UN PREMIO A UNA LINEA CLARO';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_TIPO_LINEA IS 'TIPO DE LINEA QUE INCLUYE EN EL CANJE';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_NUM_LINEA IS 'EL NRO DE LA LINEA QUE INCLUYE EN EL CANJE';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_INTERACTID IS 'ID INTERACCION';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_NUM_LINEA_SMS IS 'NRO DE LA LINEA QUE REALIZA EL CANJE VIA SMS';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_COD_CLI_PROD IS 'CODIGO DEL PRODUCTO TV EN CC AL CUAL SE VA ENTREGAR EL PREMIO';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_DIREC_CLIPROD IS 'DIRECION DEL PRODUCTO TV AL CUAL SE VA ACTIVAR EL SERVICIO DE TV';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_COD_SERV_SGA IS 'CODIGO DEL SGA QUE IDENTIFICA EL SERVICIO DE CABLE AL CUAL SE VA ENTREGAR EL PREMIO';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEFIJA.ADMPV_NOTAS IS 'NOTA DE LA INTERACCION';



CREATE UNIQUE INDEX PCLUB.PK_ADMPT_CANJEFIJA ON PCLUB.ADMPT_CANJEFIJA
(ADMPV_ID_CANJE)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE INDEX PCLUB.IDX_CANJE_CLIENTEFIJA ON PCLUB.ADMPT_CANJEFIJA
(ADMPV_COD_CLI)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE PCLUB.ADMPT_CANJEFIJA ADD (
  CONSTRAINT PK_ADMPT_CANJEFIJA
  PRIMARY KEY
  (ADMPV_ID_CANJE)
  USING INDEX PCLUB.PK_ADMPT_CANJEFIJA);

ALTER TABLE PCLUB.ADMPT_CANJEFIJA ADD (
  CONSTRAINT FK_ADMPT_CANJEFIJA_CLIENTEFIJO 
  FOREIGN KEY (ADMPV_COD_CLI) 
  REFERENCES PCLUB.ADMPT_CLIENTEFIJA (ADMPV_COD_CLI));

--CREAR TABLA DETALLE DE CANJE FIJA

CREATE TABLE PCLUB.ADMPT_CANJE_DETALLEFIJA
(
  ADMPV_ID_CANJE     NUMBER                     NOT NULL,
  ADMPV_ID_CANJESEC  NUMBER                     NOT NULL,
  ADMPV_ID_PROCLA    VARCHAR2(15 BYTE)          NOT NULL,
  ADMPV_DESC         VARCHAR2(150 BYTE),
  ADMPV_NOM_CAMP     VARCHAR2(200 BYTE),
  ADMPN_PUNTOS       NUMBER,
  ADMPN_PAGO         NUMBER,
  ADMPN_CANTIDAD     NUMBER,
  ADMPV_COD_TPOPR    VARCHAR2(2 BYTE),
  ADMPN_COD_SERVC    NUMBER,
  ADMPN_MNT_RECAR    NUMBER,
  ADMPC_ESTADO       CHAR(1 BYTE),
  ADMPD_FEC_REG      DATE                       NOT NULL,
  ADMPD_FEC_MOD      DATE,
  ADMPV_COD_PAQDAT   VARCHAR2(50 BYTE),
  ADMPV_CODTXPAQDAT  VARCHAR2(50 BYTE),
  ADMPV_USU_REG      VARCHAR2(20 BYTE),
  ADMPV_USU_MOD      VARCHAR2(20 BYTE),
  ADMPD_SOTID        VARCHAR2(40 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          8M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

COMMENT ON COLUMN PCLUB.ADMPT_CANJE_DETALLEFIJA.ADMPV_ID_CANJE IS 'Id del Canje';

COMMENT ON COLUMN PCLUB.ADMPT_CANJE_DETALLEFIJA.ADMPV_ID_CANJESEC IS 'Secuencia por cada canje';

COMMENT ON COLUMN PCLUB.ADMPT_CANJE_DETALLEFIJA.ADMPV_ID_PROCLA IS 'Codigo del Premio';

COMMENT ON COLUMN PCLUB.ADMPT_CANJE_DETALLEFIJA.ADMPV_DESC IS 'Descripción del premio';

COMMENT ON COLUMN PCLUB.ADMPT_CANJE_DETALLEFIJA.ADMPV_NOM_CAMP IS 'Nombre campaña';

COMMENT ON COLUMN PCLUB.ADMPT_CANJE_DETALLEFIJA.ADMPN_PUNTOS IS 'Cantidad Puntos';

COMMENT ON COLUMN PCLUB.ADMPT_CANJE_DETALLEFIJA.ADMPN_PAGO IS 'Aplica Pago';

COMMENT ON COLUMN PCLUB.ADMPT_CANJE_DETALLEFIJA.ADMPN_CANTIDAD IS 'Cantidad';

COMMENT ON COLUMN PCLUB.ADMPT_CANJE_DETALLEFIJA.ADMPV_COD_TPOPR IS 'Tipo de Premio';

COMMENT ON COLUMN PCLUB.ADMPT_CANJE_DETALLEFIJA.ADMPN_COD_SERVC IS 'Codigo Servicio BSCS';

COMMENT ON COLUMN PCLUB.ADMPT_CANJE_DETALLEFIJA.ADMPN_MNT_RECAR IS 'Monto Recarga IN';

COMMENT ON COLUMN PCLUB.ADMPT_CANJE_DETALLEFIJA.ADMPC_ESTADO IS 'Estado';

COMMENT ON COLUMN PCLUB.ADMPT_CANJE_DETALLEFIJA.ADMPV_COD_PAQDAT IS 'Codigo Paquete de Datos';

COMMENT ON COLUMN PCLUB.ADMPT_CANJE_DETALLEFIJA.ADMPV_CODTXPAQDAT IS 'Codigo que devuelve el proceso de entrega del paquete de datos';



CREATE UNIQUE INDEX PCLUB.PK_ADMPT_CANJE_DETALLEFIJA ON PCLUB.ADMPT_CANJE_DETALLEFIJA
(ADMPV_ID_CANJE, ADMPV_ID_CANJESEC)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE PCLUB.ADMPT_CANJE_DETALLEFIJA ADD (
  CONSTRAINT PK_ADMPT_CANJE_DETALLEFIJA
  PRIMARY KEY
  (ADMPV_ID_CANJE, ADMPV_ID_CANJESEC)
  USING INDEX PCLUB.PK_ADMPT_CANJE_DETALLEFIJA);

ALTER TABLE PCLUB.ADMPT_CANJE_DETALLEFIJA ADD (
  CONSTRAINT FK_ADMPT_CANJE_DETALLE_CANJEFI 
  FOREIGN KEY (ADMPV_ID_CANJE) 
  REFERENCES PCLUB.ADMPT_CANJEFIJA (ADMPV_ID_CANJE)
  ON DELETE CASCADE);


--CREAR TABLA DE RELACION CANJE KARDEX

CREATE TABLE PCLUB.ADMPT_CANJEDT_KARDEXFIJA
(
  ADMPV_ID_CANJE     NUMBER                     NOT NULL,
  ADMPN_ID_KARDEX    NUMBER                     NOT NULL,
  ADMPV_ID_CANJESEC  NUMBER                     NOT NULL,
  ADMPN_PUNTOS       NUMBER,
  ADMPC_TPO_KARDEX   CHAR(1 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

COMMENT ON COLUMN PCLUB.ADMPT_CANJEDT_KARDEXFIJA.ADMPV_ID_CANJE IS 'ID Canje';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEDT_KARDEXFIJA.ADMPN_ID_KARDEX IS 'ID Kardex';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEDT_KARDEXFIJA.ADMPV_ID_CANJESEC IS 'Secuencial de producto del Canje';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEDT_KARDEXFIJA.ADMPN_PUNTOS IS 'Puntos';

COMMENT ON COLUMN PCLUB.ADMPT_CANJEDT_KARDEXFIJA.ADMPC_TPO_KARDEX IS 'Tipo de Kardex';


CREATE INDEX PCLUB.IDX_ADMPT_CANJEDT_KARDEXFIJA ON PCLUB.ADMPT_CANJEDT_KARDEXFIJA
(ADMPN_ID_KARDEX)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PCLUB.IDX_CANJEDT_KFIJA ON PCLUB.ADMPT_CANJEDT_KARDEXFIJA
(ADMPV_ID_CANJE)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

--modificar la tabla CONCEPTO
ALTER TABLE PCLUB.ADMPT_CONCEPTO
ADD( ADMPV_TPO_CPTO   VARCHAR2(20 BYTE),
        ADMPC_TPO_OPER   CHAR(2 BYTE));
        
        
--MODIFICAR LA TABLA PREMIO 
ALTER TABLE PCLUB.ADMPT_PREMIO
ADD (ADMPV_COD_SERVTV VARCHAR2(50));


--CREAR LA TABLA TMP DE FACTURACION
CREATE TABLE PCLUB.ADMPT_TMP_PAGO_HFC
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_PERIODO       VARCHAR2(6 BYTE),
  ADMPN_DIAS_VENC     NUMBER,
  ADMPN_MNT_CGOFIJ    NUMBER,
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPN_PUNTOS        NUMBER,
  ADMPC_COD_ERROR     CHAR(3 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(400 BYTE),
  ADMPN_SEQ           NUMBER
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

--CREAR LA TABLA AUX PARA FACTURACION

CREATE TABLE PCLUB.ADMPT_AUX_PAGO_HFC
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_PERIODO       VARCHAR2(6 BYTE),
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

--CREAR TABLA IMP DE FACTURACION

CREATE TABLE PCLUB.ADMPT_IMP_PAGO_HFC
(
  ADMPN_ID_FILA       NUMBER                    NOT NULL,
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_PERIODO       VARCHAR2(6 BYTE),
  ADMPN_DIAS_VENC     NUMBER,
  ADMPN_MNT_CGOFIJ    NUMBER,
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPN_PUNTOS        NUMBER,
  ADMPC_COD_ERROR     CHAR(3 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(400 BYTE),
  ADMPD_FCH_TRANS     DATE,
  ADMPN_SEQ           NUMBER
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE PCLUB.ADMPT_IMP_PAGO_HFC ADD CONSTRAINT PK_ADMPT_IMP_PAGO_HFC
  PRIMARY KEY
  (ADMPN_ID_FILA)
  USING INDEX
    TABLESPACE PCLUB_INDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               );

--CREAR TABLA TMP PARA PROMCION

CREATE TABLE PCLUB.ADMPT_TMP_PROM_DTH_HFC
(
  ADMPV_COD_CLI     VARCHAR2(40 BYTE),
  ADMPN_PUNTOS      NUMBER,
  ADMPV_SERVICIO    VARCHAR2(20 BYTE),
  ADMPV_PERIODO     VARCHAR2(6 BYTE),
  ADMPV_NOM_PROMO   VARCHAR2(150 BYTE),
  ADMPD_FEC_REG     DATE,
  ADMPD_FEC_OPER    DATE,
  ADMPV_NOM_ARCH    VARCHAR2(150 BYTE),
  ADMPC_COD_ERROR   CHAR(3 BYTE),
  ADMPV_MSJE_ERROR  VARCHAR2(400 BYTE),
  ADMPN_SEQ         NUMBER,
  ADMPV_COD_TPOCL   VARCHAR2(2 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

--CREAR TABLA AUX PARA PROMOCION

CREATE TABLE PCLUB.ADMPT_AUX_PROM_DTH_HFC
(
  ADMPV_COD_CLI    VARCHAR2(40 BYTE),
  ADMPV_NOM_PROMO  VARCHAR2(100 BYTE),
  ADMPV_PERIODO    VARCHAR2(6 BYTE),
  ADMPN_PUNTOS     NUMBER,
  ADMPV_SERVICIO   VARCHAR2(20 BYTE),
  ADMPD_FEC_REG    DATE,
  ADMPD_FEC_OPER   DATE,
  ADMPV_NOM_ARCH   VARCHAR2(150 BYTE),
  ADMPV_COD_TPOCL  VARCHAR2(2 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

--CREAR TABLA IMP PARA PROMOCION

CREATE TABLE PCLUB.ADMPT_IMP_PROM_DTH_HFC
(
  ADMPN_ID_FILA     NUMBER                      NOT NULL,
  ADMPV_COD_CLI     VARCHAR2(40 BYTE),
  ADMPV_NOM_PROMO   VARCHAR2(150 BYTE),
  ADMPV_PERIODO     VARCHAR2(6 BYTE),
  ADMPD_FEC_REG     DATE,
  ADMPN_PUNTOS      NUMBER,
  ADMPV_SERVICIO    VARCHAR2(20 BYTE),
  ADMPD_FEC_OPER    DATE,
  ADMPV_NOM_ARCH    VARCHAR2(150 BYTE),
  ADMPC_COD_ERROR   CHAR(3 BYTE),
  ADMPV_MSJE_ERROR  VARCHAR2(100 BYTE),
  ADMPD_FEC_TRANS   DATE,
  ADMPN_SEQ         NUMBER,
  ADMPV_COD_TPOCL   VARCHAR2(2 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE UNIQUE INDEX PCLUB.PK_ADMPT_IMP_PROM_DTH_HFC ON PCLUB.ADMPT_IMP_PROM_DTH_HFC
(ADMPN_ID_FILA)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE PCLUB.ADMPT_IMP_PROM_DTH_HFC ADD (
  CONSTRAINT PK_ADMPT_IMP_PROM_DTH_HFC
  PRIMARY KEY
  (ADMPN_ID_FILA)
  USING INDEX PCLUB.PK_ADMPT_IMP_PROM_DTH_HFC);


--CREAR TABLA TMP DE REGULARIZACION

CREATE TABLE PCLUB.ADMPT_TMP_REGDTH_HFC
(
  ADMPV_COD_CLI     VARCHAR2(40 BYTE),
  ADMPV_NOM_REGUL   VARCHAR2(150 BYTE),
  ADMPV_PERIODO     VARCHAR2(6 BYTE),
  ADMPD_FEC_REG     DATE,
  ADMPN_PUNTOS      NUMBER,
  ADMPV_SERVICIO    VARCHAR2(20 BYTE),
  ADMPD_FEC_OPER    DATE,
  ADMPV_NOM_ARCH    VARCHAR2(150 BYTE),
  ADMPC_COD_ERROR   CHAR(2 BYTE),
  ADMPV_MSJE_ERROR  VARCHAR2(400 BYTE),
  ADMPN_SEQ         NUMBER,
  ADMPV_COD_TPOCL   VARCHAR2(2 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

--CREAR TABLA AUX PARA REGULARIZACION

CREATE TABLE PCLUB.ADMPT_AUX_REGDTH_HFC
(
  ADMPV_COD_CLI    VARCHAR2(40 BYTE),
  ADMPV_NOM_REGUL  VARCHAR2(150 BYTE),
  ADMPV_PERIODO    VARCHAR2(6 BYTE),
  ADMPN_PUNTOS     NUMBER,
  ADMPV_SERVICIO   VARCHAR2(20 BYTE),
  ADMPD_FEC_REG    DATE,
  ADMPD_FEC_OPER   DATE,
  ADMPV_NOM_ARCH   VARCHAR2(150 BYTE),
  ADMPV_COD_TPOCL  VARCHAR2(2 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

--CREAR TABLA IMP PARA REGULARIZACION

CREATE TABLE PCLUB.ADMPT_IMP_REGDTH_HFC
(
  ADMPN_ID_FILA     NUMBER                      NOT NULL,
  ADMPV_COD_CLI     VARCHAR2(40 BYTE),
  ADMPV_NOM_REGUL   VARCHAR2(150 BYTE),
  ADMPV_PERIODO     VARCHAR2(6 BYTE),
  ADMPD_FEC_REG     DATE,
  ADMPN_PUNTOS      NUMBER,
  ADMPV_SERVICIO    VARCHAR2(20 BYTE),
  ADMPD_FEC_OPER    DATE,
  ADMPV_NOM_ARCH    VARCHAR2(150 BYTE),
  ADMPC_COD_ERROR   CHAR(2 BYTE),
  ADMPV_MSJE_ERROR  VARCHAR2(400 BYTE),
  ADMPD_FEC_TRANS   DATE,
  ADMPN_SEQ         NUMBER,
  ADMPV_COD_TPOCL   VARCHAR2(2 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE UNIQUE INDEX PCLUB.PK_ADMPT_IMP_REGULARIZA_HFC ON PCLUB.ADMPT_IMP_REGDTH_HFC
(ADMPN_ID_FILA)
LOGGING
TABLESPACE PCLUB_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


ALTER TABLE PCLUB.ADMPT_IMP_REGDTH_HFC ADD (
  CONSTRAINT PK_ADMPT_IMP_REGULARIZA_HFC
  PRIMARY KEY
  (ADMPN_ID_FILA)
  USING INDEX PCLUB.PK_ADMPT_IMP_REGULARIZA_HFC);


--CREAR TABLA TMP ÁRA CAMBIO DE TITULAR

CREATE TABLE PCLUB.ADMPT_TMP_CAMBTIT_HFC
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_ESTADO        VARCHAR2(6 BYTE),
  ADMPV_TIP_DOC       VARCHAR2(40 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(40 BYTE),
  ADMPV_NOM_CLI       VARCHAR2(150 BYTE),
  ADMPV_APE_CLI       VARCHAR2(150 BYTE),
  ADMPV_SEX           VARCHAR2(10 BYTE),
  ADMPV_EST_CIV       VARCHAR2(10 BYTE),
  ADMPV_EMAIL         VARCHAR2(150 BYTE),
  ADMPV_PROV          VARCHAR2(50 BYTE),
  ADMPV_DEPT          VARCHAR2(50 BYTE),
  ADMPV_DIST          VARCHAR2(50 BYTE),
  ADMPV_CIC_FAC       VARCHAR2(10 BYTE),
  ADMPV_FEC_PRO       DATE,
  SECUENCIA           NUMBER,
  ADMPV_NROOPERACION  NUMBER,
  ADMPV_COD_ERROR     NUMBER,
  ADMPV_MSJE_ERROR    VARCHAR2(200 BYTE),
  ADMPV_NOM_ARCH      VARCHAR2(200 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

--CREAR TABLA AUX PARA CAMBIO TITULAR

CREATE TABLE PCLUB.ADMPT_AUX_CAMBTIT_HFC
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_ESTADO        VARCHAR2(6 BYTE),
  ADMPV_TIP_DOC       VARCHAR2(40 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(40 BYTE),
  ADMPV_NROOPERACION  NUMBER,
  ADMPV_FEC_PRO       DATE
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

--CREAR TABLA IMP PARA CAMBIO DE TITULAR

CREATE TABLE PCLUB.ADMPT_IMP_CAMBTIT_HFC
(
  ADMPV_FILA          NUMBER,
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_ESTADO        VARCHAR2(6 BYTE),
  ADMPV_TIP_DOC       VARCHAR2(40 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(40 BYTE),
  ADMPV_NOM_CLI       VARCHAR2(150 BYTE),
  ADMPV_APE_CLI       VARCHAR2(150 BYTE),
  ADMPV_SEX           VARCHAR2(10 BYTE),
  ADMPV_EST_CIV       VARCHAR2(10 BYTE),
  ADMPV_EMAIL         VARCHAR2(150 BYTE),
  ADMPV_PROV          VARCHAR2(50 BYTE),
  ADMPV_DEPT          VARCHAR2(50 BYTE),
  ADMPV_DIST          VARCHAR2(50 BYTE),
  ADMPV_CIC_FAC       VARCHAR2(10 BYTE),
  ADMPV_FEC_PRO       DATE,
  ADMPV_NROOPERACION  NUMBER,
  ADMPV_COD_ERROR     NUMBER,
  ADMPV_MSJE_ERROR    VARCHAR2(200 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


--CREAR TABLA TMP PARA MIGRACION DE CLIENTES

CREATE TABLE PCLUB.ADMPT_TMP_ALTACLI_HFC
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_TIPO_DOC      VARCHAR2(20 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(20 BYTE),
  ADMPV_NOM_CLI       VARCHAR2(80 BYTE),
  ADMPV_APE_CLI       VARCHAR2(80 BYTE),
  ADMPC_SEXO          CHAR(1 BYTE),
  ADMPV_EST_CIVIL     VARCHAR2(20 BYTE),
  ADMPV_EMAIL         VARCHAR2(80 BYTE),
  ADMPV_PROV          VARCHAR2(30 BYTE),
  ADMPV_DEPA          VARCHAR2(40 BYTE),
  ADMPV_DIST          VARCHAR2(200 BYTE),
  ADMPD_FEC_ACT       DATE,
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPV_COD_ERROR     CHAR(3 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(400 BYTE),
  ADMPN_SEQ           NUMBER,
  ADMPV_CICL_FACT     VARCHAR2(2 BYTE),
  ADMPV_SERVICIO      VARCHAR2(20 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

--CREAR TABLA AUX PARA MIGRACION DE CLIENTES

CREATE TABLE PCLUB.ADMPT_AUX_ALTACLI_HFC
(
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_TIPO_DOC      VARCHAR2(20 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(20 BYTE),
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


--CREAR TABLA IMP PARA LA MIGRACION DE CLIENTES

CREATE TABLE PCLUB.ADMPT_IMP_ALTACLI_HFC
(
  ADMPV_FILA          NUMBER,
  ADMPV_COD_CLI_PROD  VARCHAR2(40 BYTE),
  ADMPV_TIPO_DOC      VARCHAR2(20 BYTE),
  ADMPV_NUM_DOC       VARCHAR2(20 BYTE),
  ADMPV_NOM_CLI       VARCHAR2(80 BYTE),
  ADMPV_APE_CLI       VARCHAR2(80 BYTE),
  ADMPC_SEXO          CHAR(1 BYTE),
  ADMPV_EST_CIVIL     VARCHAR2(20 BYTE),
  ADMPV_EMAIL         VARCHAR2(80 BYTE),
  ADMPV_PROV          VARCHAR2(30 BYTE),
  ADMPV_DEPA          VARCHAR2(40 BYTE),
  ADMPV_DIST          VARCHAR2(200 BYTE),
  ADMPD_FEC_ACT       DATE,
  ADMPD_FEC_OPER      DATE,
  ADMPV_NOM_ARCH      VARCHAR2(150 BYTE),
  ADMPV_COD_ERROR     CHAR(3 BYTE),
  ADMPV_MSJE_ERROR    VARCHAR2(400 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );


CREATE TABLE PCLUB.ADMPT_TIPOS
(
  ADMPV_COD_TIPO  VARCHAR2(20 BYTE)             NOT NULL,
  ADMPV_DSC_TIPO  VARCHAR2(100 BYTE),
  ADMPV_ESTADO    CHAR(1 BYTE),
  ADMPV_GRUPO     VARCHAR2(100 BYTE)
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );