--Tabla ADMPT_EXCPREMIO_TIPOCLIE
-- Create table
CREATE TABLE PCLUB.ADMPT_EXCPREMIO_TIPOCLIE
(
  ADMPV_COD_TPOCL VARCHAR2(2) not null,
  ADMPV_ID_PROCLA VARCHAR2(15) not null
)
TABLESPACE PCLUB_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );
-- Add comments to the columns 
COMMENT ON COLUMN PCLUB.ADMPT_EXCPREMIO_TIPOCLIE.ADMPV_COD_TPOCL  is 'Codigo de Tipo de Cliente';
COMMENT ON COLUMN PCLUB.ADMPT_EXCPREMIO_TIPOCLIE.ADMPV_ID_PROCLA  is 'Codigo de Premio a Excluir';
-- Create/Recreate primary, unique and foreign key constraints 
ALTER TABLE PCLUB.ADMPT_EXCPREMIO_TIPOCLIE
  ADD CONSTRAINT PK_ADMPT_EXCPREMIO_TIPOCLIE PRIMARY KEY (ADMPV_COD_TPOCL, ADMPV_ID_PROCLA)
   USING INDEX
    TABLESPACE PCLUB_INDX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               );
  
ALTER TABLE PCLUB.ADMPT_EXCPREMIO_TIPOCLIE   ADD CONSTRAINT 
   FKADMPT_EXCPREMIO_X_PREMIO 
    FOREIGN KEY (ADMPV_ID_PROCLA)
  REFERENCES PCLUB.ADMPT_PREMIO (ADMPV_ID_PROCLA);
  
ALTER TABLE PCLUB.ADMPT_EXCPREMIO_TIPOCLIE  ADD CONSTRAINT  
   FKADMPT_EXCPREMIO_X_TIPO_CLI 
   FOREIGN KEY (ADMPV_COD_TPOCL)
  REFERENCES PCLUB.ADMPT_TIPO_CLIENTE (ADMPV_COD_TPOCL);
 
 
--Tabla  ADMPT_PRCANJTMP
  
ALTER TABLE PCLUB.ADMPT_PRCANJTMP ADD ADMPV_COD_TPOPR VARCHAR2(2);  
  
