--ELIMINAR COLUMNA PARA CANJE POR PUNTO DE AFILIACION DEBITO
ALTER TABLE PCLUB.ADMPT_CAT_CLIENTE
DROP COLUMN ADMPN_CXPT_ADEB;

--ELIMINAR COLUMNAS DE AFILIACION DEBITO EN LA TABLA TEMPORAL DE PAGOS
ALTER TABLE PCLUB.ADMPT_TMP_PAGO_CC
DROP COLUMN ADMPV_PUNTOS_ADEB;

ALTER TABLE PCLUB.ADMPT_TMP_PAGO_CC
DROP COLUMN ADMPV_ADEBITO;

--ELIMINAR COLUMNAS DE AFILIACION DEBITO EN LA TABLA FINAL DE PAGOS
ALTER TABLE PCLUB.ADMPT_IMP_PAGO_CC
DROP COLUMN ADMPV_PUNTOS_ADEB;

ALTER TABLE PCLUB.ADMPT_IMP_PAGO_CC
DROP COLUMN ADMPV_ADEBITO;

COMMIT;
