ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPV_COD_TIPAPL;
ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPV_CLAVE;	
ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPV_MENSAJE;	
ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPV_TICKET;	
ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPV_NUM_LINEA;	
ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPV_ID_GPRS;
ALTER TABLE PCLUB.ADMPT_PRCANJTMP DROP COLUMN ADMPV_ID_GPRS;
ALTER TABLE PCLUB.ADMPT_TIPO_DOC DROP COLUMN ADMPV_EQU_DWH;
