drop table PCLUB.ADMPT_TMP_PRERECARGA;

drop table PCLUB.ADMPT_AUX_PRERECARGA;
  
drop table PCLUB.ADMPT_IMP_PRERECARGA;

drop table PCLUB.ADMPT_TMP_PREANIVERS;
 
drop table PCLUB.ADMPT_AUX_PREANIVERS;
  
drop table PCLUB.ADMPT_IMP_PREANIVERS;

drop table PCLUB.ADMPT_TMP_PRESINRECARGA;
  
drop table PCLUB.ADMPT_AUX_PRESINRECARGA;

drop table PCLUB.ADMPT_IMP_PRESINRECARGA;

drop table PCLUB.ADMPT_IMP_PREACTIV;

drop table PCLUB.ADMPT_IMP_PREALTAC;

drop table PCLUB.ADMPT_IMP_PRECMBTIT;

drop table PCLUB.ADMPT_TMP_PREBAJA;

drop table PCLUB.ADMPT_AUX_PREBAJA;
  
drop table PCLUB.ADMPT_IMP_PREBAJA;

drop table PCLUB.ADMPT_IMP_PREPREPOS;

drop table PCLUB.ADMPT_IMP_PREPOSPRE;

drop table PCLUB.ADMPT_TMP_PRECARGAIN;
 
drop table PCLUB.ADMPT_AUX_PRECARGAIN;
  
drop table PCLUB.ADMPT_IMP_PRECARGAIN;

drop table PCLUB.ADMPT_TMP_PREPROMO;

drop table PCLUB.ADMPT_AUX_PREPROMO;
  
drop table PCLUB.ADMPT_IMP_PREPROMO;

drop table PCLUB.ADMPT_TIPO_APLIC;

drop table PCLUB.ADMPT_IMP_ENT_BON_PRE;

drop table PCLUB.ADMPT_IMP_PRECARGACLI;