-- Eliminar Dependencias

ALTER TABLE PCLUB.ADMPT_CANJE ADD CONSTRAINT FK_ADMPT_CANJE_KARDEX 
FOREIGN KEY 
(ADMPN_ID_KARDEX) 
REFERENCES PCLUB.ADMPT_KARDEX(ADMPN_ID_KARDEX);


ALTER TABLE PCLUB.ADMPT_CANJEDT_KARDEX ADD CONSTRAINT FK_ADMPT_CANJEDT_KADX_KARDEX 
FOREIGN KEY 
(ADMPN_ID_KARDEX) 
REFERENCES PCLUB.ADMPT_KARDEX(ADMPN_ID_KARDEX);

ALTER TABLE PCLUB.ADMPT_CANJEDT_KARDEX
DROP CONSTRAINT FK_ADMPT_CANJEDT_KADX_KARDEX;


ALTER TABLE PCLUB.ADMPT_BONO_KARDEX DROP COLUMN FECCORTA;


ALTER TABLE PCLUB.ADMPT_TMP_PRERECARGA DROP COLUMN ADMPV_CATEGORIA;
ALTER TABLE PCLUB.ADMPT_TMP_PRERECARGA DROP COLUMN ADMPV_ERROR;
ALTER TABLE PCLUB.ADMPT_TMP_PRERECARGA DROP COLUMN ADMPV_MSJE_ERROR;


--Eliminar  tabla ADMPT_KARDEX_MIG
DROP TABLE PCLUB.ADMPT_KARDEX_MIG;
  
  