drop table PCLUB.ADMPT_AUX_PREPOSPRE;
drop table PCLUB.ADMPT_AUX_PREPREPOS;

ALTER TABLE PCLUB.ADMPT_IMP_PREPOSPRE DROP COLUMN ADMPV_TELEFONO;

ALTER TABLE PCLUB.ADMPT_IMP_PREPREPOS DROP COLUMN ADMPV_CUENTA;