/* ADMPT_CONCEPTO */
ALTER TABLE PCLUB.ADMPT_CONCEPTO MODIFY ADMPV_COD_CPTO VARCHAR2(2);

/* ADMPT_KARDEX */
ALTER TABLE PCLUB.ADMPT_KARDEX MODIFY ADMPV_COD_CPTO VARCHAR2(2);
ALTER TABLE PCLUB.ADMPT_KARDEX DROP COLUMN ADMPN_TIP_PREMIO;
ALTER TABLE PCLUB.ADMPT_KARDEX DROP COLUMN ADMPD_FEC_VCMTO;
ALTER TABLE PCLUB.ADMPT_KARDEX DROP COLUMN ADMPV_USU_REG;
ALTER TABLE PCLUB.ADMPT_KARDEX DROP COLUMN ADMPV_USU_MOD;

/* ADMPT_CANJE */
ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPN_TIPCANJE;
ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPN_TIPPREMCJE;

/* ADMPT_TIPO_PREMIO */
ALTER TABLE PCLUB.ADMPT_TIPO_PREMIO DROP COLUMN ADMPN_GRUPO;

/* ADMPT_IMP_PRESINRECARGA */
ALTER TABLE PCLUB.ADMPT_IMP_PRESINRECARGA DROP COLUMN ADMPV_NOMARCHIVO;
ALTER TABLE PCLUB.ADMPT_IMP_PRESINRECARGA DROP COLUMN ADMPD_USU_REG;
ALTER TABLE PCLUB.ADMPT_IMP_PRESINRECARGA DROP COLUMN ADMPV_CODERROR;
ALTER TABLE PCLUB.ADMPT_IMP_PRESINRECARGA DROP COLUMN ADMPC_ESTADOSMS;
ALTER TABLE PCLUB.ADMPT_IMP_PRESINRECARGA DROP COLUMN ADMPD_FEC_MOD;
ALTER TABLE PCLUB.ADMPT_IMP_PRESINRECARGA DROP COLUMN ADMPD_USU_MOD;
ALTER TABLE PCLUB.ADMPT_IMP_PRESINRECARGA DROP COLUMN ADMPD_FEC_ENVIOSMS;

/* ADMPT_TMP_PRESINRECARGA */
ALTER TABLE PCLUB.ADMPT_TMP_PRESINRECARGA DROP COLUMN ADMPN_SEC;
ALTER TABLE PCLUB.ADMPT_TMP_PRESINRECARGA DROP COLUMN ADMPV_NOMARCHIVO;
ALTER TABLE PCLUB.ADMPT_TMP_PRESINRECARGA DROP COLUMN ADMPC_ESTADO;
ALTER TABLE PCLUB.ADMPT_TMP_PRESINRECARGA DROP COLUMN ADMPV_CODERROR;
ALTER TABLE PCLUB.ADMPT_TMP_PRESINRECARGA DROP COLUMN ADMPD_FEC_REG;