DROP TABLE PCLUB.ADMPT_CAMPANHA_DET;
DROP TABLE PCLUB.ADMPT_CAMPANHA;
DROP TABLE PCLUB.ADMPT_CLIE_ESTADO_BOLSA;
DROP TABLE PCLUB.ADMPT_PROCESO;

DROP INDEX PCLUB.IDX_ADMPT_CLIENTEPRODUCTO_01;
DROP INDEX PCLUB.IDX_DETALLEFIJA_01;
DROP INDEX PCLUB.IDX_KARDEXFIJA_02;
DROP INDEX PCLUB.IDX_ADMPT_CANJE_01;

ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPV_USU_REG;
ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPV_USU_MOD;
ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPV_TPO_PROC;
ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPV_VENTAID;
ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPN_SOLESVTA;
ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPN_ID_CAMP;
ALTER TABLE PCLUB.ADMPT_CANJE DROP COLUMN ADMPN_SALDO;
ALTER TABLE PCLUB.ADMPT_TIPO_CLIENTE DROP COLUMN ADMPV_PRVENTA;
ALTER TABLE PCLUB.ADMPT_TIPO_CLIENTE DROP COLUMN ADMPC_TBLCLIENTE;
ALTER TABLE PCLUB.ADMPT_CANJEFIJA DROP COLUMN ADMPV_TPO_PROC;
ALTER TABLE PCLUB.ADMPT_CANJEFIJA DROP COLUMN ADMPV_VENTAID;
ALTER TABLE PCLUB.ADMPT_CANJEFIJA DROP COLUMN ADMPN_SOLESVTA;
ALTER TABLE PCLUB.ADMPT_CANJEFIJA DROP COLUMN ADMPN_ID_CAMP;
ALTER TABLE PCLUB.ADMPT_CANJEFIJA DROP COLUMN ADMPN_SALDO;
