drop table PCLUB.ADMPT_MOVENCUESTA;
drop table PCLUB.ADMPT_CABENCUESTA;
drop table PCLUB.ADMPT_RESPUESTA;
drop table PCLUB.ADMPT_PREGUNTA;
drop table PCLUB.ADMPT_ENCUESTA;
alter table PCLUB.ADMPT_TIPO_CLIENTE drop column ADMPC_ENCUESTA;