DROP TABLE fidelidad.CPRET_MSG_ENVIOSMS;
DROP TABLE fidelidad.CPRET_CONFIG_SMS;
DROP TABLE fidelidad.CPRET_MOVCHURN;
DROP TABLE fidelidad.CPRET_TMP_MOVCHURN;
DROP TABLE fidelidad.CPRET_TMP_REP_MOVCHURN;