DROP TABLE PCLUB.ADMPT_VENCTO_PROC_TMP;

/* ADMPT_BONOPREP_ERR */
ALTER TABLE PCLUB.ADMPT_BONOPREP_ERR DROP COLUMN ADMPV_ESTADO;
ALTER TABLE PCLUB.ADMPT_BONOPREP_ERR DROP COLUMN ADMPV_MENSAJE;
ALTER TABLE PCLUB.ADMPT_BONOPREP_ERR DROP COLUMN ADMPD_FEC_PROC;
ALTER TABLE PCLUB.ADMPT_BONOPREP_ERR DROP COLUMN ADMPD_FEC_ENVIOSMS;
ALTER TABLE PCLUB.ADMPT_BONOPREP_ERR DROP COLUMN ADMPV_CONT_PROC;