-- drop sequence 
drop sequence PCLUB.ADMPT_PRERECARGA_SQ;

drop sequence PCLUB.ADMPT_IMP_PRESINRECARGA_SQ;

drop sequence PCLUB.ADMPT_PREACTIV_SQ;

drop sequence PCLUB.ADMPT_IMP_PREALTAC_SQ;

drop sequence PCLUB.ADMPT_IMP_PREPREPOS_SQ;

drop sequence PCLUB.ADMPT_IMP_PRECARGAIN_SQ;

drop sequence PCLUB.ADMPT_IMP_PREPROMO_SQ;

drop sequence PCLUB.ADMPT_PRECMBTIT_SQ;

drop sequence PCLUB.ADMPT_PREBAJA_SQ;

drop sequence PCLUB.ADMPT_IMP_PREANIV_SQ;

drop sequence PCLUB.ADMPT_IMP_PREPOSPRE_SQ; 

drop sequence PCLUB.ADMPT_IMP_ENT_BON_PRE_SQ;