-- ROLLBACK ALTER TABLE

ALTER TABLE PCLUB.ADMPT_TMP_ALTACLI_TFI
DROP COLUMN admpv_cod_nv_cli;

ALTER TABLE PCLUB.ADMPT_TMP_ALTACLI_TFI 
DROP COLUMN ADMPD_FEC_ACTIV;

ALTER TABLE PCLUB.ADMPT_TMP_ALTACLI_TFI
DROP COLUMN ADMPV_TIPO_CLI;

ALTER TABLE PCLUB.ADMPT_AUX_ALTACLI_TFI
DROP COLUMN ADMPV_TIPO_CLI;

ALTER TABLE PCLUB.ADMPT_IMP_ALTACLI_TFI
DROP COLUMN admpv_cod_nv_cli;

ALTER TABLE PCLUB.ADMPT_IMP_ALTACLI_TFI 
DROP COLUMN ADMPD_FEC_ACTIV;

ALTER TABLE PCLUB.ADMPT_IMP_ALTACLI_TFI
DROP COLUMN ADMPV_TIPO_CLI;

