
 ALTER TABLE PCLUB.ADMPT_CAT_CLIENTE drop constraint PK_ADMPT_CAT_CLIENTE;
 
 ALTER TABLE PCLUB.ADMPT_CAT_CLIENTE
  add constraint PK_ADMPT_CAT_CLIENTE primary key (ADMPN_COD_CATCLI, ADMPV_COD_TPOCL)
  using index 
  tablespace PCLUB_DATA
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    minextents 1
    maxextents unlimited
  );
  
DELETE FROM PCLUB.ADMPT_CAT_CLIENTE WHERE ADMPN_COD_CATCLI = 1 AND ADMPV_COD_TPOCL = '1';

DELETE FROM PCLUB.ADMPT_CAT_CLIENTE WHERE ADMPN_COD_CATCLI = 2 AND ADMPV_COD_TPOCL = '1';

DELETE FROM PCLUB.ADMPT_CAT_CLIENTE WHERE ADMPN_COD_CATCLI = 1 AND ADMPV_COD_TPOCL = '2';

DELETE FROM PCLUB.ADMPT_CAT_CLIENTE WHERE ADMPN_COD_CATCLI = 2 AND ADMPV_COD_TPOCL = '2';

COMMIT;