/*-------------------------TABLAS-------------------------------*/

--ALTER TABLE A TABLAS EXISTENTES

alter table PCLUB.ADMPT_CANJE modify ADMPV_MENSAJE VARCHAR2(50);
alter table PCLUB.ADMPT_CANJE_DETALLE DROP (ADMPV_COD_PAQDAT);
alter table PCLUB.ADMPT_CANJE_DETALLE DROP (ADMPV_CODTXPAQDAT);
alter table PCLUB.ADMPT_PRCANJTMP DROP (ADMPV_COD_PAQDAT);
alter table PCLUB.ADMPT_PRCANJTMP DROP (ADMPV_CODTXPAQDAT);
alter table PCLUB.ADMPT_PREMIO DROP (ADMPV_COD_PAQDAT);
 
/*-------MODIFICACION EN TIPO DE DATOS-------*/

DROP TYPE PCLUB.LISTA_PEDIDO;

DROP TYPE PCLUB.PEDIDO;

CREATE OR REPLACE TYPE PCLUB.PEDIDO  AS OBJECT
( ProdId          VARCHAR2(15),
  Campana         VARCHAR2(200),
  Puntos          NUMBER,
  Pago            NUMBER,
  Cantidad        NUMBER,
  TipoPremio      VARCHAR2(2),
  ServComercial   NUMBER,
  MontoRecarga    Number
);
/

CREATE OR REPLACE TYPE PCLUB.LISTA_PEDIDO AS VARRAY(100) OF PCLUB.PEDIDO;
/