ALTER TABLE PCLUB.ADMPT_TIPOS
DROP COLUMN ADMPV_RUTA;

DROP TABLE PCLUB.ADMPT_IMP_CAMBIOSEG CASCADE CONSTRAINTS;

DROP TABLE PCLUB.ADMPT_AUX_CAMBIOSEG CASCADE CONSTRAINTS;

DROP TABLE PCLUB.ADMPT_TMP_CAMBIOSEG CASCADE CONSTRAINTS;

ALTER TABLE PCLUB.ADMPT_MOVIMIENTOCUPONERA
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_MOVIMIENTOCUPONERA CASCADE CONSTRAINTS;

ALTER TABLE PCLUB.ADMPT_CONSULTACUPONERA
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_CONSULTACUPONERA CASCADE CONSTRAINTS;

ALTER TABLE PCLUB.ADMPT_OFERTA
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_OFERTA CASCADE CONSTRAINTS;

ALTER TABLE PCLUB.ADMPT_CUPON
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_CUPON CASCADE CONSTRAINTS;

DROP TABLE PCLUB.ADMPT_TMP_CUPONERA CASCADE CONSTRAINTS;

ALTER TABLE PCLUB.ADMPT_CUPONERA
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_CUPONERA CASCADE CONSTRAINTS;

ALTER TABLE PCLUB.ADMPT_TELEFONOCUPONERA
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_TELEFONOCUPONERA CASCADE CONSTRAINTS;

ALTER TABLE PCLUB.ADMPT_ESTABLECIMIENTO
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_ESTABLECIMIENTO CASCADE CONSTRAINTS;

DROP TABLE PCLUB.ADMPT_IMP_ALTAMASIVACUPONERA CASCADE CONSTRAINTS;

DROP TABLE PCLUB.ADMPT_AUX_ALTAMASIVACUPONERA CASCADE CONSTRAINTS;

DROP TABLE PCLUB.ADMPT_TMP_ALTAMASIVACUPONERA CASCADE CONSTRAINTS;

DROP TABLE PCLUB.ADMPT_CLIENTECUPONERALOG CASCADE CONSTRAINTS;

ALTER TABLE PCLUB.ADMPT_CLIENTECUPONERA
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_CLIENTECUPONERA CASCADE CONSTRAINTS;

ALTER TABLE PCLUB.ADMPT_SEGMENTOCUPONERA
 DROP PRIMARY KEY CASCADE;

DROP TABLE PCLUB.ADMPT_SEGMENTOCUPONERA CASCADE CONSTRAINTS;



