--TRIGGERS
--ADMPT_SALDOS_CLIENTE
CREATE OR REPLACE TRIGGER T_SALDOS_CLIENTE
BEFORE UPDATE ON PCLUB.ADMPT_SALDOS_CLIENTE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.ADMPD_FEC_MOD := SYSDATE;
END T_SALDOS_CLIENTE;

--ADMPT_KARDEX
CREATE OR REPLACE TRIGGER T_KARDEX
BEFORE UPDATE ON PCLUB.ADMPT_KARDEX
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.ADMPD_FEC_MOD := SYSDATE;
END T_KARDEX;

--ADMPT_CLIENTE
CREATE OR REPLACE TRIGGER T_CLIENTE
BEFORE UPDATE ON PCLUB.ADMPT_CLIENTE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.ADMPD_FEC_MOD := SYSDATE;
END T_CLIENTE;

--ADMPT_CLIENTEIB
CREATE OR REPLACE TRIGGER T_CLIENTE_IB
BEFORE UPDATE ON PCLUB.ADMPT_CLIENTEIB
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.ADMPD_FEC_MOD := SYSDATE;
END T_CLIENTE_IB;

--ADMPT_CANJE
CREATE OR REPLACE TRIGGER T_CANJE
BEFORE UPDATE ON PCLUB.ADMPT_CANJE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.ADMPD_FEC_MOD := SYSDATE;
END T_CANJE;

--ADMPT_CANJE_DETALLE
CREATE OR REPLACE TRIGGER T_CANJE_DETALLE
BEFORE UPDATE ON PCLUB.ADMPT_CANJE_DETALLE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
BEGIN
:NEW.ADMPD_FEC_MOD := SYSDATE;
END T_CANJE_DETALLE;