--SCRIPTS      :  GENERACION DE TABLAS
--AUTOR        :  HENRY HERRERA CH
--PROPOCISITO  :  GENERACION DE LA TABLAS , INDICES , TRIGGERS 

--------------------------------------
CREATE TABLE PCLUB.ADMPT_ALFANUMERICO
(
  ADMPN_CORRELATIVO NUMBER not null,
  ADMPV_ID_RULETA   VARCHAR2(100),
  ADMPN_ID_PROMO    NUMBER,
  ADMPV_ESTADO      VARCHAR2(2),
  ADMPD_FEC_REG     DATE,
  ADMPV_USU_REG     VARCHAR2(20),
  ADMPD_FEC_MOD     DATE,
  ADMPV_USU_MOD     VARCHAR2(20)
)
tablespace PCLUB_DATA;

comment on column PCLUB.ADMPT_ALFANUMERICO.ADMPN_CORRELATIVO  is 'Un correlativo propio de la tabla';
comment on column PCLUB.ADMPT_ALFANUMERICO.ADMPV_ID_RULETA    is 'Identificador del Alfanumerico';
comment on column PCLUB.ADMPT_ALFANUMERICO.ADMPN_ID_PROMO     is 'Referencia a la tabla  ADMPT_PROMOCION  por el campo ADMPN_ID_PROMO';
comment on column PCLUB.ADMPT_ALFANUMERICO.ADMPV_ESTADO       is 'Estado ''U'' (Usado) cualquier de esto sea vacio o Nulo es por se encuentra sin uso';
comment on column PCLUB.ADMPT_ALFANUMERICO.ADMPD_FEC_REG      is 'Fecha de registro';
comment on column PCLUB.ADMPT_ALFANUMERICO.ADMPV_USU_REG      is 'Usuario que registra';
comment on column PCLUB.ADMPT_ALFANUMERICO.ADMPD_FEC_MOD      is 'Fecha de modificacion del registro';
comment on column PCLUB.ADMPT_ALFANUMERICO.ADMPV_USU_MOD      is 'Usuario que modifica';

CREATE UNIQUE INDEX IDX_ALFANUMERICO_PROMO ON PCLUB.ADMPT_ALFANUMERICO (ADMPV_ID_RULETA, ADMPN_ID_PROMO)
tablespace PCLUB_INDX;

CREATE INDEX IDX_ALFANUMERICO_DISPONIBLE ON PCLUB.ADMPT_ALFANUMERICO (ADMPV_ESTADO, ADMPN_ID_PROMO)
tablespace PCLUB_INDX;

ALTER TABLE PCLUB.ADMPT_ALFANUMERICO   ADD CONSTRAINT PK_ALFANUMERICO_CORRELATIVO PRIMARY KEY (ADMPN_CORRELATIVO)
USING INDEX 
tablespace PCLUB_DATA;

ALTER TABLE PCLUB.ADMPT_ALFANUMERICO   ADD CONSTRAINT UNX_ALFANUMERICO_PROMO UNIQUE (ADMPV_ID_RULETA, ADMPN_ID_PROMO);



CREATE TABLE PCLUB.ADMPT_PROMOCION
(
  ADMPN_ID_PROMO  NUMBER,
  ADMPV_PROMOCION VARCHAR2(100),
  ADMPD_FEC_INI   DATE,
  ADMPD_FEC_FIN   DATE,
  ADMPV_ESTADO    VARCHAR2(2),
  ADMPD_FEC_REG   DATE,
  ADMPV_USU_REG   VARCHAR2(20),
  ADMPD_FEC_MOD   DATE,
  ADMPV_USU_MOD   VARCHAR2(20)
)
tablespace PCLUB_DATA;
  
comment on column PCLUB.ADMPT_PROMOCION.ADMPN_ID_PROMO    is 'Identificador de la tabla';
comment on column PCLUB.ADMPT_PROMOCION.ADMPV_PROMOCION   is 'Descripcion del registro';
comment on column PCLUB.ADMPT_PROMOCION.ADMPD_FEC_INI     is 'Fecha Inicio Promocion';
comment on column PCLUB.ADMPT_PROMOCION.ADMPD_FEC_FIN     is 'Fecha Fin Promocion';
comment on column PCLUB.ADMPT_PROMOCION.ADMPV_ESTADO      is '(A) Activo / (D) Desactivo';
comment on column PCLUB.ADMPT_PROMOCION.ADMPD_FEC_REG     is 'Fecha de registro de promocion';
comment on column PCLUB.ADMPT_PROMOCION.ADMPV_USU_REG     is 'usuario que registra';
comment on column PCLUB.ADMPT_PROMOCION.ADMPD_FEC_MOD     is 'Fecha Final de promocion';
comment on column PCLUB.ADMPT_PROMOCION.ADMPV_USU_MOD     is 'Usuario que modifica';



ALTER TABLE PCLUB.ADMPT_PROMOCION    ADD CONSTRAINT CHK_ESTADO_NOTNULL    CHECK ("ADMPV_ESTADO" IS NOT NULL);
ALTER TABLE PCLUB.ADMPT_PROMOCION    ADD CONSTRAINT CHK_FECHAFIN_NOTNULL  CHECK ("ADMPD_FEC_FIN" IS NOT NULL);
ALTER TABLE PCLUB.ADMPT_PROMOCION    ADD CONSTRAINT CHK_FECHAINI_NOTNULL  CHECK ("ADMPD_FEC_INI" IS NOT NULL);
ALTER TABLE PCLUB.ADMPT_PROMOCION    ADD CONSTRAINT CHK_IDPROMO_NOTNULL   CHECK ("ADMPN_ID_PROMO" IS NOT NULL);

CREATE INDEX IDX_PROMOCION ON PCLUB.ADMPT_PROMOCION (ADMPN_ID_PROMO)	
TABLESPACE PCLUB_INDX;

ALTER TABLE PCLUB.ADMPT_PROMOCION   ADD CONSTRAINT PK_PROMOCION PRIMARY KEY (ADMPN_ID_PROMO);



CREATE TABLE PCLUB.ADMPT_TIP_PREMIOPROMO
(
  ADMPN_ID_TPREMIO  NUMBER not null,
  ADMPV_DESCR_TP    VARCHAR2(200),
  ADMPV_ENV_SMS     VARCHAR2(12),
  ADMPN_APPROVINCIA VARCHAR2(2),
  ADMPD_FEC_REG     DATE,
  ADMPV_USU_REG     VARCHAR2(20),
  ADMPD_FEC_MOD     DATE,
  ADMPV_USU_MOD     VARCHAR2(20),
  ADMPV_SMS_MSJ     VARCHAR2(1000)
)
tablespace PCLUB_DATA;

-- Add comments to the columns 
comment on column PCLUB.ADMPT_TIP_PREMIOPROMO.ADMPN_ID_TPREMIO	is 'Id Correlativo para la tabla premio';
comment on column PCLUB.ADMPT_TIP_PREMIOPROMO.ADMPV_DESCR_TP      is 'Descripcion de premio';
comment on column PCLUB.ADMPT_TIP_PREMIOPROMO.ADMPV_ENV_SMS       is 'Envio por SMS (S: si envia / N: no envia)';
comment on column PCLUB.ADMPT_TIP_PREMIOPROMO.ADMPN_APPROVINCIA   is 'Este premio es para saber si aplica a provincia';
comment on column PCLUB.ADMPT_TIP_PREMIOPROMO.ADMPD_FEC_REG       is 'Fecha de registro ';
comment on column PCLUB.ADMPT_TIP_PREMIOPROMO.ADMPV_USU_REG       is 'Usuario que registra';
comment on column PCLUB.ADMPT_TIP_PREMIOPROMO.ADMPD_FEC_MOD       is 'Fecha de Modificacion';
comment on column PCLUB.ADMPT_TIP_PREMIOPROMO.ADMPV_USU_MOD       is 'Usuario que modifica';
comment on column PCLUB.ADMPT_TIP_PREMIOPROMO.ADMPV_SMS_MSJ       is 'Mensaje del SMS';

CREATE UNIQUE INDEX IDX_ADMPT_TIP_PREMIO ON PCLUB.ADMPT_TIP_PREMIOPROMO (ADMPN_ID_TPREMIO)
TABLESPACE PCLUB_INDX;

ALTER TABLE PCLUB.ADMPT_TIP_PREMIOPROMO  ADD CONSTRAINT PK_ADMPT_TIP_PREMIO PRIMARY KEY (ADMPN_ID_TPREMIO);


CREATE TABLE PCLUB.ADMPT_PREMIO_PROMO
(
  ADMPN_ID_PREMIO  NUMBER not null,
  ADMPN_ID_PROMO   NUMBER not null,
  ADMPV_DESPREMIO  VARCHAR2(400),
  ADMPV_ESTADO     VARCHAR2(2),
  ADMPN_ID_TPREMIO NUMBER,
  ADMPN_MNRECARGA  NUMBER,
  ADMPV_CODSERV    VARCHAR2(10),
  ADMPN_PUNTOS     NUMBER,
  ADMPD_FEC_REG    DATE,
  ADMPV_USU_REG    VARCHAR2(20),
  ADMPD_FEC_MOD    DATE,
  ADMPV_USU_MOD    VARCHAR2(20),
  ADMPV_PREMIO_SMS VARCHAR2(200)
)
tablespace PCLUB_DATA;
  
comment on column PCLUB.ADMPT_PREMIO_PROMO.ADMPN_ID_PREMIO  	  is 'Parte del la PK de esta tabla es un correlativo';
comment on column PCLUB.ADMPT_PREMIO_PROMO.ADMPN_ID_PROMO		  is 'Referencia a la tabla ADMPT_PROMOCION  por el campo  ADMPN_ID_PROMO';
comment on column PCLUB.ADMPT_PREMIO_PROMO.ADMPV_DESPREMIO	  is 'Descripcion del premio';
comment on column PCLUB.ADMPT_PREMIO_PROMO.ADMPV_ESTADO		  is 'Estado A = ACTIVO   D=Desactivo';
comment on column PCLUB.ADMPT_PREMIO_PROMO.ADMPN_ID_TPREMIO	  is 'Se hace referencia a la tabla ADMPT_TIP_PREMIOPROMO por el campo ADMPN_ID_TPREMIO';
comment on column PCLUB.ADMPT_PREMIO_PROMO.ADMPN_MNRECARGA	  is 'Monto Recarga';
comment on column PCLUB.ADMPT_PREMIO_PROMO.ADMPV_CODSERV		  is 'Codigo de Servicio';
comment on column PCLUB.ADMPT_PREMIO_PROMO.ADMPD_FEC_REG		  is 'Fecha de registro';
comment on column PCLUB.ADMPT_PREMIO_PROMO.ADMPV_USU_REG		  is 'Usuario Registra';
comment on column PCLUB.ADMPT_PREMIO_PROMO.ADMPD_FEC_MOD		  is 'fecha de modificacion';
comment on column PCLUB.ADMPT_PREMIO_PROMO.ADMPV_USU_MOD		  is 'Usuario modifica';

ALTER TABLE PCLUB.ADMPT_PREMIO_PROMO	  ADD CONSTRAINT PK_PREMIOPROMO PRIMARY KEY (ADMPN_ID_PREMIO, ADMPN_ID_PROMO)
USING INDEX 
TABLESPACE PCLUB_INDX;

ALTER TABLE PCLUB.ADMPT_PREMIO_PROMO	  ADD CONSTRAINT CHK_DESPREMIO_NOTNULL	  CHECK ("ADMPV_DESPREMIO" IS NOT NULL);

CREATE INDEX IDX_PREMIOPROMO_TPREMIO ON PCLUB.ADMPT_PREMIO_PROMO (ADMPN_ID_TPREMIO)
tablespace PCLUB_INDX;
  
  
CREATE TABLE PCLUB.ADMPT_MOV_PROMOCION
(
  ADMPN_CORRELATIVO   NUMBER not null,
  ADMPN_ID_CANJE      NUMBER,
  ADMPV_NUM_LINEA     VARCHAR2(20),
  ADMPN_ID_PROMO      NUMBER,
  ADMPV_ID_RULETA     VARCHAR2(100),
  ADMPV_ID_PREMIO     VARCHAR2(40),
  ADMPV_TIPO_LINEA    VARCHAR2(40),
  ADMPD_FEC_ENVIO_SMS DATE,
  ADMPD_FEC_PREMIO    DATE,
  ADMPV_ASESOR        VARCHAR2(100),
  ADMPV_CAC           VARCHAR2(40),
  ADMPV_NUM_DOC       VARCHAR2(30),
  ADMPV_TIPO_DOC      VARCHAR2(20),
  ADMPD_FEC_REG       DATE,
  ADMPV_USU_REG       VARCHAR2(20),
  ADMPD_FEC_MOD       DATE,
  ADMPV_USU_MOD       VARCHAR2(20),
  ADMPV_COID          VARCHAR2(200)
)
tablespace PCLUB_DATA;

comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPN_CORRELATIVO		is 'Identificador de la tabla  MOV_PROMOCION';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPN_ID_CANJE		is 'Hace referencia a la tabla  ADMPT_CANJE por el campo ADMPV_ID_CANJE';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPV_NUM_LINEA		is 'Campo numero de linea o Numero telefonico';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPN_ID_PROMO		is 'Hace referencia a la tabla ADMPT_PROMOCION  por el campo ADMPN_ID_PROMO';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPV_ID_RULETA		is 'Hace referencia a la tabla ADMPT_ALFANUMERICO por el campo  ADMPV_ID_RULETA';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPV_ID_PREMIO		is 'Hace referencia a la tabla ADMPT_PREMIO_PROMO  por el campo ADMPN_ID_PREMIO';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPV_TIPO_LINEA		is 'Hace referencia a tipo de linea 1 Control,  2 Prepago , 3 PostPago contenido en la tabla  ADMPT_TIPO_CLIENTE';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPD_FEC_ENVIO_SMS	is 'Fecha de envio del SMS';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPD_FEC_PREMIO		is 'Fecha de recepcion de premio';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPV_NUM_DOC			is 'Hace referencia al numero de documento';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPV_TIPO_DOC		is 'Hace referencia al tipo de documento contenido en la tabla  ADMPT_TIPO_DOC';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPD_FEC_REG			is 'Fecha de Registro';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPV_USU_REG			is 'Usuario que registra';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPD_FEC_MOD			is 'Fecha de modificación';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPV_USU_MOD			is 'Usuario modifica';
comment on column PCLUB.ADMPT_MOV_PROMOCION.ADMPV_COID			is 'Codigo de Contrato';

CREATE INDEX IDX_MOVPROMOCION_CORRE ON PCLUB.ADMPT_MOV_PROMOCION (ADMPN_CORRELATIVO)	
tablespace PCLUB_INDX;

ALTER TABLE PCLUB.ADMPT_MOV_PROMOCION		ADD CONSTRAINT PK_MOV_PROMOCION_CORRE PRIMARY KEY (ADMPN_CORRELATIVO);

CREATE TABLE PCLUB.ADMPT_AUD_PROMOCION
(
  ADMPN_ID_AUDI     NUMBER not null,
  ADMPN_ID_PROMO    NUMBER,
  ADMPD_FEC_INI_OLD DATE,
  ADMPD_FEC_FIN_OLD DATE,
  ADMPD_FEC_INI_NEW DATE,
  ADMPD_FEC_FIN_NEW DATE,
  ADMPD_FEC_REG     DATE,
  ADMPV_USU_REG     VARCHAR2(20),
  ADMPD_FEC_MOD     DATE,
  ADMPV_USU_MOD     VARCHAR2(20)
)
tablespace PCLUB_DATA;

CREATE UNIQUE INDEX IDX_AUD_PROMOCION_IDPROMO ON PCLUB.ADMPT_AUD_PROMOCION (ADMPN_ID_AUDI)
tablespace PCLUB_INDX;
  
ALTER TABLE PCLUB.ADMPT_AUD_PROMOCION	  ADD CONSTRAINT PK_AUD_PROMOCION_IDPROMO PRIMARY KEY (ADMPN_ID_AUDI);

--*--*--*--*--*--*--*-*--
---------------------------------------------------------------   
---------------------------------------------------------------
--ALTER TABLE A TABLAS EXISTENTES
ALTER TABLE PCLUB.ADMPT_KARDEX ADD(ADMPV_DESC_PROM VARCHAR2(200));
