CREATE OR REPLACE TRIGGER PCLUB.T_ALFANUMERICO BEFORE
INSERT ON PCLUB.ADMPT_ALFANUMERICO FOR EACH ROW
WHEN ( NEW.ADMPN_CORRELATIVO  IS NULL )
BEGIN
  SELECT PCLUB.ADMPT_ALFANUMERICO_SQ.NEXTVAL
  INTO   :NEW.ADMPN_CORRELATIVO
  FROM   DUAL;
END;
/
