LOAD DATA
append into table PCLUB.ADMPT_TMP_BAJA_CC
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY ';' 
TRAILING NULLCOLS
(
ADMPV_TIP_CLIENTE	CHAR,
ADMPV_CUSTCODE	CHAR,
ADMPD_FEC_BAJA	DATE "DD/MM/YYYY",
ADMPV_TIPO_DOC	CHAR,
ADMPV_NUM_DOC	CHAR,
ADMPD_FEC_OPER	"TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY')",
ADMPV_NOM_ARCH	CHAR,
ADMPC_COD_ERROR	CHAR,
ADMPV_MSJE_ERROR	CHAR,
ADMPN_SEQ	SEQUENCE(COUNT,1)
)


