LOAD DATA
append into table PCLUB.ADMPT_TMP_CAMBIOPLAN_HFCB
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY ';' 
TRAILING NULLCOLS
(
ADMPV_TIP_CLIENTE	CHAR,
ADMPV_TIPO_DOC	CHAR,
ADMPV_NUM_DOC	CHAR,
ADMPV_CUSTCODE	CHAR,
ADMPV_TIPO_SERV	CHAR,
ADMPD_FEC_CAM	DATE "DD/MM/YYYY",
ADMPC_TO CHAR,
ADMPD_FEC_OPER	"TO_DATE(TO_CHAR(SYSDATE,'DD/MM/YYYY'),'DD/MM/YYYY')",
ADMPV_NOM_ARCH	CHAR,
ADMPN_SEQ	SEQUENCE(COUNT,1)
)