--secuencia para la tabla que registra los datos que se nos envia desde el SGA

DROP SEQUENCE PCLUB.ADMPT_PREMODIF_CLIENTE_SQ;

--ELIMINACION SECUENCIA DE LA TABLA SALDOSFIJA

DROP SEQUENCE PCLUB.ADMPT_SLD_CLFIJA_SQ;

--ELIMINAR SECUENCIA TABLA KARDEXFIJA
  
DROP SEQUENCE PCLUB.ADMPT_KARDEXFIJA_SQ;

--ELIMINAR SECUENCIA TABLA IMP DE FACTURACION

DROP SEQUENCE PCLUB.ADMPT_PAGOHFC_SQ;
  
--ELIMINAR SECUENCIA DE TABLA IMP DE PROMOCION

DROP SEQUENCE PCLUB.ADMPT_IMP_PROM_DTH_HFC_SQ;

--ELIMINAR SECUENCIA DE TABLA IMP DE REGULARIZACION

DROP SEQUENCE PCLUB.ADMPT_IMP_REG_DTH_HFC_SQ;

--ELIMINAR SECUENCIA DE TABLA IMP DE CAMBIO DE TITULAR

DROP SEQUENCE PCLUB.ADMPT_SQ_CAMBTIT_HFC;

--ELIMINAR SECUENCIA DE TABLA IMP MIGRACION 

DROP SEQUENCE PCLUB.ADMPT_ALTADTH_SQ;

--ELIMINAR SECUENCIA DE TABLA CANJE

DROP SEQUENCE PCLUB.ADMPT_CANJEFIJA_SQ;
