DROP SEQUENCE PCLUB.ADMPT_CAMBIOTT_DTH_HFC_SQ;

DROP SEQUENCE PCLUB.ADMPT_ALTACLIDTH_SQ;

DROP SEQUENCE PCLUB.ADMPT_IMP_BAJADTH_SQ;

DROP SEQUENCE PCLUB.ADMPT_PAGODTH_SQ;

DROP SEQUENCE PCLUB.ADMPT_IMP_ANIVDTH_SQ;