DROP SEQUENCE PCLUB.ADMPT_MOVIMIENTOCUP_SQ;

DROP SEQUENCE PCLUB.ADMPT_CONSULTACUP_SQ;

DROP SEQUENCE PCLUB.ADMPT_TMPCUPONERA_SQ;

DROP SEQUENCE PCLUB.ADMPT_CAMBSEGMENTO_SQ;

DROP SEQUENCE PCLUB.ADMPT_OFERTA_SQ;

DROP SEQUENCE PCLUB.ADMPT_CUPON_SQ;

DROP SEQUENCE PCLUB.ADMPT_CUPONERA_SQ;

DROP SEQUENCE PCLUB.ADMPT_TELEF_CUP_SQ;

DROP SEQUENCE PCLUB.ADMPT_ALTAMASCUPONERA_SQ;

DROP SEQUENCE PCLUB.ADMPT_CLIECUPONERA_SQ;

