drop sequence PCLUB.ADMPT_IMP_ALTACLITFI_SQ;
drop sequence PCLUB.ADMPT_IMP_ANIVERSTFI_SQ;
drop sequence PCLUB.ADMPT_IMP_BAJACLI_TFI_SQ;
drop sequence PCLUB.ADMPT_IMP_PROMOCIONTFI_SQ;
drop sequence PCLUB.ADMPT_IMP_RECARGATFI_SQ;
drop sequence PCLUB.ADMPT_IMP_REGULARIZATFI_SQ;
drop sequence PCLUB.ADMPT_IMP_SINRECARGATFI_SQ;
drop sequence PCLUB.ADMPT_IMP_TFICMBTIT_SQ;