DROP SEQUENCE PCLUB.ADMPT_IMP_ALTACLIENTESERV_SQ;
DROP SEQUENCE PCLUB.ADMPT_IMP_PAGHFC_SQ;
DROP SEQUENCE PCLUB.ADMPT_IMP_ANIVCC_SQ;
DROP SEQUENCE PCLUB.ADMPT_IMP_BAJACC_SQ;

DROP SEQUENCE PCLUB.ADMPT_IMP_CAMBIOPLANHFCB_SQ;
DROP SEQUENCE PCLUB.ADMPT_PAGORPT_SQ;
DROP SEQUENCE PCLUB.ADMPT_IMP_ANIVRT_SQ;
DROP SEQUENCE PCLUB.ADMPT_IMP_ALTACLIESERVRPT_SQ;
