DROP SEQUENCE PCLUB.ADMPT_BONOPREP_ERR_SQ;
DROP SEQUENCE PCLUB.ADMPT_IMP_BONOFIDEL_PRE_SQ;
DROP SEQUENCE PCLUB.ADMPT_SALDOS_BONO_CLIENTE_SQ;
DROP SEQUENCE PCLUB.ADMPT_TMP_PRESINRECARGA_SQ;
DROP SEQUENCE PCLUB.ADMPT_IMP_ALTA_XRECARGA_PRE_SQ;
DROP SEQUENCE PCLUB.ADMPT_CLIENTE_SQ;