CREATE OR REPLACE PACKAGE PCLUB.CC_PKG_FIDELIDAD IS
  TYPE CUR_SEC IS REF CURSOR;
  PROCEDURE CC_MERGE_FIDELIDAD(P_RETORNO OUT INT);
  PROCEDURE CC_LIST_PDT_ACT(K_CUR_SALIDA OUT CUR_SEC);
  PROCEDURE CC_ACT_FIDELIDAD(P_RETORNO OUT INT);
  PROCEDURE CC_LIST_CONFIG_SMS(K_CUR_SALIDA   OUT CUR_SEC,
                               P_CONFV_OPCION IN CC_CONFIG_SMS.CONFV_OPCION%TYPE,
                               P_CONFN_CODIGO IN CC_CONFIG_SMS.CONFN_CODIGO%TYPE);
  PROCEDURE CC_ACT_FIDELIDAD_SMS(P_RETORNO OUT INT);
  PROCEDURE CC_REP_LINEAS_BL(CURLINEASBL   OUT SYS_REFCURSOR);
END CC_PKG_FIDELIDAD;
/