create or replace package PCLUB.PKG_CLAROCLUB is

procedure ADMPSI_ACTIV_IB (K_FECHA IN DATE, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR );
procedure ADMPSI_AGR_PTIB( K_CODCLIENTEIB IN NUMBER, K_CODCLIENTECC IN VARCHAR2, K_CODCONCEPTO IN VARCHAR2,K_PUNTOSIGNO IN NUMBER, K_NOMARCHIVO IN VARCHAR2, K_TIPOP IN CHAR,K_ESTADO IN CHAR);
procedure ADMPSI_CAMPA_IB (K_FECHA IN DATE ,K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);
procedure ADMPSI_CANCE_IB (K_FECHA IN DATE, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);
procedure ADMPSI_DEBITOIB(K_FECHA IN DATE, K_NOM_ARCH IN VARCHAR2, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2) ;
procedure ADMPSI_FACTU_IB(K_FECHA IN DATE,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);
procedure ADMPSS_BON_ACTTC(K_CODERROR OUT NUMBER, K_MSJERROR OUT VARCHAR2);
procedure ADMPSS_EACAMOIB(K_FECHAPROC IN DATE, CursorAcCaMo out SYS_REFCURSOR);
procedure ADMPSS_EFACAMIB(K_FECHAPROC IN DATE, CursorFaCaIB out SYS_REFCURSOR);
procedure ADMPSI_EDEBITIB(K_FECHAPROC IN DATE, CursorDebito out SYS_REFCURSOR);
procedure ADMPSS_EJDIA_IB(K_FECHA IN DATE, K_CODERROR OUT VARCHAR2, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
procedure ADMPSS_EJMEN_IB(K_FECHA IN DATE, K_CODERROR OUT VARCHAR2, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
procedure ADMPSS_EJDEB_IB(K_FECHA IN DATE, K_CODERROR OUT VARCHAR2, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
procedure ADMPSS_CLIREFER(K_NOMBRES IN VARCHAR2, K_APELLIDOS IN VARCHAR2, K_TIPO_DOC IN VARCHAR2, K_NUM_DOC IN VARCHAR2, K_NUMLINEA IN VARCHAR2, K_NUMREF IN VARCHAR2, K_IPREG IN VARCHAR2,  K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);
procedure ADMPSS_CONCLRF(K_FECHA IN DATE, CURSORCLIENTEREF OUT SYS_REFCURSOR);
procedure ADMPSS_ACTREF(K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, CursorClienteRef OUT SYS_REFCURSOR);
procedure ADMPSS_VADAT_IB(K_FECHAPROCESO IN DATE, K_INDICADOR IN CHAR, K_TRANSACCION IN VARCHAR2, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);
procedure ADMPSS_PUNTOSIB(K_FECHA IN DATE, CursorClienteIB out SYS_REFCURSOR);
procedure ADMPSS_DAT_CLIE ( K_CUSTCODE IN  VARCHAR2, K_DN_NUM IN  VARCHAR2, K_SQLERROR OUT VARCHAR2, K_cursor IN OUT SYS_REFCURSOR );
procedure ADMPSS_DAT_LINE ( K_CO_ID IN  NUMBER, K_CURSOR OUT SYS_REFCURSOR );
procedure ADMPSS_TRIADOS ( K_CO_ID IN  NUMBER, K_CURSOR OUT SYS_REFCURSOR);
procedure ADMPSS_LEESERPN(K_FECHAPROC IN DATE, CursorServPend out SYS_REFCURSOR);
procedure ADMPSS_ACTSERPN(K_IDFILA IN NUMBER, K_USUARIO IN VARCHAR2, K_MENSAJE IN VARCHAR2);
procedure ADMPSI_CLIREFINV (K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);
procedure ADMPSI_ECLIREFINV (CursorRefInv out SYS_REFCURSOR);
PROCEDURE ADMPSS_SP_STATUS_DN_NUM_CO_ID (p_flag IN INTEGER,p_valor IN VARCHAR2, v_flag_resultado OUT INTEGER, v_error OUT INTEGER, v_des_error OUT VARCHAR2);

end PKG_CLAROCLUB;