create or replace package PCLUB.PKG_CC_TRANFERENCIA is

  -- Author  : E76018
  -- Created : 31/03/2011 10:18:32 a.m.
  -- Purpose :
TYPE K_REF_CURSOR IS REF CURSOR;

PROCEDURE ADMPSS_CREA_TRASNFERENCIA
(
  K_TIPO_DOC      IN  VARCHAR2,
  K_NUM_DOC       IN  VARCHAR2,
  K_BOLSA         IN  VARCHAR2,
  K_TIPO          IN  VARCHAR2,
  K_PUNTOS        IN  NUMBER,
  K_PTO_VENTA     IN  VARCHAR2,
  K_ASESOR        IN  VARCHAR2,
  K_NOTAS         IN  VARCHAR2,
  K_ORIGEN        IN  VARCHAR2,
  K_ID_TRANSCLARO OUT NUMBER,
  K_VALOR         OUT VARCHAR2,
  K_MSJERROR      OUT VARCHAR2
);

PROCEDURE ADMPSS_TRASNFIERE_PTOS
(
  K_ID_TRANSCLARO  IN  NUMBER,
  K_ID_TRANSBONUS  IN  VARCHAR2,
  K_TIPO_DOC       IN  VARCHAR2,
  K_NUM_DOC        IN  VARCHAR2,
  K_BOLSA          IN  VARCHAR2,
  K_TIPO           IN  VARCHAR2,
  K_PUNTOS         IN  NUMBER,
  K_RESP_LOYALTY   IN  VARCHAR2,
  K_VALOR          OUT VARCHAR2,
  K_MSJERROR       OUT VARCHAR2
);

PROCEDURE ADMPSS_ACT_TRASNFERENCIA
(
  K_ID_TRANSCLARO  IN  NUMBER,
  K_ID_TRANSBONUS  IN  VARCHAR2,
  K_RESP_LOYALTY   IN  VARCHAR2,
  K_VALOR          OUT VARCHAR2,
  K_MSJERROR       OUT VARCHAR2
);

PROCEDURE ADMPSS_CAN_TRASNFERENCIA
(
  K_ID_TRANSCLARO  IN  NUMBER,
  K_ID_TRANSBONUS  IN  VARCHAR2,
  K_RESP_LOYALTY   IN  VARCHAR2,
  K_VALOR          OUT VARCHAR2,
  K_MSJERROR       OUT VARCHAR2
);

PROCEDURE ADMPSS_CON_TRASNFERENCIA
(
  K_TIPO_DOC     IN  VARCHAR2,
  K_NUM_DOC      IN  VARCHAR2,
  K_TIPO_MOV     IN  VARCHAR2,
  K_FECHA_INICIO IN  VARCHAR2,
  K_FECHA_FINAL  IN  VARCHAR2,
  K_CURSOR       OUT K_REF_CURSOR,
  K_VALOR        OUT VARCHAR2,
  K_MSJERROR     OUT VARCHAR2
);

PROCEDURE ADMPSI_ES_CLIENTE
(
  K_TIPO_DOC       IN  VARCHAR2,
  K_NUM_DOC        IN  VARCHAR2,
  K_BOLSA          IN  VARCHAR2,
  K_COD_CLIENTE    OUT VARCHAR2,
  K_COD_CLIENTE_IB OUT VARCHAR2,
  K_SALDO          OUT NUMBER,
  K_VALOR            OUT NUMBER,
  K_MSJERROR       OUT VARCHAR2
);

PROCEDURE ADMPSI_GETCLIENTESPREPAGO
(
  K_TIPO_DOC       IN  VARCHAR2,
  K_NUM_DOC        IN  VARCHAR2,
  K_CURSOR         OUT K_REF_CURSOR,
  K_VALOR            OUT NUMBER,
  K_MSJERROR       OUT VARCHAR2
);

PROCEDURE ADMPSI_GETPARAMSIST
(
  K_DESC IN VARCHAR2,
  K_VALOR OUT VARCHAR2,
  K_MSJERROR OUT VARCHAR2
);

PROCEDURE ADMPSI_GETTIPODOC
(
  K_CURSOR OUT K_REF_CURSOR
);

PROCEDURE ADMPSI_ACT_TRANS_MSGERROR
(
  K_ID_TRANSCLARO  IN  NUMBER,
  K_RESP_CLARO     IN  VARCHAR2
);
end PKG_CC_TRANFERENCIA;
/
