CREATE OR REPLACE PACKAGE pclub.PKG_CC_ENVIO_SMS IS

PROCEDURE ADMPSS_TIPIFICACIONES_MICLARO(K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, CUR_TIPI OUT SYS_REFCURSOR);

PROCEDURE ADMPSS_COUNT_SMSMICLARO(K_COUNT OUT NUMBER,K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);

PROCEDURE ADMPSS_ENVIOSMS_MICLARO(K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, CUR_SMS OUT SYS_REFCURSOR);

PROCEDURE ADMPSI_CARGA_PREP_DOL(K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);

PROCEDURE ADMPSS_COUNT_SMS(K_PROCESO IN VARCHAR2,K_USUARIO IN VARCHAR2,K_COUNT OUT NUMBER,K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);

PROCEDURE ADMPSI_ENVIOSMS_PROCESOS(K_PROCESO IN VARCHAR2,K_USUARIO IN VARCHAR2,K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, CUR_SMS OUT SYS_REFCURSOR);

PROCEDURE ADMPSS_OBTENERMENSAJE_POST(K_FLAG IN VARCHAR2,K_MENSAJE OUT VARCHAR2,K_CODERROR  OUT NUMBER,K_DESCERROR OUT VARCHAR2);
       
PROCEDURE ADMPSS_OBTENER_TELEFONOS(K_PROCESO IN VARCHAR2, K_ESTADO IN CHAR,K_FLAG IN CHAR,K_RESULTADO OUT NUMBER,K_DESRESULTADO OUT VARCHAR2, CURSORTELEFONOS out SYS_REFCURSOR);

END PKG_CC_ENVIO_SMS;
/