CREATE OR REPLACE PACKAGE PCLUB.PKG_CC_CUPONERA AS
/******************************************************************************
   NAME:       PKG_CC_CUPONERA
   PURPOSE:

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        10/08/2012      E77210 - JCGT      1. Created this package.
******************************************************************************/


 PROCEDURE ADMPSI_ALTACLIENTEDIARIO(K_TIPODOC IN VARCHAR2,K_NUMDOC IN VARCHAR2,K_NOMCLI IN VARCHAR2,K_APECLI IN VARCHAR2,K_EMAIL IN VARCHAR2,
                                                    K_ORIGEN  IN VARCHAR2, K_USUARIO IN VARCHAR2, K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_ALTACLIENTE(K_TIPODOC IN VARCHAR2,K_NUMDOC IN VARCHAR2,K_NOMCLI IN VARCHAR2,K_APECLI IN VARCHAR2,K_EMAIL IN VARCHAR2,
                                                    K_COD_SEG IN NUMBER,K_ORIGEN  IN VARCHAR2, K_USUARIO IN VARCHAR2, K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_BAJACLIENTE(K_TIPODOC IN VARCHAR2,K_NUMDOC IN VARCHAR2,K_ORIGEN  IN VARCHAR2,K_USUARIO IN VARCHAR2,K_COD_CLI OUT NUMBER,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);
 --PROCEDURE ADMPSI_BAJACLIENTE(K_TIPODOC IN VARCHAR2,K_NUMDOC IN VARCHAR2,K_ORIGEN  IN VARCHAR2,K_USUARIO IN VARCHAR2,K_COD_CLI OUT NUMBER,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);
 PROCEDURE ADMPSI_ACTCLIENTE(K_COD_CLI IN NUMBER,K_NOMCLI IN VARCHAR2,K_APECLI IN VARCHAR2,K_EMAIL IN VARCHAR2,K_ESTADO IN VARCHAR2,
                                                    K_COD_SEG IN NUMBER,K_USUARIO IN VARCHAR2, K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 -- PROCEDURE ADMPSI_CONCLIENTE(K_NUMDOC IN VARCHAR2,K_NOMCLI IN VARCHAR2,K_APECLI IN VARCHAR2,K_CUR_CLIE OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

  PROCEDURE ADMPSI_ALTAMASIVA(K_FECHA IN DATE,K_NOM_ARCH IN VARCHAR2, K_USUARIO IN VARCHAR2,K_NUMREGTOT OUT NUMBER,
                                                K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER, K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_EALTAMASIVA(K_FECHA IN DATE,K_NOM_ARCH IN VARCHAR2,K_CUR_CLIE OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_MIGRACIONCLIE(K_USUARIO IN VARCHAR2,K_NUMREGTOT OUT NUMBER,K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER, K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_CONSULTAESTABLECIMIENTO(K_CUR_EST OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_CONSULTASEGMENTO(K_CUR_SEG OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_CAMBIOTITULAR(K_TIPODOC IN VARCHAR2,K_NUMDOC IN VARCHAR2,K_TIPODOC_N IN VARCHAR2,K_NUMDOC_N IN VARCHAR2,K_NOMCLI IN VARCHAR2,K_APECLI IN VARCHAR2,K_EMAIL IN VARCHAR2,
                                                     K_ORIGEN  IN VARCHAR2, K_USUARIO IN VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_CREAESTABLECIMIENTO(K_COD_EST IN VARCHAR2,K_NOM_EST IN VARCHAR2,K_USUARIO IN VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_ACTESTABLECIMIENTO(K_COD_EST IN VARCHAR2,K_NOM_EST IN VARCHAR2,K_USUARIO IN VARCHAR2,
                                                                K_ESTADO IN VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_CONESTABLECIMIENTO(K_COD_EST IN VARCHAR2,K_NOM_EST IN VARCHAR2,K_CUR_EST OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

  PROCEDURE ADMPSI_ELIMINATELEF_EST(K_COD_EST IN VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_CREATELEF_EST(K_COD_EST IN VARCHAR2,K_DIR_EST IN VARCHAR2,K_NUM_TEL IN VARCHAR2,K_USUARIO IN VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_ACTTELEF_EST(K_COD_TEL IN NUMBER,K_COD_EST IN VARCHAR2,K_DIR_EST IN VARCHAR2,K_NUM_TEL IN VARCHAR2,K_USUARIO IN VARCHAR2,
                                                     K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_CONTELEF_EST(K_COD_EST IN VARCHAR2,K_CUR_TEL OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_CREACUPONERA(K_NOM_CUP IN VARCHAR2,K_FEC_INI IN VARCHAR2,K_FEC_FIN IN VARCHAR2,K_USUARIO IN VARCHAR2,K_ID_CUP OUT NUMBER,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_CONSULTACUPONERA(K_NOM_CUP IN VARCHAR2,K_CUR_CUP OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_ACTCUPONERA(K_ID_CUP IN NUMBER,K_NOM_CUP IN VARCHAR2,K_FEC_INI IN VARCHAR2,K_FEC_FIN IN VARCHAR2,K_ESTADO IN VARCHAR2,K_USUARIO IN VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_ELIMINACUPONERATMP(K_ID_CUP IN NUMBER,K_FLAG IN VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

  PROCEDURE ADMPSI_ELIMINACUPONERA(K_ID_CUP IN NUMBER,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_REPORTACUPONERATMP(K_ID_CUP IN NUMBER,K_USUARIO IN VARCHAR2,K_CUR_CUP OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);
 --PROCEDURE ADMPSI_VALIDAOFERTASCUP(K_ID_CUP IN NUMBER,K_CUR_CUP OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_ELIMINAOFERCUPTMP(K_ID_FILA IN NUMBER,K_ID_CUP IN NUMBER,K_CUR_CUP OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_NUEVOOFERCUPTMP(K_ID_SEG IN VARCHAR2,K_COD_EST IN VARCHAR2,K_COD_CUP IN VARCHAR2,K_DES_OFER IN VARCHAR2,K_NRO_RED IN VARCHAR2,
                K_ID_CUP IN NUMBER,K_USUARIO IN VARCHAR2,K_CUR_CUP OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_ACTOFERCUPTMP(K_ID_FILA IN NUMBER,K_ID_SEG IN VARCHAR2,K_COD_EST IN VARCHAR2,K_COD_CUP IN VARCHAR2,K_DES_OFER IN VARCHAR2,K_NRO_RED IN VARCHAR2,
                K_ID_CUP IN NUMBER,K_USUARIO IN VARCHAR2,K_CUR_CUP OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_VALIDARCUPONERATMP(K_ID_CUP IN NUMBER,K_CUR_CUP OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);
 --PROCEDURE ADMPSI_ELIMINACUPONERATMP(K_ID_FILA IN NUMBER,K_ID_CUP IN NUMBER,K_CUR_CUP OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_INSERTARCUPONERA(K_ID_CUP IN NUMBER,K_USUARIO IN VARCHAR2,K_CUR_CUP OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_ACTOFERTA(K_ID_CUP IN NUMBER,K_ID_OFER IN NUMBER,K_ESTADO IN VARCHAR2,K_USUARIO IN VARCHAR2,K_CUR_CUP OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_REPORTACUPONERA(K_ID_CUP IN NUMBER,K_USUARIO IN VARCHAR2,K_CUR_CUP OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_CONSULTACUP(K_NUM_DOC IN VARCHAR2,K_NUM_MOVIL IN VARCHAR2,K_COD_EST IN VARCHAR2,K_USUARIO IN VARCHAR2,K_RESP_SMS OUT VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_MOVIMCUP(K_NUM_DOC IN VARCHAR2,K_NUM_MOVIL IN VARCHAR2,K_COD_EST IN VARCHAR2,K_NUM_OFER IN VARCHAR2,K_USUARIO IN VARCHAR2,
 K_RESP_SMS OUT VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_CONCLIENTE(K_NUMDOC IN VARCHAR2,K_NOMCLI IN VARCHAR2,K_APECLI IN VARCHAR2,K_CUR_CLIE OUT SYS_REFCURSOR,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

  PROCEDURE ADMPSS_LISTAMOVCUPONERA(K_IDCUPONERA   IN VARCHAR2,
                                   K_FECHAINI     IN date,
                                   K_FECHAFIN     IN date,
                                   CURSORCUPONERA OUT SYS_REFCURSOR,
                                   K_CODERROR     OUT NUMBER,
                                   K_DESCERROR    OUT VARCHAR2);

 PROCEDURE ADMPSI_ALTACLIENTE_MAN(K_TIPODOC   IN VARCHAR2,
                                  K_NUMDOC    IN VARCHAR2,
                                  K_NOMCLI    IN VARCHAR2,
                                  K_APECLI    IN VARCHAR2,
                                  K_EMAIL     IN VARCHAR2,
                                  K_COD_SEG   IN NUMBER,
                                  K_ORIGEN    IN VARCHAR2,
                                  K_USUARIO   IN VARCHAR2,
                                  K_CODERROR  OUT NUMBER,
                                  K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_ELIMINARCONSULTAS(K_FECHAINI IN date,K_CODERROR  OUT NUMBER,K_DESCERROR OUT VARCHAR2);


 PROCEDURE ADMPSI_CAMBSEG_MASIVO(K_FECHA IN DATE,K_NOMARCH IN VARCHAR2,K_USUARIO IN VARCHAR2,K_NUMREGTOT OUT NUMBER,
                                                K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER, K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

 PROCEDURE ADMPSI_ECAMBSEG_MASIVO(K_FECHA IN DATE,K_NOMARCH IN VARCHAR2,K_CUR_CUP OUT SYS_REFCURSOR, K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);


END PKG_CC_CUPONERA;
/