create or replace package PCLUB.PKG_CC_PREPAGO_RECAR is
PROCEDURE ADMPSS_CATEG_PRERECARGA_WA(K_FECHA IN DATE,
                                   K_CODERROR OUT NUMBER,
                                   K_DESCERROR OUT VARCHAR2);
                   
procedure ADMPSI_PRERECAR_WA
  (
      K_USUARIO VARCHAR2,
      K_FECHA IN DATE,
      K_NUME_PROCES IN  NUMBER,
      K_CODERROR OUT NUMBER,
      K_DESCERROR OUT VARCHAR2,
      K_NUMREGTOT OUT NUMBER,
      K_NUMREGPRO OUT NUMBER,
      K_NUMREGERR OUT NUMBER
  );
 
procedure ADMPSI_PRERECAR_VALID_WA(K_FECHA IN DATE,K_NUME_PROCES IN  NUMBER,K_PARAMETRO IN NUMBER,  K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);

PROCEDURE ADMPSI_FECHAFALTA_PRO
(
  K_FECHA OUT DATE,
  K_CANTSIN_PROC OUT NUMBER,
  K_CANTSIN_CATE OUT NUMBER,
  K_CODERROR OUT NUMBER,
  K_DESCERROR OUT VARCHAR2
);

PROCEDURE ADMPSI_PRERECAR_CONF(K_PROC        IN NUMBER,
                                     K_COUNT       OUT NUMBER,
                                     K_CODERROR    OUT NUMBER,
                                     K_DESCERROR   OUT VARCHAR2);
end PKG_CC_PREPAGO_RECAR;
/