CREATE OR REPLACE PACKAGE PCLUB.PKG_CC_MIGRACION IS

PROCEDURE ADMPSS_OBTPREAPOS(K_FECHA IN DATE, K_NUMREGTOT OUT NUMBER, K_CODERROR OUT VARCHAR2, K_DESCERROR OUT VARCHAR2, CURSOROBTPREAPOS out SYS_REFCURSOR);

PROCEDURE ADMPSS_OBTPOSAPRE(K_FECHA IN DATE, K_NUMREGTOT OUT NUMBER, K_CODERROR OUT VARCHAR2, K_DESCERROR OUT VARCHAR2, CURSOROBTPOSAPRE out SYS_REFCURSOR);

PROCEDURE ADMPSS_OBTLINEAXCTA(K_TELEFONO IN VARCHAR,K_CUENTA IN VARCHAR2,K_NUMREGTOT OUT NUMBER, K_CODERROR OUT VARCHAR2, K_DESCERROR OUT VARCHAR2, CUR_LINXCTA out SYS_REFCURSOR);

PROCEDURE ADMPSS_OBTCTA(K_CUENTA IN VARCHAR2,K_TIPO_DOC IN VARCHAR2,K_NUM_DOC IN VARCHAR2,K_NUMREGTOT OUT NUMBER, K_CODERROR OUT VARCHAR2, K_DESCERROR OUT VARCHAR2, CUR_OBTCTA out SYS_REFCURSOR);

PROCEDURE ADMPSI_PREMIGPOS(K_FECHA IN DATE,K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);

PROCEDURE ADMPSI_PREMIGPRE(K_FECHA IN DATE, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);

END PKG_CC_MIGRACION;
/

