create or replace package PCLUB.PKG_CC_PREPAGO is

  procedure ADMPSI_PRERECAR(K_FECHA IN DATE, K_NUME_PROCES IN  NUMBER,K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);

  procedure ADMPSS_EPRERECAR(K_FECHA IN DATE, CURSOREPREREC out SYS_REFCURSOR);

  procedure ADMPSI_PRERECAR_VALID(K_FECHA IN DATE,K_NUME_PROCES IN  NUMBER,K_PARAMETRO IN NUMBER,  K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);

  procedure ADMPSI_PREACTIV(K_CODCLI IN VARCHAR2, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);
  procedure ADMPSS_EPREACTIV(K_FECHA IN DATE, CURSOREPREACTIV out SYS_REFCURSOR);
  procedure ADMPSI_PREALTACLI(K_FECHA IN DATE,K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
  procedure ADMPSI_REGCLIENTECC(K_NUMTELF IN VARCHAR2,K_TIPDOC IN VARCHAR2, K_NUMDOC IN VARCHAR2, K_NOMBRE IN VARCHAR2, K_APELLIDO IN VARCHAR2, K_SEXO IN VARCHAR2, K_ESTCIV IN VARCHAR2, K_EMAIL IN VARCHAR2, K_PROV IN VARCHAR2, K_DEPART IN VARCHAR2, K_DIST IN VARCHAR2, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);
  procedure ADMPSI_EPREALTACLI(K_FECHA IN DATE, CURSOREPREALTACLI out SYS_REFCURSOR);

  PROCEDURE ADMPSI_PRECMBTIT (K_FEC_PRO IN DATE, K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2, K_TOT_REG OUT NUMBER, K_TOT_PRO OUT NUMBER, K_TOT_ERR OUT NUMBER);
  PROCEDURE ADMPSI_EPRECMBTIT (K_FEC_PRO IN DATE, CMBTIT_CUR OUT SYS_REFCURSOR);
  PROCEDURE CamTituCC(K_FECHA IN DATE,CURSORCamTituCC out SYS_REFCURSOR);

  PROCEDURE ADMPSI_PRESINREC(K_NOMARCH IN VARCHAR2,
                             K_USUARIO IN VARCHAR2,
                             K_NUMREGTOT OUT NUMBER,
                             K_NUMREGVAL OUT NUMBER,
                             K_NUMREGERR OUT NUMBER,
                             K_CODERROR OUT NUMBER,
                             K_DESCERROR OUT VARCHAR2);

  PROCEDURE ADMPSI_PRESINREC_MASIVO(K_NOMARCH IN VARCHAR2,
                                    K_LINEA IN VARCHAR2,
                                    K_SALDO IN NUMBER,
                                    K_SALDO_BONO IN NUMBER,
                                    K_CODCLI_IB IN VARCHAR2,
                                    K_CONCEPTO IN VARCHAR2,
                                    K_USUARIO IN VARCHAR2,
                                    K_CODERROR OUT NUMBER,
                                    K_DESCERROR OUT VARCHAR2);

  PROCEDURE ADMPSS_TMP_PRESINRECARGA(K_NOMARCH IN VARCHAR2,
                                     K_NUMREG OUT NUMBER,
                                     K_CODERROR OUT NUMBER,
                                     K_DESCERROR OUT VARCHAR2);

  FUNCTION F_GETNUEVOCODIGO(K_CODIGO IN VARCHAR) RETURN VARCHAR2;

  PROCEDURE ADMPSI_EPRESINREC(K_NOMARCH IN VARCHAR2,
                              K_CUR_LISTA OUT SYS_REFCURSOR,
                              K_CODERROR OUT NUMBER,
                              K_DESCERROR OUT VARCHAR2);

  PROCEDURE ADMPSI_PREBAJACL(K_FECHA IN DATE,
                             K_USUARIO IN VARCHAR2,
                             K_CODERROR OUT NUMBER,
                             K_DESCERROR OUT VARCHAR2,
                             K_NUMREGTOT OUT NUMBER,
                             K_NUMREGPRO OUT NUMBER,
                             K_NUMREGERR OUT NUMBER);

  procedure ADMPSI_EPREBAJACL(K_FECHA IN DATE, CURSOREPREBAJACL out SYS_REFCURSOR);
  procedure ADMPSI_PREVENCPTO(K_CODERROR  OUT NUMBER, K_DESCERROR OUT VARCHAR2);
  procedure ADMPSI_PREMIGPRE(K_FECHINI IN DATE, K_FECHFIN IN DATE, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
  procedure ADMPSI_EPREMIGPRE(K_FECHA IN DATE, CURSOREPREMIGPRE out SYS_REFCURSOR);
  procedure ADMPSS_OBTPREAPOS(K_FECHINI IN DATE, K_FECHFIN IN DATE, K_NUMREGTOT OUT NUMBER, K_CODERROR OUT VARCHAR2, K_DESCERROR OUT VARCHAR2, CURSOROBTPREAPOS out SYS_REFCURSOR);
  procedure ADMPSI_PREMIGPOS(K_FECHINI IN DATE, K_FECHFIN IN DATE,K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
  procedure ADMPSI_EPREMIGPOS(K_FECHA IN DATE, CURSOREPREMIGPOS out SYS_REFCURSOR);
  procedure ADMPSS_OBTPOSAPRE(K_FECHINI IN DATE, K_FECHFIN IN DATE, K_NUMREGTOT OUT NUMBER, K_CODERROR OUT VARCHAR2, K_DESCERROR OUT VARCHAR2, CURSOROBTPOSAPRE out SYS_REFCURSOR);

  PROCEDURE ADMPSI_PREANIVER (K_FEC_PROCESO IN DATE, K_CODERROR OUT VARCHAR2, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
  PROCEDURE ADMPSI_EPREANIVER (K_FEC_PRO IN DATE, PREANIVER_CUR OUT SYS_REFCURSOR);

  procedure ADMPSI_TMPPROMOCION(K_CODCLI IN VARCHAR2, K_NOMPROM IN VARCHAR2,K_PERIODO IN VARCHAR2,K_PUNTOS IN NUMBER,K_NOMARCH IN VARCHAR2,K_SEQ IN NUMBER,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);
  procedure ADMPSI_PREPROMOCION(K_FECHA IN DATE,K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
  procedure ADMPSI_EPREPROMOCION(K_FECHA IN DATE, CURSOREPREPROMO out SYS_REFCURSOR);
  procedure ValPalSMS(K_PALABRA IN VARCHAR2,K_TIP_CLI IN VARCHAR2,K_CODCONTR IN NUMBER,K_COD_SERVC OUT NUMBER,K_ID_PROCLA OUT VARCHAR2,K_COD_TPOPR OUT VARCHAR2,K_PUNTOS OUT NUMBER,K_MNT_RECAR OUT NUMBER, K_COD_PAQT OUT VARCHAR2, K_CODRET OUT VARCHAR2,K_DESCERROR OUT VARCHAR2);
  procedure ADMPSS_TRANSPUNTOS(K_TELEFORI IN VARCHAR2, K_TIPCLIORI IN VARCHAR2, K_TELEFDES IN VARCHAR2, K_TIPCLIDES IN VARCHAR2, K_PUNTOS IN NUMBER,K_SALDO_CD OUT NUMBER, K_CODRET OUT NUMBER, K_MSJSERROR OUT VARCHAR2);
  procedure ADMPSI_DSCTO_PUNTO(K_COD_CLIENTE IN VARCHAR2, K_TIP_CLI IN VARCHAR2, K_PUNTOS IN NUMBER, K_CONCEPTOCC IN VARCHAR2, K_CONCEPTOIB IN VARCHAR2,K_CODERROR OUT NUMBER, K_MSJERROR OUT VARCHAR2);
  procedure ActCanSMS(K_IDCANJE IN VARCHAR2, K_MSJSMS IN VARCHAR2, K_TICKET IN VARCHAR2, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);
  procedure DelCanSMS(K_IDCANJE IN VARCHAR2, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);
  PROCEDURE ADMPSI_CARGA_CLIENTE(K_FECHA IN DATE, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
  PROCEDURE ADMPSI_CARGA_MICLARO(K_FECHA IN DATE,K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
  PROCEDURE ADMPSS_VALIDAR_CLIENTECC(K_NUMERO IN VARCHAR2,K_MENSAJE OUT VARCHAR2,K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);
  PROCEDURE ADMPSS_REGISTRO_CLIENTECC (K_TELEFONO VARCHAR2,K_TIPO_DOC VARCHAR2,K_NRO_DOC VARCHAR2,K_USUARIO VARCHAR2,K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);
  PROCEDURE ADMPSS_VALCCPREP(K_TELEFONO IN VARCHAR,
                           K_TIP_CLIENTE IN VARCHAR,
                           K_RESPUESTA OUT NUMBER,
                           K_DESCERROR OUT VARCHAR2,
                           K_MSJSIST OUT VARCHAR2);
  PROCEDURE ADMPSI_REGCLIENTESMS(K_TELEFONO IN VARCHAR,
                           K_USUARIO     IN VARCHAR,
                           K_MENSAJE     OUT VARCHAR,
                           K_RESPUESTA   OUT NUMBER,
                           K_DESCERROR   OUT VARCHAR2);
  PROCEDURE ADMPSI_REGCLIENTECC(K_COD_CLIENTE IN VARCHAR,
                           K_FEC_ENVIO     IN DATE,
                           K_RESULTADO     IN VARCHAR2,
                           K_MENSAJE       IN VARCHAR2,
                           K_USUARIO       IN VARCHAR2,
                           K_CODERROR      OUT NUMBER,
                           K_DESCERROR     OUT VARCHAR2);

 PROCEDURE ADMPSS_CATEG_PRERECARGA(K_CODERROR       OUT NUMBER,
                                   K_DESCERROR      OUT VARCHAR2);

PROCEDURE ADMPSS_SERVICIO_COMERCIAL(CURSORSERVICIO out SYS_REFCURSOR,
                                    K_CODERROR       OUT NUMBER,
                                    K_DESCERROR      OUT VARCHAR2);

PROCEDURE ADMPSI_DESAFI_VAL_INI(K_NOMARCH IN VARCHAR2,
                             K_USUARIO IN VARCHAR2,
                             K_PROCES IN NUMBER,
                             K_CODERROR OUT NUMBER,
                             K_DESCERROR OUT VARCHAR2);
PROCEDURE ADMPSI_DESAFI_PROCE(K_NOMARCH IN VARCHAR2,
                             K_USUARIO IN VARCHAR2,
                             K_PROCES IN NUMBER,
                             K_NUMREGTOT OUT NUMBER,
                             K_NUMREGVAL OUT NUMBER,
                             K_NUMREGERR OUT NUMBER,
                             K_OCODERROR OUT NUMBER,
                             K_ODESCERROR OUT VARCHAR2);



PROCEDURE ADMPSS_PREVENCPTO_PROCE
  (
  K_FECHA IN DATE,K_CATEGORIA     IN NUMBER,
  K_CODERROR      OUT NUMBER,
  K_DESCERROR     OUT VARCHAR2,
  K_NUMREGTOT     OUT NUMBER,
  K_NUMREGPRO     OUT NUMBER,
  K_NUMREGERR     OUT NUMBER);
  
  
  
  
  
  
 
PROCEDURE ADMPSI_DESAFI_CATEG(K_HILOS        IN NUMBER,
								K_NOMBREARCH IN VARCHAR,
								K_FECHA        IN DATE,
								K_CODERROR     OUT NUMBER,
								K_DESCERROR    OUT VARCHAR2);

   
                            

                             

PROCEDURE ADMPSI_DESAFI_REG_AUDITORIA( 
					vAUD_ID_PROCESO 			    IN VARCHAR2,
					vAUD_FECHA_REGISTRO 		  IN DATE,
					vAUD_DESCRIPCION_PROCESO 	IN VARCHAR2,
					vAUD_ID_EJEC_PROCESO		  IN VARCHAR2,
					vAUD_EJECUCION_PROCESO		IN VARCHAR2,
					vAUD_PARAMETROS				    IN VARCHAR2,

					vAUD_HORA_INICIO_LOTE		IN DATE,
					vAUD_HORA_FIN_LOTE	  	IN DATE,
					vAUD_LOTE_DEBE_IR			  IN VARCHAR2,
					vAUD_LOTE_EJECUTO			  IN VARCHAR2,
					vAUD_ESTADO_LOTE			  IN VARCHAR2,
					
					vAUD_REGISTRO_ERROR_LOTE 	IN VARCHAR2,
					vAUD_MENSAJE_ERROR			IN VARCHAR2,
					vUSUARIO					      IN VARCHAR2,
					vESTADO_REGISTRO			  IN VARCHAR2, ---EXITOSO, FALLIDO
					
                                     K_CODERROR    OUT NUMBER,
                                     K_DESCERROR   OUT VARCHAR2);

  
PROCEDURE ADMPSI_PREVENCPTO_CARGA
  (
  K_FECHA IN DATE,
  K_CODERROR  OUT NUMBER, 
  K_DESCERROR OUT VARCHAR2);
  
  PROCEDURE ADMPSI_DESAFI_LIMP(K_RESULTADO    OUT NUMBER,
  K_CODERROR  OUT NUMBER, 
  K_DESCERROR OUT VARCHAR2);
  


  PROCEDURE ADMPSS_PREVENCPTO_VALI(K_CODERROR  OUT NUMBER,
  K_DESCERROR OUT VARCHAR2,
  K_FECHA OUT VARCHAR2, 
  K_COUNT OUT NUMBER,
  K_COUNT_CAT OUT NUMBER);
  PROCEDURE ADMPSS_PREVENCPTO_CATEG(
                                    K_CODERROR       OUT NUMBER,
                                    K_DESCERROR      OUT VARCHAR2);

									 
end PKG_CC_PREPAGO;
/