CREATE OR REPLACE PACKAGE PCLUB.PKG_CC_PTOSFIJA IS

TYPE TAB_ARRAY IS TABLE OF VARCHAR2(50)    INDEX BY BINARY_INTEGER;
FUNCTION SPLITCAD(P_IN_STRING VARCHAR2, P_DELIM VARCHAR2) RETURN TAB_ARRAY;
FUNCTION DEVOLVER_POSICION(P_IN_STRING VARCHAR2) RETURN NUMBER;

PROCEDURE ADMPSI_BUSCARCLIENTE(K_TIPDOC IN VARCHAR2,K_NUMDOC IN VARCHAR2,K_TIPCLIE IN VARCHAR2, K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,CLIEN_CUR OUT SYS_REFCURSOR);
PROCEDURE ADMPSI_PREMODIF_CLIENTE(K_FLAG IN VARCHAR2,K_COD_CLIPROD IN  VARCHAR2,K_TIPODOC IN VARCHAR2,K_NUMDOC IN VARCHAR2,K_NOMCLI IN VARCHAR2,K_APECLI IN VARCHAR2,K_SEX IN VARCHAR2,K_EST_CIV IN VARCHAR2,
                              K_EMAIL IN VARCHAR2,K_DEPT IN VARCHAR2,K_PROV IN VARCHAR2,K_DIST IN VARCHAR2,K_CIC_FAC IN VARCHAR2,K_TIPCLIE IN VARCHAR2,
                              K_USUARIO IN VARCHAR2, K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);  

PROCEDURE ADMPSI_ALTACLIENTE(K_COD_CLIPROD IN  LISTA_CLI_PRODUCTO,K_TIPODOC IN VARCHAR2,K_NUMDOC IN VARCHAR2,K_NOMCLI IN VARCHAR2,K_APECLI IN VARCHAR2,K_SEX IN VARCHAR2,K_EST_CIV IN VARCHAR2,
                              K_EMAIL IN VARCHAR2,K_DEPT IN VARCHAR2,K_PROV IN VARCHAR2,K_DIST IN VARCHAR2,K_CIC_FAC IN VARCHAR2,K_TIPCLIE IN VARCHAR2,
                              K_USUARIO IN VARCHAR2, K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);  
                              
PROCEDURE ADMPSI_BAJACLICHFC(K_COD_CLIPROD IN LISTA_CLI_PRODUCTO,K_TIPDOC IN VARCHAR2,K_NUMDOC IN VARCHAR2,K_USUARIO IN VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);                                

PROCEDURE ADMPSI_PREVENCPTO( K_TIP_CLI IN VARCHAR2, K_USUARIO IN VARCHAR2, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);

PROCEDURE ADMPSI_FACTURAHFC (K_FECHA IN DATE,K_USUARIO IN VARCHAR2, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
PROCEDURE ADMPSI_EFACTURAHFC (K_FECHA IN DATE, CURSORPAGO OUT SYS_REFCURSOR);
--PROCEDURE ADMPSI_PRECAMBIOPLAN(K_COD_CLIPROD IN  VARCHAR2,K_TIPO_DOC IN VARCHAR2,K_NUM_DOC IN VARCHAR2,K_USUARIO IN VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);
PROCEDURE ADMPSI_CAMBIOPLAN(K_COD_CLIPROD IN  LISTA_CLI_PRODUCTO,K_TIPO_DOC IN VARCHAR2,K_NUM_DOC IN VARCHAR2,K_USUARIO IN VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);
PROCEDURE ADMPSI_VALIDARCLIENTE(K_TIPDOC IN VARCHAR2,K_NUMDOC IN VARCHAR2,K_TIPCLIE IN VARCHAR2,K_COD_CLI OUT VARCHAR2, K_MENSAJE OUT VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);
                              
/*SUSANA*/
PROCEDURE ADMPSI_PROMDTH_HFC(K_TIP_CLI IN VARCHAR2, K_USUARIO IN VARCHAR2,K_FECHA IN DATE,K_NOM_ARCH IN VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,
                                     K_NUMREGTOT OUT NUMBER,K_NUMREGPRO OUT NUMBER,K_NUMREGERR OUT NUMBER);
PROCEDURE ADMPSI_EPROMDTH_HFC( K_TIP_CLI IN VARCHAR2,K_FECHA IN DATE, K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,
                                        CURSORE_DTH_HFC_PROMO OUT SYS_REFCURSOR);
PROCEDURE ADMPSI_REGDTH_HFC(K_TIP_CLI IN VARCHAR2,K_USUARIO IN VARCHAR2, K_FECHA IN DATE,K_NOM_ARCH IN VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,
                             K_NUMREGTOT OUT NUMBER,K_NUMREGPRO OUT NUMBER,K_NUMREGERR OUT NUMBER);

PROCEDURE ADMPSI_EREGDTH_HFC(K_TIP_CLI IN VARCHAR2, K_FECHA   IN DATE, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, CURSORREGPTO OUT SYS_REFCURSOR);

PROCEDURE ADMPSI_DESCPTOS_PROMO( K_PUNTOS IN NUMBER, K_SERVICIO IN VARCHAR2, K_CODCLIE IN VARCHAR2,K_USUARIO IN VARCHAR2,K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);
                
PROCEDURE ADMPSI_CAMBTIT (K_TIP_CLI    IN VARCHAR2, K_COD_CLIPROD    IN LISTA_CLI_PRODUCTO, K_TIPODOC IN VARCHAR2,
                          K_NUMDOC     IN VARCHAR2, K_COD_CLIPROD_N  IN LISTA_CLI_PRODUCTO, K_TIPODOC_N  IN VARCHAR2,
                          K_NUMDOC_N   IN VARCHAR2, K_NOMCLI         IN VARCHAR2, K_APECLI IN VARCHAR2,
                          K_SEXO       IN VARCHAR2, K_ESTCIVIL       IN VARCHAR2, K_EMAIL  IN VARCHAR2,
                          K_PROV       IN VARCHAR2, K_DEPAR          IN VARCHAR2, K_DIST   IN VARCHAR2,
                          K_CICLOFACT  IN VARCHAR2, K_USUARIO        IN VARCHAR2, K_CODERROR  OUT NUMBER, K_DESCERROR  OUT VARCHAR2);

PROCEDURE ADMPSI_CAMBIOTITULAR_HFC(K_FECHAPROC IN DATE,K_NUMREGTOT OUT NUMBER,K_NUMREGERR OUT NUMBER,K_NUMREGPRO OUT NUMBER,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);

PROCEDURE ADMPSI_CAMBIOTITULAR_DTH (K_USUARIO IN VARCHAR2, K_FECHAOPER IN DATE,K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2 );

PROCEDURE ADMPSI_ECAMBIOTITULAR_HFC( K_FECHAPROC IN DATE,CURSORCAMBTI OUT SYS_REFCURSOR);
PROCEDURE ADMPSI_ECAMBIOTITULAR_DTH(K_FECHAPROC IN DATE, CURSORCAMBTI OUT SYS_REFCURSOR);

PROCEDURE ADMPSS_DATOS_CLIENTEDTH(K_CUSTCODE IN VARCHAR2,
                                       K_SQLERROR OUT VARCHAR2,
                                       K_CURSOR   IN OUT SYS_REFCURSOR);

PROCEDURE ADMPSS_BAJA (K_TIP_CLI IN VARCHAR2,K_CODCLIENTE IN VARCHAR2, K_TIP_BAJA IN VARCHAR2,K_COD_CLIPROD IN VARCHAR2,
                        K_USUARIO IN VARCHAR2,K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2);

/*SUSANA*/

/*JCGT MIGRACION*/
PROCEDURE ADMPSI_MIGRACLIENTEHFC(K_FEC_PROCESO IN DATE,K_USUARIO IN VARCHAR2, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER,
                                                K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
PROCEDURE ADMPSI_EMIGRACLIENTEHFC(K_FEC_PROCESO IN DATE,CURCLIENTES OUT SYS_REFCURSOR);      

PROCEDURE ADMPSS_VLD_CAMTIT       (K_TIP_CLI        IN VARCHAR2,
                             K_COD_CLIPROD    IN LISTA_CLI_PRODUCTO,
                             K_TIPODOC        IN VARCHAR2,
                             K_NUMDOC         IN VARCHAR2,
                             K_CODERROR   OUT NUMBER,
                             K_DESCERROR  OUT VARCHAR2);   
                          


PROCEDURE ADMPSI_ALTACLIENTEDTH(K_FEC_PROCESO IN DATE,K_USUARIO IN VARCHAR2, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER,
                                                K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
PROCEDURE ADMPSI_EALTACLIENTEDTH(K_FEC_PROCESO IN DATE,CURCLIENTES OUT SYS_REFCURSOR);                                                
PROCEDURE ADMPSI_BAJACLIENTEDTH(K_FECHA IN DATE,K_USUARIO IN VARCHAR2,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,
                                                K_NUMREGTOT OUT NUMBER,K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
PROCEDURE ADMPSI_EBAJACLIENTEDTH(K_FEC_PROCESO IN DATE,CURCLIENTES OUT SYS_REFCURSOR);            
PROCEDURE ADMPSI_FACTURADTH(K_FECHA IN DATE,K_USUARIO IN VARCHAR2, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, 
                                                K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
PROCEDURE ADMPSI_EFACTURADTH(K_FEC_PROCESO IN DATE,CURCLIENTES OUT SYS_REFCURSOR);                                                            
PROCEDURE ADMPSI_ANIVERSARIO (K_FEC_PROCESO IN DATE,K_USUARIO IN VARCHAR2, K_CODERROR OUT VARCHAR2, K_DESCERROR OUT VARCHAR2, 
                                                K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);                                                
PROCEDURE ADMPSI_EANIVERSARIO(K_FEC_PROCESO IN DATE,CURCLIENTES OUT SYS_REFCURSOR);            

PROCEDURE ADMPSI_ALTACLIENTE_SVR
(
  K_TIPCLIENTE IN VARCHAR2,
  K_FEC_PROCESO IN DATE,
  K_USUARIO IN VARCHAR2,
  K_CODERROR OUT NUMBER,
  K_DESCERROR OUT VARCHAR2,
  K_NUMREGTOT OUT NUMBER,
  K_NUMREGPRO OUT NUMBER,
  K_NUMCLIEXI  OUT NUMBER,
  K_NUMCLIDUP OUT NUMBER,
  K_NUMREG OUT NUMBER,
  K_NUMREGERR OUT NUMBER
);

PROCEDURE ADMPSI_ELIMINA_ALTACLIENTE_HFC
(
  K_TIPCLIENTE IN VARCHAR2,
  K_FEC_PROCESO IN DATE,
  K_NOMARC IN VARCHAR2,
  K_CODERROR OUT NUMBER,
  K_DESCERROR OUT VARCHAR2 
);

PROCEDURE ADMPSI_FACTURA
(
  K_FEC_PROCESO IN DATE,
  K_USUARIO IN VARCHAR2,
  K_CODERROR OUT NUMBER, 
  K_DESCERROR OUT VARCHAR2, 
  K_NUMREGTOT OUT NUMBER,
  K_NUMREGPRO OUT NUMBER, 
  K_NUMREGERR OUT NUMBER
 );
 
PROCEDURE ADMPSI_ANIVERSARIO_CC
(
  K_TIPCLIENTE IN VARCHAR2,
  K_FEC_PROCESO IN DATE,
  K_USUARIO IN VARCHAR2,
  K_CODERROR OUT NUMBER, 
  K_DESCERROR OUT VARCHAR2, 
  K_NUMREGTOT OUT NUMBER,
  K_NUMREGPRO OUT NUMBER, 
  K_NUMREGERR OUT NUMBER
 );

PROCEDURE ADMPSI_BAJA_CC
(
  K_TIPCLIENTE IN VARCHAR2,
  K_FEC_PROCESO IN DATE,
  K_USUARIO IN VARCHAR2,
  K_CODERROR OUT NUMBER, 
  K_DESCERROR OUT VARCHAR2, 
  K_NUMREGTOT OUT NUMBER,
  K_NUMREGPRO OUT NUMBER, 
  K_NUMREGERR OUT NUMBER
);


PROCEDURE ADMPSI_CAMBIOPLAN_HFCB
(
  K_TIPCLIENTE IN VARCHAR2,
  K_FEC_PROCESO IN DATE,
  K_USUARIO IN VARCHAR2,
  K_CODERROR OUT NUMBER,
  K_DESCERROR OUT VARCHAR2,
  K_NUMREGTOT OUT NUMBER,
  K_NUMREGPRO OUT NUMBER,
  K_NUMREGERR OUT NUMBER
 );

PROCEDURE ADMPSI_ALTACLIENTE_RPT
(
  K_TIPCLIENTE IN VARCHAR2,
  K_FEC_PROCESO IN DATE,
  K_USUARIO IN VARCHAR2,
  K_CODERROR OUT NUMBER,
  K_DESCERROR OUT VARCHAR2,
  K_NUMREGTOT OUT NUMBER,
  K_NUMREGPRO OUT NUMBER,
  K_NUMREGERR OUT NUMBER
);
 
PROCEDURE ADMPSI_FACTURA_HFC
(
  K_FEC_PROCESO IN DATE,
  K_USUARIO IN VARCHAR2,
  K_CODERROR OUT NUMBER, 
  K_DESCERROR OUT VARCHAR2, 
  K_NUMREGTOT OUT NUMBER,
  K_NUMREGPRO OUT NUMBER, 
  K_NUMREGERR OUT NUMBER
 );
 
PROCEDURE ADMPSI_ANIVERSARIO_HFC
(
  K_TIPCLIENTE IN VARCHAR2,
  K_FEC_PROCESO IN DATE,
  K_USUARIO IN VARCHAR2,
  K_CODERROR OUT NUMBER, 
  K_DESCERROR OUT VARCHAR2, 
  K_NUMREGTOT OUT NUMBER,
  K_NUMREGPRO OUT NUMBER, 
  K_NUMREGERR OUT NUMBER
 );
                                               
END PKG_CC_PTOSFIJA;
/

