create or replace package pclub.PKG_CC_PROCACUMULA is

       PROCEDURE ADMPSI_PAGO (K_FECHA IN DATE, K_CODERROR OUT NUMBER, K_DESCERROR OUT VARCHAR2, K_NUMREGTOT OUT NUMBER, K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
       PROCEDURE ADMPSS_EPAGO (K_FECHAPROC IN DATE, CURSORPAGO out SYS_REFCURSOR);
       PROCEDURE ADMPSI_ALTACONT (K_FECHA IN DATE,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,K_NUMREGTOT OUT NUMBER,K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
       PROCEDURE ADMPSI_EALTACONT (K_FECHAPROC IN DATE, CURSORALTCONT out SYS_REFCURSOR);
       PROCEDURE ADMPSI_ALTACLIC (K_FECHA IN DATE,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,K_NUMREGTOT OUT NUMBER,K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
       PROCEDURE ADMPSI_EALTACLIC (K_FECHAPROC IN DATE, CURSORALTCLI out SYS_REFCURSOR);
       PROCEDURE ADMPSI_PROMOC(K_FECHA IN DATE,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,K_NUMREGTOT OUT NUMBER,K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
       PROCEDURE ADMPSI_EPROMOC(K_FECHAPROC IN DATE, CURSORPROMPTO out SYS_REFCURSOR);
       PROCEDURE ADMPSI_ANIVERS (K_FECHA IN DATE,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,K_NUMREGTOT OUT NUMBER,K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
       PROCEDURE ADMPSI_EANIVERS (K_FECHAPROC IN DATE, CURSORANIVER out SYS_REFCURSOR);
       PROCEDURE ADMPSI_CAMBTITC (K_FECHAOPER IN DATE,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,K_NUMREGTOT OUT NUMBER,K_NUMREGPRO OUT NUMBER,K_NUMREGERR OUT NUMBER);
       PROCEDURE ADMPSI_ECAMBTITC (K_FECHAPROC IN DATE, CURSORCAMBTI out SYS_REFCURSOR);
       PROCEDURE ADMPSI_RENCONTC (K_FECHAOPER IN DATE,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,K_NUMREGTOT OUT NUMBER,K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
       PROCEDURE ADMPSI_ERENCONTC (K_FECHAPROC IN DATE, CURSORRENCONT out SYS_REFCURSOR);
       PROCEDURE ADMPSI_BAJACLIC (K_FECHA IN DATE,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,K_NUMREGTOT OUT NUMBER,K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
       PROCEDURE ADMPSI_EBAJACLIC (K_FECHAPROC IN DATE, CURSORBAJACLI out SYS_REFCURSOR);
       PROCEDURE ADMPSI_NOFACTC (K_FECHAPROCESO IN DATE,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,K_NUMREGTOT OUT NUMBER,K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
       PROCEDURE ADMPSI_ENOFACTC (K_FECHAPROC IN DATE, CURSORNOFACT out SYS_REFCURSOR);
       PROCEDURE ADMPSI_PRXRCONC (K_FECHA IN DATE,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,K_NUMREGTOT OUT NUMBER,K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
       PROCEDURE ADMPSI_EPRXRCONC (K_FECHAPROC IN DATE, CURSORPROXR out SYS_REFCURSOR);
       PROCEDURE ADMPSS_PROXRCOC(K_FECHAPROC IN DATE, C_CUR_DATOS_CLIE out SYS_REFCURSOR);
       PROCEDURE ADMPSI_REGULPTO(K_FECHA IN DATE,K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2,K_NUMREGTOT OUT NUMBER,K_NUMREGPRO OUT NUMBER, K_NUMREGERR OUT NUMBER);
       PROCEDURE ADMPSI_EREGULPTO(K_FECHAPROC IN DATE, CURSORREGPTO out SYS_REFCURSOR);
       PROCEDURE ADMPSS_CATEGCLI (K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2);
       PROCEDURE ADMPSS_PTOFACTU (K_CODERROR OUT NUMBER,K_DESCERROR OUT VARCHAR2, CURSORPUNTFAC out SYS_REFCURSOR);
       PROCEDURE ADMPSI_DSCTO_PUNTO(K_COD_CLIENTE IN VARCHAR2, K_TIP_CLI IN VARCHAR2, K_PUNTOS IN NUMBER, K_CONCEPTOCC IN VARCHAR2, K_CONCEPTOIB IN VARCHAR2,K_CODERROR OUT NUMBER, K_MSJERROR OUT VARCHAR2);

end PKG_CC_PROCACUMULA;
/

