insert into pclub.ctrlt_query
  (CTRLB_QUERY, CTRLN_FLAG, CTRLV_TITULO, CTRLV_ESTADO)
values
  (q'{SELECT CAT.ADMPN_COD_CATCLI || '-' || CAT.ADMPV_COD_TPOCL as CODIGO,
       NULL FECHA_INS,
       2 FLAG,
       CAT.ADMPV_DESC,
       CAT.ADMPV_COD_TPOCL ADMPV_COD_TPOCL_CAT,
       TIP.ADMPV_COD_TPOCL ADMPV_COD_TPOCL_TIP,
       TIP.ADMPV_DESC,
       TIP.ADMPC_ESTADO,
       TIP.ADMPV_TIPO,
       TIP.ADMPC_ENCUESTA,
       TIP.ADMPV_PRVENTA,
       TIP.ADMPC_TBLCLIENTE,
       CAT.ADMPC_TIPO,
       CAT.ADMPN_TME_PUNTO,
       CAT.ADMPV_OPER_INI,
       CAT.ADMPV_OPER_FIN,
       CAT.ADMPN_LIM_INF,
       CAT.ADMPN_LIM_SUP,
       CAT.ADMPC_ESTADO,
       CAT.ADMPN_CXPT_PPAG,
       CAT.ADMPN_CXPT_CFIJ,
       CAT.ADMPN_CXPT_CADI,
       CAT.ADMPN_PTOANIV,
       CAT.ADMPN_CXPT_ADEB
  FROM PCLUB.ADMPT_CAT_CLIENTE CAT, PCLUB.ADMPT_TIPO_CLIENTE TIP
 WHERE CAT.ADMPV_COD_TPOCL = TIP.ADMPV_COD_TPOCL}',
   2,
   'CATEGORIAS - TARIFAS',
   '1');

commit;